### ISSUE TITLE
Apple News submission denied due to "Channel content contains broken or missing text."

### ISSUE THREAD

**Issue by nickgli** [alleyinteractive/apple-news#1000]
Hello, 

Our Apple News application was denied due to the following reason; Channel content contains the broken or missing text.  Can someone please advise? Thank you!

**Comment by kevinfodness** [comment]
Please see the [Troubleshooting section in our wiki](https://github.com/alleyinteractive/apple-news/wiki/Usage#troubleshooting) and follow the steps there. When viewing your article in the News Preview tool, can you see which text is broken or missing? Can you correlate that to a part of your article that might not be translating well (or at all) into Apple News?
