### ISSUE TITLE
Updates made through 'apple_news_generate_json' not reflected in News Publisher but on Wordpress side

### ISSUE THREAD

**Issue by ashley-tam** [alleyinteractive/apple-news#1001]
### Description of the bug

Hi there, running into an interesting bug. 

We have an embedded signup form by [Brave](https://getbrave.io/) that has a lazy loaded image. 

We're using `apple_news_exporter_content_pre` to filter and remove the Brave embed, however I am guessing because the image is lazy loaded, the placeholder preloader.png image still gets added to the Apple News content as a full width image. This creates a giant gap in our article, as the image is transparent.

`{"role":"photo","URL":"bundle:\/\/preloader.png","layout":"full-width-image"},`

Here's where it gets interesting. Using `apple_news_generate_json` I am able to clean the json and remove the preloader.png. However, when an article gets published, the preloader.png chunk still exists on Apple News Publisher's json. But does not on the Wordpress side. 

If I update the article, and republish/re-push the json from Wordpress then the changes get reflected on Apple News Publisher and the preloader.png chunk gets cleaned.

Any thoughts as to what could be going on here? We schedule our articles to publish and republishing multiple times in hopes it pushes the right json isn't feasible. 

### Steps To Reproduce

1. Article gets automatically published based on schedule
2. Viewing article in News.app we see the gap left by preloader.png
3. Viewing the json from News Publisher reveals the preloader.png is still there
4. Viewing the json directly from Wordpress shows the preloader.png is gone 
5. Republishing the article so json gets repushed fixes the json and removes the preloader.png

### Additional Information

Removing the preloader.png in json file

```
add_filter( 'apple_news_generate_json', function( $json ) {
	$json = clean_preloader_img( $json );
	return $json;
} );

function clean_preloader_img( &$data ) {
	$preloader_image = '{"role":"photo","URL":"bundle:\/\/preloader.png","layout":"full-width-image"},';
	if ( is_array( $data ) ) {
		foreach ( $data as &$datum ) {
			clean_preloader_img( $datum );
		}
	}
	if ( is_string( $data ) ) {
		$data = str_replace($preloader_image, '', $data);
	}
	return $data;
}

```

**Comment by kevinfodness** [comment]
That's interesting - scheduled publish should work the same as manual publish with the operation of filters, although it appears in this case like it isn't. I wonder if the place where you wrote the code to apply the filter isn't loading when WP executes cron (which is what is used to publish scheduled posts)? Can you add some logic to that filter to perform some other side effect (e.g., writing to a log, firing off an email) so that you can see when it fires? Additionally, can you check the conditions under which that filter is being registered? Is it only being registered if `is_admin()` is true, for example?

**Comment by ashley-tam** [comment]
Upon further investigation it seems that scheduled publish isn't the issue. 

Though the issue still persists for the preloader.png to show up. Wondering if there are conflicts with lazy loading? 

When HTML is parsed into Apple News Format, is it before or after javascript has run? 

Will take a look and see if we can check when it fires

**Comment by kevinfodness** [comment]
JavaScript doesn't run at all when HTML is parsed into Apple News format. It's a pure PHP operation. If you are relying on JavaScript to lazy load your images, you will need to use a filter to modify the HTML that the Publish to Apple News plugin "sees" when it's converting it to ANF components.

**Comment by attackant** [comment]
Closing this as a stale issue @ashley-tam let us know if it's still relevant.
