### ISSUE TITLE
[BUG]: Path Traversal issue apple-news.php on line 43

### ISSUE THREAD

**Issue by lgrzegorski** [alleyinteractive/apple-news#1002]
### Description of the bug

Protection rules on the server do not allow for the plugin activation because of Path Traversal issue discovered in apple-news.php file on line 43.
Warning: require_once(/var/www/wp-content/plugins/publish-to-apple-news/./includes/meta.php): Failed to open stream: No such file or directory in /var/www/wp-content/plugins/publish-to-apple-news/apple-news.php on line 43
 Fatal error: Uncaught Error: Failed opening required '/var/www/wp-content/plugins/publish-to-apple-news/./includes/meta.php' (include_path='.')
in /var/www/wp-content/plugins/publish-to-apple-news/apple-news.php on line 43

### Steps To Reproduce

Plugin activation action.

### Additional Information

Need to remove the dot from the following code to prevent Path Traversal:  
require_once plugin_dir_path( __FILE__ ) . './includes/meta.php';

**Comment by kevinfodness** [comment]
Thanks, we'll roll up a fix for this into the next version.
