### ISSUE TITLE
The deks and bylines are missing or incorrect

### ISSUE THREAD

**Issue by General-RNG** [alleyinteractive/apple-news#1003]
### Description of the bug

Hello,

We have a problem with plugin it was working fine but now it wont update The deks and bylines on apple news.
And it wont work for all post but lets take one as example:

This is how page looks: https://www.1stdibs.com/blogs/the-study/damien-hirst-suiko/

And this is apple news link: https://apple.news/AtXqoxUS7T_moqXeLfN-TGw

Both looks similar but The deks and bylines are missing or incorrect on the Apple News. Author is different and there is no text “Fierceness and fragility coalesce as the British artist revisits a cherished motif — the butterfly.” on apple story.

### Steps To Reproduce

1. Go to site: https://www.1stdibs.com/blogs/the-study/damien-hirst-suiko/
2. Go to apple news link: https://apple.news/AtXqoxUS7T_moqXeLfN-TGw
3. Compare two provided links there will be different Author on apple news and there is no text “Fierceness and fragility coalesce as the British artist revisits a cherished motif — the butterfly.” on apple story.

**Comment by General-RNG** [comment]
<img width="1440" alt="Screenshot 2023-05-23 at 11 44 37 AM" src="https://github.com/alleyinteractive/apple-news/assets/47793485/9186acc9-cf0a-4ea5-b701-5aded96123aa">
<img width="1440" alt="Screenshot 2023-05-23 at 11 52 25 AM" src="https://github.com/alleyinteractive/apple-news/assets/47793485/0f86c3eb-e66e-4de9-b86e-234a8871a680">

**Comment by kevinfodness** [comment]
The dek is probably a custom field on your WordPress site—the plugin isn't able to understand all of the custom fields that folks create and map them to the appropriate fields in Apple News. You'll need to do that yourself using one of the plugin's filters. 

You can use the Intro component for this, which out of the box will use the post's excerpt, but that can be overridden. First, make sure to have the Intro component active in the meta component order part of the theme editor, and put it in the position you want (under the title, it looks like).

Then, you can filter [apple_news_exporter_excerpt](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_exporter_excerpt) and pass in your custom metadata value. For example:

```php
add_filter(
    'apple_news_exporter_excerpt',
    function( $excerpt, $post_id ) {
        return get_post_meta( $post_id, 'YOUR_META_KEY_FOR_DEK_HERE', true );
    },
    10,
    2
);
```

For author, I'm guessing that you're using a custom author system, or maybe just a meta field, to manage bylines. I'm guessing that Meredith Mendelsohn is the name of the _WordPress user_ that published the post. Out of the box, Publish to Apple News has support for standard WordPress authors and Co-Authors Plus. If you want to support other author plugins, or custom metadata, you'll need to map that yourself likewise using a filter like [apple_news_exporter_byline](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_exporter_byline). You may also need to filter [apple_news_metadata](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_metadata) to ensure that the byline is correct in the article listing.

**Comment by General-RNG** [comment]
Thx @kevinfodness! I'll try and let you know
