### ISSUE TITLE
[BUG]: Not displaying the correct excerpt

### ISSUE THREAD

**Issue by gpgdavid** [alleyinteractive/apple-news#1004]
### Description of the bug

Excerpts from WordPress site are not displaying on some articles that are being published on Apple News.
Instead of short article description we are seeing the Excerpts as “Date | Time”.

### Steps To Reproduce

1. Publish article from WordPress site.
2. Check article settings from Apple News
3. Under the EXCERPT field we are getting "DATE | TIME" on some articles.

**Comment by kevinfodness** [comment]
This will be fixed with the forthcoming 2.5.0 release.

**Comment by kevinfodness** [comment]
See #1091
