### ISSUE TITLE
Incompatibility with Block Editor

### ISSUE THREAD

**Issue by ucallrt** [alleyinteractive/apple-news#1005]
### Description of the bug

The plugin seems to work fine when I use the classic editor, but when I use the block editor, there is an error that keeps it from operating. 

The error that I receive is: "The "publish-to-apple-news" plugin has encountered an error and cannot be rendered."

The problem extends so far that when I go into the dashboard for the plugin, posts that were creating with the block editor are not even able to be selected to manually publish. 

It looks to be some incompatibility with the Classic Editor plugin because when I deactivate that plugin, I do not get the error. HOWEVER, I can publish to Apple News using the classic editor (when activated) just fine. 

### Steps To Reproduce

1. Install WP-Publish-to-Apple-News and Classic Editor (https://wordpress.org/plugins/classic-editor/) 
2. Create a new post using the Block Editor

**Comment by sdkjambo** [comment]
+1 on this.  Though I get the same error whether I use the Block or the Classic editor and have done so for >12 months, sadly rendering the plugin unusable.

I have latest versions of the plugin and WP core and PHP 7.4.33, and use the Total (WPBakery) theme.

**Comment by attackant** [comment]
Closing this as a duplicate.
