### ISSUE TITLE
There has been an error with the Apple News API: PUBLISHING_NOT_ALLOWED

### ISSUE THREAD

**Issue by gpgdavid** [alleyinteractive/apple-news#1013]
### Description of the bug

Unable to publish article from a WordPress site to Apple News, due to this error below:

"There has been an error with the Apple News API: PUBLISHING_NOT_ALLOWED"

### Steps To Reproduce

1. Publish post from WordPress site.

**Comment by kevinfodness** [comment]
You will need to follow up with Apple Support about this. It's likely that one of two things happened:

1. This is a new channel and it hasn't been approved yet, and you need to work with Apple to get it approved so you can start publishing to it.
2. This is an existing channel and Apple revoked your ability to publish to it and you need to follow up with them about why and how to fix it.

**Comment by attackant** [comment]
See: https://developer.apple.com/documentation/apple_news/code

>  This channel is currently not allowed to publish articles.
