### ISSUE TITLE
Add Support for phpunit using PHP 8.1 and 8.2 to CI

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/apple-news#1015]
### Description

I would like to see unit tests that test Publish to Apple News using PHP 8.1 and 8.2.

### Use Case

Run phpunit using PHP 8.1 and 8.2.

### Acceptance Criteria

- Ensure that phpunit is configured to run on PHP 8.1 and PHP 8.2 in GitHub Actions.
- Ensure all phpunit tests pass in PHP 8.1 and PHP 8.2
- Add the new PHP 8.1 and PHP 8.2 phpunit tests to branch protections (requires admin, ask a lead dev to do this).

### Technical Details

- This should be done after #1017, once phpunit is using the new reusable workflow.

**Comment by SiteBastion** [comment]
Since PHP 8 is now EOF, can this get a bump/ETA? Some hosts are forcing updates to 8.1 with 8.2 being preferred and also set to default for all new installs (WPEngine for instance)

Also, will test on 8.1/8.2 in coming week.

**Comment by kevinfodness** [comment]
@SiteBastion We are working on this currently.
