### ISSUE TITLE
Deploy to WordPress.org via GitHub Actions

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/apple-news#1016]
### Description

When a new release is created in GitHub, publish it to WordPress.org also.

### Use Case

I want to be able to create a new release from within GitHub and not need to manually push to WordPress.org.

[NYP-18347]: https://alleyinteractive.atlassian.net/browse/NYP-18347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### Acceptance Criteria

- Merging a change to `develop` that includes incrementing the version number in the main plugin file should trigger an automated workflow that builds JavaScript assets, creates a tag and a release for the new version that includes the built assets, and pushes the update to WordPress.org automatically, all using GitHub Actions (rather than the current setup, which relies on a service that we no longer use).

**Comment by attackant** [comment]
Going to look into this 10up project as a possible starting point https://github.com/marketplace/actions/wordpress-plugin-deploy

**Comment by renatonascalves** [comment]
@attackant [Here](https://github.com/renatonascalves/wp-graphql-buddypress/blob/main/.github/workflows/deploy-to-wordpress.yml) is an example of that Github Action in use. It deploys to this [plugin](https://wordpress.org/plugins/wp-graphql-buddypress/).

That GitHub action won't accomplish everything in the AC of this issue, though. You may need to merge some of the actions from here (https://github.com/alleyinteractive/.github?tab=readme-ov-file#reusable-workflows) with that one. Or create one yourself for the `.github` repo that performs all those actions.

**Comment by attackant** [comment]
> @attackant [Here](https://github.com/renatonascalves/wp-graphql-buddypress/blob/main/.github/workflows/deploy-to-wordpress.yml) is an example of that Github Action in use. It deploys to this [plugin](https://wordpress.org/plugins/wp-graphql-buddypress/).
> 
> That GitHub action won't accomplish everything in the AC of this issue, though. You may need to merge some of the actions from here (https://github.com/alleyinteractive/.github?tab=readme-ov-file#reusable-workflows) with that one. Or create one yourself for the `.github` repo that performs all those actions.

Thank you @renatonascalves I'm looking into this today.

**Comment by jakewrfoster** [comment]
@attackant / @kevinfodness is this ready to be moved to "In Review"?

**Comment by attackant** [comment]
This would be ready, except there are some new bugs [we are investigating](https://github.com/alleyinteractive/apple-news/issues/1031) before trying the release process.
