### ISSUE TITLE
"Delete Rule" Button in Automation Rules Table Fails and Removes Contents of the Entire Page

### ISSUE THREAD

**Issue by jtroynousky** [alleyinteractive/apple-news#1018]
### Description of the bug

When the Automation page has one or more automation rules set, clicking on the "Delete Rule" button removes the contents of the `apple-news-options__page` div  – effectively everything in the main content area. 

**BEFORE CLICKING DELETE RULE**
<img width="1049" alt="Screen Shot 2023-10-05 at 10 06 43 PM" src="https://github.com/alleyinteractive/apple-news/assets/435485/a41d1a15-5d0b-43ff-8ecd-ae8feb58d460">

**AFTER CLICKING DELETE RULE**
<img width="1079" alt="Screen Shot 2023-10-05 at 10 06 52 PM" src="https://github.com/alleyinteractive/apple-news/assets/435485/78d9e03d-16c8-401d-8c48-1d096dabae2b">

This produces the following output in console:
<img width="1297" alt="Screen Shot 2023-10-05 at 10 10 27 PM" src="https://github.com/alleyinteractive/apple-news/assets/435485/80a360ef-4df6-46a8-a179-8af29f1ecf2a">

### Steps To Reproduce

1. Visit **Apple News** => **Automation** in the dashboard.
2. If no automation rules are already set, add one and save.
3. Refresh the page and click any **Delete Rule** button in the rules table.

### Additional Information

We are encountering this on two of our sites that are on WordPress 6.3.1. I see the same behavior on 6.2.2 as well.

As a sanity check, I spun up a quick instance on the WordPress Playground (https://playground.wordpress.net – also 6.3.1) and I'm seeing it there, as well.

**Comment by james-tyner** [comment]
yes, I also have experienced this issue!

**Comment by attackant** [comment]
This will be fixed in the next release. Thank you @jtroynousky and @james-tyner
