### ISSUE TITLE
Address failing unit tests

### ISSUE THREAD

**Issue by attackant** [alleyinteractive/apple-news#1027]
### Description of the bug

It appears that we need to do some more work to convert to Mantle Testkit, or there is another regression that needs to be fixed since [1022](https://github.com/alleyinteractive/apple-news/issues/1022)

### Steps To Reproduce

Run unit test suite

### Additional Information

AC 
Tests are passing

**Comment by srtfisher** [comment]
This plugin isn't using Mantle Testkit, seems to be an issue with core testing if any.

**Comment by attackant** [comment]
I added mantle testkit to it...

**Comment by srtfisher** [comment]
~@attackant can you provide a link to where the plugin is using Mantle TestKit?~

Nevermind, I found it! https://github.com/alleyinteractive/apple-news/blob/release/v2.4.1/tests/bootstrap.php

What errors are you seeing?
