### ISSUE TITLE
Unable to select checklist options in Post Apple News Options Plugin

### ISSUE THREAD

**Issue by aeroplanejane** [alleyinteractive/apple-news#1028]
### Description of the bug

Since the upgrade to WordPress 6.4.1 I'm unable to select the checklist options within Apple News Options in the plugin. 
I check the box and nothing happens, and the checked value does not persist. 

<img width="491" alt="Screenshot 2023-11-15 at 09 47 11" src="https://github.com/alleyinteractive/apple-news/assets/22519682/4ace36ce-25fb-40d0-ba81-6fe48be0fa85">

I get this error: 
`react-dom.min.js?ver=18.2.0:10 Uncaught TypeError: Cannot read properties of undefined (reading 'cloneDeep')`

<img width="1705" alt="Screenshot 2023-11-15 at 09 46 36" src="https://github.com/alleyinteractive/apple-news/assets/22519682/118a9cfe-eb4c-4180-8299-9e6934af8c2d">

### Steps To Reproduce

1. Install the lastest version of WordPress 6.4.1
2. Ensure the Apple News Plugin is activated (obvs)
3. Navigate to a Post in WordPress
4. 6. Open your dev tools console
5. Open Options -> Apple News Options
6. Click on `Hidden Article` checkbox or one of the other options
7. Note that the checkbox does not store a value
8. Note the error in the console

**Comment by attackant** [comment]
Thanks @aeroplanejane I have confirmed this issue. We'll get a fix in a future release.
