### ISSUE TITLE
The "publish-to-apple-news" plugin has encountered an error and cannot be rendered.

### ISSUE THREAD

**Issue by interactivebytes** [alleyinteractive/apple-news#1030]
### Description of the bug

Since updating to WP 6.4.1 we are noticing the red message at the top of a new or existing post in block editor. Console log shows the below message.

react-dom.min.js?ver=18.2.0:10 TypeError: Cannot read properties of undefined (reading 'forEach')
    at sidebar.jsx:204:13

<img width="440" alt="image" src="https://github.com/alleyinteractive/apple-news/assets/2436576/45ef1c83-c8c1-40c5-b2d0-c28913e08621">

### Steps To Reproduce

Latest WP version 6.4.1

**Comment by attackant** [comment]
I have confirmed this bug. Thank you for reporting it, @interactivebytes
