### ISSUE TITLE
Cannot update theme JSON

### ISSUE THREAD

**Issue by alamedapost** [alleyinteractive/apple-news#1033]
### Description of the bug

Attempting to revert "end of article" section to a previous layout that worked fine. Every time I try to save edits to the component — EVEN IF I SAVE WITH NO CHANGES— I get:

> The spec for JSON could not be saved to the theme
> If you need assistance, please reach out for support on [WordPress.org] or [GitHub].
>
> The spec for Layout could not be saved to the theme
> If you need assistance, please reach out for support on [WordPress.org] or [GitHub].
> 
> No spec updates were found for End_Of_Article

How to fix?

### Steps To Reproduce

attempt to Customize Component JSON
save changes
experience failure

**Comment by kevinfodness** [comment]
I tried this locally and it's working as expected for me. The only way the "could not be saved to the theme" message should trigger is if field validation fails, and field validation failures should include a more specific error message. Was there more to the error text than what you shared here? For example, it would say something like "Theme values were not in array format" or "An invalid setting was encountered."

**Comment by alamedapost** [comment]
This was due to the functions.php file being overwritten when the theme updated. Adding the information back to functions.php fixed the issue. Thanks.
