### ISSUE TITLE
update_post_metadata Filter Can Crash on PHP 8

### ISSUE THREAD

**Issue by alamedapost** [alleyinteractive/apple-news#1034]
PHP 8 now throws a TypeError on values that are not iterable. In [at least one location](https://github.com/alleyinteractive/apple-news/blob/9458fcd019bbad2672d135407ea438862b10ad4e/includes/class-apple-news.php#L559) there is a case where the plugin does not check the return type from a function and can crash if the function returns something that is not iterable.

## Acceptance Criteria

- Analyze the code for uses of the `count()` function and ensure that, where necessary, a check is done to ensure the value is iterable before passing to the function.

## Original Submission

When plugin is enabled, setting a featured image and saving the post cause the entire site to crash. Only workaround is to disable plugin while creating posts then reactivate plugin before publication

### Steps To Reproduce

have plugin enabled
create new post
assign featured image
save
crash!

**Comment by kevinfodness** [comment]
I can't reproduce this locally on WordPress 6.4.2 with Publish to Apple News 2.4.0. It's likely that there is a conflict with another plugin or with your theme. Can you see what the error message is in the PHP logs?

**Comment by alamedapost** [comment]
2024/01/03 16:11:05 [error] 120216#120216: *1408060 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, int given in /www/alamedapost_328/public/wp-content/plugins/publish-to-apple-news/includes/class-apple-news.php:559
Stack trace:
#0 /www/alamedapost_328/public/wp-includes/class-wp-hook.php(324): Apple_News->filter_update_post_metadata(NULL, 55065, '_thumbnail_id', 55084, '')
#1 /www/alamedapost_328/public/wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array)
#2 /www/alamedapost_328/public/wp-includes/meta.php(235): apply_filters('update_post_met...', NULL, 55065, '_thumbnail_id', 55084, '')
#3 /www/alamedapost_328/public/wp-includes/post.php(2558): update_metadata('post', 55065, '_thumbnail_id', 55084, '')
#4 /www/alamedapost_328/public/wp-includes/post.php(7657): update_post_meta(55065, '_thumbnail_id', 55084)
#5 /www/alamedapost_328/public/wp-includes/post.php(4625): set_post_thumbnail(Object(WP_Post), 55084)
#6 /www/alamedapost_328/public/wp-includes/post.php(4862): wp_i" while reading response header from upstream, client: 2600:1700:ab14:8a00:4c30:d48c:5e19:e42b, server: alamedapost.com, request: "POST /wp-admin/post.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.0-fpm-alamedapost.sock:", host: "alamedapost.com:29052", referrer: "https://alamedapost.com/wp-admin/post.php?post=55065&action=edit"

**Comment by kevinfodness** [comment]
Are you using Gutenberg or the Classic Editor? Are you on WordPress 6.4.2?

**Comment by alamedapost** [comment]
Classic and Elementor. I’ve never used Gutenberg.

Yes, Wordpress 6.4.2

--


<http://linkedin.com/company/alameda-post/> [image: google+ image of
google+ icon] <https://instagram.com/alameda.post>
<https://facebook.com/alamedapost>

*Donate Now! <https://omella.com/AlamedaPost>*


Adam Gillitt, Publisher

*(He/him/his)*

<https://alamedapost.com>

Phone 510.263.8176  Mobile 510.457.1421
Email ***@***.***
Web alamedapost.com
Office 1516 Oak St. #203, Alameda, CA 94501

*Alameda Post Inc. is a 501(c)(3) nonprofit corporation. Our tax ID is
874572048.*

**Comment by kevinfodness** [comment]
I tested this using the Classic Editor plugin and it works properly there also. I did not test it using Elementor.

The line in question is comparing the result of `get_metadata` with the `$single` parameter set to `false` (the default) which should return an array, but for some reason is returning an int on your site. I suspect that there's a filter at play in third party or custom code that you have on your site that is returning the wrong data type. Calling `get_metadata` with `$single` set to false should return an array of all postmeta values for that key, and it should be an empty array if no values are set, an array with one item if only one is set, etc. You may want to look for instances of the filter `get_post_metadata` which may not be respecting the `$single` parameter and would return an integer instead of an array.

I'm going to apply the `bug` label on this issue though, because the plugin could be doing a better job of validating the data type before using it.

**Comment by alamedapost** [comment]
Thank you for the detailed explanation.

To clarify, I don’t use Elementor for individual posts, just for pages.

This bug has been happening for a while, so our production staff is used to
flipping off the plug-in before creating a new post, but it will be nice to
not have to do that anymore.

Thanks again.


--


<http://linkedin.com/company/alameda-post/> [image: google+ image of
google+ icon] <https://instagram.com/alameda.post>
<https://facebook.com/alamedapost>

*Donate Now! <https://omella.com/AlamedaPost>*


Adam Gillitt, Publisher

*(He/him/his)*

<https://alamedapost.com>

Phone 510.263.8176  Mobile 510.457.1421
Email ***@***.***
Web alamedapost.com
Office 1516 Oak St. #203, Alameda, CA 94501

*Alameda Post Inc. is a 501(c)(3) nonprofit corporation. Our tax ID is
874572048.*

**Comment by attackant** [comment]
@alamedapost Do you want to test out https://github.com/alleyinteractive/apple-news/pull/1037 and see if this fixes your issue? I didn't see any other likely issues with usages of count() elsewhere.

**Comment by alamedapost** [comment]
Just uploaded 2.4.1 and did a quick test with an empty post and added the featured image. The post saved successfully with no crash. We will test further during today's production cycle and report back if there are any problems.

Thank you!

**Comment by alamedapost** [comment]
Unfortunately, it did not solve the issue. Some images work, others do not.
This is an error from one that did not.

2024/01/03 23:33:44 [error] 120216#120216: *1465164 FastCGI sent in stderr:
"PHP message: PHP Fatal error: Uncaught TypeError: count(): Argument #1
($value) must be of type Countable|array, int given in
/www/alamedapost_328/public/wp-content/plugins/apple-news-release-v2.4.1/includes/class-apple-news.php:559
Stack trace:
#0 /www/alamedapost_328/public/wp-includes/class-wp-hook.php(324):
Apple_News->filter_update_post_metadata(NULL, 55127, '_thumbnail_id',
55210, '')
#1 /www/alamedapost_328/public/wp-includes/plugin.php(205):
WP_Hook->apply_filters(NULL, Array)
#2 /www/alamedapost_328/public/wp-includes/meta.php(235):
apply_filters('update_post_met...', NULL, 55127, '_thumbnail_id', 55210, '')
#3 /www/alamedapost_328/public/wp-includes/post.php(2558):
update_metadata('post', 55127, '_thumbnail_id', 55210, '')
#4 /www/alamedapost_328/public/wp-includes/post.php(7657):
update_post_meta(55127, '_thumbnail_id', 55210)
#5 /www/alamedapost_328/public/wp-includes/post.php(4625):
set_post_thumbnail(Object(WP_Post), 55210)
#6 /www/alamedapost_328/public/wp-includes/post.php(4862):" while reading
response header from upstream, client:
2600:1700:442:2ed0:80a8:8bf4:2975:60b0, server: alamedapost.com, request:
"POST /wp-admin/post.php HTTP/2.0", upstream:
"fastcgi://unix:/var/run/php8.0-fpm-alamedapost.sock:", host: "
alamedapost.com:29052", referrer: "
https://alamedapost.com/wp-admin/post.php?post=55127&action=edit"


--


<http://linkedin.com/company/alameda-post/> [image: google+ image of
google+ icon] <https://instagram.com/alameda.post>
<https://facebook.com/alamedapost>

*Donate Now! <https://omella.com/AlamedaPost>*


Adam Gillitt, Publisher

*(He/him/his)*

<https://alamedapost.com>

Phone 510.263.8176  Mobile 510.457.1421
Email ***@***.***
Web alamedapost.com
Office 1516 Oak St. #203, Alameda, CA 94501

*Alameda Post Inc. is a 501(c)(3) nonprofit corporation. Our tax ID is
874572048.*

**Comment by attackant** [comment]
thanks for the follow up... investigating.

**Comment by attackant** [comment]
@alamedapost Can you confirm that /www/alamedapost_328/public/wp-content/plugins/apple-news-release-v2.4.1/includes/class-apple-news.php:559 is this?
`	if ( false !== $old_value && is_array( $old_value ) && 1 === count( $old_value ) ) {`
In that case the fatal should not be possible, so I'm wondering if the old version of that line is somehow still being loaded.

**Comment by alamedapost** [comment]
No, it's not.  559 is

if ( 1 === count( $old_value ) ) {

I will delete and re-upload and check again


--


<http://linkedin.com/company/alameda-post/> [image: google+ image of
google+ icon] <https://instagram.com/alameda.post>
<https://facebook.com/alamedapost>

*Donate Now! <https://omella.com/AlamedaPost>*


Adam Gillitt, Publisher

*(He/him/his)*

<https://alamedapost.com>

Phone 510.263.8176  Mobile 510.457.1421
Email ***@***.***
Web alamedapost.com
Office 1516 Oak St. #203, Alameda, CA 94501

*Alameda Post Inc. is a 501(c)(3) nonprofit corporation. Our tax ID is
874572048.*

**Comment by attackant** [comment]
Yes, that's the old version then.

**Comment by alamedapost** [comment]
How may I download the updated version again? The version i have saved
locally does not have the correct code at line 559.


--


<http://linkedin.com/company/alameda-post/> [image: google+ image of
google+ icon] <https://instagram.com/alameda.post>
<https://facebook.com/alamedapost>

*Donate Now! <https://omella.com/AlamedaPost>*


Adam Gillitt, Publisher

*(He/him/his)*

<https://alamedapost.com>

Phone 510.263.8176  Mobile 510.457.1421
Email ***@***.***
Web alamedapost.com
Office 1516 Oak St. #203, Alameda, CA 94501

*Alameda Post Inc. is a 501(c)(3) nonprofit corporation. Our tax ID is
874572048.*

**Comment by alamedapost** [comment]
Or do i just need to edit that one line?

**Comment by attackant** [comment]
You can try editing that line or download the zip here: https://github.com/alleyinteractive/apple-news/releases/tag/v2.4.1

**Comment by alamedapost** [comment]
Thanks. I'll let you know if that does not solve the issue in a little bit... I really appreciate the assistance.

**Comment by attackant** [comment]
The new release won't be on wordpress.org until tomorrow probably.

**Comment by alamedapost** [comment]
Thank you Damian. We got through the rest of production with no crashes.


--


<http://linkedin.com/company/alameda-post/> [image: google+ image of
google+ icon] <https://instagram.com/alameda.post>
<https://facebook.com/alamedapost>

*Donate Now! <https://omella.com/AlamedaPost>*


Adam Gillitt, Publisher

*(He/him/his)*

<https://alamedapost.com>

Phone 510.263.8176  Mobile 510.457.1421
Email ***@***.***
Web alamedapost.com
Office 1516 Oak St. #203, Alameda, CA 94501

*Alameda Post Inc. is a 501(c)(3) nonprofit corporation. Our tax ID is
874572048.*

**Comment by kevinfodness** [comment]
@alamedapost the new version just went live about an hour ago (v2.4.3). If you update, this should fix the issue for you. Please let me know if it does not.

**Comment by alamedapost** [comment]
Thanks very much, it is installed.


--


<http://linkedin.com/company/alameda-post/> [image: google+ image of
google+ icon] <https://instagram.com/alameda.post>
<https://facebook.com/alamedapost>

*Donate Now! <https://omella.com/AlamedaPost>*


Adam Gillitt, Publisher

*(He/him/his)*

<https://alamedapost.com>

Phone 510.263.8176  Mobile 510.457.1421
Email ***@***.***
Web alamedapost.com
Office 1516 Oak St. #203, Alameda, CA 94501

*Alameda Post Inc. is a 501(c)(3) nonprofit corporation. Our tax ID is
874572048.*
