### ISSUE TITLE
Bylines not showing

### ISSUE THREAD

**Issue by alamedapost** [alleyinteractive/apple-news#1036]
### Description of the bug

Since December 25, none of the articles we have posted to Apple News show the byline. They do show the time and date stamp (which is also incorrect and reported separately)

### Steps To Reproduce

publish article to Apple News with byline
review article on Apple News to check for byline
fail, no byline

**Comment by kevinfodness** [comment]
I'm not able to reproduce this on WordPress 6.4.2 and Publish to Apple News 2.4.0. The byline field appears with the WordPress author set. We haven't changed anything on our end, and to my knowledge, neither has Apple. Did something change on your site on December 25th? Did you update any plugins or make changes to your theme? Are you using native WordPress authors, or a plugin to manage authors, or a custom field?

**Comment by alamedapost** [comment]
Thanks for pointing me in the right direction, the theme was updated over the holiday and the functions.php file was overwritten. I reinstalled the code and it's working as expected. Thanks!
