### ISSUE TITLE
New 2.4.5 release breaks posting

### ISSUE THREAD

**Issue by alamedapost** [alleyinteractive/apple-news#1048]
### Description of the bug

After updating to the most current version of the plugin, articles do not publish to apple news and the following error message is shown: 
**There has been an error with the Apple News API: INVALID_DOCUMENT - Resource with URI [bundle://] not found. (keyPath components->0->components->0)**

### Steps To Reproduce

Make an attempt to publish to apple news automatically or manually. 

### Additional Information

Nothing else has changed about our config. rolling back to an older version.

**Comment by alamedapost** [comment]
Successfully posted after rolling back.

**Comment by attackant** [comment]
@alamedapost thank you for this, what version is working for you?

**Comment by alamedapost** [comment]
2.4.3 is working

**Comment by attackant** [comment]
@alamedapost Can you check for me if you can a successfully hit add and then delete on the automation rules screen (`/wp-admin/admin.php?page=apple-news-automation`) on your currently installed version? I'm trying to track down the version where that feature broke, you do not need to save changes, just hit Add Rule and then Delete Rule, and let me know if you see a JS error? 🙇🏼‍♂️

**Comment by alamedapost** [comment]
When I tried it just now, the entire page went blank after I clicked on
"delete rule" and I was unable to do anything else without refreshing the
page.

Also that page takes a very long time to populate its data from internal
categories,

A
--


<http://linkedin.com/company/alameda-post/> [image: google+ image of
google+ icon] <https://instagram.com/alameda.post>
<https://facebook.com/alamedapost>

*Donate Now! <https://omella.com/AlamedaPost>*


Adam Gillitt, Publisher

*(He/him/his)*

<https://alamedapost.com>

Phone 510.263.8176  Mobile 510.457.1421
Email ***@***.***
Web alamedapost.com
Office 1516 Oak St. #203, Alameda, CA 94501

*Alameda Post Inc. is a 501(c)(3) nonprofit corporation. Our tax ID is
874572048.*

**Comment by attackant** [comment]
@alamedapost If possible can you send me a Download of a JSON file that caused this for testing?

**Comment by attackant** [comment]
Actually, @alamedapost never mind about the export! I think I have a fix already.

**Comment by alamedapost** [comment]
Ok, that makes it easier. Thanks.

A
--


<http://linkedin.com/company/alameda-post/> [image: google+ image of
google+ icon] <https://instagram.com/alameda.post>
<https://facebook.com/alamedapost>

*Donate Now! <https://omella.com/AlamedaPost>*


Adam Gillitt, Publisher

*(He/him/his)*

<https://alamedapost.com>

Phone 510.263.8176  Mobile 510.457.1421
Email ***@***.***
Web alamedapost.com
Office 1516 Oak St. #203, Alameda, CA 94501

*Alameda Post Inc. is a 501(c)(3) nonprofit corporation. Our tax ID is
874572048.*

**Comment by benmek-wsm** [comment]
@attackant Hi, I am experiencing this same error when using version 2.4.8. I manually installed the 2.4.0 built version and I was able to successfully publish on that version. Should I create a new issue?

**Comment by mogmarsh** [comment]
@benmek-wsm yes, a new issue would be great. Thank you!

**Comment by benmek-wsm** [comment]
@mogmarsh I tried to create replication steps and upgraded the manual installed 2.4.0 version to the latest version but for some reason I am no longer getting the error. 

Initial scenario was fresh install of latest version through WP Admin so I retried that and it works now as well. Very weird, sorry for the false alarm.

**Comment by mogmarsh** [comment]
@benmek-wsm no worries! Thanks for the update!
