### ISSUE TITLE
Article Format Not Accepted

### ISSUE THREAD

**Issue by budezllc** [alleyinteractive/apple-news#105]
Got this from apple on a few posts. Is there something specific to get around this? 	
	
While reviewing your Apple News Format submission, we noticed that something isn't quite right. Please resolve these issues, and then resubmit your content at News Publisher.
Articles contain exposed unicode, HTML, or XML.
Regards,
The Apple News Team

**Comment by bcampeau** [comment]
That's a very generic issue. You should be validating your content using the News Preview tool to get the actual error.

If you're experiencing exposed unicode, HTML or XML it doesn't sound like you're using this plugin. Everything is converted to markdown or Apple News components.

**Comment by pembo13** [comment]
Looks like `htmlentities($text, ENT_NOQUOTES | ENT_IGNORE | ENT_HTML5, 'UTF-8')` needs to be called on the generated value for the `text` entries of the nested JSON objects.
