### ISSUE TITLE
Non-prefixed option names

### ISSUE THREAD

**Issue by johnbillion** [alleyinteractive/apple-news#106]
All of the settings in `Apple_Exporter\Settings::settings` are stored in individual options without a prefix. These should be prefixed, or stored in a single serialised option with a suitable name.

**Comment by bcampeau** [comment]
Yeah, I'm aware. This was a decision made by the original plugin authors and unfortunately it went out into the wild as such. It's on the list but thanks for officially opening an issue. We'll probably fix this in the next version or two and include a data migration script that triggers automatically on upgrade.
