### ISSUE TITLE
Can't delete automation rules

### ISSUE THREAD

**Issue by adamengst** [alleyinteractive/apple-news#1063]
### Description of the bug

I created a number of automation rules, but they didn't work the way I expected and force an extra step when assigning Apple News categories to a post. So I want to delete them, but every time I click Delete Rule in the Automations screen, I get a blank (within the WordPress chrome) screen at this URL: https://example.com/wp/wp-admin/admin.php?page=apple-news-automation . When I go back to the Automations screen, the rule has not been deleted.

Honestly, all I want to do is remove all the automation and go back to being able to assign categories manually without the extra step of avoiding the automation rules.

### Steps To Reproduce

1. Create an automation rule.
2. Click Delete Rule.
3. Get sent to a blank page without the rule being deleted.

### Additional Information

Automations screen where I click Delete Rule
![Arc 2024-02-12 at 12 48 36@2x](https://github.com/alleyinteractive/apple-news/assets/36641103/9700cf65-53c5-4215-9f52-79748fd41041)

Blank screen that results from clicking Delete Rule
![Arc 2024-02-12 at 12 48 43@2x](https://github.com/alleyinteractive/apple-news/assets/36641103/ecff78c9-9d92-430a-967f-2bec5a21a077)

**Comment by kevinfodness** [comment]
Are you using the latest version (2.4.6)? We shipped some fixes for errors on the Automation screen last week.

**Comment by adamengst** [comment]
Nope, looks like 2.4.3—let me get my developer to update and I'll report back.
