### ISSUE TITLE
How to add a Newsletter Signup at end of article.

### ISSUE THREAD

**Issue by mattpramschufer** [alleyinteractive/apple-news#1064]
### Description

Hello, I have been looking through the docs and the wiki and I just can't seem to find the correct way to add a newsletter sign up at the end of the article.  I am looking at https://developer.apple.com/documentation/apple_news/apple_news_format_tutorials/creating_a_newsletter_sign-up_element

And then I am customizing the JSON for the `End of Article` component.  I just do not understand which JSON goes in the JSON section and which goes in the Layout Section.

For the JSON section I have tried added

```
{
      "role": "container",
      "layout": "newsletterLayout",
      "style": "newsletterStyle",
      "components": [
        {
          "role": "heading3",
          "text": "Lorem ipsum dolor sit amet",
          "textStyle": "newsletterHeadingTextStyle",
          "layout": "newsletterHeadingLayout"
        },
        {
          "role": "body",
          "text": "Sign up for our daily newsletter, delivered straight to your inbox.",
          "textStyle": "newsletterBodyTextStyle",
          "layout": "newsletterBodyLayout"
        },
        {
          "role": "link_button",
          "format": "html",
          "URL": "https://apple.com",
          "text": "Sign Up &#x2197;&#xFE0E;",
          "textStyle": "newsletterButtonTextStyle",
          "layout": "newsletterButtonLayout",
          "style": "newsletterButtonStyle"
        }
      ]
    }
```
But that will not save

I have added 
```
{
    "newsletterLayout": {
        "padding": 30
    },
    "newsletterHeadingLayout": {
        "margin": {
            "bottom": 24
        }
    },
    "newsletterBodyLayout": {
        "margin": {
            "bottom": 26
        }
    },
    "newsletterButtonLayout": {
        "padding": {
            "left": 24,
            "right": 24,
            "top": 12,
            "bottom": 12
        }
    }
}
```

To the layout section and that seemed to save but I just can't figure out what JSON I can actually input into the JSON section.

Any help would be much appreciated and thank you in advance!

**Comment by kevinfodness** [comment]
You don't need to put anything in the layout section - you can put it all in the component JSON section if you want to. What message do you get when trying to save the JSON? You mentioned it doesn't save - does it give you an error?

The instructions on Apple's site assume you're modifying the entire JSON document, and have you adding items to componentLayouts and componentStyles. I'd recommend adding those layouts and styles inline rather than using references. For example, instead of doing:

```json
{
  "layout": "newsletterLayout"
}
```

Do:

```json
{
  "layout": {
    "padding": 30
  }
}
```

And so on.

**Comment by mattpramschufer** [comment]
The error that I am getting when saving the json is 
```
The spec for JSON had invalid tokens and cannot be saved

If you need assistance, please reach out for support on [WordPress.org](https://wordpress.org/support/plugin/publish-to-apple-news) or [GitHub](https://github.com/alleyinteractive/apple-news/issues).
```

Even if I try to remove the layout and do inline I am still getting the error 
```
The spec for JSON was empty or invalid. Reverting to the previous spec.

Dismiss this notice.
No spec updates were found for End_Of_Article
```



when trying to save 

```
{
      "role": "container",
      "components": [
        {
          "role": "heading3",
          "text": "Lorem ipsum dolor sit amet",
        },
        {
          "role": "body",
          "text": "Sign up for our daily newsletter, delivered straight to your inbox.",
        },
        {
          "role": "link_button",
          "format": "html",
          "URL": "https://apple.com",
          "text": "Sign Up &#x2197;&#xFE0E;",
        }
      ]
    }
```

**Comment by kevinfodness** [comment]
The error message is correct - the JSON you entered isn't valid. The field will actually highlight the line that isn't valid with a red X. In this case, it's highlighting lines 7, 11, and 17 because the previous lines end with a comma and shouldn't. While you can have trailing commas after the end of the last item in a list in JavaScript, in JSON, it's a syntax error. To be safe, you can run your JSON through a linter like jsonlint.com and confirm it's valid JSON before attempting to save it in the Customize JSON view.

**Comment by kevinfodness** [comment]
The "Invalid Tokens" message is caused by the Sign Up text. There are special tokens that are replaced dynamically, and they begin and end with a `#`, so the pattern matcher is seeing `#x2197;&#` and sees that as an invalid token and is rejecting it. Rather than using escaped text there, you should be able to enter UTF-8 characters directly.

**Comment by mattpramschufer** [comment]
Excellent support!  Thank you so much.  I will follow back up on this ticket with my exact code when I have it completed so someone else can utilize it!

**Comment by mattpramschufer** [comment]
Okay if anyone is interested the final code to add a newsletter subscribe box to the end of the article that looks like 
![final](https://github.com/alleyinteractive/apple-news/assets/4295444/bf72b227-5a60-4890-8603-e505802c8e55)

is the following

In the JSON box 
```
{
    "role": "container",
    "layout": "end-of-article-layout",
    "style": {
        "margin": {
            "top": 50,
            "bottom": 50
        },
        "padding": 30,
        "backgroundColor": "#f6f6f4",
        "opacity": 1,
        "border": {
            "all": {
                "width": 1,
                "color": "#e9e9e7"
            }
        }
    },
    "components": [
        {
            "role": "heading2",
            "text": "Sign Up For Our Newsletter",
            "format": "html",
            "textStyle": {
                "fontName": "Baskerville-SemiBold",
                "fontSize": 26,
                "lineHeight": 42,
                "tracking": -0.03,
                "textColor": "#000000",
                "textAlignment": "center"
            },
            "layout": {
                "margin": {
                    "top": 0,
                    "bottom": 10
                }
            }
        },
        {
            "role": "body",
            "text": "Sign up to receive regular updates on topics of interest to people in rural<br> communities and small towns.",
            "format": "html",
            "textStyle": {
                "textAlignment": "center",
                "fontName": "Helvetica"
            },
            "layout": {
                "margin": {
                    "top": 0,
                    "bottom": 20
                }
            }
        },
        {
            "role": "link_button",
            "format": "html",
            "URL": "https://barnraisingmedia17744.activehosted.com/f/37",
            "text": "Sign Up »",
            "style": {
                "backgroundColor": "#c4693c",
                "textColor": "#ffffff",
                "mask": {
                    "type": "corners",
                    "radius": 12
                }
            },
            "layout": {
                "padding": 10
            },
            "textStyle": {
                "textColor": "#ffffff",
                "fontName": "Helvetica",
                "fontSize": 16
            }
        }
    ]
}
```

and then in the Layout box

```
{
    "columnStart": 0,
    "columnSpan": 6,
    "margin": {
        "top": 30,
        "bottom": 30
    },
    "padding": 15
}
```

I hope that helps someone!  And thank you again @kevinfodness for the super quick response and help with this issue.
