### ISSUE TITLE
New Automation Option: Prepend Text to Article Titles

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/apple-news#1065]
### Description

I would like to see an option for prepending text to article titles based on assigned taxonomy.

### Use Case

A user could create an Automation rule to prepend the word "Opinion:" to an article title if it has a category of Opinion when publishing to Apple News.

**Comment by mogmarsh** [comment]
It would be great if there were separate controls to prepend text to the metadata title and the headline.
