### ISSUE TITLE
Add Support for Text Alignment

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/apple-news#1077]
### Description of the bug

Body elements can be aligned left/right/center/justified in WordPress, but that doesn't carry over to Apple News. We need to be able to honor the proper `textAlignment` setting based on what the user selected in WordPress.

### Steps To Reproduce

1. Create a paragraph
2. Align it to the right
3. Publish
4. Observe that the paragraph is aligned left in Apple News

**Comment by dlh01** [comment]
#1115 missed this.
