### ISSUE TITLE
Article body not populating in Apple News

### ISSUE THREAD

**Issue by cmaniates** [alleyinteractive/apple-news#1099]
### Description of the bug

I've connected our Apple News channel with WordPress, but the article body is not appearing in Apple News when I publish articles to Apple News via Wordpress. The headline, author and date all show, but then nothing else.

### Steps To Reproduce

When you navigate to the article on our website (https://www.cars.com/articles/ford-recalls-over-42000-bronco-sports-escapes-for-fire-risk-481097/) you see the full article.

When you navigate to the Apple News version of this article (https://apple.news/AfcGf3RdbTt2QdH1xGdddFw) you see the headline, date, author and main image, but nothing else.

### Additional Information

I'm not sure what the issue might be - perhaps our version of WordPress isn't fully compatible with the plugin, or maybe I need to change a setting in order to get the article body to render in Apple News. Would love any sort of insight into solving this issue!

**Comment by kevinfodness** [comment]
Is it possible you're using a page builder of some sort on your site? The Publish to Apple News plugin works by taking what is in the `post_content` field and converting it into your article body. If your article body really lives somewhere else, like in a page builder or in postmeta, it won't know about it, and can't automatically convert it. However, that doesn't mean that you can't use the plugin, but it does mean that you will need to do some coding to get it to work properly. You can use the [apple_news_exporter_content filter](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_exporter_content) to provide the HTML for the article body and the plugin can take it from there.

**Comment by cmaniates** [comment]
I believe we do use a page builder, so this is very helpful. I apologize if this is a silly question, but where does the filter code need to be stored? I am not a developer, so I just want to be sure I'm providing our dev team with as much information as possible so they can apply it.

Thank you!

**Comment by mogmarsh** [comment]
@cmaniates custom code can be added to a custom WordPress theme or plugin for the project. The dev team should be familiar with adding filters. It's a common WordPress concept.

**Comment by cmaniates** [comment]
Excellent, thank you for your help!!
