### ISSUE TITLE
Some errors on the setting dashboard

### ISSUE THREAD

**Issue by wei888** [alleyinteractive/apple-news#110]
Some errors on the setting dashboard

Component Order	
Strict Standards: call_user_func() expects parameter 1 to be a valid callback, non-static method Admin_Apple_Settings_Section_Formatting::render_meta_component_order() should not be called statically, assuming $this from compatible context Admin_Apple_Settings_Section_Formatting in /srv/www/wordpress-default/wp-content/plugins/apple-news/admin/settings/class-admin-apple-settings-section.php on line 496

And when I failed to publish the article that already published using the plug-in version got from wordpress plugin successfully before, Got API error as well, Wonder if you can give some advice.

Thanks,
Wei

**Comment by bcampeau** [comment]
The dashboard errors were resolved in #111. If you're having issues with the API, please open a separate issue for that with more details.

Thanks.
