### ISSUE TITLE
Allow HTML in Image Caption

### ISSUE THREAD

**Issue by fangyizhu** [alleyinteractive/apple-news#1103]
### Description

Hello,

We sometimes have HTML tags in image caption, currently they are not rendered as HTML, but as plain text.

We can avoid this issue by not having HTML tags in image captions, but it would be better if they can be rendered as HTML.

<img width="827" alt="Screenshot 2024-04-16 at 1 26 56 PM" src="https://github.com/alleyinteractive/apple-news/assets/1818823/5f0a5acc-3bed-4c91-86e0-4fe03cb5938f">

### Use Case

Links in image caption.

**Comment by kevinfodness** [comment]
Hi @fangyizhu —

I'm not able to replicate this issue using the latest version of the plugin in a sandbox environment. I've tried in both the block editor and the classic editor, and the link is rendering properly in both cases. Additionally, there is an automated test that confirms the behavior of HTML, including links, in image captions, which is passing.

Is it possible that there is something in your theme or one of the other plugins you are using that is causing a conflict here?

**Comment by fangyizhu** [comment]
Our channel is pending Apple approval, so I'll get back to you with more examples some time next week.

**Comment by fangyizhu** [comment]
It's not a problem for us anymore. If we run into it again I'll reopen.
