### ISSUE TITLE
Truncate Changelog Section of WordPress.org Readme

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/apple-news#1104]
### Description of the bug

WordPress.org truncates changelogs that are over 5000 words. As of a recent release, we hit that cap, and need to proactively remove older changelog entries.

## Acceptance Criteria

Truncate the changelog of the WordPress.org Readme so that it only contains information on the last 5 releases (no more than 5000 words) and links to the releases section in GitHub for a full version history.

### Steps To Reproduce

1. Log in to WordPress.org as a plugin maintainer
2. Navigate to the Publish to Apple News plugin
3. See the message about the changelog being too long

**Comment by renatonascalves** [comment]
Have you considered adding a link to the [Github Release](https://github.com/alleyinteractive/apple-news/releases) instead? I do think it is more friendly to user sharing the changes there, but I also see several projects sharing only the link of the, external, release.
