### ISSUE TITLE
Gutenberg Cover pattern causing error when publishing to Apple News

### ISSUE THREAD

**Issue by aharper-fox** [alleyinteractive/apple-news#1117]
### Description of the bug

When trying to publish an article through the plugin, there is an error occurring for most of our articles. We've narrowed it down to the plugin trying to convert the Gutenberg cover block into a photo with a caption but because it contains a header, that doesn't quite translate. I'd like to create a special component for this as we use it for a curated list of related stories. I did see that there was possibly an aside component that may be introduced. I'm happy to reconfigure our related posts so that they translate better through the plugin.

### Steps To Reproduce

1. Insert article copy 2. Insert related stories block (pattern). 3. Publish to Apple News 4. Receive this error ![Screenshot 2024-05-06 at 5 40 18 PM](https://github.com/alleyinteractive/apple-news/assets/169101691/862c654a-4c0e-460f-9550-af13d6b9996a)

### Additional Information

[article-104610.json](https://github.com/alleyinteractive/apple-news/files/15226864/article-104610.json)
https://www.cvilletomorrow.org/it-was-once-his-familys-farm-the-largest-black-owned-farm-in-albemarle-county-but-now-we-all-own-part-of-it/

**Comment by kevinfodness** [comment]
I've confirmed this and I'm working on a fix.

**Comment by aharper-fox** [comment]
> I've confirmed this and I'm working on a fix.

Thank you!

**Comment by kevinfodness** [comment]
This will release with v2.5.0 of the plugin.
