### ISSUE TITLE
Caption shortcode tag appearing in excerpt metadata

### ISSUE THREAD

**Issue by kevinlisota** [alleyinteractive/apple-news#112]
Sometimes our articles begin with an image, and sometimes that image has a caption.

When a caption starts an article, the resulting caption shortcode will sometimes appear in the Apple News excerpt when showing our list of articles.

I believe this isn't being stripped before sending to the Apple News API. Obviously Apple News has no knowledge of a WP shortcode.

This looks like the problematic section:

```
metadata":{"excerpt":"[caption id=\"attachment_238259\" align=\"aligncenter\" width=\"630\"] Pathable's Jordan Schwartz spent three months working from Europe last spring. In Portugal, he had a view of the ocean as he looked toward the town of Salema. (Via Jordan Schwartz)[/caption]\r\n\r\n
```

**Comment by bcampeau** [comment]
Thanks for reporting. Will you be submitting a pull request to address this or are you asking us to fix it?
