### ISSUE TITLE
[Question]: state of plugin in comparison to fork

### ISSUE THREAD

**Issue by KLVTZ** [alleyinteractive/apple-news#113]
Question
=======
I see that this plugin is a current fork of [beezwax/WP-Publish-to-Apple-News][Beezwax]:

- Do we find ourselves merging this back into the fork version?
- How does this relate in terms of release lifecycle in comparison to [wordpress plugins][Wordpress]

[Beezwax]: https://github.com/beezwax/WP-Publish-to-Apple-News
[Wordpress]: https://wordpress.org/plugins/publish-to-apple-news/

**Comment by bcampeau** [comment]
1. Beezwax started this plugin, we have since taken it over. Our repository is the current official version and is endorsed by Apple.
2. Not sure I understand your question.

**Comment by KLVTZ** [comment]
@bcampeau thanks for replying back. 

In other words, I see that this plugin is actively maintained and supported but am unsure when this is released to the wordpress plugin site. I see that the current version is `1.0.5` and was updated about a month ago. But after grabbing it and doing it a comparison, there are some differences. Most obviously in the `tests` folder. Bootstrapping an `apple-export.php` file that no longer exists. Obviously, this has been fixed in this repo.

I was hoping we could embrace semantic versioning by tagging this repo. So if you iteratively make changes, you can prepare a release that would match the wordpress plugin site. Otherwise, I am unsure how far behind the wordpress plugin site is in comparison to this repository.

I made a similar suggestion on [FoundationPress theme][FoundationPress] with great results in predicting what is implemented in each release and how it relates to the wordpress plugin site.

[FoundationPress]: https://github.com/olefredrik/FoundationPress/releases

**Comment by bcampeau** [comment]
It's not uncommon for the github repo to be ahead of the WordPress.org or WordPress VIP versions. Check out any of Automattic's own plugins.

We can look at this for the next version. 1.0.6 should be out within the next week or less.
