### ISSUE TITLE
Setting "Show a publish meta box... Apple News enabled" to "No" does not hide the settings panel in Gutenberg.

### ISSUE THREAD

**Issue by surrealwebs** [alleyinteractive/apple-news#1136]
### Description of the bug

After setting the "Show a publish meta box on post types that have Apple News enabled." to "no" on the Settings page, we are expecting to hide the Settings sidebar panel in the Gutenberg editor, however, this is not the case. We are controlling all of the necessary settings through configuration and the presence of this panel is confusing authors.

### Steps To Reproduce

1. Install and configure the plugin (we are at version 2.4.8)
2. Select "post" as a supported post type.
3. Disable the meta box by setting the option to no.
4. Save the settings page.
5. Create a post and observe the plugin sidebar is accessible.

### Additional Information

Here are screenshots of out settings page and the existence of the settings bar.

We are currently running version 2.4.8 and are planning on updating soon, however, reviewing recent release notes it doesn't appear this has been addressed.

We are running WP 6.5 in a multisite configuration.

![an-settings-page](https://github.com/alleyinteractive/apple-news/assets/424134/af8db176-d844-453a-92fb-f4be87c19e7f)
![an-sidebar-active](https://github.com/alleyinteractive/apple-news/assets/424134/d2e45407-658c-4d2e-a6d1-b0a7dd40278f)

**Comment by renatonascalves** [comment]
That might be confusing but that setting is about the meta box for posts using the classic editor, not the block editor.

![CleanShot 2024-10-14 at 20 56 41@2x](https://github.com/user-attachments/assets/001ec441-6bda-4273-a3d7-f9a15ddcb7e1)

cc: @kevinfodness was it the goal to hide from the Block Editor too? The naming, meta box, tells me it was not, but trying to confirm just in case.

**Comment by kevinfodness** [comment]
There are certain configuration values that can only be set via this interface. Keeping it on in the block editor was by design. Individual users can hide it using the block editor controls, but disabling it entirely isn't something that we want to do at the plugin level.
