### ISSUE TITLE
Fatal Error, latest version `2.5.0`

### ISSUE THREAD

**Issue by zane-kanopi** [alleyinteractive/apple-news#1150]
### Description of the bug

Getting the following Fatal Error on plugin activation:
```
Fatal error: Uncaught Apple_Push_API\Request\Request_Exception: NOT_ALLOWED in /var/www/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php:285
```

### Steps To Reproduce

1. Install plugin.
2. Activate plugin.

**Comment by kevinfodness** [comment]
I'm not able to reproduce this on a fresh WordPress install. Is it possible to get more detailed logs, including what the source of the request was?

**Comment by jeremylind** [comment]
I am having the same issue on any page request on the site, front-end or admin, after updating to `2.5.0`. Here's a sample stack trace:
```
XXX.XXX.XX.X -  25/Jul/2024:18:17:55 +0000 "POST mydomain.com/wp-login.php" 500 /www/.wordpress/wp-login.php 81436048 11124080 368.382 10240 16.29%
[25-Jul-2024 18:17:56] WARNING: child 36878 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Apple_Push_API\Request\Request_Exception: NOT_ALLOWED in /www/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php:285"
[25-Jul-2024 18:17:56] WARNING: child 36878 said into stderr: "Stack trace:"
[25-Jul-2024 18:17:56] WARNING: child 36878 said into stderr: "#0 /www/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php(411): Apple_Push_API\Request\Request->parse_response(Array, true, 'get', NULL, NULL, '', '')"
[25-Jul-2024 18:17:56] WARNING: child 36878 said into stderr: "#1 /www/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php(138): Apple_Push_API\Request\Request->request('GET', 'https://news-ap...')"
[25-Jul-2024 18:17:56] WARNING: child 36878 said into stderr: "#2 /www/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/class-api.php(169): Apple_Push_API\Request\Request->get('https://news-ap...')"
[25-Jul-2024 18:17:56] WARNING: child 36878 said into stderr: "#3 /www/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/class-api.php(105): Apple_Push_API\API->send_get_request('https://news-ap...')"
[25-Jul-2024 18:17:56] WARNING: child 36878 said into stderr: "#4 /www/wp-content/plugins/publish-to-apple-news/admin/apple-actions/index/class-channel.php(29): Apple_Push_API\API->get_channel('f9..."
```

**Comment by smerriman** [comment]
Same here, with a fatal error on all pages of the site after upgrading to 2.5.

The plugin is making a request to a URL like https://news-api.apple.com/channels/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

with these parameters (have x-ed out the actual values):
```
(
    [reject_unsafe_urls] => 1
    [timeout] => 3
    [headers] => Array
        (
            [Authorization] => HHMAC; key=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx; signature=xxxxxx/xxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxx; date=2024-07-29T23:13:26+00:00
        )

    [method] => GET
)
```

**Comment by gd1jfas** [comment]
Having a similar Fatal error after updating to `2.5.0`. It happened when the API keys were updated (making the keys in the config outdated), this shouldn't cause a fatal error

```
Fatal error: Uncaught Apple_Push_API\Request\Request_Exception: API_KEY_NOT_FOUND in /code/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php:285 
Stack trace: 
#0 /code/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php(411): Apple_Push_API\Request\Request->parse_response(Array, true, 'get', NULL, NULL, '', '') 
#1 /code/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php(138): Apple_Push_API\Request\Request->request('GET', 'https://news-ap...')
#2 /code/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/class-api.php(169): Apple_Push_API\Request\Request->get('https://news-ap...') 
#3 /code/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/class-api.php(105): Apple_Push_API\API->send_get_request('https://news-ap...') 
#4 /code/wp-content/plugins/publish-to-apple-news/admin/apple-actions/index/class-channel.php(29): Apple_Push_API\API->get_channel('495e9796-29a6-4...') 
#5 /code/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/class-theme.php(368): Apple_Actions\Index\Channel->perform() 
#6 /code/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/class-theme.php(2105): Apple_Exporter\Theme::get_fonts() 
#7 /code/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/class-theme.php(1978): Apple_Exporter\Theme->validate() 
#8 /code/wp-content/plugins/publish-to-apple-news/includes/class-apple-news.php(1127): Apple_Exporter\Theme->set_value('cite_color', '#4f4f4f') 
#9 /code/wp-content/plugins/publish-to-apple-news/includes/class-apple-news.php(506): Apple_News->upgrade_to_2_5_0() 
#10 /code/wp-includes/class-wp-hook.php(324): Apple_News->action_plugins_loaded('') 
#11 /code/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array) 
#12 /code/wp-includes/plugin.php(517): WP_Hook->do_action(Array) 
#13 /code/wp-settings.php(555): do_action('plugins_loaded') 
#14 /code/wp-config.php(113): require_once('/code/wp-settin...') 
#15 /code/wp-load.php(50): require_once('/code/wp-config...') 
#16 /code/wp-blog-header.php(13): require_once('/code/wp-load.p...') 
#17 /code/index.php(17): require('/code/wp-blog-h...') 
#18 {main} thrown in /code/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php on line 285 
```

**Comment by smerriman** [comment]
Is this plugin abandoned? 2.5 was released 2 months ago and still causes an immediate fatal error on my site and others.. not very promising..

**Comment by kevinfodness** [comment]
No, the plugin is not abandoned. There are over 1,000 active installations of version 2.5.0 that are working without issue. I have tried, and have been unable, to reproduce this issue on a fresh installation and on an upgrade of an older installation. The error message indicates that you have an Apple News API key set in your database that is invalid. We can release a patch that prevents this error condition from causing a fatal, but you will need to set your API key to a valid value. If you have the ability to update your database, the API key is stored in the `wp_options` table using the `apple_news_settings` key. You can remove this option from the options table, which will clear the fatal and allow you to reset your API credentials to valid values.

**Comment by smerriman** [comment]
The most recent commenter above was related to invalid API keys; that may be a separate bug unrelated to the other reported here and replicated by others, which is NOT_ALLOWED. In this case, the API key is valid and works with prior versions of the plugin (indeed if I change to an invalid key, then the error changes.)

**Comment by kevinfodness** [comment]
The plugin is making a request to get information about your channel. This API request is new in version 2.5.0. It pulls the list of installed custom fonts on your channel (if any) to make them available in the theme editor. Apple's documentation about this endpoint does not list `NOT_ALLOWED` as a response code: https://developer.apple.com/documentation/apple_news/read_channel_information. The only explanation that makes any kind of sense is that your API key allows you to post articles to your channel but not read information about it, which could be a misconfiguration on Apple's side, and you should reach out to Apple News support about that. The best we can do in the plugin is to catch the fatal and surface an error message in the admin. I'll ship an update to that effect.

**Comment by smerriman** [comment]
Thank you. Yes, either way, it's definitely a critical bug for the plugin to take down the entire site if it receives unexpected information from Apple, so having it fail more gracefully will definitely be a step in the right direction.

**Comment by kevinfodness** [comment]
@zane-kanopi @jeremylind @smerriman @gd1jfas Version 2.5.1 has now been released which includes a fix for this error (whereby it will print an admin notice instead of triggering a fatal error). Please try this new version of the plugin and let me know if this resolves your issue.

**Comment by smerriman** [comment]
While this makes the error less apparent, it still doesn't actually resolve the true issue, so I'm putting in a support request to Apple as suggested.

However, regardless of their response, can you clarify why a call to the Apple News API needs to be performed when visitors access the front-end of the site - surely this is putting unnecessary load on the server?

(I see if it gets a successful response, it stores it as a transient for 5 minutes - but I'm still not sure why this has anything to do with front-end site access.)

**Comment by kevinfodness** [comment]
Under normal circumstances, that code should not be executing on the front-end. The only times it should be called are when attempting to save an Apple News theme (admin, logged in user, administrator permissions) or when the Apple News themes page or edit page is loaded (admin, logged in user, administrator permissions). However, sometimes version updates include necessary changes to how information is stored in the database, in which case we run an upgrade routine on `plugins_loaded` if the version of the plugin has changed (the "current" version is cached in the database, and that is compared to the version that the plugin reports). The upgrade to version 2.5.0 included a routine to update and migrate data in themes. Normally, this happens in the admin when an administrator upgrades to a new version of the plugin, although it's possible for this routine to run on the front-end if a front-end request happens to hit it before an admin request does. You're right that front-end requests should never be executing code like this, so I will file an issue to update the upgrade routine code so that it never executes on the front-end.
