### ISSUE TITLE
Email Error Notifications

### ISSUE THREAD

**Issue by teachernerd** [alleyinteractive/apple-news#1153]
### Description

Is there a way (beyond the failure messages that appear in the WP dashboard) to alert a channel admin via email when a post fails to publish to Apple News?

**Comment by renatonascalves** [comment]
@teachernerd See the #1180 pull request for a possible solution here. I'm adding a hook that fires when a post fails to be pushed to Apple News.

Any developer can use the action to send a notification, an email, etc. :)

**Comment by teachernerd** [comment]
That sounds like exactly what we need. Thank you!
