### ISSUE TITLE
Root-Relative Image URLs Use Wrong Function for Base URL

### ISSUE THREAD

**Issue by ptpittman** [alleyinteractive/apple-news#1157]
### Description of the bug

I have a production site using the [Roots Bedrock](https://roots.io/bedrock/) Wordpress boilerplate. Bedrock moves several things around but the pertinent one here is that Wordpress functionality is moved to a /wp url on the front end (ie /wp/wp-admin), with a redirect to this from the standard locations.  And image uploads are served from /app/uploads, rather than the standard wp-content location. 

All works fine for pushing articles to Apple News, _except_ if an article contains an inline image block. These throw errors because they attempt to read images from a URL beginning with “/wp/app/uploads”, rather than “/app/uploads” – somewhere in there the URL is getting rewritten to add the /wp, even though this is not present in the actual content.

The error received is: 

`There has been an error with the Apple News API: INVALID_DOCUMENT - Unable to read uri [https://(site.com)/wp/app/uploads/2024/09/(xxx).jpeg], `

This URL is a 404, it is correct without the /wp (ie just /app/uploads/2024...). The error repeats once for each inline image in the article.

This same issue does _not_ occur for featured/thumbnail images, only for articles with inline ones.

I can hack around this with a redirect to the correct URL at the nginx level, but it seems like this plugin is using the wrong hook to get a base URL somewhere deep in there... 

### Steps To Reproduce

1. Deploy a basic [Bedrock](https://roots.io/bedrock/) boilerplate site.
2. Post an article which contains an inline image anywhere in the block editor.
3. Attempt to publish to Apple News.

# Acceptance Criteria

* Update the plugin to replace instances of `site_url` with `home_url` in cases where we're creating full URLs out of root-relative URLs (see https://github.com/search?q=repo%3Aalleyinteractive%2Fapple-news%20site_url&type=code)

**Comment by kevinfodness** [comment]
My guess here is that Bedrock is doing something different in a frontend context vs. an admin one, and Apple News article generation happens in an admin context. Can you copy the blocks for the post (ideally out of the `post_content` column in the database, but you can also do copy all blocks from the block editor) and paste it here so I can see the source of what the plugin is working with when it attempts to translate the article from blocks to Apple News format?

**Comment by ptpittman** [comment]
For sure. Here’s a real world example ([taken from this page](https://threemagazine.com/culture/5-must-watch-movies-coming-to-tiff-this-year/)):


One of the relevant image blocks pasted from block editor:
```
<!-- wp:image {"id":992,"sizeSlug":"large","linkDestination":"none","className":"is-style-full"} -->
<figure class="wp-block-image size-large is-style-full"><img src="/app/uploads/2024/09/The_Mother_and_the_Bear_Still_Hero-1024x512.jpeg" alt="" class="wp-image-992"/></figure>
<!-- /wp:image -->

```

This is that same post selected directly out of mysql post_content column: [example-post-content.txt](https://github.com/user-attachments/files/16936129/example-post-content.txt)

The links in both definitely don’t have the /wp, so that’s coming from somewhere else along the processing pipeline...

**Comment by kevinfodness** [comment]
It's coming from here: https://github.com/alleyinteractive/apple-news/blob/develop/includes/apple-exporter/class-exporter-content.php#L111

Because Apple News needs a full URL, it takes root-relative URLs (like in your example) and passes it through `site_url` which Bedrock defines as being prefixed with `wp` in the `.env` file, per the example here: https://github.com/roots/bedrock/blob/a7500124f6b872b1bad31742e3dd7d3659514dc4/.env.example#L15

We should update the plugin to use `home_url` here instead of `site_url` since `home_url` points to the front end of the website but `site_url` doesn't necessarily. We'll get this queued up for the next release. In the meantime, you can filter the JSON that the plugin produces using the [apple_news_generate_json filter](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_generate_json) to remove the `/wp/` segment yourself.

**Comment by kevinfodness** [comment]
Thanks for catching this bug!

**Comment by ptpittman** [comment]
Amazing, appreciate the super swift investigation!!

**Comment by mogmarsh** [comment]
@kevinfodness we should definitely test a stock WordPress install with WordPress in a subfolder, just to make sure that works as well. I think in that case we might want `site_url`... maybe we just need to add a filter to what we currently have.
The use case I have in mind is [this setup](https://developer.wordpress.org/advanced-administration/server/wordpress-in-directory/)

**Comment by ptpittman** [comment]
Does that [apple_news_generate_json filter](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_generate_json) run before or after the format_src_url function that’s causing this? My attempt at doing a search and replace within that filter doesn’t appear to be preventing the error, so I’m guessing maybe it’s happening before this point? (Or alternatively i’m just not understanding the structure of that json array... Also possible.)

**Comment by kevinfodness** [comment]
That filter runs after. It should be the final JSON that is sent to Apple.

**Comment by ptpittman** [comment]
Right, so in this case we never get there because the error occurs before. I can kludge it with a server redirect for now I think, until you get the fix rolled out.

**Comment by kevinfodness** [comment]
That error shouldn't occur until the JSON is sent to Apple, and this hook fires immediately before, so you should have an opportunity to correct it before it goes out. However, you're right that a server redirect should also be able to solve the problem on a temporary basis.
