### ISSUE TITLE
No Save Button Functioning, Settings Page

### ISSUE THREAD

**Issue by matfleaydaly** [alleyinteractive/apple-news#119]
Title says it all. Latest update 1.0.6 has caused the settings page to have no ability to save. Therefor the plugin will not work for new installations or for installations that wish to make changes in the settings page.
Overall the save button is just not present.
Could we please have a fix ASAP guys :)
Cheers!

**Comment by bcampeau** [comment]
This was resolved in version 1.0.7 and the latest `master` branch here.
