### ISSUE TITLE
Error in Component Order section in settings

### ISSUE THREAD

**Issue by markbattistella** [alleyinteractive/apple-news#121]
Receiving the error:

**Component Order**
`Fatal error: Using $this when not in object context in /public_html/_wp/wp-content/plugins/publish-to-apple-news/admin/settings/class-admin-apple-settings-section-formatting.php on line 233`

But the sections of the text above are moveable objects.

**Comment by bcampeau** [comment]
This was resolved in version 1.0.7 and the latest `master` branch here.
