### ISSUE TITLE
Error in page load for list of published articles

### ISSUE THREAD

**Issue by markbattistella** [alleyinteractive/apple-news#122]
I received the error on the first article, but have had it midway down the list before. Only way to fix at the moment is to clear the db table from this post.

`Fatal error: Uncaught exception 'Apple_Push_API\Request\Request_Exception' with message 'NOT_FOUND' in /public_html/_wp/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php:201 Stack trace: #0 /public_html/_wp/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php(157): Apple_Push_API\Request\Request->parse_response(Array, true, 'get') #1 /public_html/_wp/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/class-api.php(158): Apple_Push_API\Request\Request->get('https://u48r14....') #2 /public_html/_wp/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/class-api.php(103): Apple_Push_API\API->send_get_request('https://u48r14....') #3 /public_html/_wp/wp-content/plugins/publish-to-apple-news/admin/apple-actions/index/class-get.php(44): Apple_Push_API\API->get_article('0c8d4af2-d071-4...') #4 /public_html/_wp/wp-content/plugins/publish-to-apple-news in /public_html/_wp/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php on line 201`

**Comment by bcampeau** [comment]
`NOT_FOUND` indicates that you are trying to access an invalid endpoint in the API. I would need more information on the articles and especially the `apple_news_` postmeta values stored for it to provide any insight here.

**Comment by markbattistella** [comment]
I know from that article it was using another plugin [page_link_to](https://wordpress.org/plugins/page-links-to/) and a little excerpt. It also had a custom shortcode.

    apple_news_api_created_at       2016-03-27T09:37:45Z
    apple_news_api_id               0c8d4af2-d071-4404-87cd-58ff66b5cf1f
    apple_news_api_modified_at      2016-03-27T09:39:24Z
    apple_news_api_revision         AAAAAAAAAAAAAAAAAAAAAA==
    apple_news_api_share_url        https://apple.news/ADI1K8tBxRASHzVj_ZrXPHw

This is all the data for this post. I understand the plugin is causing the issue here, but on other posts I have had I can't see.

**Comment by markbattistella** [comment]
#123 may be a cause to this

**Comment by bcampeau** [comment]
We just committed a fix to the `master` branch that resolves this if you'd like to pull the latest.

It will be released to WP.org and VIP with version 1.0.8.
