### ISSUE TITLE
Published Date/Time Suggestion

### ISSUE THREAD

**Issue by matfleaydaly** [alleyinteractive/apple-news#126]
G'day there,
After updating from the RSS Feed to the new Apple News Format i've been republishing my articles via this plugin.
It seems that when i publish them it appears on Apple News as they were published when i clicked publish instead of when i made the original post.
Stupid question but is there anyway that there might be an option to be able to match the publish date the post publish date?
Cheers in advanced!

**Comment by bcampeau** [comment]
We'll look into this for you

**Comment by matfleaydaly** [comment]
Appreciate the assistance mate!

**Comment by bcampeau** [comment]
We'll be adding the date metadata to the plugin in the next version. Currently, Apple will always show the publish date as the time you push the post to their API but they'll soon be respecting this metadata to allow you to push in older content but not have it show at the top of your feed.

**Comment by bcampeau** [comment]
Closing this in favor of #108
