### ISSUE TITLE
Any way to add custom fonts?

### ISSUE THREAD

**Issue by chrisdmacrae** [alleyinteractive/apple-news#128]
I've done a pretty good job of writing my own components for the plugin using the hooks provided. 

Wondering if similar functionality exists for the bundles. I've tried digging, but debugging workspaces is a challenge.

If there was a hook that I could add the URLs into as the bundles are created and then move the font files to the tmp directory by hand at the same time, that would work.

Thanks!

**Comment by bcampeau** [comment]
All you need to do is add the fonts to the workspace. This could be accomplished using the filter `apple_news_get_bundles`: 

https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-exporter/class-workspace.php#L125

**Comment by chrisdmacrae** [comment]
Gave this a go but I have no idea how to specify the content-type information for the file. I'm receiving the error `UNSUPPORTED_MEDIA_TYPE` which I'm assuming is because the content-type for the font-files isn't set to application/octet-stream

**Comment by bcampeau** [comment]
Can you please provide the entire bundle, images, font files and the JSON file?

Thanks.

**Comment by chrisdmacrae** [comment]
Hey Bradford, here is a zip of a working apple news debugger bundle.

[Apple News Tester.zip](https://github.com/alleyinteractive/apple-news/files/208452/Apple.News.Tester.zip)

Inside is article.json, all of the fonts, and the two images in the test article. There is also a bundle.json to show you the json encoded value of `$bundles` just before it goes out to the Apple News endpoint. 

Caveat is that this is an article drafted on my local environment so the URLs are all local. localhost:80 can be replaced with mindsea.com if needed.

**Comment by bcampeau** [comment]
Thanks, this may take a bit to get to in the queue to debug but I'll let you know.

**Comment by danielbachhuber** [comment]
@chrisdmacrae Were you able to get custom fonts working? If so, do you submit the font file as a part of the publishing payload, or does it need to be whitelisted by Apple?

**Comment by webdeveric** [comment]
@bcampeau @danielbachhuber I'm building out a design for work and it uses custom fonts. I asked our Apple contact about it and they asked me to email the fonts so they can upload them to our channel manually. They do not currently accept fonts via the API.

**Comment by kevinfodness** [comment]
Closing this issue as it needs to be handled by Apple. Once the font has been added by Apple on their end, you can simply reference it by name in the JSON you send.

**Comment by jtyarks** [comment]
Apologies for following up on this closed item, but I'd like to clarify how to properly add custom fonts to a project. The April 2016 reply mentions modifying the workspace, while the March 2017 reply says it simply needs to be referenced in the JSON after submitting fonts to Apple.

Steps taken to date:

1. I submitted the font files to Apple, and they confirmed they had been uploaded to their backend 

2. I modified the font list to include said fonts as options:

```
function custom_fonts( $fonts ) {
    $fonts[] = 'Lora-Regular';
    $fonts[] = 'Lora-Bold';
    $fonts[] = 'Lora-BoldItalic';
    $fonts[] = 'Lora-Italic';
    $fonts[] = 'OpenSans-Bold';
    $fonts[] = 'OpenSans-Italic';
    $fonts[] = 'OpenSans-Regular';

    return $fonts;
}
add_filter( 'apple_news_fonts_list', 'custom_fonts' );
```

3. I selected the new fonts from the Theme editor

4. I downloaded an article and confirmed via the News Preview app that the custom fonts display

When I submit an article to Apple News, however, I'm seeing errors for each component that say the fonts are missing:

> There has been an error with the API:
> INVALID_DOCUMENT - Custom font
> OpenSans-Bold
> not found. (keyPath components->1->components->0)
> INVALID_DOCUMENT - Custom font
> Lora-Regular
> not found. (keyPath components->1->components->4)

I assumed this meant that the first response about bundling the fonts with the workspace was correct, so I added code to do so:

```
function custom_bundle( $post_meta = null, $ID = null ) {

    if ( null === $ID ) {
      global $post;
      $ID = $post->id;
    }

    if ( null === $post_meta ) {
      $post_meta = get_post_meta( $ID, 'apple_news_api_bundle' );
    }

    $post_meta[] = "path/to/fonts/Lora-Regular.ttf";
    $post_meta[] = "path/to/fonts/Lora-Bold.ttf";
    $post_meta[] = "path/to/fonts/Lora-BoldItalic.ttf";
    $post_meta[] = "path/to/fonts/Lora-Italic.ttf";
    $post_meta[] = "path/to/fonts/OpenSans-Bold.ttf";
    $post_meta[] = "path/to/fonts/OpenSans-Italic.ttf";
    $post_meta[] = "path/to/fonts/OpenSans-Regular.ttf";

    return $post_meta;
}
add_filter( 'apple_news_get_bundles', 'op_bundle' ); 
```

...but, I'm still receiving the same API errors.

I can go back to Apple to ensure they uploaded the fonts but, assuming they did, is there something silly I'm missing here?

Many thanks.
