### ISSUE TITLE
Nested images are ignored

### ISSUE THREAD

**Issue by chrisdmacrae** [alleyinteractive/apple-news#129]
Consider the following markup:

``` html
<ul>
    <li>
        <img class="wp-image-4709 size-medium alignright" src="http://www.mindsea.com/wp-content/uploads/2013/06/img_autoLayout_sizeClasses-1-300x241.png" alt="auto layout and size classes" width="300" height="241">
        Select the first tab &nbsp;in the right panel and uncheck <strong>Use&nbspAuto Layout</strong>. This will remove constraints and simplify working in Interface Builder for beginners.
    </li>
<ul>
```

The text nodes inside the `<li>` are rendered, but the image is not.

**Comment by bcampeau** [comment]
Can you please provide a link to the post on your site that's experiencing this issue?

**Comment by chrisdmacrae** [comment]
Absolutely. See the link below. Anywhere the images are shown within the list items, they are ignored.

http://www.mindsea.com/2016/02/mobile-prototyping-for-designers-with-xcode-storyboards/
