### ISSUE TITLE
Check support of non-oEmbed YouTube/Vimeo videos

### ISSUE THREAD

**Issue by bcampeau** [alleyinteractive/apple-news#132]
See:

https://wordpress.org/support/topic/youtube-vimeo-videos
https://wordpress.org/support/topic/embedded-videos-stripped-out-on-publish

**Comment by bcampeau** [comment]
Also confirm support for all short link formats.

**Comment by benmillett** [comment]
Not sure if you'd rather have examples here or in the WP support pages. I'm having embedded videos stripped out.

[Example post](http://blog.benmillett.us/alone-part-3-i-am-a-rock/)
This is the embeded iframe that is stripped:
`<div class="embedcenter"><iframe title="YouTube video player" width="640" height="360" src="http://www.youtube.com/embed/J2nN-Yrt1EU?rel=0&iv_load_policy=3" frameborder="0" allowfullscreen></iframe></div>`

The publish message says both the iframe and div are stripped. If I change to just the iframe, it still gets stripped. The JSON shows no trace of there having been any iframe/embed there.

**Comment by bcampeau** [comment]
Correct, this is the issue we'll be resolving.

**Comment by benmillett** [comment]
Thanks for this fantastic plugin. With everything that is entailed with publishing to Apple News, this is certainly a lifesaver. I know other people have been reporting this issue so I wasn't sure if you needed (yet another) example or not.
I did just try to remove the div to the following and republish.
`<iframe title="YouTube video player" width="640" height="360" src="http://www.youtube.com/embed/J2nN-Yrt1EU?rel=0&iv_load_policy=3" frameborder="0" allowfullscreen class="embedcenter"></iframe>`
I get an error with this json (which I'm sure you have copies of already from other people):
Array
(
   [headers] => Array
       (
           [date] => Wed, 13 Apr 2016 01:56:26 GMT
           [request-id] => 50f28bf2-1e68-4de4-98c8-a6926ea8667a
           [content-type] => application/json; charset=UTF-8
           [content-length] => 316
           [connection] => keep-alive
       )

   [body] => {"errors":[{"code":"INVALID_DOCUMENT","keyPath":["root","components","[3]","URL"],"value":"null","message":"\"URL\" was <null> should be valid URL with one of [\"http\",\"https\"] scheme(s)"},{"code":"INVALID_DOCUMENT","keyPath":["root","components","[3]"],"message":"no components defined for role=embedwebvideo"}]}
   [response] => Array
       (
           [code] => 400
           [message] => Bad Request
       )

   [cookies] => Array
       (
       )
   [filename] => 
)

**Comment by bcampeau** [comment]
This issue has been reported in detail, thanks. It will be investigated and resolved when it comes up in queue.

**Comment by bcampeau** [comment]
This has been moved up for review and inclusion in the version 1.0.8 release.

**Comment by benmillett** [comment]
Thanks!

**Comment by bcampeau** [comment]
This is now resolved in the latest master branch and will be released soon as version 1.0.8.

**Comment by benmillett** [comment]
Thanks for fixing this! It is working for me now.

**Comment by bcampeau** [comment]
Glad to hear

**Comment by benmillett** [comment]
Is this a known embed format that's supposed to be working? I copied it from the vimeo video page and pasted it into a post that also has a youtube video. YouTube video publishes, this vimeo one does not. I've tried both versions below and both fail. The YouTube that works is wrapped in a div like the second vimeo code below.
```
<iframe src="https://player.vimeo.com/video/90380576?color=669933&portrait=0" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<div class="embedcenter"><iframe src="https://player.vimeo.com/video/90380576?portrait=0&amp;color=669933" title="Vimeo video player" width="640" height="360" frameborder="0" allowfullscreen></iframe></div>
```

**Comment by benmillett** [comment]
Ignore my comment. The fix in pull 156 addresses my issue. https://github.com/alleyinteractive/apple-news/pull/156
