### ISSUE TITLE
Review caption alignment

### ISSUE THREAD

**Issue by bcampeau** [alleyinteractive/apple-news#133]
Ensure this is local to this site and not a general issue: https://wordpress.org/support/topic/image-caption-formatting-is-message-up?replies=3#post-8239039

**Comment by vincepettit** [comment]
I've noticed this bug too

**Comment by vincepettit** [comment]
Here's some examples of the bug, the first and third images show the caption in the wrong place, the second image (in the same article) shows the caption in the correct place!

![image1](https://cloud.githubusercontent.com/assets/530457/14815610/4d4ef4dc-0ba4-11e6-8662-2b51b3edb984.PNG)
![image3](https://cloud.githubusercontent.com/assets/530457/14815609/4d4e80b0-0ba4-11e6-95c5-fc33426cc928.PNG)
![image2](https://cloud.githubusercontent.com/assets/530457/14815608/4d4e672e-0ba4-11e6-8318-f28f5c5ca1e9.PNG)

**Comment by vincepettit** [comment]
Any progress on this?

**Comment by bcampeau** [comment]
Some other folks have mentioned this, but we have had other priorities ahead of it in the queue.

**Comment by bcampeau** [comment]
We'll also be adding styling options for captions as part of this.

**Comment by kevinfodness** [comment]
The first component of this (captions being kept with the image) has been fixed in a prior version. For 1.2.2 we will be adding caption styling options.
