### ISSUE TITLE
Review handling of URLs in the post body

### ISSUE THREAD

**Issue by santsys** [alleyinteractive/apple-news#148]
I'm receiving an "INVALID_DOCUMENT" error when publishing various posts. Attached is the JSON. I was unable to see anything specifically wrong with the document.

[article-2692.zip](https://github.com/alleyinteractive/apple-news/files/214080/article-2692.zip)

**Comment by santsys** [comment]
From the detailed error report, this appears to be from improper handling for URLs that are not complete, for example, '/blog/post/' instead of 'http://www.site.com/blog/post'.

**Comment by biruk360** [comment]
The plugin is super help but facing the same problem, when do you think this will be resolved.
Thanks.

**Comment by bcampeau** [comment]
As an update, this will also resolve issues with anchor links which are not currently supported by Apple News.

**Comment by bcampeau** [comment]
We should also handle trimming URL in case spaces are incorrectly added in HTML. Browsers will ignore that, but Apple News won't).

**Comment by bcampeau** [comment]
Also see: https://wordpress.org/support/topic/getting-closer-but-url-issues

**Comment by vendruscolo** [comment]
Hi there, any news on this issue?

**Comment by bcampeau** [comment]
We will provide an update on the milestone date in the next two weeks.
