### ISSUE TITLE
INVALID_DOCUMENT Error

### ISSUE THREAD

**Issue by OPPtester** [alleyinteractive/apple-news#152]
All of a sudden, when I tried to publish an article I got this error:

There has been an error with the API. Please make sure your API settings are correct and try again: INVALID_DOCUMENT

All was working fine and I was able to publish 3 articles earlier this AM. I can access iCloud and see published articles, all seem to be fine.

Please advise.

Thanks,

**Comment by OPPtester** [comment]
Tested by publishing another article and that was successful. The problem article has an unordered list not sure if that's making it invalid.

**Comment by bcampeau** [comment]
Can you please post the JSON that's generated for that article as well as the HTML for it from the "Text" tab in the WordPress editor? We'll look into it.

**Comment by OPPtester** [comment]
Sure thing:

`{"version":"1.1","identifier":"post-22094","language":"en","title":"Chipotle Mexican Grill (CMG) Shareholder Calls for Board Shakeup","documentStyle":{"backgroundColor":"#FFFFFF"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"title","text":"Chipotle Mexican Grill (CMG) Shareholder Calls for Board Shakeup","textStyle":"default-title"},{"role":"container","layout":"headerContainerLayout","style":{"fill":{"type":"image","URL":"bundle:\/\/Chipotle_Grill.jpg","fillMode":"cover"}},"behavior":{"type":"background_parallax"}},{"role":"byline","text":"by Marie Cabural | Apr 13, 2016 | 12:51 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"body","text":"CtW Investment Group is calling for a Board shakeup at Chipotle Mexican Grill (NYSE:CMG) citing the reason that the company\u2019s stock price declined nearly 40% due to negative headlines and federal investigations over the last three quarters.\n\nThe investment group said the company failed to effectively address governance and shortcomings, and noted that its flawed recruitment process resulted in an \u201centrenched and insular Board with a startling lack of racial and gender diversity.\u201d","format":"markdown","textStyle":"dropcapBodyStyle","layout":"body-layout"},{"role":"heading4","text":"Chipotle shareholders\u2019 immediate concerns","format":"markdown","textStyle":"default-heading-4","layout":"heading-layout"},{"role":"body","text":"The investment group said immediate concerns of investors include the following:\n\n- Chipotle is facing slowing momentum and potential growth challenges going forward and needs a genuinely independent oversight.\n- The company has persistent governance problems including excessively long director tenures and low demographic diversity\n- The Board is refusing to adopt a meaningful form of proxy access despite 49.9% shareholder support","format":"markdown","textStyle":"default-body","layout":"body-layout"},{"role":"heading4","text":"CtW encouraged shareholders to replace two incumbent directors","format":"markdown","textStyle":"default-heading-4","layout":"heading-layout"},{"role":"body","text":"CtW Investment encouraged Chipotle shareholders [not to support the reelection of Patrich Flynn and Darlene Friedman](\/Users\/Marie\/Pictures\/CMG_Final_April13.pdf), the long-term incumbents of the Nominating and Corporate Governance Committee of the company\u2019s Board.\n\nAccording to Dieter Waizenegger, executive director of CtW Investment, Flynn and Friedman \u201cmust be held accountable for failing to sufficiently refresh the Board and failing to bring about attentive, independent, and diverse oversight of management that shareholders deserve.\u201d\n\nHe encouraged Chipotle shareholders to intervene now.\u00a0 He believes that Chipotle can overcome its problems on effective leadership and growth if the Board is refreshed with new voices.\n\n\u201cWe strongly believe that demographic diversity in the boardroom leads to healthier debates, better decisions and greater adaptability to change. Empirical studies have also found a positive relationship between company performance and greater board diversity,\u201d said Waizenegger.\n\n\u201cChipotle\u2019s long-term outlook depends on a strong, independent and diverse board equipped to provide rigorous and forward-thinking oversight. Refreshment is the first step. To reverse the course of stagnation and implement serious refreshment, I urge you to join us in opposing the reelection of directors Flynn and Friedman on May 11, 2016,\u201d he said.","format":"markdown","textStyle":"default-body","layout":"body-layout"}],"componentTextStyles":{"dropcapBodyStyle":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"lineHeight":24,"textColor":"#000000","linkStyle":{"textColor":"#428bca"},"dropCapStyle":{"numberOfLines":2,"numberOfCharacters":1,"fontName":"Georgia-Bold","textColor":"#000000"}},"default-body":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"lineHeight":24,"textColor":"#000000","linkStyle":{"textColor":"#428bca"}},"default-heading-4":{"fontName":"AvenirNext-Bold","fontSize":21,"lineHeight":52,"textColor":"#000000","textAlignment":"left"},"default-title":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"textColor":"#000000","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"AvenirNext-Medium","fontSize":17,"textColor":"#53585f"}},"componentLayouts":{"body-layout":{"columnStart":0,"columnSpan":5,"margin":{"top":25,"bottom":25}},"heading-layout":{"columnStart":0,"columnSpan":7,"margin":{"top":15,"bottom":15}},"headerContainerLayout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true,"minimumHeight":"50vh","margin":{"top":0,"bottom":25}},"byline-layout":{"columnStart":0,"columnSpan":7,"margin":{"top":10,"bottom":10}}},"metadata":{"excerpt":"CtW Investment Group is calling for a Board shakeup at Chipotle Mexican Grill (NYSE:CMG) citing the reason that the company\u2019s stock price declined nearly 40% due to negative headlines and federal investigations over the last three quarters.\r\n\r\nThe investment group said the company failed to effectively address governance and shortcomings, and noted that its flawed recruitment process resulted in an \u201centrenched and insular Board with a startling lack of racial and gender diversity.\u201d\r\nChipotle shareholders\u2019 immediate concerns\r\nThe investment group said immediate concerns of investors include the following:\r\n\r\n\tChipotle is facing slowing momentum and potential growth challenges going forward and needs a genuinely independent oversight.\r\n\tThe company has persistent governance problems including excessively long director tenures and low demographic diversity\r\n\tThe Board is refusing to adopt a meaningful form of proxy access despite 49.9% shareholder support\r\n\r\nCtW encouraged shareholders to replace two incumbent directors\r\nCtW Investment encouraged Chipotle shareholders not to support the reelection of Patrich Flynn and Darlene Friedman, the long-term incumbents of the Nominating and Corporate Governance Committee of the company\u2019s Board.\r\n\r\nAccording to Dieter Waizenegger, executive director of CtW Investment, Flynn and Friedman \u201cmust be held accountable for failing to sufficiently refresh the Board and failing to bring about attentive, independent, and diverse oversight of management that shareholders deserve.\u201d\r\n\r\nHe encouraged Chipotle shareholders to intervene now.\u00a0 He believes that Chipotle can overcome its problems on effective leadership and growth if the Board is refreshed with new voices.\r\n\r\n\u201cWe strongly believe that demographic diversity in the boardroom leads to healthier debates, better decisions and greater adaptability to change. Empirical studies have also found a positive relationship between company performance and greater board diversity,\u201d said Waizenegger.\r\n\r\n\u201cChipotle\u2019s long-term outlook depends on a strong, independent and diverse board equipped to provide rigorous and forward-thinking oversight. Refreshment is the first step. To reverse the course of stagnation and implement serious refreshment, I urge you to join us in opposing the reelection of directors Flynn and Friedman on May 11, 2016,\u201d he said.","thumbnailURL":"bundle:\/\/Chipotle_Grill.jpg","canonicalURL":"http:\/\/www.opptrends.com\/2016\/04\/chipotle-shareholder-board-shakeup\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"1.0.7"},"advertisingSettings":{"frequency":1,"layout":{"margin":{"top":15,"bottom":15}}}}`

And for the HTML, I hope this is what you wanted:

`CtW Investment Group is calling for a Board shakeup at Chipotle Mexican Grill (NYSE:CMG) citing the reason that the company’s stock price declined nearly 40% due to negative headlines and federal investigations over the last three quarters.

The investment group said the company failed to effectively address governance and shortcomings, and noted that its flawed recruitment process resulted in an “entrenched and insular Board with a startling lack of racial and gender diversity.”
<h4>Chipotle shareholders’ immediate concerns</h4>
The investment group said immediate concerns of investors include the following:
<ul>
	<li>Chipotle is facing slowing momentum and potential growth challenges going forward and needs a genuinely independent oversight.</li>
	<li>The company has persistent governance problems including excessively long director tenures and low demographic diversity</li>
	<li>The Board is refusing to adopt a meaningful form of proxy access despite 49.9% shareholder support</li>
</ul>
<h4><strong>CtW encouraged shareholders to replace two incumbent directors</strong></h4>
CtW Investment encouraged Chipotle shareholders <a href="/Users/Marie/Pictures/CMG_Final_April13.pdf">not to support the reelection of Patrich Flynn and Darlene Friedman</a>, the long-term incumbents of the Nominating and Corporate Governance Committee of the company’s Board.

According to Dieter Waizenegger, executive director of CtW Investment, Flynn and Friedman “must be held accountable for failing to sufficiently refresh the Board and failing to bring about attentive, independent, and diverse oversight of management that shareholders deserve.”

He encouraged Chipotle shareholders to intervene now.  He believes that Chipotle can overcome its problems on effective leadership and growth if the Board is refreshed with new voices.

“We strongly believe that demographic diversity in the boardroom leads to healthier debates, better decisions and greater adaptability to change. Empirical studies have also found a positive relationship between company performance and greater board diversity,” said Waizenegger.

“Chipotle’s long-term outlook depends on a strong, independent and diverse board equipped to provide rigorous and forward-thinking oversight. Refreshment is the first step. To reverse the course of stagnation and implement serious refreshment, I urge you to join us in opposing the reelection of directors Flynn and Friedman on May 11, 2016,” he said.`

**Comment by OPPtester** [comment]
Found the issue. There's an incomplete URL/Link in the content by the author which I overlooked. Once removed, the post was published with no issues.

Had to look into it again after publishing another post with unordered list and was OK, so I figured that can't be it.

Apologies for the false alarm :-)
