### ISSUE TITLE
Table handling in Apple News

### ISSUE THREAD

**Issue by bcampeau** [alleyinteractive/apple-news#153]
How can we translate HTML tables to Apple News?

See: https://wordpress.org/support/topic/shortcodes-layout-options

**Comment by vincepettit** [comment]
Any news on tables in Apple News?

**Comment by bcampeau** [comment]
Issues are prioritized based on the top priorities across all sites and to date, you're the only one who has brought this up so we haven't been able to move this up the list. The plugin is open source and we accept pull requests from the community if you'd like to make your own contribution to get this moving faster. Unfortunately I can't offer more than that at this time.

**Comment by justintylermoore** [comment]
I second Vince. I will start working on a solution. I need to send a pull request for a couple of improvements I have made, including a new column in the list page for "section".

**Comment by bcampeau** [comment]
We'll be happy to review any pull requests for inclusion. Keep in mind we'll be looking for adherence to [WordPress](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [WordPress VIP](https://vip.wordpress.com/documentation/vip/best-practices/) coding standards.

Thanks!

**Comment by kevinfodness** [comment]
Closing this issue in favor of #430 now that table support has been officially added as of iOS11.
