### ISSUE TITLE
Apple Status NOT_FOUND; Sync Status Published

### ISSUE THREAD

**Issue by randyrants** [alleyinteractive/apple-news#157]
I'm in what appears to be a strange state: my articles are not in iCloud and that shows up as "NOT_FOUND" in the Apple News plugin list of articles, which is correct.  However, the Sync Status still shows as "Published" so no matter how many times I click "publish" the articles don't get sent over.

Is there a way to reset the Publish status for the articles in the system?  I've removed the plug in - and all the data - but it appears that the status values don't get removed.

Not opposed to running a SQL script as well; just don't know which flag or where to run it.

**Comment by bcampeau** [comment]
We already have #117 open to address this.

In the meantime, just manually remove any post meta values starting with `apple_news_` to clear status and republish.

**Comment by randyrants** [comment]
Oops - sorry - didn't see the existing bug!  Bad user, no cookie.

Which table should I be looking for that in?  Thanks!

**Comment by bcampeau** [comment]
wp_postmeta

**Comment by randyrants** [comment]
Thanks!  Got me back to a good state.
