### ISSUE TITLE
Sponsored posts - need access to post ID in apple_news_api_post_meta

### ISSUE THREAD

**Issue by smerriman** [alleyinteractive/apple-news#162]
Apple requires setting an isSponsored flag as metadata on sponsored posts. While the plugin provides an apple_news_api_post_meta filter to add your own meta, it doesn't provide any reference to the post ID, making it impossible to tell whether the post should be sponsored or not. Using global $post is unlikely to work as the plugin doesn't appear to set up post data in the global variable anywhere.

Can the post ID be passed through to this filter somehow?

**Comment by bcampeau** [comment]
That's a good point. I'm realizing now the original developers didn't pass the post ID down the chain so there are a few levels to negotiate here. If we can't get this into 1.1, we'll definitely get it into 1.1.1.

Also we should probably just add support for isSponsored directly in the plugin.

**Comment by bcampeau** [comment]
@smerriman this issue got bounced around a lot, but it will definitely make it into the next version
