### ISSUE TITLE
Automated publishing to sections

### ISSUE THREAD

**Issue by bcampeau** [alleyinteractive/apple-news#167]
Consider auto mapping of categories to sections or allowing to set a default section to publish to. This also includes mapping themes as defined in #180 to categories.

**Comment by danielbachhuber** [comment]
@bcampeau Is it possible to include the section by filtering `apple_news_generate_json`? Or is publishing to a specific section out of scope currently?

**Comment by bcampeau** [comment]
@danielbachhuber You can choose the section to publish to now via the checkboxes provided on both the meta box and the publish screen from the Apple News list view. This ticket is intended to allow automatic mapping to sections based on category.

If you mean a programmatic solution for mapping in the meantime, sections are passed in via the API request and you can filter those meta values using `apple_news_api_post_meta`: https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-push-api/request/class-request.php#L303

We've only just added `$post_id` to that filter so if you're not running the latest github master, FYI.

Alternatively, if you save the Apple News sections in the post meta value `apple_news_sections` the plugin will just pick them up automatically on publish: https://github.com/alleyinteractive/apple-news/blob/master/admin/apple-actions/index/class-push.php#L167-L171

**Comment by danielbachhuber** [comment]
> You can choose the section to publish to now via the checkboxes provided on both the meta box and the publish screen from the Apple News list view.

Ah — missed that because I don't have the API key set locally :( Thanks!

**Comment by bcampeau** [comment]
Exactly. Once you have the API info set, it automatically pulls in all sections created in Apple News. Note there's a cache so you might not see new sections immediately.
