### ISSUE TITLE
Fatal error: Can't use method return value in write context

### ISSUE THREAD

**Issue by brshewmaker** [alleyinteractive/apple-news#17]
In my environment (running PHP 5.4.45) , I'm getting the following fatal error:

```Fatal error: Can't use method return value in write context in admin/class-admin-apple-news-list-table.php on line 289. Output triggered in /srv/www/wp-content/plugins/query-monitor/collectors/php_errors.php on line 142```

The culprit line seems to be this:
```php
if ( ! empty( $this->get_pagenum() ) && $this->get_pagenum() > 1 ) {
    $params['paged'] = $this->get_pagenum();
}
```
If I change it to something like this, it seems to works fine:
```php
$pagenum = $this->get_pagenum();
if ( isset($pagenum) && $pagenum > 1 ) {
    $params['paged'] = $this->get_pagenum();
}
```

**Comment by bcampeau** [comment]
I thought we got all the PHP 5.5+ specific code, but looks like this one was missed. This is fixed now so please pull the latest master branch.
