### ISSUE TITLE
Ads getting inserted even though no ads are selected.

### ISSUE THREAD

**Issue by jdrsqrd** [alleyinteractive/apple-news#172]
We are seeing ads in our Apple News articles even though we have "Enable Advertisements" set to "no"

**Comment by bcampeau** [comment]
Can you please provide a sample JSON file for a post that is experiencing this issue?

**Comment by jdrsqrd** [comment]
Gladly
`{"version":"1.1",
"identifier":"post-1",
"language":"en",
"title":"5 Facts Behind Apple's $1 Billion Ride-Sharing Investment",
"documentStyle":{"backgroundColor":"#FFFFFF"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"title",
"text":"5 Facts Behind Apple's $1 Billion Ride-Sharing Investment",
"textStyle":"default-title"},{"role":"container",
"layout":"headerContainerLayout",
"style":{"fill":{"type":"image",
"URL":"bundle:\/\/2016-05-13T021108Z_1_LYNXNPEC4C02G_RTROPTP_4_APPLE-EARNINGS-e1463107807491.jpg",
"fillMode":"cover"}},"behavior":{"type":"background_parallax"}},{"role":"byline",
"text":"by Lulu Yilun Chen, Bloomberg | May 13, 2016 | 11:09 AM",
"textStyle":"default-byline",
"layout":"byline-layout"},{"role":"quote",
"text":"Skift Take: \nDidi is dominating China in a way that Uber would love to dominate any market. It's the one ride-sharing company that's going beyond points A and B to a larger suite of services.\n\n",
"format":"markdown",
"textStyle":"default-pullquote",
"layout":"anchor-layout-right",
"anchor":{"targetComponentIdentifier":"component-573618d85d217",
"targetAnchorPosition":"center",
"rangeStart":0,"rangeLength":1},"animation":{"type":"fade_in",
"userControllable":true,"initialAlpha":0}},{"role":"body",
"text":"[Apple Inc. is investing $1 billion in Chinese ride-sharing service Didi Chuxing](https:\/\/skift.com\/2016\/05\/12\/apple-invests-1-billion-in-ubers-asian-rival-didi\/), which dominates Uber Technologies Inc. in the world\u2019s biggest market. Here are five things to know about Didi:\n\n**1. History:\u00a0**Didi, formally known as Xiaoju Kuaizhi Inc., traces its beginnings to 2012 and rival taxi-hailing apps that gained backing from China\u2019s biggest Internet companies.\n\nDidi Dache was supported by Tencent Holdings Ltd., which took part in a $100 million fundraising round in 2014. A rival service, Kuaidi Dache, also started in 2012 and attracted investment from e-commerce giant Alibaba Group Holding Ltd.\n\nThe two apps merged in February 2015, after brutal competition drove up losses, and subsequently expanded their businesses beyond calling taxis. They serve 300 million passengers in more than 400 cities.\n\n**2. Names behind it:\u00a0**The Beijing-based company\u2019s chief executive officer is Cheng Wei, a former employee of Alibaba. He recruited Jean Liu from Goldman Sachs Group Inc. to be chief operating officer of Didi Dache in 2014, and she was named president in February 2015.\n\nThe board of directors include Lucy Peng, a co-founder of Alibaba who is now CEO of its finance affiliate Zhejiang Ant Small & Micro Financial Services Group Co.; and Martin Lau, president of Tencent.\n\nIn addition to Apple, its investors include DST, Tiger Global Management, SoftBank Group Corp. and Temasek Holdings Pte.\n\n**3. Scope of services:\u00a0**What started as a service for hailing taxis has morphed into a company that offers ride-sharing, bus hiring, chauffeur services, auto financing and test-drive services. The app completes more than 11 million rides a day \u2014 or 127 rides a second \u2014 and is the second-biggest platform for online transactions in China after Alibaba\u2019s Taobao shopping mall.\n\nDidi said it has 99 percent of the market for taxi-hailing apps and 87 percent of the private car-hailing services. It works with 14 million registered drivers in more than 400 cities, and it broke even in about half of those locations.\n\nBy 2018, the company wants to serve 30 million passengers a day, with a waiting time within three minutes.\n\n**4. Rivals:\u00a0**Didi competes with Uber in China and has started taking that fight abroad. At home, Didi dominates, with Uber saying it wants to be in at least 100 cities this year, or about a quarter of the market that\u00a0Didi is operating in. Uber also attracted investments form Baidu Inc., owner of China\u2019s most-popular search engine and is said to have been supported by China Life Insurance Co., the nation\u2019s largest insurer.\n\nOverseas, Didi has partnered with Lyft Inc., India\u2019s Ola and Southeast Asia\u2019s Grab to fight the San Francisco-based Uber.\n\nUber is valued at $62.5 billion. Didi\u2019s latest fundraising round values the company at about $26 billion, according to people familiar with the matter.\n\n**5. China\u2019s regulations:\u00a0**China\u2019s national government may be seen as more friendly toward ride-hailing services than local governments, which often are trying to protect their own taxi services. Didi believes it can help China alleviate the massive traffic jams and choking air pollution that plague its cities, and the national agency that oversees taxis scrapped some regulations in March to make it easier for the ride-sharing services to do business.\n\nIn October, Shanghai gave Didi a license for private-car bookings, and the company is working with more city governments to adopt a similar model, it said at the time. Shanghai is seen as a traditional testing ground for nationwide economic policies, so other cities could follow suit.\n\nYet both Didi and Uber face a thicket of regulations from local authorities. Didi now is trying to ally with the startups founded by provincial and city governments, welcoming them to link their services to Didi\u2019s app and website.\n\n_\u00a92016 Bloomberg L.P._",
"format":"markdown",
"textStyle":"dropcapBodyStyle",
"layout":"body-layout",
"identifier":"component-573618d85d217"},{"role":"body",
"text":"_This article was written by Lulu Yilun Chen from [Bloomberg](http:\/\/www.bloomberg.com) and was legally licensed through the NewsCred publisher network._",
"format":"markdown",
"textStyle":"default-body",
"layout":"body-layout",
"identifier":"component-573618d85d024"},{"role":"photo",
"URL":"bundle:\/\/px.gif",
"layout":"anchor-layout-right",
"anchor":{"targetComponentIdentifier":"component-573618d85d024",
"targetAnchorPosition":"center",
"rangeStart":0,"rangeLength":1},"animation":{"type":"fade_in",
"userControllable":true,"initialAlpha":0}}],"componentTextStyles":{"dropcapBodyStyle":{"textAlignment":"left",
"fontName":"AvenirNext-Regular",
"fontSize":16,"lineHeight":24,"textColor":"#000000",
"linkStyle":{"textColor":"#ffb900"},"dropCapStyle":{"numberOfLines":2,"numberOfCharacters":1,"fontName":"Georgia-Bold",
"textColor":"#000000"}},"default-body":{"textAlignment":"left",
"fontName":"AvenirNext-Regular",
"fontSize":16,"lineHeight":24,"textColor":"#000000",
"linkStyle":{"textColor":"#ffb900"}},"default-pullquote":{"fontName":"AvenirNext-Regular",
"fontSize":20,"textColor":"#3691ce",
"textTransform":"none",
"lineHeight":22,"textAlignment":"left"},"default-title":{"fontName":"HelveticaNeue",
"fontSize":48,"lineHeight":52,"textColor":"#000000",
"textAlignment":"left"},"default-byline":{"textAlignment":"left",
"fontName":"AvenirNext-Medium",
"fontSize":17,"textColor":"#53585f"}},"componentLayouts":{"body-layout":{"columnStart":0,"columnSpan":5,"margin":{"top":25,"bottom":25}},"anchored-image":{"margin":{"top":25,"bottom":25}},"anchor-layout-right":{"columnStart":3,"columnSpan":4},"quote-layout":{"margin":{"top":15,"bottom":15}},"headerContainerLayout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true,"minimumHeight":"50vh",
"margin":{"top":0,"bottom":25}},"byline-layout":{"columnStart":0,"columnSpan":7,"margin":{"top":10,"bottom":10}}},"metadata":{"excerpt":"Apple Inc. is investing $1 billion in Chinese ride-sharing service Didi Chuxing, which dominates Uber Technologies Inc. in the world\u2019s biggest market. Here are five things to know about Didi: 1. History:\u00a0Didi, formally known as Xiaoju Kuaizhi Inc., traces its beginnings to 2012 and rival taxi-hailing apps that gained backing from China\u2019s biggest Internet companies....",
"thumbnailURL":"bundle:\/\/2016-05-13T021108Z_1_LYNXNPEC4C02G_RTROPTP_4_APPLE-EARNINGS-e1463107807491.jpg",
"dateCreated":"2016-05-13T11:09:35-04:00",
"dateModified":"2016-05-13T14:03:11-04:00",
"datePublished":"2016-05-13T11:09:35-04:00",
"canonicalURL":"https:\/\/skift.com\/2016\/05\/13\/5-facts-behind-apples-1-billion-ride-sharing-investment\/",
"generatorIdentifier":"publish-to-apple-news",
"generatorName":"Publish to Apple News",
"generatorVersion":"1.1.1"}}`

**Comment by bcampeau** [comment]
This JSON does not contain the `frequency` or `bannerType` properties and therefore according to the [Apple News Format Reference](https://developer.apple.com/library/ios/documentation/General/Conceptual/Apple_News_Format_Ref/AdvertisingSettings.html#//apple_ref/doc/uid/TP40015408-CH93-SW1) there should be no ads here.

Please send this issue to Apple News support for their feedback and let us know if you need any further assistance after that.
