### ISSUE TITLE
Articles show five hour delay

### ISSUE THREAD

**Issue by lifestyled** [alleyinteractive/apple-news#173]
Whenever I submit an article using the plugin, I'll immediately check my feed in Apple News and the article will show as having been submitted five hours ago. My WP and iCloud settings both have my correct timezone, and this only seems to have started happening after the previous update.

**Comment by seanchayes** [comment]
I see that too.

**Comment by bcampeau** [comment]
Can you please post a JSON file here that was affected by the issue and let us know the exact time and date you pushed it and your correct timezone?

Thanks.

**Comment by seanchayes** [comment]
Here's a recent article - renamed to be .txt for GitHub but is native json.
We are hosted on WordPress VIP, timezone is Chicago
[article-219989 copy.txt](https://github.com/alleyinteractive/apple-news/files/277976/article-219989.copy.txt)

Debug log of the article attached too:
[article-219989-debug.txt](https://github.com/alleyinteractive/apple-news/files/277990/article-219989-debug.txt)

Let me know if you need any further information.
Thank you

**Comment by lifestyled** [comment]
I unfortunately have no idea how to do that. I can tell you I'm hosted with Amazon's service, my timezone is also Chicago, and I'm on the most recent update of the plugin. If you can direct me on how to provide the files you need, I'll get on it right away. Sorry for not being quite as helpful, this is all a very new frontier for me.

**Comment by bcampeau** [comment]
@lifestyled no worries, the information provided by @seanchayes identified the issue. Apple News was not actually using the date meta values in the JSON until very recently and it appears the WordPress site time zone is not being taken into account. We'll work to correct that immediately.

**Comment by bcampeau** [comment]
Thanks for pointing out this critical issue. This was just fixed by #176 and version 1.1.3 has just been released as well to roll this out to everyone.

**Comment by lifestyled** [comment]
Awesomeness. Thank you for working on this and for the great plug-in!
