### ISSUE TITLE
Jetpack gallery support

### ISSUE THREAD

**Issue by bcampeau** [alleyinteractive/apple-news#174]
Many sites use Jetpack galleries and we should automatically translate them into Apple News format galleries.

See: https://wordpress.org/support/topic/error-504-gateway-timeout-1?replies=8#post-8436693

**Comment by bcampeau** [comment]
Should also support standard WordPress galleries too. See: https://wordpress.org/support/topic/low-res-images/#post-8216947

**Comment by kevinfodness** [comment]
Resolved via #462.
