### ISSUE TITLE
Support for Co-Authors Plus

### ISSUE THREAD

**Issue by seanchayes** [alleyinteractive/apple-news#175]
Some of our content is provided by a third party and we publish that content using Co-Authors Plus to display the attribution on our site. However, we noticed that the Apple News plugin pulls the post_author directly when exporting / publishing to Apple News.

Is there any plan to support guest authors through Co-Authors Plus when creating the byline?

If not or until it does I see that we could probably address it using the 'apple_news_exporter_byline' filter to perhaps yield the same result.

**Comment by bcampeau** [comment]
We will never support CAP directly since third party plugin support is a slippery slope to go down. 

However, plenty of other sites are doing exactly what you describe using either that filter or `apple_news_generate_json`. We don't plan on changing that.
