### ISSUE TITLE
Auto-publish not working

### ISSUE THREAD

**Issue by jerrythompson** [alleyinteractive/apple-news#177]
On Wordpress VIP and with automatically publish to Apple News and Asynchronously publish to Apple News both set to yes, posts are rarely ever published.  Currently publishing 150-200 posts per day and less than 5 ever successfully publish to Apple News automatically.

**Comment by bcampeau** [comment]
Are these scheduled posts? This could be a duplicate of #116.

Do you have debug mode enabled? If not, you should enable it and check for the API responses.
