### ISSUE TITLE
apple_news_loaded_settings filter

### ISSUE THREAD

**Issue by patrickbajao** [alleyinteractive/apple-news#182]
Hi,

I want to set the plugin settings (API key, secret, channel ID, fonts, font sizes, etc.) in code instead of adding them via admin console. That way we can ensure that same settings are applied on different environments (we have 3 environments: development, staging, and production). Looked at the code and found the `apple_news_loaded_settings` filter. Based on my understanding, that's being called whenever the settings is fetched. So I added a hook for that in our theme's `functions.php`. But it seems that it's not being called.

Here's the code I added for the hook:

```php
add_filter('apple_news_loaded_settings', 'setup_apple_news_settings');

function setup_apple_news_settings($loaded_settings) {
  $loaded_settings->set('api_key', APPLE_NEWS_KEY);
  $loaded_settings->set('api_secret', APPLE_NEWS_SECRET);
  $loaded_settings->set('api_channel', APPLE_NEWS_CHANNEL_ID);

  return $loaded_settings;
}
```

The constants are defined and I excluded them for privacy.

When I update a post, it doesn't get pushed to Apple News. Also, I can still see this message: Your Apple News API settings seem to be empty. Please fill in the API key, API secret and API channel fields in the plugin configuration page.

Am I using the correct filter for this? Or is there a better way to do it? Or do I really have to set everything via admin console?

Thanks,
Patrick

**Comment by bcampeau** [comment]
I think the issue is that settings are defined as a static variable in Admin_Apple_News and once that class is instantiated, which happens as soon as the plugin loads, your filter is firing too late to override the values.

See if that helps you out and if not, we can look into it further.

**Comment by patrickbajao** [comment]
Hi @bcampeau,

Thanks for the explanation. It makes sense to me now.

I ended up writing an mu-plugin specific for our WP installation since the theme's `functions.php` gets loaded after the plugins. Then I put the filter there. It also makes sense to do that since overriding the settings is not theme related.

Thanks for the help!
