### ISSUE TITLE
Articles contain exposed unicode, HTML, or XML

### ISSUE THREAD

**Issue by therobotguyllc** [alleyinteractive/apple-news#183]
This is continuation from a thread on the WP support site that for reason unknown to me would not let me post links or code.

Here is a link to the file with the JSON text [http://dustoffthebible.com/wp-content/uploads/2016/06/JSON-Contents.txt](url)

Here is the actual text....

{"version":"1.1","identifier":"post-7428","language":"en","title":"Co-Founder Of TBN, Jan Crouch, Is Now Passed. What Will Her Legacy Be?","documentStyle":{"backgroundColor":"#FAFAFA"},"layout":{"columns":7,"width":1024,"margin":50,"gutter":20},"components":[{"role":"header","layout":"headerPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"bundle:\/\/Jan-Crouch-and-Franklin-Graham.jpg"}],"behavior":{"type":"parallax","factor":0.8}},{"role":"container","layout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#FAFAFA"},"components":[{"role":"title","text":"Co-Founder Of TBN, Jan Crouch, Is Now Passed. What Will Her Legacy Be?","textStyle":"default-title","layout":"title-layout"},{"role":"byline","text":"by Admin | Jun 3, 2016 | 9:55 AM","textStyle":"default-byline","layout":"byline-layout"}]},{"role":"divider","layout":"divider-layout","stroke":{"color":"#E6E6E6","width":1}},{"role":"body","text":"A little over a week ago major Christian news networks like the [Christian Post](http:\/\/www.christianpost.com\/news\/jan-crouch-tbn-dies-at-78-after-suffering-massive-stroke-164656\/) started reporting the death of Jan Crouch, the wife of Paul Crouch and co-founder of TBN. While I do not approve of the TBN theology, philosophy, or routine tax evasion, I do want to recognize that Jan Crouch was a Christian and real believer in Christ. At age 78 she had a stroke and unfortunately went on to be with our creator.","format":"markdown","textStyle":"dropcapBodyStyle","layout":"body-layout"},{"role":"body","text":"While I remember her most for her many extravagant hair cuts, I believe most will have a different memory. For those who follow the TBN preaching and the Word of Faith preachers they will be mourning the death of Mrs. Crouch. For those on the other end of the isle it is more likely that she will be remembered for extravagant spending and a lavish life style supported by donations from Christian viewers around the world.","format":"markdown","textStyle":"default-body","layout":"body-layout","identifier":"component-575612f13c95f"},{"role":"photo","URL":"bundle:\/\/Jan-Crouch-Blonde-Pink-Hair-2.jpg","layout":"anchor-layout-right","anchor":{"targetAnchorPosition":"center","rangeStart":0,"rangeLength":1,"targetComponentIdentifier":"component-575612f13c95f"}},{"role":"photo","URL":"bundle:\/\/Jan-Crouch-Blonde-Pink-Hair.jpg","layout":"anchor-layout-right","anchor":{"targetAnchorPosition":"center","rangeStart":0,"rangeLength":1,"targetComponentIdentifier":"component-575612f13c9e6"}},{"role":"photo","URL":"bundle:\/\/Jan-Crouch-Purple-Hairt.png","layout":"anchor-layout-right","anchor":{"targetAnchorPosition":"center","rangeStart":0,"rangeLength":1,"targetComponentIdentifier":"component-575612f13ca42"}},{"role":"photo","URL":"bundle:\/\/Jan-Crouch-White-Hair-Cone.jpg","layout":"anchor-layout-right","anchor":{"targetAnchorPosition":"center","rangeStart":0,"rangeLength":1,"targetComponentIdentifier":"component-575612f13caa4"}},{"role":"body","text":"\u00a0","format":"markdown","textStyle":"default-body","layout":"body-layout","identifier":"component-575612f13c9e6"},{"role":"body","text":"\u00a0","format":"markdown","textStyle":"default-body","layout":"body-layout","identifier":"component-575612f13ca42"},{"role":"divider","layout":"divider-layout","stroke":{"color":"#E6E6E6","width":1}},{"role":"heading3","text":"About Jan Crouch","format":"markdown","textStyle":"default-heading-3","layout":"heading-layout"},{"role":"body","text":"**Born:\u00a0**Janice Wendell Bethany \n**Died:\u00a0**May 31, 2016 (aged\u00a078) \n**Married:** Paul Crouch, 1957 \u2013 2013 (Paul passed in 2013 having been married to Jan for 56 years!!) \n**Christian Denomination:** Pentecostal \n**Children:**\u00a0[Paul Crouch, Jr.](https:\/\/en.wikipedia.org\/wiki\/Paul_Crouch,_Jr.)\u00a0& [Matthew Crouch](https:\/\/en.wikipedia.org\/wiki\/Matthew_Crouch) \n**Parents:\u00a0**Reverend and Mrs. Edgar W. Bethany \n**Filmography:\u00a0**She was a producer, known for [Praise the Lord](http:\/\/www.imdb.com\/title\/tt0278229?ref_=nmbio_mbio) (1973), [First to Know](http:\/\/www.imdb.com\/title\/tt0312095?ref_=nmbio_mbio)(1990) and [The Glory of America](http:\/\/www.imdb.com\/title\/tt0982067?ref_=nmbio_mbio) (1996).\n\n**Honor & Awards**\n\n- 1990: Honorary Doctor of Humane Letters degree from [Oral Roberts University](https:\/\/en.wikipedia.org\/wiki\/Oral_Roberts_University)\n- Golden Angel Award \u2013 Excellence in Media","format":"markdown","textStyle":"default-body","layout":"body-layout","identifier":"component-575612f13caa4"},{"role":"divider","layout":"divider-layout","stroke":{"color":"#E6E6E6","width":1}},{"role":"heading3","text":"Further Reading About Jan Crouch (and Paul)","format":"markdown","textStyle":"default-heading-3","layout":"heading-layout"},{"role":"body","text":"[Jan Crouch Obituary](http:\/\/www.legacy.com\/ns\/jan-crouch-obituary\/180165905)\n\n[TBN Co-Founder Jan Crouch Goes on to Glory After Massive Stroke](http:\/\/www.charismanews.com\/us\/57489-tbn-co-founder-jan-crouch-goes-on-to-glory-after-massive-stroke)\n\n[Televangelist Paul Crouch Leaves a Dirty Legacy; Evangelical Christians Look the Other Way](http:\/\/www.patheos.com\/blogs\/friendlyatheist\/2013\/12\/02\/televangelist-swindler-paul-crouch-leaves-a-dirty-legacy-evangelical-christians-look-the-other-way\/)\n\n[\u00a0Charity Navigator Assessment Rating For Trinity Broadcasting Network](http:\/\/www.charitynavigator.org\/index.cfm?bay=search.summary&orgid=4574)\n\n[Family Battle Offers Look Inside Lavish TV Ministry](http:\/\/www.nytimes.com\/2012\/05\/05\/us\/tbn-fight-offers-glimpse-inside-lavish-tv-ministry.html?_r=0)\n\n[Private jets, 13 mansions and a $100,000 mobile home just for the dogs: Televangelists \u2018defrauded tens of million of dollars from Christian network\u2019](http:\/\/www.dailymail.co.uk\/news\/article-2119493\/Private-jets-13-mansions-100-000-mobile-home-just-dogs-Televangelists-defrauded-tens-million-dollars-Christian-network.html)","format":"markdown","textStyle":"default-body","layout":"body-layout"},{"role":"divider","layout":"divider-layout","stroke":{"color":"#E6E6E6","width":1}}],"componentTextStyles":{"dropcapBodyStyle":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":14,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18,"dropCapStyle":{"numberOfLines":4,"numberOfCharacters":1,"padding":5,"fontName":"AvenirNext-Bold","textColor":"#4f4f4f"}},"default-body":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":14,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-heading-3":{"fontName":"AvenirNext-Bold","fontSize":24,"lineHeight":52,"textColor":"#333333","textAlignment":"left"},"default-title":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"textColor":"#333333","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"AvenirNext-Medium","fontSize":13,"textColor":"#7c7c7c"}},"componentLayouts":{"divider-layout":{"columnStart":0,"columnSpan":7,"margin":{"top":25,"bottom":25}},"body-layout":{"columnStart":0,"columnSpan":5,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":5,"margin":{"top":12,"bottom":30}},"anchored-image":{"margin":{"top":25,"bottom":25}},"heading-layout":{"columnStart":0,"columnSpan":7,"margin":{"top":15,"bottom":15}},"anchor-layout-right":{"columnStart":3,"columnSpan":4},"headerPhotoLayout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true},"title-layout":{"margin":{"top":30,"bottom":0}},"byline-layout":{"columnStart":0,"columnSpan":7,"margin":{"top":10,"bottom":10}}},"metadata":{"excerpt":"A little over a week ago major Christian news networks like the Christian Post started reporting the death of Jan Crouch, the wife of Paul Crouch and co-founder of TBN. While I do not approve of the TBN theology, philosophy, or routine tax evasion, I do want to recognize that Jan Crouch was a Christian...","thumbnailURL":"bundle:\/\/Jan-Crouch-and-Franklin-Graham.jpg","dateCreated":"2016-06-03T13:55:43+00:00","dateModified":"2016-06-03T17:16:51+00:00","datePublished":"2016-06-03T13:55:43+00:00","canonicalURL":"http:\/\/dustoffthebible.com\/Blog-archive\/2016\/06\/03\/co-founder-of-tbn-jan-crouch-is-now-passed-what-will-her-legacy-be\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"1.1.4"},"advertisingSettings":{"frequency":2,"layout":{"margin":{"top":15,"bottom":15}}}}

**Comment by bcampeau** [comment]
Thanks we'll look at this soon. Expect to hear back more in the next few days.

**Comment by therobotguyllc** [comment]
thank you!

**Comment by bcampeau** [comment]
I took a look at your JSON file and it's not generating any errors in the News Preview tool and also looks fine visually.

Have you contacted Apple News support about this and asked exactly why they're flagging this content for this error? Unfortunately, I'm not seeing any issues and nothing related to the plugin.

**Comment by therobotguyllc** [comment]
Thanks for checking it out. It's possible that it was one of my other posts. I submitted 3. I deleted the other 2 and resubmitted just that one. I will contact apple as well.

Thanks a ton, will be updating review to 5 stars.

Justin Holmes 
419-677-1048

**Comment by bcampeau** [comment]
Thanks, we'd appreciate that if you did.
