### ISSUE TITLE
Another five hour delay?

### ISSUE THREAD

**Issue by seanchayes** [alleyinteractive/apple-news#187]
Referencing #173 

The home/category pages on Apple News are showing content as older than it is - by 5 hours.

![image](https://cloud.githubusercontent.com/assets/999288/16021095/7d34f096-3176-11e6-9180-af554ed76bc1.png)

We took a break publishing on Apple News and restarted last week - I saw the issue then but waited and published more over the past weekend to see if it was consistent or not. And it seems that every new article is displayed on this screen as older that it is. However, the good news is that when we click through to the article page the correct publish time is displayed.

Example content added:
[cops-drunken-motorcyclist-article-233470.json.txt](https://github.com/alleyinteractive/apple-news/files/312597/cops-drunken-motorcyclist-article-233470.json.txt)

**Comment by bcampeau** [comment]
Publish time is passed through in a meta value and should be accurate. 

Can you make sure you have the right time zone set for WordPress and also that your web host has the server time set to the correct time zone?

Thanks.

**Comment by seanchayes** [comment]
Got it - this is what I'm seeing in our WordPress admin. I can check with WordPress VIP if they are experiencing any time issues too.

![image](https://cloud.githubusercontent.com/assets/999288/16059140/56fb24d2-3247-11e6-96d5-1e0b037a16f9.png)

**Comment by bcampeau** [comment]
My fault, I didn't realize you were on VIP. No, that definitely wouldn't be an issue there.

Can you post a JSON file for a post that's having this issue?

Thanks.

**Comment by seanchayes** [comment]
There's one in the original posting in this issue.

And thank you

**Comment by bcampeau** [comment]
The JSON was a dead giveaway. VIP is still on 1.1.2 and this time zone bug was fixed in 1.1.3. They're reviewing the latest updates now for deployment and that will fix your issue instantly once it's done.

**Comment by seanchayes** [comment]
Good to have conclusive evidence.

To that end can the version number be displayed in the Settings, Apple News
screen? I can open a new issue/enhancement for that request if appropriate.

Thank you

**Comment by bcampeau** [comment]
Most plugins don't do that on VIP, but the version number is clearly displayed in the JSON.

**Comment by seanchayes** [comment]
Got it - thanks

**Comment by bcampeau** [comment]
VIP should have updated by now, can you confirm your issue is resolved?

**Comment by seanchayes** [comment]
I see accurate publish times displayed on those home/category pages now using 1.1.4

Thank you
