### ISSUE TITLE
Allow customizing JSON for individual components

### ISSUE THREAD

**Issue by bcampeau** [alleyinteractive/apple-news#193]
We will add a custom field for every JSON component that shows the base JSON generated by the component with placeholders for the data inserted by variables. We will allow this to be customizable so that intermediate users can use the Apple News format reference to tweak display of individual elements with a bit more flexibility.

**Comment by kaynenh** [comment]
@bcampeau I'm looking to do exactly this. Can you point me in the direction of what file(s) currently translate the Wordpress html to json? I'd like to make some tweaks with a couple of components while you continue to work on getting this customization into the plugin.

**Comment by bcampeau** [comment]
Keep in mind how this will work alongside #180, whichever is handled first.
