### ISSUE TITLE
Update minimum PHP version to 5.3.6

### ISSUE THREAD

**Issue by stevecullum** [alleyinteractive/apple-news#194]
I've only had one article published recently. The others say this when I try to publish them: 

> There has been an error with the API. Please make sure your API settings are correct and try again: The attachment article.json could not be included in the request because it was empty.

**Comment by bcampeau** [comment]
This is likely an issue with your web host. Please try enabling remote images in the plugin settings and see if that works better for you.

**Comment by stevecullum** [comment]
Same error... :-(

**Comment by bcampeau** [comment]
Where is your site hosted?

**Comment by stevecullum** [comment]
Media Temple

**Comment by bcampeau** [comment]
Can you check if the method you're using to deliver your image (locally hosted or CDN) is using chunked transfer encoding? That's not currently supported by the Apple News API unfortunately.

**Comment by stevecullum** [comment]
We are not using chunked method.

**Comment by bcampeau** [comment]
Chunked transfer encoding is now supported in any case. Are you still experiencing the issue?

**Comment by stevecullum** [comment]
Yes. We have only had one article go through since enabling the API and using the plugin.

**Comment by stevecullum** [comment]
I noticed that "Asynchronously publish to Apple News" wasn't set to YES, so I just did. I went back to publish a bulk of articles, and it showed they went through successfully. But when I opened up the plugin again, I saw that each of them had the same error as before.
![screen shot 2016-06-29 at 4 28 01 pm](https://cloud.githubusercontent.com/assets/19938527/16467751/a8e3ff96-3e16-11e6-9a66-ebc22f8aed0d.png)
![screen shot 2016-06-29 at 4 28 17 pm](https://cloud.githubusercontent.com/assets/19938527/16467752/a8e9c458-3e16-11e6-86c9-c34a3bc01566.png)

**Comment by bcampeau** [comment]
If article.json is empty, there's likely a PHP error occurring somewhere in the process or a plugin that's conflicting with the publishing process. We've actually never seen anyone else experience this error with the JSON file. It usually occurs only for images under the conditions I've mentioned previously while helping you troubleshoot.

Have you checked your PHP error logs or tried disabling other plugins and/or your theme to rule out any conflicts?

**Comment by bcampeau** [comment]
Any further info on this issue? Were you able to track down any PHP errors?

**Comment by stevecullum** [comment]
We have disabled all other plugins and our theme, and still nothing works.

**Comment by bcampeau** [comment]
Right, but have you checked your PHP error logs as requested? If article.json is empty, that leads me to believe something is failing in the process of publishing the article on your server.

**Comment by stevecullum** [comment]
Here's what we found...  

> [Tue Aug 09 08:52:43 2016] [warn] [client 74.203.138.20] mod_fcgid: stderr: PHP Warning:  Cannot modify header information - headers already sent by (output started at /var/www/vhosts/wiinintendo.net/httpdocs/wp-includes/class.wp-scripts.php:224) in /var/www/vhosts/wiinintendo.net/httpdocs/wp-includes/pluggable.php on line 1167, referer: http://www.nintendofuse.com/wp-admin/admin.php?page=apple_news_index&s&_wpnonce=5892e386f0&_wp_http_referer=%2Fwp-admin%2Fadmin.php%3Fpage%3Dapple_news_index&action=-1&apple_news_publish_status=pending&apple_news_date_from&apple_news_date_to&filter_action=Filter&paged=1&action2=-1

**Comment by stevecullum** [comment]
Also, this...

> [Tue Jun 14 13:45:11 2016] [warn] [client 73.100.39.38] mod_fcgid: stderr: PHP Warning:  DOMDocument::saveHTML() expects exactly 0 parameters, 1 given in /var/www/vhosts/wiinintendo.net/httpdocs/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/components/class-component.php on line 175, referer: http://www.nintendofuse.com/wp-admin/admin.php?page=apple_news_bulk_export&ids=63224.63198.63195.63190.63189.63185.63179.63171.63167.63137.63132.63130.63126.63119.63087.63083.63080.63076.63070.63013

**Comment by bcampeau** [comment]
What PHP version are you running?

**Comment by stevecullum** [comment]
PHP Version 5.3.5

**Comment by bcampeau** [comment]
OK, I think we've sorted this out then. The minimum PHP version in the plugin was listed as 5.3.0 by the original developer and I've never given it a second thought since.

However, the usage of a parameter in `DOMDocument::saveHTML( $node )` was not supported until PHP 5.3.6. 

We'll update the minimum PHP version notice in a future version of the plugin. However, there's absolutely nothing we can do for you here. That function is absolutely required for the plugin and we would strongly recommend anyway that you update to a more recent PHP version. 5.3 is very, very old at this point in general.

Thanks.

**Comment by stevecullum** [comment]
Ok, I passed this on to our website manager, and we're going to try getting this upgraded ASAP. I will let you know if that does not fix it.

**Comment by stevecullum** [comment]
PHP and everything else updated. Still getting this error: 
"There has been an error with the API. Please make sure your API settings are correct and try again: The attachment article.json could not be included in the request because it was empty."

**Comment by bcampeau** [comment]
Resetting your codes will do nothing to solve this. If the JSON file is empty, that would still be indicative of a PHP error.

**Comment by stevecullum** [comment]
Never mind. I misread what our site manager told me. They will SOON be upgraded, but are not yet.

**Comment by bcampeau** [comment]
That makes much more sense then. Thanks.

**Comment by stevecullum** [comment]
After all the updates have been completed, we are still getting the same error:

> There has been an error with the API. Please make sure your API settings are correct and try again: The attachment article.json could not be included in the request because it was empty.

**Comment by bcampeau** [comment]
@stevecullum, 

The update was merely to create a warning so people with a PHP version lower than 5.3.6 would know they can't use the plugin. 

We can't actually "fix" this. You still need to have your host update to a more recent version. Official support for PHP 5.3 in general ceased over two years ago. 

Thanks.

**Comment by stevecullum** [comment]
No, I meant after all OUR updates were complete, not yours. :-)

**Comment by bcampeau** [comment]
Have you re-checked your PHP error logs? If article.json is empty, you must still be experiencing some sort of error.
