### ISSUE TITLE
Undefined index error

### ISSUE THREAD

**Issue by bcampeau** [alleyinteractive/apple-news#196]
Halt publishing when this occurs and figure out the root cause of the issue.

For example:

`<b>Notice</b>:  Undefined index: anchor in <b>/plugins/publish-to-apple-news/includes/apple-exporter/components/class-component.php</b> on line <b>209</b><br />`

**Comment by kevinfodness** [comment]
This is called from `class-components.php` on line 283 in version 1.2.1 and doesn't assume that the value exists. The current code in `class-component.php` runs an `isset()` before returning, so we can safely close this issue now.
