### ISSUE TITLE
Body copy needs opaque background when lead image is portrait

### ISSUE THREAD

**Issue by clarelisbeth** [alleyinteractive/apple-news#197]
When the body text is scrolled over the main image on iPad, there is no solid background colour on the text, so when it sits on top of the image, it is often unreadable. 

I think this only occurs on taller images - usually portrait. 

Some example articles: 
https://apple.news/A-uJukkwTQE-F1rXQ6p3EkA
https://apple.news/AdcapKpvtTVCtgd0eKvUMrA

Screenshots attached. 

Thanks! 

![img_0575](https://cloud.githubusercontent.com/assets/1040923/16376603/091687e0-3c59-11e6-8247-acc592cef8e0.PNG)
![img_0573](https://cloud.githubusercontent.com/assets/1040923/16376604/09172308-3c59-11e6-8bfc-81b047e66ab8.PNG)

**Comment by bcampeau** [comment]
This should be fixed in version 1.1.5. Please upgrade and confirm.
