### ISSUE TITLE
Error with Image

### ISSUE THREAD

**Issue by LennonNZ** [alleyinteractive/apple-news#203]
When Publishing the Article I get this error . Can this be looked into?

JSON Included.

**Comment by bcampeau** [comment]
Please paste that as code or attach as a file. It's not readable as you've pasted it.

Also can you please clarify what you're looking for from this request? 

Thanks.

**Comment by bcampeau** [comment]
Will you be following up on this request? Thanks.

**Comment by LennonNZ** [comment]
Strange.. I uploaded the JSON. as an attachment. Will upload again

**Comment by LennonNZ** [comment]
[ERROR1.txt](https://github.com/alleyinteractive/apple-news/files/387285/ERROR1.txt)

This should be the sent JSON and the error message recieved.

**Comment by bcampeau** [comment]
You can't use GIFs as featured images, only JPGs. See: https://developer.apple.com/library/ios/documentation/General/Conceptual/Apple_News_Format_Ref/Metadata.html

If you had used the [News Preview tool](https://developer.apple.com/news-preview/), you could have found this yourself just by dragging the JSON file into the tool.
