### ISSUE TITLE
Image alignment and responsive resizing

### ISSUE THREAD

**Issue by kaynenh** [alleyinteractive/apple-news#206]
Hi! Thanks for the great plugin. Rewriting html to the apple news format is a beast and we're thankful you have written this plugin.

I have a question concerning the <img> tags and their conversion to the apple news json format. It seems that no matter what we do, the images always align to the right of an article. Is there any way to force that alignment to be centered with nothing left or right of the image? The right alignment really does some weird things with text wrapping in our testing. My proposed idea would be to center the image on a new line, separated on top and bottom by the apple news divider element (ensuring no text wrapping occurs).

Also, we've debating making all our images larger than 1024 per your documentation "Note that images smaller than the body width (~1024px) will always be aligned. If you want to display an image without alignment, make sure it’s big enough." However, when we attempt to insert >1024px images, the images still seem to be aligning and are not actually full-width. We'd love to see them pseudo-responsively resize to the full-column width if possible.

Can you help with this? Thank you!

**Comment by bcampeau** [comment]
This already exists as issue #184. Take a look through that thread and see if that answers your question. We will support custom image alignment in a future version.

**Comment by kaynenh** [comment]
Thanks for following up so quickly! I'll take a look at that logic referenced in #184 and see if I can get the alignment working the way we want it to. Any thoughts on the second question about the images not going full-width when they are greater than 1024? The image next to "Suzanne" attached is 1250 wide and on the ipad, it's put into a column. On an iphone, however, it's full-width.

![img_0607](https://cloud.githubusercontent.com/assets/786286/17145267/26d8be4c-531f-11e6-82b5-9736b0ff95d2.PNG)

**Comment by bcampeau** [comment]
`1024` is set as the layout width here: https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-exporter/class-settings.php#L134-L142 so images can't expand beyond that. This was a decision that was made when creating the default template built into the plugin.

You can of course modify any aspect of the JSON you'd like. For something global like this, I'd probably just use the `apple_news_generate_json` filter to change this in the final output: https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-exporter/class-exporter.php#L192
