### ISSUE TITLE
Auto-Publishing Not Functioning 

### ISSUE THREAD

**Issue by christineyoon** [alleyinteractive/apple-news#208]
We've changed our plugin settings to:

Automatically publish to Apple News: YES
Automatically update Apple News: YES
Asynchronously publish to Apple News: YES

And, per recommendation from Will Sharp on Apple Dev, we also tried setting `Asynchronously publish to Apple News: NO` but we still can’t get posts to autopublish.

Filing this bug per the recommendation of Brad Campeau-Laurion and Austin Smith.

**Comment by bcampeau** [comment]
Are the affected posts all scheduled posts? If so, this is probably this existing issue: https://github.com/alleyinteractive/apple-news/issues/116

It's meant to be resolved in a future plugin version.

Thanks.

**Comment by christineyoon** [comment]
All posts are affected, not just scheduled posts.

**Comment by bcampeau** [comment]
This was fixed in #214 and was closed as part of #116. You can pull the latest master from github for the fix or wait for the official 1.1.6 release on Monday on WordPress.org.

**Comment by csesno** [comment]
Hi, we updated our plugin to the latest version per your recommendation here. 

The latest version addressed the auto-publishing bug for *scheduled posts only*. So five articles of ours were successfully pushed to ANF overnight. 

As Christine mentioned in this issue, autopublishing was not working for any of our posts, not just for scheduled. 

This is progress, but only addresses the issue for a very small fraction of our content. The vast majority of our content is published in real-time (not future scheduled in WP). 

Any ideas for what's going on here? Is there anything I can provide to help troubleshoot this, like an article.json or API response (of one of our successfully published scheduled posts)?

**Comment by bcampeau** [comment]
@csesno you should read the discussion that just happened here: https://github.com/alleyinteractive/apple-news/issues/116#issuecomment-244104711

It's very likely you need to filter `apple_news_publish_capability` in your theme to something lower than `manage_options`. I'd suggest `edit_posts` or whatever the common capability is that's shared among the users that are publishing these posts.

Thanks.

**Comment by csesno** [comment]
we'll try that.

**Comment by bcampeau** [comment]
Thanks @csesno and I'd appreciate if you can update us on the result.

**Comment by csesno** [comment]
@bcampeau The filter you suggested plus the latest version of the plugin has fixed our autopublishing. Thanks for the help!
