### ISSUE TITLE
Evaluate usage of manage_options as the default publish capability

### ISSUE THREAD

**Issue by bcampeau** [alleyinteractive/apple-news#223]
There may be people depending on this, so we can't necessarily change it. However, we may want to make it editable via an admin setting, in addition to the filter.

I'd also propose that we may want to make the setting default to `edit_posts` moving forward. For those sites that are upgrading rather than a fresh install, I'd also propose that they default to `manage_options` instead to create backwards compatibility.

**Comment by kevinfodness** [comment]
Will handle in the context of #420.
