### ISSUE TITLE
Can't change the pull quote anymore.

### ISSUE THREAD

**Issue by ibrtsn** [alleyinteractive/apple-news#226]
Every time I change it, it gets back to it's original state.

**Comment by bcampeau** [comment]
@ibrtsn support for open source software is provided as freely as the software itself. Therefore, you only get back what you put in. A single sentence description isn't enough for us to work with to help you out.

Can you please provide the following detailed information:

1. Detailed steps to replicate the issue
2. Screenshots, where appropriate
3. Your WordPress version
4. Your Apple News plugin version
5. The browser and operating system you're using
6. Sample JSON files for the post(s) in question, if appropriate

Thanks.

**Comment by ibrtsn** [comment]
I'm very sorry.
I was preparing the blog for publishing to apple news and testing the visual export in the apple news preview app. The articles I used were already published to the web, but are still drafts in apple news. When I want to change the pull quote and click update, the text I inserted disappears and pending review appears. But the text is still gone.

I'm running wordpress 4.6 and the latest version of the apple news plugin (1.1.7). My operating system is Mac Os X El Capitan and I 'm using Safari.

There isn't a problem with the .json itself I suppose.

Thanks in advance!

**Comment by bcampeau** [comment]
Sorry, but I'm still not following the steps to replicate this. Can you please provide step-by-step screenshots of how to replicate the issue?

Thanks.

**Comment by ibrtsn** [comment]
The first screenshot is the current status of all articles.
In the second screenshot, you can see which changes I would like to make.
The last screenshot is what I can see after clicking the update button.
<img width="1280" alt="screen shot 2016-09-07 at 17 20 09" src="https://cloud.githubusercontent.com/assets/21290088/18317922/ec5e6780-751f-11e6-88ee-3cc559136668.png">
<img width="1280" alt="screen shot 2016-09-07 at 17 22 14" src="https://cloud.githubusercontent.com/assets/21290088/18317924/ec995656-751f-11e6-8f4a-866a6a5fcb58.png">
<img width="1280" alt="screen shot 2016-09-07 at 17 23 08" src="https://cloud.githubusercontent.com/assets/21290088/18317923/ec875b90-751f-11e6-9bd5-df33190c975d.png">

**Comment by bcampeau** [comment]
This is a legitimate bug. We're looking into it.

**Comment by ibrtsn** [comment]
Thanks!

**Comment by bcampeau** [comment]
@ibrtsn can you confirm that you have **Automatically publish to Apple News** set to **Yes**?

**Comment by ibrtsn** [comment]
These are my current settings
<img width="562" alt="screen shot 2016-09-07 at 22 23 28" src="https://cloud.githubusercontent.com/assets/21290088/18327214/c0ba3a26-7549-11e6-8e77-84d48fedcd53.png">

**Comment by bcampeau** [comment]
Perfect, thanks. It appears this bug is only affecting people with auto publish enabled so that confirms it for us. We're working on a fix.

**Comment by ibrtsn** [comment]
Thank you very much for the fast response!

**Comment by bcampeau** [comment]
Version 1.1.8 has the fix and is now live on github. You can grab the `master` branch from here.

It will be released to WordPress.org on Monday.
