### ISSUE TITLE
Where do you add the API keys

### ISSUE THREAD

**Issue by sabistar** [alleyinteractive/apple-news#230]
Excuse me for being ignorant but I just cant seem to see where I enter the API Keys.  I have installed the plugin successfully  and the instructions say :
..., enter your private API Key, Secret, and Channel settings into the “Apple News API” fields. Once entered, you can begin publishing WordPress site content to Apple News.
I have searched everywhere for them and even changed browsers from safari to chrome to find these fields but they do not appear in the plugin Edit.   Where are they?

**Comment by bcampeau** [comment]
Go to Settings > Apple News in your WordPress dashboard.
