### ISSUE TITLE
Apple News Articles Failing Validation

### ISSUE THREAD

**Issue by mattking5000** [alleyinteractive/apple-news#234]
From Apple:

> While reviewing your Apple News Format submission, we noticed that something isn't quite right. Please resolve these issues, and then resubmit your content at News Publisher<https://www.icloud.com/#newspublisher>.
> Articles contain exposed unicode, HTML, or XML.

JSON output *seems* ok, but hard to validate:

`{"version":"1.1","identifier":"post-20910","language":"en","title":"The Talent Docket: October 31, 2016","documentStyle":{"backgroundColor":"#FAFAFA"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"header","layout":"headerPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"bundle:\/\/photo-1425421669292-0c3da3b8f529-1.jpg"}],"behavior":{"type":"parallax","factor":0.8}},{"role":"container","layout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#FAFAFA"},"components":[{"role":"title","text":"The Talent Docket: October 31, 2016","textStyle":"default-title","layout":"title-layout"},{"role":"byline","text":"by Frank Kalman | Oct 31, 2016 | 1:30 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"body","text":"As the service sector in the United States continues to boom, with jobs swelling in health care and declining in manufacturing, productivity gains remain elusive, reports [The Wall Street Journal (Paywall)](http:\/\/www.wsj.com\/articles\/while-services-sector-booms-productivity-gains-remain-elusive-1477842608).\n\n\u2026\n\nWhen companies appoint female CEOs, stock prices tank, according to a\u00a0report from [Quartz](http:\/\/qz.com\/709934\/companies-that-appoint-female-ceos-receive-more-negative-media-attention\/).\n\n\u2026\n\nCompanies with checkered histories are better off actively addressing them to the public, writes [_The Economist_](http:\/\/www.economist.com\/news\/business\/21709349-dutch-case-suggests-firms-horrible-stains-their-history-are-better-facing-up).\n\n\u2026\n\nWhy are immigrants more entrepreneurial? _[Harvard Business Review](https:\/\/hbr.org\/2016\/10\/why-are-immigrants-more-entrepreneurial)_ explores.\n\n\u2026\n\nFinally, Facebook\u2019s AI director explains how he hires the smartest minds in the world, via [Business Insider](http:\/\/www.businessinsider.com\/interview-yann-lecun-facebook-ai-deepmind-2016-10).","format":"markdown","textStyle":"dropcapBodyStyle","layout":"body-layout-last"}]}],"componentTextStyles":{"dropcapBodyStyle":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428BCA"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18,"dropCapStyle":{"numberOfLines":4,"numberOfCharacters":1,"padding":5,"fontName":"AvenirNext-Bold","textColor":"#4f4f4f"}},"default-body":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428BCA"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-title":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"textColor":"#333333","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"AvenirNext-Medium","fontSize":13,"textColor":"#7c7c7c"}},"componentLayouts":{"body-layout":{"columnStart":0,"columnSpan":5,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":5,"margin":{"top":12,"bottom":30}},"headerPhotoLayout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true},"headerBelowTextPhotoLayout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true,"margin":{"top":30,"bottom":0}},"title-layout":{"margin":{"top":30,"bottom":0}},"byline-layout":{"columnStart":0,"columnSpan":7,"margin":{"top":10,"bottom":10}}},"metadata":{"excerpt":"As the service sector in the United States continues to boom, with jobs swelling in health care and declining in manufacturing, productivity gains remain elusive, reports The Wall Street Journal (Paywall). ... When companies appoint female CEOs, stock prices tank, according to a\u00a0report from Quartz. ... Companies with checkered histories are better off actively addressing...","thumbnailURL":"bundle:\/\/photo-1425421669292-0c3da3b8f529-1.jpg","dateCreated":"2016-10-31T13:30:26+00:00","dateModified":"2016-10-31T14:10:16+00:00","datePublished":"2016-10-31T13:30:26+00:00","canonicalURL":"http:\/\/www.talenteconomy.io\/2016\/10\/31\/the-talent-docket-october-31-2016\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"1.1.9"},"advertisingSettings":{"frequency":1,"layout":{"margin":{"top":15,"bottom":15}}}}`

**Comment by bcampeau** [comment]
This is a known issue which will be investigated soon.

**Comment by mattking5000** [comment]
Hi, just wondering if there's any news on this issue?

**Comment by pembo13** [comment]
Looks like `htmlentities($text, ENT_NOQUOTES | ENT_IGNORE | ENT_HTML5, 'UTF-8')` needs to be called on the generated value for the `text` entries of the nested JSON objects.

In this case, `\u2026` should be `&hellip;` -- `htmlentities` can handle this conversion.

**Comment by pembo13** [comment]
In `includes/apple-exporter/components/class-component.php:139` changing `$this->text      = $text;` to `$this->text      = htmlentities($text, ENT_NOQUOTES | ENT_IGNORE | ENT_HTML5, 'UTF-8');` might be enough to solve this at a high level.

Alternatively in `includes/apple-exporter/components/class-body.php` adding the following line to the beginning of the `build( $text )` function will target just the body component, which is likely to be more susceptible to copy-and-paste Unicode characters:

`$text = htmlentities($text, ENT_NOQUOTES | ENT_IGNORE | ENT_HTML5, 'UTF-8');`

**Comment by bcampeau** [comment]
This is something we're looking into for an upcoming version. Stay tuned.

**Comment by bcampeau** [comment]
I'm closing this issue for a few reasons.

1. `json_encode` is what actually converts characters to the `\uXXXX` format. It's perfectly valid and gets decoded on the other end. There's nothing at all invalid with the JSON in this ticket and if Apple rejected it, @mattking5000 you should really reach out to them for a more detailed explanation.
2. The issues that people are experiencing are with valid characters being turned into **sets** of invalid unicode characters like a `'` ending up as `\u00c3\u00a2\u00c2\u0080\u00c2\u0099` in the JSON.
3. We are going to introduce error handling for this condition to hopefully identify more reports of this issue on other sites.
