### ISSUE TITLE
Srcsets prevent images from being included

### ISSUE THREAD

**Issue by bcampeau** [alleyinteractive/apple-news#236]
Looks like possibly the srcset attribute breaks the regular expression that matches images. It should simply pull in the full size image from the src attribute and ignore the srcset.

See: https://wordpress.org/support/topic/images-didnt-appear-in-published-post/

**Comment by danielbachhuber** [comment]
If this was the case, wouldn't it affect all WordPress installs (e.g. inline images wouldn't ever be included)?

I'm pretty sure images with srcset work. In the process of debugging why our images weren't being included, I ran into https://github.com/Automattic/jetpack/issues/6179

**Comment by bcampeau** [comment]
The issue requires further investigation at some point

**Comment by kevinfodness** [comment]
This should not be an issue any longer, since we are explicitly matching the `src` attribute now.
