### ISSUE TITLE
Please add formatting for captions

### ISSUE THREAD

**Issue by nataliefeibish** [alleyinteractive/apple-news#237]
There is no way to tell a caption from the rest of the article -- very confusing when reading. Just italics would be fine.

**Comment by bcampeau** [comment]
You can customize the output of Apple News through any of the numerous filters included, but if you want this to be a setting we can consider it for a future version.

**Comment by nataliefeibish** [comment]
We can’t customize captions, it is not included in the filter that I can find. If you could show me how to do this, several people I work with would be very happy.

— Nat

——————————————————————————————
The ticketing email has changed.
Please email work requests to webhelp@religionnews.com

**Comment by bcampeau** [comment]
`apple_news_generate_json` lets you customize the final ANF output for the article, so there's really nothing that can't be customized.

**Comment by nataliefeibish** [comment]
Are we talking about the plugin? I’ll pull it up and try to figure out what you’re talking about.

— Nat

——————————————————————————————
The ticketing email has changed.
Please email work requests to webhelp@religionnews.com

**Comment by bcampeau** [comment]
I am talking about writing custom code in your theme that uses the filter hook I mentioned to modify the JSON output. If that's something you don't know how to do, you'll have to wait until we add this as a setting in the future.

Thanks.

**Comment by nataliefeibish** [comment]
Cool thanks. Just saying that since this is for people who publish news, usually with images and captions, and your plugin can’t handle making captions look different than text, so that readers won’t get confused, it might be something you bump up on the ol’ priority scale. Most people who use your plugin might notice that.

But thanks for the condescension?

— Nat

——————————————————————————————
The ticketing email has changed.
Please email work requests to webhelp@religionnews.com

**Comment by bcampeau** [comment]
"condescension"? Not sure I follow.

There are over 40 requests in queue and they have to be prioritized based on urgency. Although you may consider this urgent, there are many others that wouldn't. Furthermore, the plugin offers dozens of action and filter hooks to modify the behavior for those that know how to write a little bit of code. This is pretty standard practice for any WordPress plugin since we can't possibly include every single feature someone might want.

**Comment by nataliefeibish** [comment]
Captions is not a niche feature. It’s pretty major. Hugely so, when you’re under contract to give certain credits but you find that when you export captions they run into the rest of the copy, causing confusion. Even if you would just right-justify them or something, anything so that readers know that it’s not meant to be incorporated with the rest of the story visually.

And I agree, writing json is easy, figuring out where to access the environment between wp and apple news is not.

— Nat

——————————————————————————————
The ticketing email has changed.
Please email work requests to webhelp@religionnews.com

**Comment by bcampeau** [comment]
I'd start with this hook: https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-exporter/class-exporter.php#L192

**Comment by nataliefeibish** [comment]
Thanks. :)

— Nat

——————————————————————————————
The ticketing email has changed.
Please email work requests to webhelp@religionnews.com

**Comment by kevinfodness** [comment]
Hi @nataliefeibish—

The ability to add caption-specific styles is being added in the next version (1.2.2). Thanks for the feedback!
