### ISSUE TITLE
 API: NOT_FOUND (KEYPATH CHANNELID)

### ISSUE THREAD

**Issue by banjoski** [alleyinteractive/apple-news#238]
We cannot publish any of our WordPress posts to Apple News. We get the error:

THERE HAS BEEN AN ERROR WITH THE API: NOT_FOUND (KEYPATH CHANNELID)

Can anyone help?

**Comment by bcampeau** [comment]
Have you entered your API settings into the Apple News plugin settings?

Are you certain that your channel is approved and live?

Thanks.

**Comment by banjoski** [comment]
Yes, our Apple News channel is approved and live
https://apple.news/TPuih4T-XTu6hJCX4zkrJeQ <https://apple.news/TPuih4T-XTu6hJCX4zkrJeQ>

Exactly how do I get the API settings and where do I enter them in the plugin?

David Bandrowski
davidbandrowski.com
banjoski@gmail.com

**Comment by bcampeau** [comment]
Go to Settings > Apple News in your WordPress dashboard to get started. There's a link to the Apple News documentation to help you get those values. They're available from your iCloud Publisher account.

Thanks.

**Comment by banjoski** [comment]
I can find that in my WordPress dashboard, but the link just takes me here
https://developer.apple.com/news-publisher/ <https://developer.apple.com/news-publisher/>

I can’t find my API credentials in Apple News so I can cross check the credentials that are loaded on the plugin.

David Bandrowski
davidbandrowski.com
banjoski@gmail.com

**Comment by bcampeau** [comment]
Please log into your [iCloud News Publisher account](https://www.icloud.com/#newspublisher) then click on "Channel info" from the top nav and then "API Key" from the subnav. Everything you need is there.

Thanks.

**Comment by banjoski** [comment]
Success! Thx!

David Bandrowski
davidbandrowski.com
banjoski@gmail.com
