### ISSUE TITLE
API Response: Array

### ISSUE THREAD

**Issue by Kauschen** [alleyinteractive/apple-news#240]
Got this email today from Apple News. I have the proper API keys installed in all the right places, but still can't get any stories to publish to Apple News since March 16th, 2016

Eric

---

API Response:
Array
(
   [headers] => Requests_Utility_CaseInsensitiveDictionary Object
       (
           [data:protected] => Array
               (
                   [www-authenticate] => HHMAC
                   [content-type] => application/json; charset=UTF-8
                   [content-length] => 41
               )

       )

   [body] => {"errors":[{"code":"API_KEY_NOT_FOUND"}]}
   [response] => Array
       (
           [code] => 401
           [message] => Unauthorized
       )

   [cookies] => Array
       (
       )

   [filename] => 
   [http_response] => WP_HTTP_Requests_Response Object
       (
           [response:protected] => Requests_Response Object
               (
                   [body] => {"errors":[{"code":"API_KEY_NOT_FOUND"}]}
                   [raw] => HTTP/1.1 401 Unauthorized
WWW-Authenticate: HHMAC
Content-Type: application/json; charset=UTF-8
Content-Length: 41

{"errors":[{"code":"API_KEY_NOT_FOUND"}]}
                   [headers] => Requests_Response_Headers Object
                       (
                           [data:protected] => Array
                               (
                                   [www-authenticate] => Array
                                       (
                                           [0] => HHMAC
                                       )

                                   [content-type] => Array
                                       (
                                           [0] => application/json; charset=UTF-8
                                       )

                                   [content-length] => Array
                                       (
                                           [0] => 41
                                       )

                               )

                       )

                   [status_code] => 401
                   [protocol_version] => 1.1
                   [success] => 
                   [redirects] => 0
                   [url] => https://u48r14.digitalhub.com/channels/57e052bf-5929-4585-aaff-69b372729db2/articles
                   [history] => Array
                       (
                       )

                   [cookies] => Requests_Cookie_Jar Object
                       (
                           [cookies:protected] => Array
                               (
                               )

                       )

               )

           [filename:protected] => 
           [data] => 
           [headers] => 
           [status] => 
       )

)

Request Meta:

Array
(
   [data] => Array
       (
           [links] => Array
               (
                   [sections] => Array
                       (
                       )

               )

           [isPreview] => 1
       )

)

Image Settings:

Bundled images:
https://i1.wp.com/baghdadbythebaysf.com/wp-content/uploads/2016/11/amazon-logo-1-1007x1007.png?resize=300%2C300
https://i1.wp.com/baghdadbythebaysf.com/wp-content/uploads/2016/11/amazon-logo-1-1007x1007.png?resize=300%2C300

JSON:
{"version":"1.1","identifier":"post-5460","language":"en","title":"The \"Amazon Effect\" In San Francisco","documentStyle":{"backgroundColor":"#FAFAFA"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"title","text":"The \"Amazon Effect\" In San Francisco","textStyle":"default-title","layout":"title-layout"},{"role":"header","layout":"headerBelowTextPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"bundle:\/\/amazon-logo-1-1007x1007.png"}],"behavior":{"type":"parallax","factor":0.8}},{"role":"container","layout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#FAFAFA"},"components":[{"role":"byline","text":"by Eric Kauschen | Nov 25, 2016 | 6:44 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"body","text":"I like [Amazon.com](http:\/\/www.amazon.com). I like it a lot, but there\u2019s problems with that which I noticed the other day when I was driving around in San Francisco. I saw quite a few street merchants who had closed up shop here. No sign that they had moved. They just emptied out the place and left.\n\nI remembered the places that were there and have come to call this _**The Amazon Effect**_. It\u2019s not really all Amazon\u2019s fault, but they do what they do very well, probably better than most other online retailers. Buying online today is easy. The tech company [which I am now a previous employee of] would buy everything through Amazon and Amazon Prime Now. I had a bad headache one day and I can\u2019t take aspirin so I asked the girl who handles purchasing if there was any Tylenol around. She told me, _**If I don\u2019t find you within an hour check back with me and I\u2019ll have some Tylenol for you**_.\n\nShe didn\u2019t tell me to walk up to the local drug store which I could have done. I didn\u2019t even think about where it was coming from, but I happened to be upstairs and in walks a guy from Amazon Prime Now and delivered a bottle of 250 Tylenol which she handed over to me.\n\nHow pray tell, does a local store that I could have easily walked to and got what I need deal with that when someone can just pulled their smartphone and with a couple of taps get it delivered right to them within an hour? **They can\u2019t**. This is what I am calling [again] _**The Amazon Effect**_. Technology has made it so easy to order and return merchandise no matter how big or how small that there\u2019s no point to have to leave your house.\n\nThis is creating a problem with local merchants in San Francisco. It\u2019s probably happening all over the place, but in San Francisco where rent to live is already high, it\u2019s high for business owners as well. If you have to be rich to live in San Francisco, rich people will still need to buy things and that\u2019s what stores are for. If there\u2019s no stores then people will have to turn to their computers instead of going out shopping anymore.\n\nI\u2019ve noticed that there seem to be lots of people, in particular millennials who have no problem buying their groceries online instead of going to the store. For me, I personally want to be the one who looks at my meat and produce and decide if I want this apple or that apple. I don\u2019t want a worker who\u2019s paid minimum wage in a city that\u2019s too expensive to live in and probably doesn\u2019t care too much other than filling the orders quickly to pick my food for me.\n\nBig chain stores can easily survive this because sometimes you just want a pair of socks, not a pair of socks knitted by a fair trade paid Guatemalan single mother struggling. But chain stores has special rules in San Francisco so you have to have a car to get to most of them because they\u2019re outside the City. It\u2019s a noble idea, but I can\u2019t spend $20 on a pair of socks. Smaller family owned businesses like your corner stores that you can run to when you forgot something are hit the most. They can\u2019t compete on price unless they\u2019re selling booze or cigarettes and even on those products their markup is pretty small.\n\nRestaurants are hit as well, but San Francisco has the most restaurants in the nation and with a limited amount of food ideas there\u2019s only so many ways you can serve a burger, burrito or Asian food. Restaurants aren\u2019t as affected by Amazon because tech has allowed them to cook and deliver food through all of the food delivery tech companies so they don\u2019t need drivers, but if you\u2019ve got a ton of the same type of restaurants too close to each other then they all are kind of screwed.\n\nI unfortunately don\u2019t have an answer for this problem unless the City can offer incentives to these smaller businesses like they are to the big tech companies. Sometimes it seems that those who think San Francisco isn\u2019t what it used to be are blaming the people coming here without thinking the fact that San Francisco is changing because of the businesses we\u2019re losing.\n\nOh well, I guess I\u2019ll go get a Starbuck\u2019s Latte.","format":"markdown","textStyle":"dropcapBodyStyle","layout":"body-layout-last"}]}],"componentTextStyles":{"dropcapBodyStyle":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"lineHeight":24,"textColor":"#000000","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18,"dropCapStyle":{"numberOfLines":4,"numberOfCharacters":1,"padding":5,"fontName":"Georgia-Bold","textColor":"#000000"}},"default-body":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"lineHeight":24,"textColor":"#000000","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-title":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"textColor":"#000000","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"AvenirNext-Medium","fontSize":17,"textColor":"#53585f"}},"componentLayouts":{"anchored-image":{"margin":{"top":25,"bottom":25}},"body-layout":{"columnStart":0,"columnSpan":5,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":5,"margin":{"top":12,"bottom":30}},"title-layout":{"margin":{"top":30,"bottom":0}},"headerPhotoLayout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true},"headerBelowTextPhotoLayout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true,"margin":{"top":30,"bottom":0}},"byline-layout":{"columnStart":0,"columnSpan":7,"margin":{"top":10,"bottom":10}}},"metadata":{"excerpt":"I like Amazon.com. I like it a lot, but there's problems with that which I noticed the other day when I was driving around in San Francisco. I saw quite a few street merchants who had closed up shop here. No sign that they had moved. They just emptied out the place and left. I...","thumbnailURL":"bundle:\/\/amazon-logo-1-1007x1007.png","dateCreated":"2016-11-26T02:44:48+00:00","dateModified":"2016-11-26T02:47:52+00:00","datePublished":"2016-11-26T02:44:48+00:00","canonicalURL":"http:\/\/baghdadbythebaysf.com\/2016\/11\/the-amazon-effect-in-san-francisco\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"1.1.9"}}

MIME request:
Authorization: HHMAC; key=48906056-a6d3-4837-ae23-ecad657c89de; signature=2iV64Qc9oRRca8zeOmb8Z+cOtNjgZnot037rB38yK+Y=; date=2016-11-26T02:49:01+00:00
Content-Length: 27376
Content-Type: multipart/form-data; boundary=f6a86928d5482d4d23d89fba1725bbd5

--f6a86928d5482d4d23d89fba1725bbd5
Content-Type: application/json
Content-Disposition: form-data; name=metadata

{"data":{"links":{"sections":[]},"isPreview":true}}
--f6a86928d5482d4d23d89fba1725bbd5
Content-Type: application/json
Content-Disposition: form-data; name=my_article; filename=article.json; size=7229

{"version":"1.1","identifier":"post-5460","language":"en","title":"The \"Amazon Effect\" In San Francisco","documentStyle":{"backgroundColor":"#FAFAFA"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"title","text":"The \"Amazon Effect\" In San Francisco","textStyle":"default-title","layout":"title-layout"},{"role":"header","layout":"headerBelowTextPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"bundle:\/\/amazon-logo-1-1007x1007.png"}],"behavior":{"type":"parallax","factor":0.8}},{"role":"container","layout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#FAFAFA"},"components":[{"role":"byline","text":"by Eric Kauschen | Nov 25, 2016 | 6:44 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"body","text":"I like [Amazon.com](http:\/\/www.amazon.com). I like it a lot, but there\u2019s problems with that which I noticed the other day when I was driving around in San Francisco. I saw quite a few street merchants who had closed up shop here. No sign that they had moved. They just emptied out the place and left.\n\nI remembered the places that were there and have come to call this _**The Amazon Effect**_. It\u2019s not really all Amazon\u2019s fault, but they do what they do very well, probably better than most other online retailers. Buying online today is easy. The tech company [which I am now a previous employee of] would buy everything through Amazon and Amazon Prime Now. I had a bad headache one day and I can\u2019t take aspirin so I asked the girl who handles purchasing if there was any Tylenol around. She told me, _**If I don\u2019t find you within an hour check back with me and I\u2019ll have some Tylenol for you**_.\n\nShe didn\u2019t tell me to walk up to the local drug store which I could have done. I didn\u2019t even think about where it was coming from, but I happened to be upstairs and in walks a guy from Amazon Prime Now and delivered a bottle of 250 Tylenol which she handed over to me.\n\nHow pray tell, does a local store that I could have easily walked to and got what I need deal with that when someone can just pulled their smartphone and with a couple of taps get it delivered right to them within an hour? **They can\u2019t**. This is what I am calling [again] _**The Amazon Effect**_. Technology has made it so easy to order and return merchandise no matter how big or how small that there\u2019s no point to have to leave your house.\n\nThis is creating a problem with local merchants in San Francisco. It\u2019s probably happening all over the place, but in San Francisco where rent to live is already high, it\u2019s high for business owners as well. If you have to be rich to live in San Francisco, rich people will still need to buy things and that\u2019s what stores are for. If there\u2019s no stores then people will have to turn to their computers instead of going out shopping anymore.\n\nI\u2019ve noticed that there seem to be lots of people, in particular millennials who have no problem buying their groceries online instead of going to the store. For me, I personally want to be the one who looks at my meat and produce and decide if I want this apple or that apple. I don\u2019t want a worker who\u2019s paid minimum wage in a city that\u2019s too expensive to live in and probably doesn\u2019t care too much other than filling the orders quickly to pick my food for me.\n\nBig chain stores can easily survive this because sometimes you just want a pair of socks, not a pair of socks knitted by a fair trade paid Guatemalan single mother struggling. But chain stores has special rules in San Francisco so you have to have a car to get to most of them because they\u2019re outside the City. It\u2019s a noble idea, but I can\u2019t spend $20 on a pair of socks. Smaller family owned businesses like your corner stores that you can run to when you forgot something are hit the most. They can\u2019t compete on price unless they\u2019re selling booze or cigarettes and even on those products their markup is pretty small.\n\nRestaurants are hit as well, but San Francisco has the most restaurants in the nation and with a limited amount of food ideas there\u2019s only so many ways you can serve a burger, burrito or Asian food. Restaurants aren\u2019t as affected by Amazon because tech has allowed them to cook and deliver food through all of the food delivery tech companies so they don\u2019t need drivers, but if you\u2019ve got a ton of the same type of restaurants too close to each other then they all are kind of screwed.\n\nI unfortunately don\u2019t have an answer for this problem unless the City can offer incentives to these smaller businesses like they are to the big tech companies. Sometimes it seems that those who think San Francisco isn\u2019t what it used to be are blaming the people coming here without thinking the fact that San Francisco is changing because of the businesses we\u2019re losing.\n\nOh well, I guess I\u2019ll go get a Starbuck\u2019s Latte.","format":"markdown","textStyle":"dropcapBodyStyle","layout":"body-layout-last"}]}],"componentTextStyles":{"dropcapBodyStyle":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"lineHeight":24,"textColor":"#000000","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18,"dropCapStyle":{"numberOfLines":4,"numberOfCharacters":1,"padding":5,"fontName":"Georgia-Bold","textColor":"#000000"}},"default-body":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"lineHeight":24,"textColor":"#000000","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-title":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"textColor":"#000000","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"AvenirNext-Medium","fontSize":17,"textColor":"#53585f"}},"componentLayouts":{"anchored-image":{"margin":{"top":25,"bottom":25}},"body-layout":{"columnStart":0,"columnSpan":5,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":5,"margin":{"top":12,"bottom":30}},"title-layout":{"margin":{"top":30,"bottom":0}},"headerPhotoLayout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true},"headerBelowTextPhotoLayout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true,"margin":{"top":30,"bottom":0}},"byline-layout":{"columnStart":0,"columnSpan":7,"margin":{"top":10,"bottom":10}}},"metadata":{"excerpt":"I like Amazon.com. I like it a lot, but there's problems with that which I noticed the other day when I was driving around in San Francisco. I saw quite a few street merchants who had closed up shop here. No sign that they had moved. They just emptied out the place and left. I...","thumbnailURL":"bundle:\/\/amazon-logo-1-1007x1007.png","dateCreated":"2016-11-26T02:44:48+00:00","dateModified":"2016-11-26T02:47:52+00:00","datePublished":"2016-11-26T02:44:48+00:00","canonicalURL":"http:\/\/baghdadbythebaysf.com\/2016\/11\/the-amazon-effect-in-san-francisco\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"1.1.9"}}
--f6a86928d5482d4d23d89fba1725bbd5
Content-Type: application/octet-stream
Content-Disposition: form-data; name=amazon-logo-1-1007x1007png; filename=amazon-logo-1-1007x1007.png; size=19591

(binary contents of amazon-logo-1-1007x1007.png)
--f6a86928d5482d4d23d89fba1725bbd5--
API Response:
Array
(
   [headers] => Requests_Utility_CaseInsensitiveDictionary Object
       (
           [data:protected] => Array
               (
                   [www-authenticate] => HHMAC
                   [content-type] => application/json; charset=UTF-8
                   [content-length] => 41
               )

       )

   [body] => {"errors":[{"code":"API_KEY_NOT_FOUND"}]}
   [response] => Array
       (
           [code] => 401
           [message] => Unauthorized
       )

   [cookies] => Array
       (
       )

   [filename] => 
   [http_response] => WP_HTTP_Requests_Response Object
       (
           [response:protected] => Requests_Response Object
               (
                   [body] => {"errors":[{"code":"API_KEY_NOT_FOUND"}]}
                   [raw] => HTTP/1.1 401 Unauthorized
WWW-Authenticate: HHMAC
Content-Type: application/json; charset=UTF-8
Content-Length: 41

{"errors":[{"code":"API_KEY_NOT_FOUND"}]}
                   [headers] => Requests_Response_Headers Object
                       (
                           [data:protected] => Array
                               (
                                   [www-authenticate] => Array
                                       (
                                           [0] => HHMAC
                                       )

                                   [content-type] => Array
                                       (
                                           [0] => application/json; charset=UTF-8
                                       )

                                   [content-length] => Array
                                       (
                                           [0] => 41
                                       )

                               )

                       )

                   [status_code] => 401
                   [protocol_version] => 1.1
                   [success] => 
                   [redirects] => 0
                   [url] => https://u48r14.digitalhub.com/channels/57e052bf-5929-4585-aaff-69b372729db2/articles
                   [history] => Array
                       (
                       )

                   [cookies] => Requests_Cookie_Jar Object
                       (
                           [cookies:protected] => Array
                               (
                               )

                       )

               )

           [filename:protected] => 
           [data] => 
           [headers] => 
           [status] => 
       )

)

Request Meta:

Array
(
   [data] => Array
       (
           [links] => Array
               (
                   [sections] => Array
                       (
                       )

               )

           [isPreview] => 1
       )

)

Image Settings:

Bundled images:
https://i1.wp.com/baghdadbythebaysf.com/wp-content/uploads/2016/11/amazon-logo-1-1007x1007.png?resize=300%2C300
https://i1.wp.com/baghdadbythebaysf.com/wp-content/uploads/2016/11/amazon-logo-1-1007x1007.png?resize=300%2C300

JSON:
{"version":"1.1","identifier":"post-5460","language":"en","title":"The \"Amazon Effect\" In San Francisco","documentStyle":{"backgroundColor":"#FAFAFA"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"title","text":"The \"Amazon Effect\" In San Francisco","textStyle":"default-title","layout":"title-layout"},{"role":"header","layout":"headerBelowTextPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"bundle:\/\/amazon-logo-1-1007x1007.png"}],"behavior":{"type":"parallax","factor":0.8}},{"role":"container","layout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#FAFAFA"},"components":[{"role":"byline","text":"by Eric Kauschen | Nov 25, 2016 | 6:44 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"body","text":"I like [Amazon.com](http:\/\/www.amazon.com). I like it a lot, but there\u2019s problems with that which I noticed the other day when I was driving around in San Francisco. I saw quite a few street merchants who had closed up shop here. No sign that they had moved. They just emptied out the place and left.\n\nI remembered the places that were there and have come to call this _**The Amazon Effect**_. It\u2019s not really all Amazon\u2019s fault, but they do what they do very well, probably better than most other online retailers. Buying online today is easy. The tech company [which I am now a previous employee of] would buy everything through Amazon and Amazon Prime Now. I had a bad headache one day and I can\u2019t take aspirin so I asked the girl who handles purchasing if there was any Tylenol around. She told me, _**If I don\u2019t find you within an hour check back with me and I\u2019ll have some Tylenol for you**_.\n\nShe didn\u2019t tell me to walk up to the local drug store which I could have done. I didn\u2019t even think about where it was coming from, but I happened to be upstairs and in walks a guy from Amazon Prime Now and delivered a bottle of 250 Tylenol which she handed over to me.\n\nHow pray tell, does a local store that I could have easily walked to and got what I need deal with that when someone can just pulled their smartphone and with a couple of taps get it delivered right to them within an hour? **They can\u2019t**. This is what I am calling [again] _**The Amazon Effect**_. Technology has made it so easy to order and return merchandise no matter how big or how small that there\u2019s no point to have to leave your house.\n\nThis is creating a problem with local merchants in San Francisco. It\u2019s probably happening all over the place, but in San Francisco where rent to live is already high, it\u2019s high for business owners as well. If you have to be rich to live in San Francisco, rich people will still need to buy things and that\u2019s what stores are for. If there\u2019s no stores then people will have to turn to their computers instead of going out shopping anymore.\n\nI\u2019ve noticed that there seem to be lots of people, in particular millennials who have no problem buying their groceries online instead of going to the store. For me, I personally want to be the one who looks at my meat and produce and decide if I want this apple or that apple. I don\u2019t want a worker who\u2019s paid minimum wage in a city that\u2019s too expensive to live in and probably doesn\u2019t care too much other than filling the orders quickly to pick my food for me.\n\nBig chain stores can easily survive this because sometimes you just want a pair of socks, not a pair of socks knitted by a fair trade paid Guatemalan single mother struggling. But chain stores has special rules in San Francisco so you have to have a car to get to most of them because they\u2019re outside the City. It\u2019s a noble idea, but I can\u2019t spend $20 on a pair of socks. Smaller family owned businesses like your corner stores that you can run to when you forgot something are hit the most. They can\u2019t compete on price unless they\u2019re selling booze or cigarettes and even on those products their markup is pretty small.\n\nRestaurants are hit as well, but San Francisco has the most restaurants in the nation and with a limited amount of food ideas there\u2019s only so many ways you can serve a burger, burrito or Asian food. Restaurants aren\u2019t as affected by Amazon because tech has allowed them to cook and deliver food through all of the food delivery tech companies so they don\u2019t need drivers, but if you\u2019ve got a ton of the same type of restaurants too close to each other then they all are kind of screwed.\n\nI unfortunately don\u2019t have an answer for this problem unless the City can offer incentives to these smaller businesses like they are to the big tech companies. Sometimes it seems that those who think San Francisco isn\u2019t what it used to be are blaming the people coming here without thinking the fact that San Francisco is changing because of the businesses we\u2019re losing.\n\nOh well, I guess I\u2019ll go get a Starbuck\u2019s Latte.","format":"markdown","textStyle":"dropcapBodyStyle","layout":"body-layout-last"}]}],"componentTextStyles":{"dropcapBodyStyle":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"lineHeight":24,"textColor":"#000000","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18,"dropCapStyle":{"numberOfLines":4,"numberOfCharacters":1,"padding":5,"fontName":"Georgia-Bold","textColor":"#000000"}},"default-body":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"lineHeight":24,"textColor":"#000000","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-title":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"textColor":"#000000","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"AvenirNext-Medium","fontSize":17,"textColor":"#53585f"}},"componentLayouts":{"anchored-image":{"margin":{"top":25,"bottom":25}},"body-layout":{"columnStart":0,"columnSpan":5,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":5,"margin":{"top":12,"bottom":30}},"title-layout":{"margin":{"top":30,"bottom":0}},"headerPhotoLayout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true},"headerBelowTextPhotoLayout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true,"margin":{"top":30,"bottom":0}},"byline-layout":{"columnStart":0,"columnSpan":7,"margin":{"top":10,"bottom":10}}},"metadata":{"excerpt":"I like Amazon.com. I like it a lot, but there's problems with that which I noticed the other day when I was driving around in San Francisco. I saw quite a few street merchants who had closed up shop here. No sign that they had moved. They just emptied out the place and left. I...","thumbnailURL":"bundle:\/\/amazon-logo-1-1007x1007.png","dateCreated":"2016-11-26T02:44:48+00:00","dateModified":"2016-11-26T02:47:52+00:00","datePublished":"2016-11-26T02:44:48+00:00","canonicalURL":"http:\/\/baghdadbythebaysf.com\/2016\/11\/the-amazon-effect-in-san-francisco\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"1.1.9"}}

MIME request:
Authorization: HHMAC; key=48906056-a6d3-4837-ae23-ecad657c89de; signature=2iV64Qc9oRRca8zeOmb8Z+cOtNjgZnot037rB38yK+Y=; date=2016-11-26T02:49:01+00:00
Content-Length: 27376
Content-Type: multipart/form-data; boundary=f6a86928d5482d4d23d89fba1725bbd5

--f6a86928d5482d4d23d89fba1725bbd5
Content-Type: application/json
Content-Disposition: form-data; name=metadata

{"data":{"links":{"sections":[]},"isPreview":true}}
--f6a86928d5482d4d23d89fba1725bbd5
Content-Type: application/json
Content-Disposition: form-data; name=my_article; filename=article.json; size=7229

{"version":"1.1","identifier":"post-5460","language":"en","title":"The \"Amazon Effect\" In San Francisco","documentStyle":{"backgroundColor":"#FAFAFA"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"title","text":"The \"Amazon Effect\" In San Francisco","textStyle":"default-title","layout":"title-layout"},{"role":"header","layout":"headerBelowTextPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"bundle:\/\/amazon-logo-1-1007x1007.png"}],"behavior":{"type":"parallax","factor":0.8}},{"role":"container","layout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#FAFAFA"},"components":[{"role":"byline","text":"by Eric Kauschen | Nov 25, 2016 | 6:44 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"body","text":"I like [Amazon.com](http:\/\/www.amazon.com). I like it a lot, but there\u2019s problems with that which I noticed the other day when I was driving around in San Francisco. I saw quite a few street merchants who had closed up shop here. No sign that they had moved. They just emptied out the place and left.\n\nI remembered the places that were there and have come to call this _**The Amazon Effect**_. It\u2019s not really all Amazon\u2019s fault, but they do what they do very well, probably better than most other online retailers. Buying online today is easy. The tech company [which I am now a previous employee of] would buy everything through Amazon and Amazon Prime Now. I had a bad headache one day and I can\u2019t take aspirin so I asked the girl who handles purchasing if there was any Tylenol around. She told me, _**If I don\u2019t find you within an hour check back with me and I\u2019ll have some Tylenol for you**_.\n\nShe didn\u2019t tell me to walk up to the local drug store which I could have done. I didn\u2019t even think about where it was coming from, but I happened to be upstairs and in walks a guy from Amazon Prime Now and delivered a bottle of 250 Tylenol which she handed over to me.\n\nHow pray tell, does a local store that I could have easily walked to and got what I need deal with that when someone can just pulled their smartphone and with a couple of taps get it delivered right to them within an hour? **They can\u2019t**. This is what I am calling [again] _**The Amazon Effect**_. Technology has made it so easy to order and return merchandise no matter how big or how small that there\u2019s no point to have to leave your house.\n\nThis is creating a problem with local merchants in San Francisco. It\u2019s probably happening all over the place, but in San Francisco where rent to live is already high, it\u2019s high for business owners as well. If you have to be rich to live in San Francisco, rich people will still need to buy things and that\u2019s what stores are for. If there\u2019s no stores then people will have to turn to their computers instead of going out shopping anymore.\n\nI\u2019ve noticed that there seem to be lots of people, in particular millennials who have no problem buying their groceries online instead of going to the store. For me, I personally want to be the one who looks at my meat and produce and decide if I want this apple or that apple. I don\u2019t want a worker who\u2019s paid minimum wage in a city that\u2019s too expensive to live in and probably doesn\u2019t care too much other than filling the orders quickly to pick my food for me.\n\nBig chain stores can easily survive this because sometimes you just want a pair of socks, not a pair of socks knitted by a fair trade paid Guatemalan single mother struggling. But chain stores has special rules in San Francisco so you have to have a car to get to most of them because they\u2019re outside the City. It\u2019s a noble idea, but I can\u2019t spend $20 on a pair of socks. Smaller family owned businesses like your corner stores that you can run to when you forgot something are hit the most. They can\u2019t compete on price unless they\u2019re selling booze or cigarettes and even on those products their markup is pretty small.\n\nRestaurants are hit as well, but San Francisco has the most restaurants in the nation and with a limited amount of food ideas there\u2019s only so many ways you can serve a burger, burrito or Asian food. Restaurants aren\u2019t as affected by Amazon because tech has allowed them to cook and deliver food through all of the food delivery tech companies so they don\u2019t need drivers, but if you\u2019ve got a ton of the same type of restaurants too close to each other then they all are kind of screwed.\n\nI unfortunately don\u2019t have an answer for this problem unless the City can offer incentives to these smaller businesses like they are to the big tech companies. Sometimes it seems that those who think San Francisco isn\u2019t what it used to be are blaming the people coming here without thinking the fact that San Francisco is changing because of the businesses we\u2019re losing.\n\nOh well, I guess I\u2019ll go get a Starbuck\u2019s Latte.","format":"markdown","textStyle":"dropcapBodyStyle","layout":"body-layout-last"}]}],"componentTextStyles":{"dropcapBodyStyle":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"lineHeight":24,"textColor":"#000000","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18,"dropCapStyle":{"numberOfLines":4,"numberOfCharacters":1,"padding":5,"fontName":"Georgia-Bold","textColor":"#000000"}},"default-body":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"lineHeight":24,"textColor":"#000000","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-title":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"textColor":"#000000","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"AvenirNext-Medium","fontSize":17,"textColor":"#53585f"}},"componentLayouts":{"anchored-image":{"margin":{"top":25,"bottom":25}},"body-layout":{"columnStart":0,"columnSpan":5,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":5,"margin":{"top":12,"bottom":30}},"title-layout":{"margin":{"top":30,"bottom":0}},"headerPhotoLayout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true},"headerBelowTextPhotoLayout":{"columnStart":0,"columnSpan":7,"ignoreDocumentMargin":true,"margin":{"top":30,"bottom":0}},"byline-layout":{"columnStart":0,"columnSpan":7,"margin":{"top":10,"bottom":10}}},"metadata":{"excerpt":"I like Amazon.com. I like it a lot, but there's problems with that which I noticed the other day when I was driving around in San Francisco. I saw quite a few street merchants who had closed up shop here. No sign that they had moved. They just emptied out the place and left. I...","thumbnailURL":"bundle:\/\/amazon-logo-1-1007x1007.png","dateCreated":"2016-11-26T02:44:48+00:00","dateModified":"2016-11-26T02:47:52+00:00","datePublished":"2016-11-26T02:44:48+00:00","canonicalURL":"http:\/\/baghdadbythebaysf.com\/2016\/11\/the-amazon-effect-in-san-francisco\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"1.1.9"}}
--f6a86928d5482d4d23d89fba1725bbd5
Content-Type: application/octet-stream
Content-Disposition: form-data; name=amazon-logo-1-1007x1007png; filename=amazon-logo-1-1007x1007.png; size=19591

(binary contents of amazon-logo-1-1007x1007.png)
--f6a86928d5482d4d23d89fba1725bbd5--

**Comment by bcampeau** [comment]
Have you reached out to Apple News support? If your API key is invalid, there's nothing we can do on our end.
