### ISSUE TITLE
Visual Composer shortcodes don't work

### ISSUE THREAD

**Issue by jhowley1989** [alleyinteractive/apple-news#250]
Just leaving this in case it helps anyone else...

As per https://github.com/WP-API/WP-API/issues/2578

You need to call `WPBMap::addAllMappedShortcodes();` so that VC shortcodes get registered.  Probably best in `apple_news_do_fetch_exporter` action

**Comment by jhowley1989** [comment]
As above this is easily resolved, I just wanted to leave a record of the fix so it is more easily discovered.

**Comment by bcampeau** [comment]
We're not ever going to support Visual Composer or any other WordPress page builder. Filter hooks are available for this exact reason and you're welcome to handle that way.

If Visual Composer wants to handle this or if you'd like to release a plugin for it, you're more than welcome.
