### ISSUE TITLE
Title not displayed, missing from components

### ISSUE THREAD

**Issue by sanchothefat** [alleyinteractive/apple-news#26]
I have a patch for this, but seems odd for it not to be there as this will be affecting all users. Perhaps Apple made a change recently affecting this.

**Comment by sanchothefat** [comment]
Sorry @bcampeau - forget most people will have all notifications off except for mentions! I used to get way too many GH emails.

**Comment by bcampeau** [comment]
As commented on the pull request, we'll definitely merge this very soon for the next release. In the meantime, you can definitely use one of the filters to insert this. Thanks!

**Comment by sanchothefat** [comment]
Great! Let me know if I can help with any of the tests.
