### ISSUE TITLE
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string)

### ISSUE THREAD

**Issue by protoolreviews** [alleyinteractive/apple-news#260]
There has been an error with the API:
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->2->components->153->text)
INVALID_DOCUMENT - no components defined for role=heading3 (keyPath components->2->components->153)

**Comment by bcampeau** [comment]
This is a duplicate of #205
