### ISSUE TITLE
Issue with Instagram component support

### ISSUE THREAD

**Issue by bcampeau** [alleyinteractive/apple-news#261]
https://developer.apple.com/library/content/documentation/General/Conceptual/Apple_News_Format_Ref/Instagram.html#//apple_ref/doc/uid/TP40015408-CH22-SW1

**Comment by webdeveric** [comment]
@bcampeau I've found that adding `global $post;` before `get_post()` will make the Instagram oEmbeds work properly. 

https://github.com/alleyinteractive/apple-news/blob/master/admin/apple-actions/index/class-export.php#L59

**Comment by bcampeau** [comment]
Instagram components aren't officially supported by the plugin at this time, hence this issue. We'll take your suggestion into consideration when we get there.
