### ISSUE TITLE
There has been an error with the API: NOT_FOUND (keyPath articleId)

### ISSUE THREAD

**Issue by jietouwuzhe** [alleyinteractive/apple-news#265]
when i publish news , i got error : There has been an error with the API: NOT_FOUND (keyPath articleId)

**Comment by bcampeau** [comment]
Please ensure you've [entered your API credentials](https://github.com/alleyinteractive/apple-news/wiki/configuration#api-settings) correctly into the Apple News Settings.

**Comment by chuckmacak** [comment]
I am getting the same error and my creds are entered in the plugin

**Comment by iamkingsleyf** [comment]
same error even in 2019 and yes my API is correct as new articles are pushed to apple news
