### ISSUE TITLE
Invalid unicode character sequences were found that could cause display issues on Apple News

### ISSUE THREAD

**Issue by CriticalCareDVM** [alleyinteractive/apple-news#273]
Any recommendations?

Full disclosure - I'm a nube to this. Am just a guy trying to get my blog more exposure through Apple News. Don't know coding, but am willing to learn and am a pretty quick learner. Any help is greatly appreciated!

**Comment by bcampeau** [comment]
Can you please provide the JSON output for that post? If you don't know how to do that, [please read the instructions here](https://github.com/alleyinteractive/apple-news/wiki/usage#downloading-posts).

Thanks.

**Comment by CriticalCareDVM** [comment]
I think I did it properly

cgb

**Comment by bcampeau** [comment]
There's no JSON file here. You can also just paste it here as `code`.

**Comment by bcampeau** [comment]
This is a duplicate of issue #271 so please follow up there. Thanks.
