### ISSUE TITLE
Unsupported components

### ISSUE THREAD

**Issue by CriticalCareDVM** [alleyinteractive/apple-news#275]
i have a couple of posts that won't publish and give me the following errors:

<img width="699" alt="screen shot 2017-01-11 at 21 56 03" src="https://cloud.githubusercontent.com/assets/25047316/21876535/56a4524e-d849-11e6-89f9-0e23b5f2e379.png">

<img width="609" alt="screen shot 2017-01-11 at 21 59 33" src="https://cloud.githubusercontent.com/assets/25047316/21876536/58961696-d849-11e6-8465-87d2861df5b7.png">

i can't seem to upload JSONs to here - i keep getting a message that the file type isn't supported.

i'm sorry in advance if this is quite remedial, but i'm definitely a tube. excited to learn but absolutely bloody dumb when it comes to this stuff. thanks for any help!

**Comment by bcampeau** [comment]
Please copy and paste the JSON for the affected posts here as `code`. Alternatively you can use a [github gist](https://gist.github.com/).

**Comment by kevinfodness** [comment]
Hi @CriticalCareDVM—

Tables are not supported by the Apple News format, even when HTML formatting is turned on. There is an open issue to add support for tables in some form in a future version of the plugin here:

https://github.com/alleyinteractive/apple-news/issues/153

Unfortunately, you won't be able to export content containing tables at this time.
