### ISSUE TITLE
activation error

### ISSUE THREAD

**Issue by heysooooos** [alleyinteractive/apple-news#276]
Parse error: syntax error, unexpected T_STRING in /home/content/39/7725539/html/grannytravels/wp-content/plugins/publish-to-apple-news/apple-news.php on line 44

I have deleted and reinstalled the plugin but get the same error.

Help appreciated.
Thanks

**Comment by bcampeau** [comment]
You're using an invalid version of PHP. It needs to be 5.3.6 or higher. Please contact your web host and see if they can upgrade you. The minimum requirements to use this plugin are [defined in the wiki](https://github.com/alleyinteractive/apple-news/wiki/installation#minimum-requirements).

Thanks.

**Comment by heysooooos** [comment]
thank you I will let godaddy know


*Susan Colby949.220.6856*
*011 27 (71) 563.6551 (South Africa)*

GrannyTravels.com <http://grannytravels.com/>
My Portfolio
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LQ1ydVdnGtn1qfXknW4WrNGj56dPLqf4T4RxM02?t=https%3A%2F%2Fsusancolby.contently.com%2F&si=5626402954543104&pi=0092661a-43f1-4d30-f058-e630a24468b9>
My Steller
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LQ1ydVdnGtn1qfXknW4WrNGj56dPLqf4T4RxM02?t=https%3A%2F%2Fsteller.co%2Fheysooooos&si=5626402954543104&pi=0092661a-43f1-4d30-f058-e630a24468b9>
My Stock Photos
<http://t.sidekickopen68.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LQ1ydVdnGtn1qfXknW4WrNGj56dPLqf4T4RxM02?t=https%3A%2F%2Fwww.eyeem.com%2Fu%2Fheysooooos&si=5626402954543104&pi=0092661a-43f1-4d30-f058-e630a24468b9>
