### ISSUE TITLE
Add the ability to use the Manual Author input in Wordpress.

### ISSUE THREAD

**Issue by NewMediaCentralDeveloper** [alleyinteractive/apple-news#279]
I request that if a name is entered into the Manual Author input box on wordpress that it overrides the name of the person who posted the wordpress article. In my organization, the authors do not all have wordpress accounts. So we use the manual author input to attribute each author. However I've noticed that when Apple News pulls this info in the app, it uses the who actually posted info and not the manual author input. I'd like to have this option.

**Comment by bcampeau** [comment]
I'm not sure what you mean by "Manual Author" input. Is that a WordPress plugin?

**Comment by kevinfodness** [comment]
Hi @NewMediaCentralDeveloper—

Alternately, you could use the `apple_news_exporter_byline` filter to modify the byline that is generated by the plugin to hook into the manual author functionality that you have on your site. As you can imagine, we cannot build in support for every third party plugin, but there are a number of filters available that allow you to customize the output yourself.
