### ISSUE TITLE
Can't add custom fonts

### ISSUE THREAD

**Issue by sanchothefat** [alleyinteractive/apple-news#28]
Couple of steps needed here in my view:

1. Add a field on the settings page for uploading ttf or otf files
2. Add the uploaded fonts to the tmp folder during push along with other media
3. Enable addition of fonts through code by adding a filter for an array of post script names and file paths

Point 3 is probably the quickest / simplest win. I'll work on a patch to cover all points though.

**Comment by harvitronix** [comment]
Currently, fonts need to be e-mailed to Apple to be included in our channel. It doesn't look like we can currently send fonts along with other media, though perhaps that's going to change?

So I think point 3 is the best bet for now.

What do you think, @bcampeau?

**Comment by bcampeau** [comment]
#3 is could also be useful for other non-standard stuff they could allow us to bundle, so I'd be open to a PR for that.

**Comment by sanchothefat** [comment]
@bcampeau @harvitronix good to know thanks. I'll work on that angle to start with and see about adding a hook for adding any other files from a theme or plugin to the tmp folder during push / update.

**Comment by bcampeau** [comment]
Are you still planning on submitting a PR for this or has this been handled otherwise? Thanks.
