### ISSUE TITLE
<pre> tags don't get monospace / white-space treatment

### ISSUE THREAD

**Issue by chriscoyier** [alleyinteractive/apple-news#286]
Even with "Enable HTML support?" **Yes** ...

![screen shot 2017-01-24 at 5 58 04 pm](https://cloud.githubusercontent.com/assets/69156/22270659/aa338550-e25e-11e6-9c52-0b071a283c31.png)

Which in the cool little preview area look like this:

![screen shot 2017-01-24 at 5 58 17 pm](https://cloud.githubusercontent.com/assets/69156/22270671/b8575062-e25e-11e6-86f6-be7732046531.png)

And in the WordPress editor look like this:

![screen shot 2017-01-24 at 5 59 01 pm](https://cloud.githubusercontent.com/assets/69156/22270692/d11e7152-e25e-11e6-86ef-b4af72a00122.png)

Come out in Apple News like this:

![img_2300](https://cloud.githubusercontent.com/assets/69156/22270699/dad6cbcc-e25e-11e6-880a-97293369aef4.PNG)

**Comment by kevinfodness** [comment]
I believe this will be fixed by the 1.2.4 update, in which I made `pre` a first-class citizen for constructing block elements. In my local pre-release branch, what you have in the text tab renders properly in my JSON output.

**Comment by kevinfodness** [comment]
@chriscoyier—

Now that the 1.2.4 update is out, can you try again and let me know how you fare?

Thanks.

**Comment by chriscoyier** [comment]
Not so good I'm afraid. I definitely have the HTML support checkbox on. 

I just freshly installed the plugin and freshly posted a new post. Here's a post on Apple News on my iPhone after publishing:

![img](http://d.pr/i/unDL/4RLIX3id+)

I published a few other articles and got some weird errors about simple HTML elements being removed: 

![screen shot 2017-03-09 at 1 35 45 pm](https://cloud.githubusercontent.com/assets/69156/23765045/cba27354-04cd-11e7-803c-88bc3b6d8012.png)

And some weird timeout errors on certain posts:

![screen shot 2017-03-09 at 1 36 54 pm](https://cloud.githubusercontent.com/assets/69156/23765047/d0d64c56-04cd-11e7-9a5e-c57ac34ab4f5.png)

**Comment by bcampeau** [comment]
Are you using remote images? Timeouts can definitely occur if you're still using bundled images.

**Comment by bcampeau** [comment]
@chriscoyier I think this might be related to #352. We should be releasing a fix for that tomorrow as version 1.2.7 if you want to retest once it's out.

**Comment by kevinfodness** [comment]
Hi @chriscoyier—can you try again on the latest version (1.2.7)? It's working fine for me on 1.2.7 in both the downloaded JSON and my test Apple News channel.

**Comment by chriscoyier** [comment]
Works! 

Here and there I get random stuff like:

![screen shot 2017-05-11 at 11 46 39 am](https://cloud.githubusercontent.com/assets/69156/25958751/899b0996-363f-11e7-93f0-353599c249d9.png)

But 90% of posts are publishing and looking great!

**Comment by kevinfodness** [comment]
Great! I'm going to close this ticket so I can close out the 1.2.7 milestone, but if you can provide the JSON for one of the failing posts in a separate issue, I'd be really interested to see it.

Thanks!
