### ISSUE TITLE
Determine whether Apple News JSON is being prepared when rendering a shortcode

### ISSUE THREAD

**Issue by danielbachhuber** [alleyinteractive/apple-news#287]
When inside a shortcode callback, it would be helpful if there was an explicit API for determining whether Apple News JSON is being prepared (vs. rendering a feed, etc.)

Possibly `is_apple_news()`, which referenced some state stored inside of `Apple_Actions\Index()->fetch_exporter()`?

**Comment by bcampeau** [comment]
@danielbachhuber would a constant work better/equivalently for you?

**Comment by danielbachhuber** [comment]
A constant _could_ work, but is less perfect imo, because a constant can't be unset. You'd also need to make the assumption that the process always ends immediately after the JSON is being prepared.
