### ISSUE TITLE
admin_notices show up in the wrong place

### ISSUE THREAD

**Issue by webdeveric** [alleyinteractive/apple-news#300]
I've noticed that `admin_notices` show up in the wrong spot on the settings page.

![image](https://cloud.githubusercontent.com/assets/1823514/22530126/d90e81ee-e89f-11e6-814c-e4f3383aa53d.png)

The JS that moves the `<div>` is here: https://github.com/WordPress/WordPress/blob/master/wp-admin/js/common.js#L391

I think the fix is to change `<h3>` to `<h2>` here: https://github.com/alleyinteractive/apple-news/blob/c28ca60d3169c171d19c8663d1323862b4f10093/admin/partials/page_options_section.php#L1

**Comment by bcampeau** [comment]
This is already fixed in the latest master and will be released with version 1.2.2 tomorrow

**Comment by webdeveric** [comment]
@bcampeau I'm using version `1.2.2` and the `admin_notices` are still going in the wrong spot. 

![image](https://cloud.githubusercontent.com/assets/1823514/22600046/87895b18-e9fe-11e6-8fe8-c1c928696a27.png)
