### ISSUE TITLE
Exclude post from Apple News?

### ISSUE THREAD

**Issue by kcomposite** [alleyinteractive/apple-news#319]
Other than marking the box to publish an article as a Preview, is there a simple way to exclude a new post from being sent to Apple News?

**Comment by kevinfodness** [comment]
Hi @kcomposite—

There is no way in the admin to exclude specific posts from being sent to Apple News if you have the "Automatically publish to Apple News when published in WordPress" setting set to "yes".

If you set that setting to "no", you can manually publish whichever articles you wish and be in full control of publishing.

Alternately, you could use the `apple_news_skip_push` filter to prevent posts from being pushed to Apple News, either through a custom field that you define, or through rules such as belonging to a particular category, etc. You would need to write the code for that yourself in the theme or in a plugin.

More info is available here: https://github.com/alleyinteractive/apple-news/wiki/action-and-filter-hooks#adminapple-actionsindexclass-pushphp-1
