### ISSUE TITLE
Handle cases where images are wrapped in headings

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/apple-news#320]
This code:

`<h2><img src="..."></h2>`

Yields an empty `heading2` element in the rendered JSON, both removing the image and causing a problem with an empty content element. The image component should be modified to determine if an image is the only element inside of a containing tag, and should be transformed to an image element instead of an empty heading.

Technically, this is input error, but since it is easy enough to do in the visual editor by mistake, the plugin should account for it.

**Comment by VenusVenus** [comment]
Thank you.  HOwever, I get a list of errors when I try to publish.... here's the short version:

There has been an error with the API:
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->27->text)
INVALID_DOCUMENT - no components defined for role=heading2 (keyPath components->27)

**Comment by kevinfodness** [comment]
If you convert the `<h2>` wrapping your image to a `<p>` and try again, do you still get the error? Can you check to ensure there aren't other places in your post where you have `<h2>`s wrapping images?

**Comment by VenusVenus** [comment]
It doesn't appear that my images are wrapped in a <h> tag.  

<a href="http://ayrial.com/wp-content/uploads/2016/03/Viviana_Estrada.png"><img class=" wp-image-14208 alignleft" src="http://ayrial.com/wp-content/uploads/2016/03/Viviana_Estrada.png" alt="Viviana_Estrada, Feng Shui Chinese Astrology" width="215" height="144" /></a>

**Comment by VenusVenus** [comment]
I’ve checked and I don’t see any images wrapped in <h2> . I did find the image code and it ended with <a> I removed that and it still didn’t  help. 

 

]<a href="http://ayrial.com/wp-content/uploads/2013/04/Viviana_Estrada.png"><img class=" wp-image-17096 alignleft" src="http://ayrial.com/wp-content/uploads/2013/04/Viviana_Estrada.png" alt="" width="197" height="173" /></a>

 

Is it possible this  plugin for apple news isn’t compatible with Fushion Sliders?

**Comment by bcampeau** [comment]
We don't guarantee compatibility with every WordPress plugin since many produce HTML that's incompatible with Apple News or just generally invalid, as @kevinfodness outlined here. It's up to you or the plugin developer to rectify any incompatibilities with Apple News.

**Comment by VenusVenus** [comment]
Oh, thanks!  APPLE news points to Github regarding the plugin issues.  I merely brought up the sliders, however they are not marked with any <h2> tags.  There’s NOTHING, no text nor images with <h2> tags that I can see!!!!

**Comment by kevinfodness** [comment]
Hi @VenusVenus—

In the pastebin.com link you sent in #353 there is the following, which I believe is the root cause of your difficulty:

```html
<h2><a href="http://ayrial.com/wp-content/uploads/2017/02/logo2x1.png"><img class="aligncenter size-full wp-image-19373" src="http://ayrial.com/wp-content/uploads/2017/02/logo2x1.png" alt="" width="352" height="152" /></a></h2>
```

What happens during processing is that all HTML tags get stripped from within the headings, which triggers a bug where there is no bare text, as is the case in the above snippet.

It is possible that Fusion Slider is causing issues with the plugin, but my local tests point to this block being the root cause, and not Fusion Slider. You should be able to edit this HTML directly from within the Text tab in the content editor and swap the `<h2>` for a `<p>`.
