### ISSUE TITLE
Programmatically delete

### ISSUE THREAD

**Issue by smerriman** [alleyinteractive/apple-news#340]
I want to have a script which regularly deletes 'old' posts from Apple News (and ensures they don't get republished upon editing).

While posts can be manually deleted via the Apple News overview page, the function which do so appear to be deeply embedded within inaccessible classes.

Could the deletion script be made accessible - or any other suggestions? (Barring something ugly like having a cron script 'log in' and visit the deletion URL).

**Comment by bcampeau** [comment]
Why can't you construct an instance of the `Delete` class? The constructor and the `perform` function are both public.

https://github.com/alleyinteractive/apple-news/blob/master/admin/apple-actions/index/class-delete.php
