### ISSUE TITLE
Do not require administrator email if Enable Debugging is set to "no"

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/apple-news#342]
Currently, you cannot save the plugin settings if you do not enter an administrator email, even if Enable Debugging is set to "no."

Add logic to set the "required" attribute on the administrator email field conditionally using JavaScript depending on the value of the Enable Debugging setting.

**Comment by bcampeau** [comment]
It's being enforced at the browser level because the attribute is set on the form element.
