### ISSUE TITLE
Include custom fields in body of article?

### ISSUE THREAD

**Issue by DaveHamilton** [alleyinteractive/apple-news#354]
We have a few custom post types where the "body" of the post is assembled by combining together a few fields. Podcasts are an example, where we have 4 text blocks (`body`, `sponsor block`, and `shownotes`, not in that order) that combine together to form the "full" article. The Publish to Apple News plugin defaults to using just the `body` field for this. This simultaneously makes sense but also only displays part of the full article resulting in an incomplete post appearing in Apple News.

I took a look at the custom Themes and JSON but didn't see a way to control what was in the body of an article being pushed. Am I missing something simple, or is this more difficult than I'm hoping? ;)

**Comment by kevinfodness** [comment]
Hi @DaveHamilton—

In order to include custom fields, you will need to hook into `apple_news_exporter_content_pre`: https://github.com/alleyinteractive/apple-news/wiki/Action-and-Filter-Hooks#filter-hooks

If you're unfamiliar with filters, I'd recommend reading https://codex.wordpress.org/Glossary#Filter and https://developer.wordpress.org/reference/functions/add_filter/.

**Comment by phylaxis** [comment]
Sorry, I meant to post this last week. Just in case if may help folks in the future looking for how to do this here is the code we ended up using.

`function add_content_to_apple_news($content, $ID) {

 $post = get_post($ID);

 //For podcasts custom post_type add in the teaser and the sponsors.
 if($post->post_type == 'podcasts' ) {
  $teaser = get_field('podcast_teaser', $ID, false);  //get data from ACF field
  $sponsors = get_field('podcast_sponsors', $ID, false);  //get data from ACF field

  $content = $teaser . $content . $sponsors;
 }

  return $content;
}
add_filter( 'apple_news_exporter_content_pre', 'add_content_to_apple_news', 10, 2 );`

**note** We use Advanced Custom Fields Pro so in this example you'll see the calls to it's `get_field()` function. We probably should also wrap this with a check to make sure ACF installed and active. Finally if you're not using ACF you'll probably be doing a call `get_post_meta()` https://developer.wordpress.org/reference/functions/get_post_meta/

**Comment by nyckelplaya** [comment]
Just wanted to pop in and say thank you, @phylaxis! I was able to modify this for my custom fields and wrapped the output in <h2> tags. Looks like it's all working. You saved me some time!

**Comment by phylaxis** [comment]
So glad to hear it helped @nyckelplaya .

**Comment by edmedina06** [comment]
I have a similar issue. I am trying to change the author with a custom field and I have and I haven't had any luck. I have added a filter and still looks like the filter doesn't get picked up. Can someone point me in the right direction

Thanks in advance

**Comment by edmedina06** [comment]
I have even edited the method from the Action Class format_byline and Looks like this one doesnt get triggred or at least it gets overwritten
