### ISSUE TITLE
Adding additional taxonomies to Sections category

### ISSUE THREAD

**Issue by phylaxis** [alleyinteractive/apple-news#357]
We have a few custom post types that we use on our site and would like to be able to use the taxonomies from those post types to map to our sections. I see from the documentation that there is a `apple_news_section_taxonomy` filter, but when I try to add to the taxonomies I get an error. It seems like this filter will only accept one taxonomy at a time, is that correct? I also tried just filtering with the taxonomy from my custom post type and while the 'labels' changed to reflect the new taxonomy the filter (drop down) did not return any of the category names. Our custom post type taxonomy is not hierarchical, so is that also an issue?

**Comment by bcampeau** [comment]
It only accepts one taxonomy at this time. There are no plans to support multiple taxonomies for this feature, but feel free to send a pull request through if you have a suggestion.

**Comment by kevinfodness** [comment]
This is now handled via the Automation feature, which replaced Section mappings, and has support for all registered taxonomies.
