### ISSUE TITLE
Cannot Publish API Error

### ISSUE THREAD

**Issue by Willidude** [alleyinteractive/apple-news#360]
I'm really not sure what the issue is and not very code savvy but I cannot post to Apple news right now. I just get an error code that tells me to ask for help. The error reads as follows:

There has been an error with the API: There has been an error with your request: cURL error 7: couldn't connect to host

If you need assistance, please reach out for support on WordPress.org or GitHub.

Any help would be really appreciated!

**Comment by bcampeau** [comment]
If you're seeing a cURL error, that's a problem with your web host. Please reach out to their support as it appears they're blocking access to the Apple News API.
