### ISSUE TITLE
Fix blank lines causing null text errors when html format is used

### ISSUE THREAD

**Issue by bcampeau** [alleyinteractive/apple-news#365]
A pull request was suggested in #364, but I think we need a more robust regex-based solution.

**Comment by iamkingsleyf** [comment]
This issue still exist.
`There has been an error with the API:
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->3->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->3)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->6->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->6)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->9->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->9)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->11->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->11)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->13->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->13)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->15->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->15)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->17->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->17)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->19->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->19)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->21->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->21)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->23->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->23)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->25->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->25)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->27->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->27)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->29->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->29)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->31->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->31)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->33->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->33)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->35->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->35)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->37->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->37)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->39->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->39)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->41->text)
INVALID_DOCUMENT - no components defined for role=body (keyPath components->1->components->41)

If you need assistance, please reach out for support on WordPress.org or GitHub.`

**Comment by bobbenedetti** [comment]
I noticed this space between paragraphs start about couple of weeks ago using the Wordpress mac app to write the post. I had to add spaces manually because because when post was previewed out published there were no spaces between paragraphs even though the editor showed spaces
