### ISSUE TITLE
Don't know where to put my Apple News API Key and other codes in App

### ISSUE THREAD

**Issue by mrandrew7** [alleyinteractive/apple-news#369]
Could somebody help me where exactly am I supposed to put the API key in the Wordpress Publish to Apple News at?  I'm brand new to this and looked all over.  I can't seem to find it.  Thanks!

**Comment by bcampeau** [comment]
@mrandrew7 please read the wiki: https://github.com/alleyinteractive/apple-news/wiki/Configuration. Everything is clearly explained there.

Thanks.

**Comment by mrandrew7** [comment]
It doesn't say in there

**Comment by kevinfodness** [comment]
In the link above, under API Settings, it shows you where to get your Channel ID, Key ID, and Secret from the iCloud Publisher page. Below that, it shows you where to enter them on the Publish to Apple News Settings screen.

If you aren't seeing Apple News as a menu item in WordPress, you will need to ensure that the plugin is active on the Plugins screen.

**Comment by mrandrew7** [comment]
On my app in Wordpress, it doesn't give me that window.  Do we put the
channel ID on Icloud publisher or directly on my site?

**Comment by mrandrew7** [comment]
The Plugin is active

**Comment by bcampeau** [comment]
What role does your login have on the site?

**Comment by mrandrew7** [comment]
It's my site

**Comment by kevinfodness** [comment]
Hi @mrandrew7 — on the left side of the WordPress admin, where you've got Plugins, Users, Tools, and Settings, do you see an item labeled "Apple News"? For me, it appears directly below "Settings." If so, you need to hover on it or click on it and then go to the Settings submenu item. You can see what it should look like in the wiki screenshot here: https://github.com/alleyinteractive/apple-news/raw/master/assets/images/apple-news-menu-settings.png

If you don't see that menu item, then something else is wrong. If the plugin is indeed active, I would try disabling other plugins you have active on the site to determine if one of them is conflicting with Publish to Apple News.

**Comment by saleskick9999** [comment]
Hello - just wondering if anyone has an existing api key access to news publisher that they would be willing to sell - as apple news is not currently offering access
