### ISSUE TITLE
Where on here does it tell you to put your API and everything?

### ISSUE THREAD

**Issue by mrandrew7** [alleyinteractive/apple-news#370]
Can someone help me where it tells you to put your API and other codes to publish from Wordpress to Apple News?

**Comment by kevinfodness** [comment]
Closing as a duplicate of #369.

**Comment by mrandrew7** [comment]
It's not duplicate.  Show me where it says where to put them PLEASE!

**Comment by kevinfodness** [comment]
Hi @mrandrew7 — it's a duplicate because we're having the conversation in #369.
