### ISSUE TITLE
Ampersands converting to &amp; in titles

### ISSUE THREAD

**Issue by gregbarbosa** [alleyinteractive/apple-news#383]
First saw this issue after someone in the Apple News team reached out to me. It appears that any articles that contain an ampersand in the title are being converted to `&amp;`. This causes them to appear incorrectly in Apple News. 

Not sure what steps to take to resolve this one.

![img_7139](https://cloud.githubusercontent.com/assets/1592502/26765115/18dab8ac-4943-11e7-9578-a275546fbb33.PNG)

**Comment by kevinfodness** [comment]
This is fixed in the latest `master`. We're working on releasing version 1.3.0 in the coming weeks, which will include this fix.
