### ISSUE TITLE
Unpublishing an article doesn't remove it from Apple News

### ISSUE THREAD

**Issue by kevinlisota** [alleyinteractive/apple-news#385]
We just unpublished an article on our site that was accidentally published too early. 

Specifically, we changed the status from "publish" to "draft." While that removed the live article from the site, it did not remove it from Apple News.

We do have the "automatically delete from Apple news" option set to Yes.

I had to go in to Apple News portal and delete this article manually.

**Comment by rahulsprajapati** [comment]
I think this one is with Apple news API, they are not allowing us to move the article back to draft status.
> Once an article has been published with isPreview set to false, the setting cannot be changed to true.

ref: https://developer.apple.com/library/content/documentation/General/Conceptual/News_API_Ref/UpdateArticle.html

**Comment by kevinlisota** [comment]
If that is the case, I suggest removing the UI that says the following:

"Automatically delete from Apple News when deleted in WordPress"

We had an instance where an article under embargo was mistakenly published early. We assumed it was removed everywhere when we unpublished it, but it remained on Apple News for half a day until we realized it was still there.

Does it remove articles if you delete them from WP?

**Comment by bcampeau** [comment]
The plugin deletes articles from Apple News if they're deleted from WordPress and the automatic delete setting is enabled. There is no trigger to handle moving a post back to draft. You'd have to manually delete from Apple News in that instance.
