### ISSUE TITLE
Get VIP to update

### ISSUE THREAD

**Issue by mattheu** [alleyinteractive/apple-news#39]
We'd really like to get a newer version of this running on WordPress.com VIP. I was going to open a support request, but wanted to check in with you first.

- Shall I go ahead and open a ticket requesting update to latest version from github?
- Any reason not to update to latest trunk? or would it be better to use latest tagged  1.0 release?
- If the latter - are you planning a new tagged release any time soon? As there are some features we'd like that came after this.

**Comment by bcampeau** [comment]
The latest version is already on VIP as a release candidate. You can use it immediately in your themes via:

`wpcom_vip_load_plugin( 'apple-news', 'plugins', true );`

I'll leave this issue open until they move the release candidate into the production version.

**Comment by mattheu** [comment]
Ah cool I forgot all about this ;)

**Comment by bcampeau** [comment]
The latest version has been live on VIP for a bit, so closing this.
