### ISSUE TITLE
Suggested approach for rendering Apple News version of a shortcode?

### ISSUE THREAD

**Issue by danielbachhuber** [alleyinteractive/apple-news#398]
We have a shortcode that we'd like to create to make sure is rendered in high definition for Apple News.

Is there a way I can return the Apple News JSON from my shortcode callback? Or do I need to return a mock from the shortcode callback, and then use the `apple_news_generate_json` filter to create the final representation?

**Comment by danielbachhuber** [comment]
The crazy idea I have right now is for the shortcode to return base64-encoded JSON, and then add some processing logic on `apple_news_generate_json` that extracts the JSON before final delivery.

**Comment by kevinfodness** [comment]
If the shortcode is generating something that is digestable by the Apple News plugin as HTML, then you could use the `apple_news_exporter_content_pre` filter and render your shortcode as HTML with modifications (e.g., use a higher-rez image). The plugin would do the rest of the work from there.

If you want to have fine-grained control over the JSON that is being produced, then yes, you would need to use a placeholder of some sort and unpack it in `apple_news_generate_json`.

This is related to your other issue #287, which we hope to address in a future version of the plugin.

**Comment by danielbachhuber** [comment]
> If you want to have fine-grained control over the JSON that is being produced, then yes, you would need to use a placeholder of some sort and unpack it in `apple_news_generate_json`.

This is the approach I ended up taking, which worked out reasonably well:

```
$apple_news_json['components'][] = array(
	'role'    => 'body',
	'text'    => $buy_now_text,
	'style'   => array(
		'backgroundColor' => '#FFCF00',
		'border' => array(
			'all' => array(
				'width' => 8,
				'style' => 'solid',
				'color' => '#FFCF00',
			),
		),
	),
	'textStyle' => array(
		'textColor' => '#FFF',
		'textAlignment' => 'center',
		'linkStyle' => array(
			'textColor' => '#FFF',
		)
	),
	'additions' => array(
		array(
			'type' => 'link',
			'URL'  => esc_url_raw( $link ),
			'rangeStart' => 0,
			'rangeLength' => strlen( $buy_now_text ),
		),
	),
);
// Needs to be wrapped in <p> or it will be stripped
return '<p>bgr-apple-news-base64-decode:' . base64_encode( json_encode( $apple_news_json ) ) . '</p>';
```

**Comment by kevinfodness** [comment]
Great. Seems like a reasonable enough solution until we add support for an exporter flag in #287.
