### ISSUE TITLE
THERE HAS BEEN AN ERROR WITH THE API: INVALID_DOCUMENT – THE URL,

### ISSUE THREAD

**Issue by stormchasepilot** [alleyinteractive/apple-news#401]
Sent a support ticket to Apple today that resulted on me being directed to this forun on the ground of it being a WordPress Plugin Issue.

Looked over the forum and seem as though im not the only one struggling over the past few days.

Below is the information I sent to Apple on request.

Blog Title
Source Code Of Video Likey Giving The Issue
Error Message

***Tittle1***
Kansas City Underwater After Heavy Rains

<iframe style=”border: none; overflow: hidden;” src=”https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Fkshbtv%2Fvideos%2F10154719547091190%2F&show_text=0&width=560″ width=”560″ height=”315″ frameborder=”0″ scrolling=”no” allowfullscreen=”allowfullscreen”></iframe>

Error Message
THERE HAS BEEN AN ERROR WITH THE API: INVALID_DOCUMENT – THE URL, [HTTPS://PLAYER.VIMEO.COM/VIDEO/], IS INVALID. PLEASE SEE DOCUMENTATION FOR MORE DETAILS ABOUT EMBEDDED VIDEO. (KEYPATH COMPONENTS->1->COMPONENTS->4)

***Tittle2***
Developing: Possible Tornado Destroys Homes On Maryland’s Kent Island As Storm Leaves Thousands Without Power

<iframe src=”//www.washingtonpost.com/video/c/embed/98f358d4-706a-11e7-8c17-533c52b2f014″ width=”480″ height=”290″ frameborder=”0″ scrolling=”no” allowfullscreen=”allowfullscreen”></iframe>

Error Message
THERE HAS BEEN AN ERROR WITH THE API: INVALID_DOCUMENT – THE URL, [HTTPS://PLAYER.VIMEO.COM/VIDEO/], IS INVALID. PLEASE SEE DOCUMENTATION FOR MORE DETAILS ABOUT EMBEDDED VIDEO. (KEYPATH COMPONENTS->1->COMPONENTS->3)

***Tittle3***
BREAKING NEWS: St. Louis Jail Will Add Portable A/C Units Following Viral Video Of Inmates “Screaming”

<iframe style=”border: none; overflow: hidden;” src=”https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Fattn%2Fvideos%2F1446622468706541%2F&show_text=0&width=400″ width=”400″ height=”400″ frameborder=”0″ scrolling=”no” allowfullscreen=”allowfullscreen”></iframe>

Error Message
THERE HAS BEEN AN ERROR WITH THE API: INVALID_DOCUMENT – THE URL, [HTTPS://PLAYER.VIMEO.COM/VIDEO/], IS INVALID. PLEASE SEE DOCUMENTATION FOR MORE DETAILS ABOUT EMBEDDED VIDEO. (KEYPATH COMPONENTS->1->COMPONENTS->6)

**Comment by kevinfodness** [comment]
Apple News Format only supports embedded web videos from YouTube and Vimeo: https://developer.apple.com/library/content/documentation/General/Conceptual/Apple_News_Format_Ref/EmbedVideo.html#//apple_ref/doc/uid/TP40015408-CH15-SW1

However, you have discovered a bug with how we are doing URL matching for embedded videos, which we will need to address. I'll open a separate issue for that. The plugin should more gracefully handle videos that it can't embed, rather than erroring out.
