### ISSUE TITLE
Issue with ellipsis, "' & certain embeds

### ISSUE THREAD

**Issue by mstaneluis** [alleyinteractive/apple-news#402]
We are receiving an error whenever we try to submit a story with an ellipsis.  
![screen shot 2017-07-25 at 11 37 34 am](https://user-images.githubusercontent.com/5775954/28735032-8648391c-73b1-11e7-9977-11121278302b.png)

**Comment by kevinfodness** [comment]
I'm not seeing any issues when I publish an article with ellipsis. Can you send a Pastebin link with the post content from the Text tab so I can test with the content you are using, please?

The empty text content issue is known and will be addressed in #205.

Also, can you confirm that you are on the latest public version (1.2.7)? We addressed some Unicode encoding issues in a recent version, so if you aren't on latest, upgrading may solve your problem.

**Comment by dhanendrannewscorp** [comment]
@kevinfodness I'm also facing some unicode issues when using emojis in the content. I'm using the latest version (1.2.7) of the plugin.
<img width="1091" alt="screen shot 2017-08-07 at 4 42 32 pm" src="https://user-images.githubusercontent.com/19810308/29024387-72c050ec-7b8f-11e7-9e35-96d82dd32dd1.png">

**Comment by mstaneluis** [comment]
@kevinfodness here is the pastebin link: https://pastebin.com/M0tG6nWW
We are on 1.2.7.  We also are on WordPress 4.8.1.  I see that 1.3.0 has been released. Are any of the encoding issues solved in that version?

**Comment by kevinfodness** [comment]
@dhanendrannewscorp We're tracking the emojis issue in #404 because it should be handled separately. @mstaneluis Version 1.3.0 was primarily about themes, but you can certainly check and see if the new version resolves any issues. If you're still experiencing problems on the latest version, please let me know.

**Comment by kevinfodness** [comment]
@mstaneluis Actually, on version 1.3.0 with the pastebin you provided, I'm seeing the same issue. I'm going to reopen to track.

**Comment by kevinfodness** [comment]
Ampersands, escaped as `&amp;`, are causing issues when using Markdown as the output format. When using HTML format it renders fine.

**Comment by kevinfodness** [comment]
Resolved via #465.
