### ISSUE TITLE
Emojis not supported in Apple News plugin

### ISSUE THREAD

**Issue by dhanendrannewscorp** [alleyinteractive/apple-news#404]
We are facing some error when we use some emojis in the content.
<img width="1091" alt="unicode error" src="https://user-images.githubusercontent.com/19810308/29109787-f2482c7c-7d01-11e7-8d42-e1b2e25187c8.png">
Can you able to provide support the Emojis on the plugin? Also it would be good to provide any filter hook for [$separators](https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-exporter/class-exporter.php#L60)? So that we can able to filter out the unicode exceptions.

**Comment by bcampeau** [comment]
It looks like the emojis are getting trapped by a condition that checks for otherwise invalid characters. They are supported by Apple News. We'll add this to be resolved in the next version of the plugin.

We'll also look at filtering separators.

**Comment by dhanendrannewscorp** [comment]
@bcampeau thank you for taking a look at this issue. Do you have any tentative time for the next release?

**Comment by bcampeau** [comment]
We do not have a planned release at this time, but this will definitely get included.
