### ISSUE TITLE
"API: Invalid_Type" error message

### ISSUE THREAD

**Issue by max-woven** [alleyinteractive/apple-news#406]
Hello, just want to give you the heads up.

Recently we had a problem where some posts were not published to Apple News because of "API: Invalid_Type" error.

After some investigation I've found out that sometimes `sections` value in JSON was set as object instead of array. For example:

This code is valid and allowed us to publish posts:
`{"data":{"links":{"sections":["https:\/\/news-api.apple.com\/sections\/...","https:\/\/news-api.apple.com\/sections\/..."]}}}`

But the one below failed with "API: Invalid_Type" error:
`{"data":{"links":{"sections":{"0":"https:\/\/news-api.apple.com\/sections\/...","2":"https:\/\/news-api.apple.com\/sections\/..."}}}}`

This patch in our theme fixed the problem:
```
/**
 * Convert sections from associated to indexed array to prevent sections to be encoded as hashmap
 * @param array $meta
 * @return array
 */
function uproxx_fix_apple_news_sections( $meta ) {

	// Check if meta['data'] exists and is array
	if ( empty( $meta ) || ! isset( $meta['data'] ) || ! is_array( $meta['data'] ) ) {
		return $meta;
	}

	// Check if $meta['data']['links']['sections'] exists and is array
	if ( ! isset( $meta['data']['links'] ) || ! isset( $meta['data']['links']['sections'] ) || ! is_array( $meta['data']['links']['sections'] ) ) {
		return $meta;
	}

	// Convert
	$meta['data']['links']['sections'] = array_values( $meta['data']['links']['sections'] );

	// Final result
	return $meta;
}
add_filter( 'apple_news_api_post_meta', 'uproxx_fix_apple_news_sections' );
```

Max

**Comment by bcampeau** [comment]
Thanks, @max-woven. We'll take a look at this for future inclusion in the plugin.
