### ISSUE TITLE
PHP notices when using WP_DEBUG

### ISSUE THREAD

**Issue by webdeveric** [alleyinteractive/apple-news#407]
When on `wp-admin/admin.php?page=apple-news-theme-edit`, I see the following with `WP_DEBUG` on.

![image](https://user-images.githubusercontent.com/1823514/29465822-349672f0-8400-11e7-8313-a7b7465b343b.png)
![image](https://user-images.githubusercontent.com/1823514/29465899-7bd6ec44-8400-11e7-9920-f2d5cf0ca68f.png)

**Comment by kevinfodness** [comment]
Thanks for the report! I'll take a look and see what's going on.

**Comment by webdeveric** [comment]
I installed this plugin from `master` and the deprecation notice is gone, but `$theme_name` is still causing a notice.

![image](https://user-images.githubusercontent.com/1823514/29732029-6edeb664-89ac-11e7-92c6-0a404ef4e8f0.png)
