### ISSUE TITLE
Not using the class variable in constructor

### ISSUE THREAD

**Issue by dhanendrannewscorp** [alleyinteractive/apple-news#409]
In `Admin_Apple_Post_Sync` constructor, we are setting the [$settings](https://github.com/alleyinteractive/apple-news/blob/master/admin/class-admin-apple-post-sync.php#L20) variable with the instance of class `Admin_Apple_Settings`, if the constructor not getting the valid parameter.

But that variable not been used on the followed lines [here](https://github.com/alleyinteractive/apple-news/blob/master/admin/class-admin-apple-post-sync.php#L37), instead we are using the function parameter directly. This causing some issues in my project. 

The code should be as below;
```
// Register update hook if needed.
if ( 'yes' === $this->settings->get( 'api_autosync' )
    || 'yes' === $this->settings->get( 'api_autosync_update' )
) {
	// This needs to happen after meta boxes save.
	add_action( 'save_post', array( $this, 'do_publish' ), 99, 2 );
}

// Register delete hook if needed.
if ( 'yes' === $this->settings->get( 'api_autosync_delete' ) ) {
	add_action( 'before_delete_post', array( $this, 'do_delete' ) );
}
```

Can you make this change? and do you accept PR's?

**Comment by bcampeau** [comment]
Please submit a pull request with your proposed changes and we'll evaluate. Thanks.

**Comment by dhanendrannewscorp** [comment]
@bcampeau I have raised a PR for this issue https://github.com/alleyinteractive/apple-news/pull/410
