### ISSUE TITLE
Re-add the apple_news_fonts_list hook

### ISSUE THREAD

**Issue by aayler** [alleyinteractive/apple-news#411]
Greetings,

There used to be a filter on = https://github.com/alleyinteractive/apple-news/wiki/Action-and-Filter-Hooks that references a `apple_news_fonts_list` hook, which seems to have been removed.

Can you please direct me to documentation as to how this is currently handled, as custom fonts are not definable, and in the case where we did define custom fonts, the theme is not able to save, returning a message similar to : "Could not save theme Default: Invalid font value Gotham-Book specified for setting body_font"

Thanks!

**Comment by webdeveric** [comment]
@aayler I also used that filter and I had to do a workaround in my code.

```php
add_action('plugins_loaded', function() {
    $theme = '\Apple_Exporter\Theme';

    if ( class_exists( $theme ) ) {
        $fonts = $theme::get_fonts();
        // Update $fonts here

        $reflection = new \ReflectionProperty($theme, '_fonts');
        $reflection->setAccessible(true);
        $reflection->setValue($fonts);
    }
});
```

**Comment by kevinfodness** [comment]
Hi @aayler—

Custom fonts on the Apple News platform need to be uploaded by Apple before you can use them. We didn't want to make it seem like a custom font could be used simply by selecting it, hence the removal of the filter. We can look into re-adding it with warnings to this effect. In the meantime, I would recommend setting the custom font by using the Customize JSON feature and replacing the variable name of the font with the postscript name that you want to use.
