### ISSUE TITLE
Undefined property: stdClass::$message

### ISSUE THREAD

**Issue by webdeveric** [alleyinteractive/apple-news#412]
With `WP_DEBUG` on, I'm getting the following:

`Notice: Undefined property: stdClass::$message in /app/public/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php on line 270`

Steps to recreate:

1. publish an article with this plugin
1. manually delete the article from icloud news publisher
1. view article listing table (`wp-admin/admin.php?page=apple_news_index`)
   ![image](https://user-images.githubusercontent.com/1823514/29727835-1cb483d4-899b-11e7-97d1-0cd375ae9a74.png)
1. Try to delete article from within this plugin
   ![image](https://user-images.githubusercontent.com/1823514/29727778-e1a5d144-899a-11e7-896e-4f5df1c15b93.png)

**Comment by bcampeau** [comment]
It looks like that's only NOTICE level, so no non-developers are seeing that. We'll roll a fix into the next release.
