### ISSUE TITLE
NOT_FOUND (keyPath articleId)

### ISSUE THREAD

**Issue by thekumachan** [alleyinteractive/apple-news#415]
![publish-to-apple-news error](https://user-images.githubusercontent.com/12398086/29837039-eb399966-8cab-11e7-923d-70fb11242f6b.png)
I am receiving multiple errors about NOT_FOUND (keyPath articleId).  Is that something on my Wordpress side or is it on the Apple News side?  How can I go about fixing these issues?

**Comment by bcampeau** [comment]
NOT_FOUND would indicate the article may have been removed or that your channel wasn't live yet at the time you tried to publish.

Either way, this is on the Apple News side and doesn't have anything to do with the plugin. If you're unclear on the reason behind these errors, you should follow up with Apple News support.

Thanks.

**Comment by thekumachan** [comment]
Sounds great.  Thank you very much for your help.

**Comment by abuzer** [comment]
Hi @thekumachan , How was this fixed? Can you please share your experience?
Thank
