### ISSUE TITLE
Undefined index: apple_news_maturity_rating

### ISSUE THREAD

**Issue by webdeveric** [alleyinteractive/apple-news#418]
With `WP_DEBUG` on, I'm getting these notices, which break the `<select>` options.

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/1823514/29942523-ceea3110-8e5b-11e7-9209-077bdf47ef30.png">

**Comment by kevinfodness** [comment]
Thanks for the report—we'll look into it.
