### ISSUE TITLE
Page Builder Shortcode Displays In Body In Apple News

### ISSUE THREAD

**Issue by SADSports** [alleyinteractive/apple-news#419]
I am using the Salient Visual Composer to post on my website. Everything looks great on my website, but when the "Publish to Apple News" plugin posts to Apple News, all of the shortcode is displayed. Is this a problem with the plugin? Or is there something that I can do to remedy this issue and display properly with Apple News. 

Like I said, everything displays perfect on my website, but the issues arise within Apple News. Any help is appreciated. Below is an example of shortcode that shows up in Apple News

[vc_row type="in_container" full_screen_row_position="middle" scene_position="center" text_color="dark" text_align="left" overlay_strength="0.3"][vc_column column_padding="no-extra-padding" column_padding_position="all" background_color_opacity="1" background_hover_color_opacity="1" column_shadow="none" width="1/1" tablet_text_alignment="default" phone_text_alignment="default" column_border_width="none" column_border_style="solid"][vc_column_text]

**Comment by bcampeau** [comment]
We don't support third party visual composers. It's up to those plugin authors to support compatibility with Apple News.
