### ISSUE TITLE
Swap deprecated wpcom_vip functions for core versions

### ISSUE THREAD

**Issue by pjpak** [alleyinteractive/apple-news#423]
https://github.com/alleyinteractive/apple-news/blob/dd00129b96ded48f71ec19a121460833b6454827/admin/class-admin-apple-sections.php#L440

**Comment by kevinfodness** [comment]
Targeted functions:

`wpcom_vip_get_term_by()`
`wpcom_vip_get_category_by_slug()`
`wpcom_vip_get_term_link()`
