### ISSUE TITLE
The spec for JSON had invalid tokens and cannot be saved

### ISSUE THREAD

**Issue by nep** [alleyinteractive/apple-news#424]
When trying to save custom Byline JSON in the Default theme, I get the following error:

/wp-admin/admin.php?page=apple-news-json
"The spec for JSON had invalid tokens and cannot be saved"

The JSON I'm trying to save is simply the default:

```
{
    "role": "byline",
    "text": "#text#"
}
```

This is causing all the News stories to have the same byline, so it makes the plugin unusable, sadly.

**Comment by nep** [comment]
Hi folks. Any suggestions about why this might be still occuring?

**Comment by bcampeau** [comment]
`This is causing all the News stories to have the same byline`

Is this before or after you tried to update the default JSON?

**Comment by nep** [comment]
After.  I updated the default, and now I can't change it back to the default.

**Comment by bcampeau** [comment]
OK, we'll log this as a bug for the next version. Feel free to submit a pull request if you have a solution in the meantime.

Thanks.

**Comment by kevinfodness** [comment]
I can't reproduce this issue in the latest version. We relaxed some of the handling for JSON validation, which may have fixed this issue. I made several modifications to the custom JSON and set it back to the original, and all worked as expected. If anyone is encountering this issue and has specific steps to reproduce that apply to the latest version, please file a new issue and we will look into it.
