### ISSUE TITLE
Article Stuck in Drafts

### ISSUE THREAD

**Issue by FiveDesign** [alleyinteractive/apple-news#427]
I published a blog post and it has the Apple News Status "Live" and the Sync Status "Published" now. However, the Article is not actually published. Instead, it appears in the Drafts section on my iCloud News Publisher account. Please help.

**Comment by bcampeau** [comment]
Is your channel approved by Apple?

**Comment by FiveDesign** [comment]
I thought so... but I just read somewhere, that you have to publish 3 articles or more in order to submit them for review. So I guess that's the problem and my channel is not approved yet. I just started and only sent one article over so far. Sorry, my bad.

**Comment by bcampeau** [comment]
No worries. It's a common source of confusion.
