### ISSUE TITLE
Async Publishing Docs?

### ISSUE THREAD

**Issue by bransinanderson** [alleyinteractive/apple-news#429]
The publish times is extremely slow sending data on post publish or update to Apple. Looking into "Asynchronously publish to Apple News" instead for scheduled publishing. Where can I find more information on how this is suppose to work?

**Comment by kevinfodness** [comment]
Hi @bransinanderson—

We've got a blurb about this on our wiki: https://github.com/alleyinteractive/apple-news/wiki/configuration#api-settings

Since you're having issues with slow publish times, async looks like a good solution for you. I'm going to close this issue, but if you have problems with async, feel free to open a new one.

Thanks for using Publish to Apple News!

**Comment by bransinanderson** [comment]
Yeah I saw that.

Publish to Apple News using a single scheduled event rather than on publish. This is generally only necessary if you're forced to use bundled images and you're having issues with timeouts on publish. We generally recommend leaving this set to 'no' and using remote images.

How do I trigger the event. I don't see it in the documentation you've sent?

**Comment by kevinfodness** [comment]
You don't trigger the event—it uses WP Cron and happens automatically. More info on WP Cron: https://www.smashingmagazine.com/2013/10/schedule-events-using-wordpress-cron/

If you're noticing that the posts aren't publishing after a short period of time (anything longer than 15 minutes is likely problematic) then you need to check with your hosting provider to see if WP Cron is supported/running. By default, WP Cron uses web requests to trigger jobs, but you can disable this method and use a real cron job to trigger WP Cron runs if you have access to the server to schedule cron jobs. This approach is useful if your site either doesn't get a lot of traffic or is behind a proxy or CDN.

**Comment by bransinanderson** [comment]
I see now. Thank you.
