### ISSUE TITLE
component format does not select parser?

### ISSUE THREAD

**Issue by aayler** [alleyinteractive/apple-news#431]
Greetings,

When the "format" of a particular component is selected to "html," there is an additional protected method checking if the component is `html_enabled()`.

Is there a way using filters to allow a particular component to be "html enabled" even if the format in the customized JSON is already set to "html?" (currently returning "markdown" as the parser)

Thanks!

**Comment by kevinfodness** [comment]
Hi @aayler—

That's a good suggestion. I'll label this as an enhancement for a future version.

**Comment by kevinfodness** [comment]
This will ship as part of 1.4.0.
