### ISSUE TITLE
Apple News Status

### ISSUE THREAD

**Issue by csassienie** [alleyinteractive/apple-news#432]
Hi,

I'm having issue with publishing my articles. The _Sync Status_ for all my articles says 'Published', however, the _Apple News Status_ says 'NOT_FOUND (keyPath articleId)'. Because of this, none of my articles are showing up in my iCloud.

I saw this [issue](https://github.com/alleyinteractive/apple-news/issues/157) about it saying I needed to remove the metadata, however, I can't find any apple_news_ metadata. I also saw this [issue](https://github.com/alleyinteractive/apple-news/issues/117) was resolved that should automatically clear the metadata when articles fail.

Can you help me remove any of the metadata to try and restart everything?

Thanks,
Charlie

**Comment by kevinfodness** [comment]
In the WordPress postmeta table, there will be keys in the form of `apple_news_api_%` that contain information about the article's status from the Apple News API. It sounds like the `apple_news_api_id` is set locally (which would have come from the Apple News API) but isn't matching an article on Apple's side.

Is your channel fully approved and activated? Can you send one of the API IDs to Apple to see if they can figure out why the linkage is broken? The API IDs would have been returned from the Apple News API, so if they are set, then it should mean that the article was created on their side at some point.

If you need to reset the API status for all articles, you can delete all postmeta that starts with `apple_news_api_`, but note that this is destructive and it will break any linkage between your site and Apple News articles in your iCloud account. You should make a full database backup before performing that operation.

**Comment by csassienie** [comment]
It's strange about the apple ID not matching on Apple's side. I think I want to reset the API status for all the articles and delete the metadata. For some reason I can't find anything when I search my post meta table that includes 'apple' in. Any ideas?

**Comment by kevinfodness** [comment]
Hi @csassienie—

I apologize for the delay in responding. Your query for the postmeta would need to be a `LIKE` query where the `meta_key` is `LIKE 'apple_news_api_%'. If you are on a multisite environment, you will need to ensure that you are querying the proper postmeta table for the specific site you're working on.

Let me know if you're still stuck and I can give you an example SQL query.
