### ISSUE TITLE
Apple News Suddenly Only Pulling Through Image And Headline Only

### ISSUE THREAD

**Issue by shancake** [alleyinteractive/apple-news#433]
The Apple News team have flagged a recent issue that is now plaguing our Apple News channel (Press Start Australia).

Basically, only the featured images of our stories are getting pulled across. I’ve attached our JSON file for you to take a look at.

https://www.dropbox.com/s/800fbq2e5exru0q/article-54386%5B1%5D.json?dl=0

**Comment by kevinfodness** [comment]
Hi @shancake—

I apologize for the delay in responding—it's been very busy over the past few weeks. I downloaded your JSON and opened it in News Preview, and wasn't able to replicate your issue. I can see the article content in News Preview.

If this is still an issue for you, can you please provide the information requested here so I can dig in further: https://github.com/alleyinteractive/apple-news/wiki/usage#getting-help

Thanks!
