### ISSUE TITLE
Plugin Pulling in Double Images for the Article Photo

### ISSUE THREAD

**Issue by swshelper** [alleyinteractive/apple-news#435]
I reached out to Apple News about this issue. They informed to contact you guys stating that it is a plugin issue. https://apple.news/AxFAR11n2S3-FLL4r0eccnw

**Comment by kevinfodness** [comment]
Hi @swshelper —

I'm tackling this issue now, but I'm not able to reproduce it using the markup from the linked article on your site. Can you provide me with the raw content from the `Text` tab in the WordPress editor, please? I'm thinking it's possible that something is rendering differently during the Apple News JSON preparation than the normal web view.

Thanks!

**Comment by swshelper** [comment]
Hi Kevin,

Whatever the issue was...it is no longer the case. It seems to be working just fine now.

**Comment by kevinfodness** [comment]
Glad to hear it! Thanks!
