### ISSUE TITLE
Add support for changing API keys

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/apple-news#438]
When a user changes API keys, they can receive FORBIDDEN responses from the API due to trying to access resources that were created under the old API key. Currently, the only way to change API keys is to completely uninstall the plugin and reinstall, then reconfigure. The plugin should provide a way to clear out data automatically when API keys are changed, or require a two-step process of disconnecting the keys first, then reconnecting.

**Comment by moehamid73** [comment]
I changed the keys and got the Forbidden message. I deactivated, uninstalled, reinstalled several times, and the plugin always comes back with the old settings. How can i clean uninstall and install, or solve the Forbidden issue?

**Comment by kevinfodness** [comment]
The plugin maintains postmeta attached to articles, such as the ID of the article in Apple News. If you switch keys, you'll get an error for anything that you used to have access to from the old key that you no longer have access to using the new key. We would need to build a feature whereby old information could be completely cleared out, which could be very time-consuming on a large site with a lot of articles, and would be destructive if done inadvertently. You can do this manually by targeting the `apple_news_*` postmeta and deleting references for older articles from the database directly.

**Comment by kevinfodness** [comment]
I'm closing this as not something we're going to support out of the box with the plugin. Changing credentials would involve changing Apple News channels completely, which isn't a use case we're prepared to support natively.
