### ISSUE TITLE
Issues with Video component

### ISSUE THREAD

**Issue by AlexAscherson** [alleyinteractive/apple-news#44]
Hi there,

Thanks so much for this great plugin.  I have been have using it to generate Apple News Format, but one issue I have is that for some reason the embeddable video component doesn't seem to work for me. 

Here is the code being used to generate the video markup that goes into the content:

```php
 $html = '<p><iframe class="youtube" src="https://www.youtube.com/embed/'. $a['id'] .'" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></p>';
```

Is there anything there that would stop it from being parsed as a embeddable video component?

Stepping through the code, in a post with no content except an embedded video inside a p tag, it will check a node with the tagname p, failing to match it as a p element and then testing it as a container.

It then checks a node with tagname 'iframe', failing to match it on the iframe check, with a nodevalue of "".

Not sure what im doing wrong here, have checked it without the ```html
 <p>
``` wrapper and i just get an empty article.  

Unlike the gallery element the video component doesnt state what exactly it expects to find (e.g. A div with class gallery).

What exactly is the iframe/embed component trying to match on/ any ideas why this isnt working?  Let me know if you need any other info, would be very grateful for any advice you can give me on this.

**Comment by bcampeau** [comment]
Doesn't look like you pasted the code. Can you make sure you're using the proper markdown (https://guides.github.com/features/mastering-markdown/) or paste it into a gist?

Thanks.

**Comment by AlexAscherson** [comment]
Sorry about that:

' $html = '<p><iframe class="youtube" src="https://www.youtube.com/embed/'. $a['id'] .'" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></p>';'

**Comment by AlexAscherson** [comment]
"$html = '<p><iframe class="youtube" src="https://www.youtube.com/embed/'. $a['id'] .'" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></p>';"

**Comment by AlexAscherson** [comment]
```php
 $html = '<p><iframe class="youtube" src="https://www.youtube.com/embed/'. $a['id'] .'" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></p>';
```

**Comment by bcampeau** [comment]
The plugin is expecting the URL by itself in a paragraph like:

`<p>https://www.youtube.com/watch?v=KK9bwTlAvgo</p>`

It works only with YouTube and Vimeo currently.

If you think we should handle more cases, pull requests are welcome. Thanks!

**Comment by AlexAscherson** [comment]
Thanks so much for your quick reply.  Maybe im understanding this wrong, but for me, when the $content of the article is: 

    $content = '<p>https://www.youtube.com/embed/YFCmFvlJpK0</p>'

nb.  I have changed this to https://www.youtube.com/watch/YFCmFvlJpK0 with no effect.

In the apple news preview tool I get:

![screen shot 2015-12-14 at 16 52 32](https://cloud.githubusercontent.com/assets/12135010/11787352/21218c60-a283-11e5-8e94-7da6f1077570.png)

Is there something im missing here?  For me a video wrapped in a p sis being parsed as a body element.  I could also have sworn that I have seem it working in a iframe before?  Might be wrong about that or have made some changes to the plugin, but it certainly checks for Iframe tags doesnt it?  Or is Iframe just showing up instead of the embed web media class?

I have tested it with:
'''
<iframe> '<p>https://www.youtube.com/embed/YFCmFvlJpK0</p>' </iframe>
<iframe> '<p>https://www.youtube.com/watch/YFCmFvlJpK0</p>' </iframe>

'<p>https://www.youtube.com/watch/YFCmFvlJpK0</p>' 
'<p>https://www.youtube.com/embed/YFCmFvlJpK0</p>'

**Comment by bcampeau** [comment]
Please take a look at this line and see what the plugin is trying to match: https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-exporter/components/class-embed-web-video.php#L15

**Comment by AlexAscherson** [comment]
Thanks for the help!   Got it working in the end by rewriting the html back into the basic youtube link.  Originally they were Iframes, but I couldnt get the component factory to recognise these reliably so decided to keep things as simple as possible.

**Comment by mattheu** [comment]
I have run into a similar issue actually and looking at the code for this it does appear to have some fallback handling for iFrames. However your youtube URLs you are using does NOT match the pattern @bcampeau linked to above. I think this part should either be removed or improved. I'm about to open another ticket related to this code actually. See #45
