### ISSUE TITLE
Soundcloud embedding

### ISSUE THREAD

**Issue by daviddarke** [alleyinteractive/apple-news#440]
Hi there, we are looking after a site that runs it's podcast via soundcloud. They usually publish an article with the SoundCloud embed attached on their site (this then tickles into Apple News).

Currently, there is no embed appearing.

Is this something that can be handled via this plugin?  I've looked in `publish-to-apple-news/includes/apple-exporter/components/class-embed-web-video.php` and see regex for vimeo and youtube. Yet no mention of SoundCloud?

**Comment by daviddarke** [comment]
Any thoughts on this?

**Comment by kevinfodness** [comment]
Apple News Format doesn't support SoundCloud embeds, and the Audio component needs a direct link to the audio file, which SoundCloud doesn't provide, as far as I know.
