### ISSUE TITLE
JS Error on Theme Preview on PC

### ISSUE THREAD

**Issue by gratrockstar** [alleyinteractive/apple-news#441]
I am seeing a JS error on Theme editing on PC (Win10, Chrome 62):
Uncaught ReferenceError: appleNewsSettings is not defined
Looks like the issue is on line 28 of /assets/js/preview.js:
.text( appleNewsSettings.fontNotice )  but appleNewsSettings hasn't been defined anywhere.  I tested to use appleNewsThemeEdit.fontNotice which resolves the error but that variable is connected to enqueuing /assets/js/theme-edit.js. 
It doesn't throw an error on MacOS in Chrome.  This should be fixed to not throw a js error on PC.

**Comment by kevinfodness** [comment]
I've got a PR to fix this.

**Comment by kevinfodness** [comment]
Merged into the v2.1.1 branch, will release when we release 2.1.1, likely in a week or so.
