### ISSUE TITLE
Gutenberg integration?

### ISSUE THREAD

**Issue by danielbachhuber** [alleyinteractive/apple-news#442]
Any ideas for or plans as to what Apple News integration with Gutenberg might look like?

I'm currently researching for https://github.com/WordPress/gutenberg/issues/4151 and would love to tap into any existing discussion that's been had.

Notably, it seems like there might be some additional effort correctly translating the default blocks to corresponding Apple News JSON.

**Comment by bcampeau** [comment]
We're working on a roadmap for 2018 and we'll update when we have something. At the present time, our first concern will be to ensure the existing meta box works well within the extended settings area.

**Comment by kevinfodness** [comment]
Fixed via release of v2.0.0.
