### ISSUE TITLE
PHG Console

### ISSUE THREAD

**Issue by simon3163** [alleyinteractive/apple-news#446]
Hi All,
I just wanted to know what everyones thoughts of the PHG Console are?

In particular the 'clicks' section. For me, this always seems far more than the reality and never seems to a line with other stats like Twitter/FB Analytics...

Anyone with any advice on how to read it?

Simon

**Comment by bcampeau** [comment]
@simon3163 PHG console is outside the scope of the plugin. 

I'd suggest the Apple Developer Forums as a better place for this discussion: https://forums.developer.apple.com/community/distribution/apple-news/

Thanks.
