### ISSUE TITLE
Feature images seen as 'invalid documents'

### ISSUE THREAD

**Issue by patrickgunning** [alleyinteractive/apple-news#447]
Have been trying to upload some articles from our wordpress backend today, but every time I upload an article I'm met by the following error message.

There has been an error with the API: INVALID_DOCUMENT - Unable to read uri [https://riotmag.co/wp-content/uploads/2018/01/Love-Saves-The-Day.jpg]

The news publisher was working fine yesterday, and it's just been the last few hours it's started playing up. Any ideas what the issue might be?

**Comment by bcampeau** [comment]
Unfortunately, this is either an issue with the Apple News API or your web host. You should follow up through their respective support channels.

**Comment by patrickgunning** [comment]
Thanks!
