### ISSUE TITLE
Video URL matched but invalid JSON created.

### ISSUE THREAD

**Issue by mattheu** [alleyinteractive/apple-news#45]
Originally commented in WP Enterprise Slack channel, but cross posting here too. 

So standard embeds, a single url on its own line, all work fine. But I have a URL that wasn't added correctly, and this is causing errors. My article ended up with the HTML like so:  

```
<p>https://www.youtube.com/watch?v=lEsPhTbJhuo<br>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam in dui mauris. Vivamus hendrerit arcu sed erat molestie vehicula.</p>
```

In this case, the node is matched. However the `build ` method appears to handle both the URL on its own line, and also tries to do some smart matching on iFrames.

The code tries to treat mine as the latter.

What to do? Whilst my situation is not 100% correct embed format, it shouldn't create invalid JSON.

I think we should remove the fallback iFrame handling. The iFrame code would NOT match the initial nodeMatches logic anyway. Furthermore - its appears there are issues with this anyway: see https://github.com/alleyinteractive/apple-news/issues/44. For youtube at least, the src required by the iFrame is different from that used by the pattern for this component.

Alternatively, we can improve the iFrame code to actually work. I have run into some issues with Jetpack enabled where youtube videos are converted into an iFrame before AN gets to them.

**Comment by bcampeau** [comment]
I wouldn't want to remove any functionality since folks could be using it. Getting it to work correctly is the better route.

I would definitely be open as well to a pull request that also included better handling of alternate YouTube URL formats as discussed in #44.

**Comment by mattheu** [comment]
Actually support for iFrames was removed already and this code should never really be called. See https://github.com/alleyinteractive/apple-news/commit/04b576c761d6ceee77a08fec72a86da95026a268

**Comment by bcampeau** [comment]
Good call. I'll be happy to look at a pull request for the proposed fix whenever you have it!

**Comment by mattheu** [comment]
https://github.com/alleyinteractive/apple-news/pull/46/files addresses this issue.
