### ISSUE TITLE
Shortcode/HTML not rendering if followed by a string

### ISSUE THREAD

**Issue by manewc** [alleyinteractive/apple-news#450]
This isn't necessarily a bug, but thought I would mention as an updated feature. We have noticed that when content is inserted immediately after a shortcode, or HTML markup, that it doesn't get correctly parsed in Apple News. For instance:

`[custom_shortcode]content[/custom_shortcode]more content here` or `Text <em>italicized</em>end of the sentence.`

**Comment by kevinfodness** [comment]
This works properly using the latest version of the plugin with HTML format enabled, so I'm going to close.
