### ISSUE TITLE
Error API wrong signature when trying to publish to Apple News

### ISSUE THREAD

**Issue by MotherHand** [alleyinteractive/apple-news#451]
Hi

I've just set up Apple News for my wordpress site but am having trouble publishing. I tried resetting the API key with a new one but it's made no difference, same error. Can anyone suggest a fix?

The debug message I got is this:

API Response:
Array
(
   [headers] => Requests_Utility_CaseInsensitiveDictionary Object
       (
           [data:protected] => Array
               (
                   [request-id] => 1a433100-1243-11e8-9e0f-c108ee55de58
                   [www-authenticate] => HHMAC
                   [content-type] => application/json;charset=UTF-8
                   [content-length] => 39
               )

       )

   [body] => {"errors":[{"code":"WRONG_SIGNATURE"}]}
   [response] => Array
       (
           [code] => 401
           [message] => Unauthorized
       )

   [cookies] => Array
       (
       )

   [filename] => 
   [http_response] => WP_HTTP_Requests_Response Object
       (
           [response:protected] => Requests_Response Object
               (
                   [body] => {"errors":[{"code":"WRONG_SIGNATURE"}]}
                   [raw] => HTTP/1.1 401 Unauthorized
Request-Id: 1a433100-1243-11e8-9e0f-c108ee55de58
WWW-Authenticate: HHMAC
Content-Type: application/json;charset=UTF-8
Content-Length: 39

{"errors":[{"code":"WRONG_SIGNATURE"}]}
                   [headers] => Requests_Response_Headers Object
                       (
                           [data:protected] => Array
                               (
                                   [request-id] => Array
                                       (
                                           [0] => 1a433100-1243-11e8-9e0f-c108ee55de58
                                       )

                                   [www-authenticate] => Array
                                       (
                                           [0] => HHMAC
                                       )

                                   [content-type] => Array
                                       (
                                           [0] => application/json;charset=UTF-8
                                       )

                                   [content-length] => Array
                                       (
                                           [0] => 39
                                       )

                               )

                       )

                   [status_code] => 401
                   [protocol_version] => 1.1
                   [success] => 
                   [redirects] => 0
                   [url] => https://news-api.apple.com/channels/0bade538-4ae3-4e71-bd3e-e8141fe919c7/articles
                   [history] => Array
                       (
                       )

                   [cookies] => Requests_Cookie_Jar Object
                       (
                           [cookies:protected] => Array
                               (
                               )

                       )

               )

           [filename:protected] => 
           [data] => 
           [headers] => 
           [status] => 
       )

)

Request Meta:

Array
(
   [data] => Array
       (
           [isPreview] => 1
           [maturityRating] => GENERAL
       )

)

**Comment by bcampeau** [comment]
You can get this error if your channel isn't yet approved and you're trying to publish something live, rather than in preview mode.

If that's not the case, you'll need to follow up with Apple News support since we can't tell you why their API is rejecting your content.

Thanks.

**Comment by MotherHand** [comment]
Thanks! I'm trying to publish three articles that are already live on my wordpress site. I'm not familiar with preview mode or where to find it?

**Comment by MotherHand** [comment]
ok I've spotted it. The box is checked to publish as a draft on apple news.

**Comment by bcampeau** [comment]
It's irrelevant if the articles are already live on WordPress. Your channel must be approved by Apple before you can publish to Apple News in live mode. If it is not approved, that's the likely source of the issue and you should publish in draft mode until they approve you.

**Comment by MotherHand** [comment]
Thanks, I'm trying to publish in draft mode but still getting the same error. Is there anything else I can try?

**Comment by bcampeau** [comment]
If you're certain you've entered your API information correctly, then you'll need to contact Apple News support. Please provide them with the same debugging information you gave to us.
