### ISSUE TITLE
False positive in detection of invalid unicode character sequences

### ISSUE THREAD

**Issue by amyevans** [alleyinteractive/apple-news#458]
See https://wordpress.org/support/topic/apple-news-publishing-api-errors/

`\u2026\u201d` (`…”`) is getting caught here: https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-exporter/class-exporter.php#L230 and being flagged as an "Invalid unicode character sequence"

**Comment by kevinfodness** [comment]
We made the Unicode checker much less overzealous in 1.4.0. Closing.
