### ISSUE TITLE
Add logic to handle hyperlinked images

### ISSUE THREAD

**Issue by jnsprngs** [alleyinteractive/apple-news#468]
When a hyperlinked image is included in the body of a post, the Apple News plugin generates a generic error: 
`The Apple News JSON is invalid and cannot be published.`

**Comment by jnsprngs** [comment]
If Apple News does not support hyperlinked images, the link should be stripped and successfully publish (with a warning if possible).

**Comment by kevinfodness** [comment]
This error does not occur on the latest version of the plugin with HTML format enabled. Closing.
