### ISSUE TITLE
Sync posts by post category

### ISSUE THREAD

**Issue by wageeeez** [alleyinteractive/apple-news#470]
it will be great if we would be able to select the categories to be synced.

**Comment by kevinfodness** [comment]
@wageeeez — as in, don't sync posts unless they match a specific category? Can you provide some additional details here? Thanks.

**Comment by haneef95** [comment]
Hi,

I'm looking for something similar. This feature exists to an extent in the Yoast News SEO plugin, whereby, you can exclude certain articles based on the category that it is in. This feature is used to exclude articles from going onto Google News and Bing News.

I need this feature for a site which posts some content that are not necessarily considered to be news. So, they have a category called 'Non-news', and they don't want the articles in this category to appear on Apple News.

How can this be achieved with this plugin?

Thanking you,

Kind regards,
