### ISSUE TITLE
Add embedded images

### ISSUE THREAD

**Issue by DigitalSportsDaily** [alleyinteractive/apple-news#471]
Hello is there a way to embed images from Getty. 

The only way I can find is if I upload the image to my wordpress however I do not own the rights to the actual image, but I can get a legal license to embed from Getty in two different formats, neither of which render the image on Apple News

ex. 1 

<div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:Roboto,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:594px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/933488416" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:66.66667% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/933488416?et=AHq_UOZPRGJSy2EUwZSTwg&tld=com&sig=RgUD_cccBwlA1LK-4IfAfhxpCbfZGQDBGTwT_UVe0F4=&caption=true&ver=1" scrolling="no" frameborder="0" width="594" height="396" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div></div>

ex. 2 

<a id='AHq_UOZPRGJSy2EUwZSTwg' class='gie-single' href='http://www.gettyimages.com/detail/933488416' target='_blank' style='color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;'>Embed from Getty Images</a><script>window.gie=window.gie||function(c){(gie.q=gie.q||[]).push(c)};gie(function(){gie.widgets.load({id:'AHq_UOZPRGJSy2EUwZSTwg',sig:'RgUD_cccBwlA1LK-4IfAfhxpCbfZGQDBGTwT_UVe0F4=',w:'594px',h:'396px',items:'933488416',caption: true ,tld:'com',is360: false })});</script><script src='//embed-cdn.gettyimages.com/widgets.js' charset='utf-8' async></script>

All that is left is a simple link that says embedd from Getty but no image appears.

Or is there a code work around where I could make the div show the image

**Comment by kevinfodness** [comment]
Unfortunately, the Apple News format cannot support images included in this way. You need an actual reference to the image file.
