### ISSUE TITLE
More tag not stripped out

### ISSUE THREAD

**Issue by eliseboyd** [alleyinteractive/apple-news#48]
We use the More tag on all of our posts - in the outputted json file, it seems that the comment tags are stripped out, but it still outputs the word 'more'

E.g.
Nullam ac egestas nunc.more

**Comment by bcampeau** [comment]
We don't make heavy use of the More tag, so probably never saw this. Can you send over a pull request to address this?

**Comment by smerriman** [comment]
Have done so here: https://github.com/alleyinteractive/apple-news/pull/49
