### ISSUE TITLE
There has been an error with the API: INVALID_DOCUMENT - Unable to read uri

### ISSUE THREAD

**Issue by clickbeep** [alleyinteractive/apple-news#520]
I am currently unable to publish articles with featured images.  Every time I do, I get:
"There has been an error with the API: INVALID_DOCUMENT - Unable to read uri [https://www.domain.com/media/image.jpg]"

I've used this plugin in the past without issue.  This is a new install.  I've tried on two clean installs, no theme, no plugins.  The image uploads fine, works fine on the site, and I can copy and paste the image location it is showing into a new tab and the image shows just fine.

After creating the WP install, I have changed the upload path from wp-content to media by changing my wp-config.php file from
define( 'UPLOADS', 'wp-content/'.'files' );
to
define( 'UPLOADS', ''.'media' );

It looks cleaner to me, and doesn't scream out "I HAVE A WORDPRESS BLOG" to everyone.
If I remove the featured image, or don't include one at all, the article publishes to Apple News just fine.

-----

If I upload an article with no images, it goes fine.  If I try to use an image in a post, I get the error:
"The following components are unsupported by Apple News and were removed: img"

-----

I noticed that if I launch a redesign as test.domain.com, and then once I complete the site I change my DNS to point to www.domain.com, the screenshots of the Apple News themes breaks.  (Apple News > Themes)
I can edit the theme, and manually change the links to the screenshots, but it always defaults to whatever the OG site name is.  Changing the name in the wp-config.php file with
define('WP_SITEURL', 'https://www.site.com);
define('WP_HOME', 'https://www.site.com');
doesn't fix it.

**Comment by kevinfodness** [comment]
If the images are accessible remotely, then they should work properly. Is this issue still ongoing today? Is it possible that there was a blip with the Apple News service in not being able to access the images on your server?

Can you send a link to a post that is failing to publish that contains images? That will help me to determine why it is failing.

You are correct, the screenshot URL is saved in the `wp_options` table as a full URL, so if you switch your site domain, you will need to update that value. When we switch site domains, we use `WP-CLI` and the `wp search-replace` tool to handle this for us: https://developer.wordpress.org/cli/commands/search-replace/

**Comment by clickbeep** [comment]
Yeah, it is still going.

Article:
https://www.clickbeep.net/articles/montblanc-launches-a-smart-watch-band/

Errors:
There has been an error with the API: INVALID_DOCUMENT - Unable to read uri [https://www.clickbeep.net/media/montblancsmartband001.jpg]
The following components are unsupported by Apple News and were removed: img

Featured Image:
https://www.clickbeep.net/media/montblancsmartband001.jpg

Featured Image as the article shows it:
https://www.clickbeep.net/media/montblancsmartband001-1080x1080.jpg

(This is utterly stupid to me, that the theme has to make a separate image, even though I use 1080x1080 images for my featured images, but that's a theme thing.  I'm just glad I got it to show square images like I want instead of rectangle images like the theme maker wrote.)

Article Image:
https://www.clickbeep.net/media/montblancsmartband002.jpg

**Comment by kevinfodness** [comment]
That's very strange—I'm able to access those images with no problems, so it seems to me that Apple should be able to as well. The error you're receiving is being passed directly from the Apple News API response, so that's what Apple's servers are saying is the issue. I would recommend opening a support ticket with them to inquire why their servers can't see your image, given that it is publicly available. You could also take a look at your server logs to see if requests are being blocked for some reason.

**Comment by yhongvs** [comment]
I have same issue.

**Comment by mdzahid786** [comment]
I am also getting the same issue with the featured images

`There has been an error with the Apple News API: INVALID_DOCUMENT - Unable to read uri `
