### ISSUE TITLE
Initial report: Nonce verification fails on publish in master branch

### ISSUE THREAD

**Issue by davisshaver** [alleyinteractive/apple-news#521]
With the plugin enabled, updating a post results in a screen titled `Something went wrong` and with the error text, `The link you followed has expired.`

Examining the internals of `check_admin_referer()`, the `apple_news_publish` action appears to be passed with a `null` nonce value.

With the plugin disabled, the post will update or publish as normal.

**Comment by davisshaver** [comment]
Reverting the plugin to the latest versioned release (v1.3.0) fixed the problem.

Looks like @kevinfodness had some related changes in https://github.com/alleyinteractive/apple-news/commit/6a65af6be1574ada70855a7ab7ebf6a139e5c758.

**Comment by kevinfodness** [comment]
Hi @davisshaver —

I've tried a few different combinations of settings, and I can't get this error to pop for me. Can you confirm that this error still occurs using the latest code in `master`? Can you provide your settings in the "Apple News API" section other than the channel ID/key/secret please? Also, can you confirm that the process you are using is edit post > click update > see error?

Thanks!

**Comment by davisshaver** [comment]
Hey @kevinfodness, closing this as I've been unable to recreate! will let you know if I see it again.

**Comment by kevinfodness** [comment]
Hey @davisshaver — thanks for checking!
