### ISSUE TITLE
The link you followed has expired.

### ISSUE THREAD

**Issue by iamkingsleyf** [alleyinteractive/apple-news#537]
Hello;

We are having the following error <strong>"The link you followed has expired."</strong> when you click on publish post, this is happening across 2 sites and once the plugin is disabled it works fine. its happening on https://thegloor.com and https://healthable.org

Thanks

**Comment by iamkingsleyf** [comment]
i found this also

https://wordpress.org/support/topic/plugin-conflict-200/

**Comment by iamkingsleyf** [comment]
any update

**Comment by danielbachhuber** [comment]
Duplicate of #544
