### ISSUE TITLE
wink emoticon in content outputs null

### ISSUE THREAD

**Issue by bremser** [alleyinteractive/apple-news#538]
A very tiny bug here - a bunch of my articles were not publishing and when I would download them, the contents were null. It took me some time to try to figure out what the reason was, what they had in common. Turns out if the post had a wink emoticon ;) - that caused the problem. Removing it fixed it. 

I wanted to automatically remove or replace them to avoid having to edit them out in the future, but ran into some issues there. I'm not sure if it's the plugin or Wordpress, but what my strategy was to add a few lines to apple-exporter/class-html.php in the format function (where it strips the script tag).

I tried:
$html = str_replace( ' ;)', '', $html );
and
$html = preg_replace(';\)', '', $html);
And neither of these worked. The str replace outputs null. preg_replace seems to match, but strips out the entire body HTML (the JSON file is only the header styles and meta) Other tests to replace characters and words worked, I wonder if Wordpress or Jetpack is handling emoticons. Also when I manually replaced the emoticon with the winking emoiji HTML (&#x1f609;) that also threw up a JSON error. 

Any suggestions appreciated!

**Comment by kevinfodness** [comment]
Version 1.4.0, which was released June 21, should have fixed this issue. Can you tell me if this is still occurring on the latest version of the plugin? If so, can you provide the raw content from the Text tab in your editor?

**Comment by bremser** [comment]
Hi Kevin - this was definitely occurring last month in July, after that update. Here's an example post with the issue - https://www.101cookbooks.com/sunset-coconut-goji-nectar/
The raw content from the text tab around the wink is:
`Add a splash of tequila (later in the day), and you've got a nice cocktail on your hands. ;) </p>`

**Comment by kevinfodness** [comment]
Thanks—we'll take a look!

**Comment by kevinfodness** [comment]
I just tested this in the most recent version, and the wink text is replaced with an actual emoji, which shows up correctly in the output.
