### ISSUE TITLE
ALL AJAX in WP admin lists HANGS

### ISSUE THREAD

**Issue by gdvine** [alleyinteractive/apple-news#542]
Upon installing this plugin and only this plugin, every AJAX operation on every list page in the Admin (and perhaps elsewhere?) **hangs** on submit. The submit does work in the background, but you need to refresh the page to see it.

This is a very serious UX bug. To test, just try to Quick edit any post and see the loading indicator hang.

**Comment by danielbachhuber** [comment]
Duplicate of #544

**Comment by kevinfodness** [comment]
We just released version 1.4.2 on WordPress.org to fix this problem. If you still experience the issue on the latest version, please let me know. Thanks!
