### ISSUE TITLE
How to use `apple_news_register_component` filter

### ISSUE THREAD

**Issue by cscomfort** [alleyinteractive/apple-news#543]
I'm relatively new to working with WordPress filters and seem to be having particular difficulty determining how to use the `apple_news_register_component` filter. Could someone please provide me an simple example of how to properly call the function, say for the `img` shortname?

Many thanks in advance.

**Comment by cscomfort** [comment]
In the meantime, I'm using the following callback with the `apple_news_initialize_components` filter:

```php
public function init_components($components) {
    $components['img'] = '\\Path\\To\\Custom\\ImageClass';
    return $components;
}
```
Not sure what consequences there may be with this workaround, but looks to be working for now...

**Comment by kevinfodness** [comment]
Yes, you can replace existing component registrations with your own classes in this way. There is a related issue to make this easier: #417

**Comment by umeshnevase** [comment]
@kevinfodness @cscomfort 
I tried to unset and re register same component by some modification through `apple_news_initialize_components` filter. But the classes defined in theme are not registering componentd
Fatal error: Uncaught Error: Class "MyTheme\Components\example" not found
in /plugins/publish-to-apple-news/includes/apple-exporter/class-component-factory.php on line 212

**Comment by kevinfodness** [comment]
Sounds like the autoloader isn't able to find that class, or it isn't being loaded for some other reason. Note that exports happen in an admin context and not a frontend context, so if you've got logic in your theme that only runs on the front end, it won't work for Apple News.

**Comment by umeshnevase** [comment]
@kevinfodness Thank you for quick reply.
I'm running logic on apple_news_initialize_components filter, which is only run o Apple news export from wp-admin. 
I tried to initialise the component from both theme and other plugin. The autoloader not loading the class. Do you have any suggestion? or did you tried this in any plugin or theme to override the default component with new?

**Comment by kevinfodness** [comment]
We've successfully done this before. I'm sorry I don't have any additional ideas for you - you'll have to chase down why your autoloader isn't working properly. Are you using Composer to generate your autoloader? Can you look at the Composer autoloader that was generated to see if it's correctly mapping the MyTheme namespace? Can you confirm that the autoloader is using the proper case? Most hosting platforms are case-sensitive, so if the folder is `components` but your autoloader is looking for `Components` that could cause it to fail. If you don't have Xdebug set up already, I'd recommend setting it up locally to help chase down this issue.
