### ISSUE TITLE
Quick Edit problem

### ISSUE THREAD

**Issue by kuoko** [alleyinteractive/apple-news#544]
Hi guys,
Unfortunately the following line is partially breaking the Quick Edit feature which remains stuck with the loader spinning.

https://github.com/alleyinteractive/apple-news/blob/master/admin/class-admin-apple-meta-boxes.php#L52

The action is fired everytime there is a save_post and the admin-ajax call returns 403 error due to some missing POST data.

A fix could be putting that line under a conditional

```
if($_REQUEST['action'] !== 'inline-save') {
                    add_action( 'save_post_' . $post_type, array( $this, 'do_publish' ), 10, 2 );
                }
```

**Comment by danielbachhuber** [comment]
👍 I have this problem too.

**Comment by danielbachhuber** [comment]
#547 fixes the issue for me.

As a really hacky interim fix, I've put `wp_nonce_field( 'apple_news_publish', 'apple_news_nonce' );` in the Quick Edit HTML.

**Comment by danielbachhuber** [comment]
@mboynes Could we get this in a 1.4.2 release?

**Comment by kevinfodness** [comment]
Hi @danielbachhuber —

I'm currently the lead dev for this plugin, and I'd be happy to get this resolved quickly. Your PR looks good on first glance. I'll run a few tests of my own, and then I can release 1.4.2 on .org and via VIP.

Thanks!

**Comment by kevinfodness** [comment]
Hi @kuoko —

Thanks for the issue report. I apologize for the delay in responding—I have been traveling. We'll get a solution to this posted soon.

**Comment by danielbachhuber** [comment]
Thanks @kevinfodness! Happy to help out if you need it.

**Comment by kuoko** [comment]
Hi guys,
no worries @kevinfodness and thanks for the fix! @danielbachhuber

**Comment by iamkingsleyf** [comment]
alright thanks everyone.
