### ISSUE TITLE
Headings don't support HTML tags

### ISSUE THREAD

**Issue by cscomfort** [alleyinteractive/apple-news#551]
Looking over the Heading component class, I see that the builder function is stripping tags from the heading content. This looks to be a holdover from markdown support, but now that the plugin is defaulting to HTML can we return to offering some sane support tags?

**Comment by kevinfodness** [comment]
You are correct—the tags get stripped from headings. However, they shouldn't need to be, so I'll add this as an enhancement for version 2 of the plugin.
