### ISSUE TITLE
Don't ob_start() on every page load

### ISSUE THREAD

**Issue by danielbachhuber** [alleyinteractive/apple-news#56]
`ob_start()` shouldn't be included in `__construct()` of `Admin_Apple_News`, which is instantiated on every page load. I'm not sure why this hasn't broken things.

**Comment by bcampeau** [comment]
Neither me or VIP noticed that in our code review. Will check it out.

**Comment by bcampeau** [comment]
Reopening this since I've discovered the original plugin had far more of a rat's nest than expected.
