### ISSUE TITLE
Undefined indexes

### ISSUE THREAD

**Issue by schrapel** [alleyinteractive/apple-news#561]
When I click export on an article and PHP errors are displayed I get the following notices in the JSON.

The fix seems quite trivial. We need to make sure that components have a default value populated or exclude them. 

I do not know why this component does not have a role value.

I am happy to create a PR for this change but since there are many paths to a solution here I wanted to open an issue here first to discuss which function we should patch. 

WordPress version: 4.9.7
Plugin Version: 1.4.3
Theme Active: Twenty Seventeen
Plugins Active: Publish to Apple News (rest are disabled)

<details>
<summary>PHP Notices & JSON Export</summary>
<br />
<b>Notice</b>:  Undefined index: role in <b>/var/www/example.com/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php</b> on line <b>592</b><br />
<br />
<b>Notice</b>:  Undefined index: role in <b>/var/www/example.com/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php</b> on line <b>605</b><br />
<br />
<b>Notice</b>:  Undefined index: role in <b>/var/www/example.com/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php</b> on line <b>597</b><br />
<br />
<b>Notice</b>:  Undefined index: role in <b>/var/www/example.com/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php</b> on line <b>602</b><br />
<br />
<b>Notice</b>:  Undefined index: role in <b>/var/www/example.com/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php</b> on line <b>592</b><br />
<br />
<b>Notice</b>:  Undefined index: role in <b>/var/www/example.com/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php</b> on line <b>605</b><br />
<br />
<b>Notice</b>:  Undefined index: role in <b>/var/www/example.com/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php</b> on line <b>597</b><br />
<br />
<b>Notice</b>:  Undefined index: role in <b>/var/www/example.com/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php</b> on line <b>602</b><br />
<br />
<b>Notice</b>:  Undefined index: role in <b>/var/www/example.com/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php</b> on line <b>411</b><br />
<br />
<b>Notice</b>:  Undefined index: role in <b>/var/www/example.com/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php</b> on line <b>411</b><br />
{"version":"1.7","identifier":"post-13","language":"en-US","title":"Test","documentStyle":{"backgroundColor":"#fafafa"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"title","text":"Test","format":"html","textStyle":"default-title","layout":"title-layout"},{"role":"byline","text":"by Toby | Sep 24, 2018 | 4:21 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"intro","text":"http:\/\/www.youtube.com\/watch?v=tXtATeQ7GKg &nbsp; https:\/\/twitter.com\/Twitter\/status\/1042781956830887936 &nbsp; https:\/\/www.instagram.com\/p\/Bn4xKHBjGUB\/?taken-by=instagram\n","textStyle":"default-intro"},{"role":"embedwebvideo","aspectRatio":1.777,"URL":"https:\/\/www.youtube.com\/embed\/tXtATeQ7GKg"},[],{"role":"tweet","URL":"https:\/\/twitter.com\/Twitter\/status\/1042781956830887936","layout":"tweet-layout"},[],{"role":"instagram","URL":"https:\/\/www.instagram.com\/p\/Bn4xKHBjGUB\/"}],"componentTextStyles":{"default-title":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"tracking":0,"textColor":"#333333","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"AvenirNext-Medium","fontSize":13,"lineHeight":24,"tracking":0,"textColor":"#7c7c7c"},"default-intro":{"fontName":"AvenirNext-Regular","fontSize":18,"lineHeight":24,"textColor":"#4f4f4f"}},"textStyles":{"default-tag-code":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"},"default-tag-pre":{"textAlignment":"left","fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f","paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-tag-samp":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"}},"componentLayouts":{"tweet-layout":{"margin":{"top":30,"bottom":30},"columnStart":0,"columnSpan":7},"title-layout":{"margin":{"top":30,"bottom":0}},"byline-layout":{"margin":{"top":10,"bottom":10},"columnStart":0,"columnSpan":7}},"metadata":{"excerpt":"http:\/\/www.youtube.com\/watch?v=tXtATeQ7GKg &nbsp; https:\/\/twitter.com\/Twitter\/status\/1042781956830887936 &nbsp; https:\/\/www.instagram.com\/p\/Bn4xKHBjGUB\/?taken-by=instagram","dateCreated":"2018-09-24T16:21:52+00:00","dateModified":"2018-09-25T12:06:58+00:00","datePublished":"2018-09-24T16:21:52+00:00","canonicalURL":"http:\/\/example.com\/2018\/09\/24\/test\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"1.4.3"},"advertisingSettings":{"frequency":1,"layout":{"margin":{"top":15,"bottom":15}}}}
</details>

<details>
<summary>Article Content</summary>

http://www.youtube.com/watch?v=tXtATeQ7GKg

&nbsp;

https://twitter.com/Twitter/status/1042781956830887936

&

https://www.instagram.com/p/Bn4xKHBjGUB/?taken-by=instagram
</details>

**Comment by kevinfodness** [comment]
That is strange. I haven't seen that issue. What version of PHP are you using?

**Comment by schrapel** [comment]
5.6

**Comment by kevinfodness** [comment]
This may be related to the Instagram embed issue you posted earlier. I'll mark this as a bug pending further analysis.

**Comment by jb510** [comment]
PHP 7.2
Apple-news Version 1.4.3

'm seeing this all over my error logsPHP 7.2:
```

PHP Notice:  Undefined index: role in /html/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php on line 411
PHP Notice:  Undefined index: role in /html/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php on line 411
PHP Notice:  Undefined index: role in /html/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php on line 597
PHP Notice:  Undefined index: role in /html/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php on line 602
PHP Notice:  Undefined index: role in /html/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php on line 592
PHP Notice:  Undefined index: role in /html/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php on line 605
```

Per https://developer.apple.com/documentation/apple_news/component
`role string (Required)`

Can/Should a default 'role' be assigned to all components?  

Can this be traced back to invalid markup perhaps?  If so, is that or could that be logged more meaningfully?
