### ISSUE TITLE
The following components are unsupported by Apple News and were removed: script script

### ISSUE THREAD

**Issue by schrapel** [alleyinteractive/apple-news#562]
If I dump out the nodes being processed you see these nodes. This leads me to believe that the embed is being processed in the content by WordPress.

![screenshot 2018-09-25 07 54 20](https://user-images.githubusercontent.com/3613405/46015577-46c9ea80-c098-11e8-83cb-481e579451c3.png)

If I remove this filter `remove_filter( 'the_content', array( $GLOBALS['wp_embed'], 'autoembed' ), 8 );` everything works fine without any errors.

WordPress version: 4.9.7
Plugin Version: 1.4.3
Theme Active: Twenty Seventeen
Plugins Active: Publish to Apple News (rest are disabled)

<details>
<summary>Post Content</summary>

https://www.instagram.com/p/Bn4xKHBjGUB/?taken-by=instagram

http://www.youtube.com/watch?v=tXtATeQ7GKg

https://twitter.com/Twitter/status/1042781956830887936
</details>

**Comment by kevinfodness** [comment]
Yes, you can't embed items that use script tags, and they will have to be removed or modified. Is this an addendum to your previous issue?

**Comment by schrapel** [comment]
This is not related to the previous issue. The issue here is that core WordPress Embeds are being rendered before generating the Apple News content

**Comment by kevinfodness** [comment]
I'm going to mark this as a bug, because the plugin should work out of the box with default WordPress embeds. Do you know if this is specifically with Instagram, or is it happening with other embeds also? It's possible that Instagram changed their embed code, and it's not being properly parsed by the plugin.

**Comment by schrapel** [comment]
I am not sure. This is an example of a Instagram embed which contains a `<script>` tag https://api.instagram.com/oembed/?url=http://instagr.am/p/fA9uwTtkSN/ but I am sure many others do the same thing.

**Comment by kevinfodness** [comment]
Yes, and we have support for various embed formats, including those that contain `<script>` tags. However, it's a regular expression match, and it's possible that a new format of embed needs to be added to this plugin to avoid the issue you described.
