### ISSUE TITLE
The Apple News JSON is invalid and cannot be published.

### ISSUE THREAD

**Issue by schrapel** [alleyinteractive/apple-news#564]
Sometimes when we click "Update post" on an existing post we will get the error `The Apple News JSON is invalid and cannot be published.`. If we click "Update post" again it will process successfully. The happens if we click update without changing any of the fields (title, post_name, post_content, etc).

After debugging the value parse to `Push::sanitize_json` is an empty string `''`. I am not quite sure why from one update to another this value would be empty and the next populated (As it should be)

WordPress version: 4.9.7
Plugin Version: 1.4.3
Theme Active: Twenty Seventeen
Plugins Active: Publish to Apple News (rest are disabled)

**Comment by schrapel** [comment]
I tested this and produced the error of a fresh version of 4.9.7.

**Comment by duanestorey** [comment]
I have this issue as well, but only on certain servers. It will fail randomly, and then sometimes work randomly too.

**Comment by kevinfodness** [comment]
Do you have any other plugins active? In particular, are you using Gutenberg? We have done some testing with Gutenberg and have not noticed any issues, but it's possible that there is an operation that is causing empty content to be sent as JSON. Alternately, it is possible that an upstream failure is resulting in empty JSON. Are you seeing any errors in your logs from PHP?

**Comment by schrapel** [comment]
@kevinfodness Everything is in the first post of this issue. Not using Gutenberg and the only active plugin is this one. Nothing was in the error log either

**Comment by kevinfodness** [comment]
I haven't seen this behavior before, and it will be difficult to diagnose since it only happens occasionally, and seemingly without a specific cause. Would it be possible for you to introduce some logging into the plugin source to try to catch the failure in the act? Specifically, logging what is coming in for parsing using the `apple_news_exporter_content_pre` filter, and then just returning the original value at the end of the function: https://github.com/alleyinteractive/apple-news/wiki/Action-and-Filter-Hooks#adminapple-actionsindexclass-exportphp-1

**Comment by duanestorey** [comment]
Hi Kevin,

I actually modified that hook to interject my own content, and it still happened.  What was coming in was nothing, and what was going out was HTML. I logged that and the final json.  In all cases the HTML was generated, but when it failed the json was completely empty, as in a blank string.

Duane

**Comment by hayhurst** [comment]
I'm also seeing this issue on some articles, same error message.

Tried exporting the article .json, but just get a file that simply contains the word "null"

Happy to help with any diagnostics as seen this on a few of our articles.

**Comment by kevinfodness** [comment]
If it's coming back null, then that means something is interfering with the process of exporting the content, or your content is empty. I'd try the usual culprits - disable other plugins to see if there is a conflict, try with using one of the stock themes (e.g., Twenty Nineteen) to see if it is an issue with custom code in your theme.

Also, the plugin is only able to "see" what is in `post_content`, or what is entered into the main editor. If you are building your content using something like Advanced Custom Fields (ACF) and building the page using a PHP template that references custom fields in postmeta, then the plugin won't be able to "see" that and you'll end up with empty content.

**Comment by orenwolf** [comment]
We're seeing the same issue. Is there a way to get a more detailed error? The issue is intermittent which makes it extra-annoying, because we're obviously not changing our config post-to-post, and we don't have any special fields or post types in play, either.
