### ISSUE TITLE
Articles contain repeating text

### ISSUE THREAD

**Issue by iamkingsleyf** [alleyinteractive/apple-news#565]
Hello;

I just received a mail from Apple that the first paragraph is appearing twice, i now own an iphone so i checked and its true with one of my other channels.

see screenshots https://imgur.com/a/62QRwxz

Please how do i fix it?

Regards

**Comment by iamkingsleyf** [comment]
out of 3k users am i the only one having this problem?

**Comment by schrapel** [comment]
@iamkingsleyf Under the `Component Order` setting for your active theme, you should move intro to inactive.

**Comment by iamkingsleyf** [comment]
@schrapel  wooow never knew, seems the default theme has the issue, i just checked the other themes and there is nothing like that.

Thanks....

**Comment by kevinfodness** [comment]
You would have to update and re-publish the existing articles. Sounds like we have a fix, though.
