### ISSUE TITLE
"There has been an error with the API" error message is confusing, not actionable

### ISSUE THREAD

**Issue by paulschreiber** [alleyinteractive/apple-news#573]
One of our editors received this message:
>There has been an error with the API: There has been an error with your request: cURL error 28: Operation timed out after 300001 milliseconds with 0 bytes received.

Problems:
• No indication that this is Apple News-related
• Too much technical detail
• No suggested corrective action provided

**Comment by kevinfodness** [comment]
That's a good point, @paulschreiber. It would be worthwhile to add a log of messages visible only to admins and provide a different message to non-admins.

**Comment by kevinfodness** [comment]
These messages have been updated to specify that they're coming from Publish to Apple News.
