### ISSUE TITLE
cURL error 35: error:140770FC:SSL

### ISSUE THREAD

**Issue by gregoryjcook** [alleyinteractive/apple-news#576]
PHP and Curl are up to date. Reissued Apple News API Keys. Wordpress 4.9.8, PHP 7.0.21, cURL 7.54.1, on Win 2008 R2 Ent Sp1.

The complete error message:

There has been an error with the API: There has been an error with your request: cURL error 35: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

**Comment by ryanrbftp** [comment]
We are getting the same when publishing and updating:
`There has been an error with your request: cURL error 35: SSL connect error`

**Comment by kevinfodness** [comment]
I answered this in WP.org forums, closing here.
