### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by rynebarber** [alleyinteractive/apple-news#579]
Hello,

Fairly recently we have been receiving the API error API: INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->12->text) on all posts in Wordpress. I have read elsewhere that this could be caused by a blank text field but I can't find any cause for it. Would you be able to help?

Thanks.

**Comment by kevinfodness** [comment]
Yep, can you please follow the instructions here to provide a full issue report: https://github.com/alleyinteractive/apple-news/wiki/usage#getting-help

That information will allow me to trace the problem and attempt to reproduce it on my end. Thanks!
