### ISSUE TITLE
API: INVALID_DOCUMENT Invalid URL 

### ISSUE THREAD

**Issue by laurenamberquinn** [alleyinteractive/apple-news#584]
Hi

I received this message: There has been an error with the API: INVALID_DOCUMENT - Invalid URL=[#]. Only URLs starting with http://, https://, tel: and mailto: are supported. (keyPath components->3->components->9)

page: https://bromeliario.com/1-week-brazil-itinerary-7-day/

I have changed nothing about the format of this post from all my other pages. Can you help me figure out what is wrong?

Thank you so so much.

Regards,
Lauren

**Comment by kevinfodness** [comment]
I replied to this issue in the WordPress.org forums, so I'm going to close this issue here. Please let me know if my solution doesn't resolve your problem.
