### ISSUE TITLE
Parse error?

### ISSUE THREAD

**Issue by duanestorey** [alleyinteractive/apple-news#585]
Hey everyone,

Thanks for all the hard work on this plugin - it  works great.

I had a  strange issue though where I had a paragraph tag that wouldn't output no matter what.  I eventually tracked it down and realized that it had the British pound (currency) symbol in it.  If I removed that, it ended up being added to Apple News.  With it, it ended up being output as an empty field on Apple News.

Is there something special I need to do with the content to make that parse properly?

Thanks.

**Comment by kevinfodness** [comment]
Interesting—that shouldn't cause an issue. I'll flag this as a bug that needs confirmation. It may be a Unicode issue.

**Comment by kevinfodness** [comment]
We added additional Unicode character support, so this should no longer be an issue. It worked fine for me on the latest version.
