### ISSUE TITLE
Photo Galleries -- Horizontal gallery support?

### ISSUE THREAD

**Issue by seanrasmussen** [alleyinteractive/apple-news#588]
Articles with photo galleries appear as just long scrolling articles with image-caption-image-caption etc....

Is there a way to get a slider-like gallery experience in Apple News with this plugin?

**Comment by kevinfodness** [comment]
Yes, there is support for both standard WordPress galleries using the `[gallery]` shortcode as well as Jetpack galleries. Are you using a third party plugin for galleries? If so, you will need to filter the output of the third party plugin to convert it to a standard WordPress gallery in order for this plugin to be able to properly read it. The most straightforward way to do this is likely in the `apple_news_exporter_content_pre` filter: https://github.com/alleyinteractive/apple-news/wiki/Action-and-Filter-Hooks#adminapple-actionsindexclass-exportphp-1

**Comment by seanrasmussen** [comment]
Thanks Kevin. We do have a custom gallery snippet in our functions.php. I did add a filter to that hook, though, but it didn't seem to fix the issue....

**Comment by kevinfodness** [comment]
Yes, if the gallery is able to be translated it will be a swipeable gallery in Apple News. What was the filter that you put on the hook?

**Comment by seanrasmussen** [comment]
Hi Kevin, I found the right hook to remove our custom gallery for Apple News.... So now Apple News gets the standard WP Gallery (and behaves as expected with swiping etc)..

I wonder if that might be a good future enhancement to the plugin? -- an interface which specifies how to deal with these shortcodes before pushing to Apple News? 

Anyway, here's the snippet I used in my functions.php (if anyone else needs to do something similar):

```
add_action('apple_news_do_fetch_exporter', 'spr_remove_custom_gallery_for_apple_news');
  function spr_remove_custom_gallery_for_apple_news() {
      remove_filter('post_gallery', 'spr_custom_post_gallery');
  }
```

**Comment by kevinfodness** [comment]
Unfortunately, we can't detect all possible overrides of galleries, nor know whether an override can be safely removed to fall back to a standard gallery. We have built in support for Jetpack gallery overrides, since that is a common use case, but everything else will likely need to be a filter.

**Comment by seanrasmussen** [comment]
Yeah, makes sense....
