### ISSUE TITLE
API forbidden

### ISSUE THREAD

**Issue by Saif206** [alleyinteractive/apple-news#589]
It is regarding connecting CMS, I have changed data on my WordPress website, after that, I am unable to post articles to Apple News through API. It says API is forbidden in my WordPress dashboard. I have even changed the API key, still, it is not working, Please reply and resolve my query.
![img_20181209_011737](https://user-images.githubusercontent.com/45720450/49690098-51e9ce00-fb51-11e8-95fb-5605b3dc900a.JPG)

**Comment by kevinfodness** [comment]
That message is coming directly from Apple, and the error code description is that you are trying to access something via the API that you don't have permission to access: https://developer.apple.com/documentation/apple_news/code

My guess is that something in your API settings is incorrect, such as channel ID, API key, or secret. If you are copying and pasting these values, ensure you are not accidentally copying extra spaces or return characters on either end of the string.
