### ISSUE TITLE
Containers and Sections?

### ISSUE THREAD

**Issue by AlexAscherson** [alleyinteractive/apple-news#60]
Hi Guys,

Just a quick one, just wondering if the plugin supported containers and sections yet? Couldn't find any reference to them in the readme and in the code their doesnt seem to be a component defined though there is a check to see if a component has child nodes.

Is this something that is supported yet? I am guessing not but if so I would be happy to add the info to the readme for others if someone can fill me in.   I am looking to produce something that looks like this from the Apple News Example articles:

![screen shot 2016-01-07 at 11 42 34](https://cloud.githubusercontent.com/assets/12135010/12169853/cbcba6ec-b533-11e5-84f5-3cfe0c9ebb44.png)

**Comment by bcampeau** [comment]
Containers and sections are supported but there is no way to automatically parse those from a post. The plugin handles only basic formatting options that can be extracted from any post. There are dozens of hooks that can be used by any developer for implementing complex custom templates.

If you have a proposal for how this could be automatically parsed from a post, we're always open to a pull request.

Thanks.

**Comment by AlexAscherson** [comment]
Could this be done simply via div elements and classes? Or even just element classes? <div class = "container">, <div class="container-title"> etc?  Then allow people to hook in and change the classes to fit the structure of their particular containers?  Im something of a newbie but could have a crack at it if this seems a reasonable approach.

**Comment by bcampeau** [comment]
You can create your own custom component classes and filter out the built-in ones using this filter: https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-exporter/class-component-factory.php#L93. There are also numerous filters throughout every class to modify components.

You can optionally just filter the entire JSON output using: https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-exporter/class-workspace.php#L81 or https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-exporter/class-workspace.php#L106
