### ISSUE TITLE
Apple News Plugin Error: There has been an error with the API: FAILED_TO_PARSE_IMAGE 

### ISSUE THREAD

**Issue by hbscreatives** [alleyinteractive/apple-news#603]
Please help me to publish Apple News on the plugin, Apple News Plug In, Error message is here: 

There has been an error with the API: FAILED_TO_PARSE_IMAGE - Failed to parse image with URI [bundle://GIFvUw_nveM].

Help me...!

**Comment by kevinfodness** [comment]
My guess here is that you have an image with no filename extension. Can you ensure the image has a filename extension that matches its MIME type and try again?

**Comment by cem-wm** [comment]
Any updates on this? I'm getting the same error whenever there are YouTube embeds in the articles. For some reason the plugin seems to think those are image files. 

Here's the error message: FAILED_TO_PARSE_IMAGE - FAILED TO PARSE IMAGE WITH URI [HTTPS://WWW.YOUTUBE.COM/EMBED/2V4GVB_NEYG?VERSION=3&REL=1&FS=1&AUTOHIDE=2&SHOWSEARCH=0&SHOWINFO=1&IV_LOAD_POLICY=1&WMODE=TRANSPARENT].

**Comment by Nateldn** [comment]
I've got the same error, though it seems to be related to a video embed  [VideoPress].  When the video is removed, the plugin works fine.

**Comment by kevinfodness** [comment]
There's a fix for this in more recent versions of the plugin - we improved the code that is used to detect image source compared to other types of source strings. If you are using the latest version and are still experiencing an issue, please let me know.
