### ISSUE TITLE
Unable to post images - Errors

### ISSUE THREAD

**Issue by channeld** [alleyinteractive/apple-news#605]
I have errors in some posts when I click to publish them to Apple News. These are:

A. The following components are unsupported by Apple News and were removed:
img
img
img
img

B. There has been an error with the API: INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->3->components->43->text)

I read an instruction to open Remote images. Did that. Same error.
Any ideas? Example post: https://agreekadventure.com/mount-parnassus-greece-trekking/

**Comment by kevinfodness** [comment]
The text issue seems like the main problem - consolidating discussion of that issue on #707.
