### ISSUE TITLE
Posts stuck Pending: cache pollution with async jobs issue

### ISSUE THREAD

**Issue by mikeyarce** [alleyinteractive/apple-news#607]
### Summary: 

When sending many posts to Apple News within a short period of time, posts frequently get stuck as "Pending", and don't publish to Apple News.

### Example:

1. User opens up 10 tabs with posts
2. Goes through each one, publishing them all to Apple News
3. The first one is fine, the latter ones sometimes will publish, but sometimes get stuck as Pending.
4. Resetting the posts and sending again fixes the issue.

### Cache pollution theory:

On WordPress.com VIP, we send these jobs to be run by our async jobs server - and I think what's going on is that when the job is scheduled, it's doing a cache sync and loading cache for the job to run.  However, since a job was just run seconds ago, and the first cache sync was still finishing, the 2nd job ends up loading the cache from the first job which doesn't have the right data.   The job then runs without the right post data, and so the post never publishes.

### Notes:

- The posts always have the `apple_news_api_pending` value, but don't have the `apple_news_api_async_in_progress` value.   
- The jobs don't "fail" because they run without errors.
- There are no PHP Fatal Errors or Warnings to note
- The debugging options are set but no emails are sent for the posts that get stuck.
- This seems to only happen when a large amount of articles are being pushed close together.
- Resetting and re-sending fixes these posts in my tests.

### Idea:

What if there was a job runner for the publish to Apple News action?  The runner would first add the right post meta for the posts that are being sent over, and then would queue them up in batches and send them out in order.  Then it would call itself to see if any other posts need sending until the queue was empty.   This would prevent all the jobs running at the same time for the site which we think might be what's causing the collisions.

**Comment by kevinfodness** [comment]
It seems like this is specifically an issue at the intersection of the async option being enabled + the VIP Jobs system + publishers clicking "Publish" on several articles in rapid succession, in which case I would not be in favor of creating a job runner to address this particular set of circumstances. The async publishing option was created for one of the earliest versions of the plugin, when Apple did not support remote images, and people were experiencing timeouts as a result of bundling and sending large images. At this point, our recommendation is to use synchronous publishing with the remote images setting turned on. We can, instead, remove the async publishing option entirely and display a message to anyone who was using that option on upgrade.

**Comment by kevinfodness** [comment]
Marking this as an enhancement to remove the async option entirely in a future release. For now, publishers should not be using the async option and should be using the Remote Images setting.

**Comment by dartiss** [comment]
@kevinfodness do you have any thoughts on when this might be implemented?

**Comment by kevinfodness** [comment]
No, although we are hard at work on releasing v2 of the plugin, which will include full support for Gutenberg, and we may need to tweak that functionality a bit in the process.

**Comment by kevinfodness** [comment]
We made remote images default to yes in the new version of the plugin, but async publishing is still available as an option. We are still planning on removing it in a future version.
