### ISSUE TITLE
Channel content contains broken or missing text

### ISSUE THREAD

**Issue by jcrafael** [alleyinteractive/apple-news#608]
Hello,
I need help, because I already installed Apple News plugin and configure with parameters from Apple Publisher keys in Wordpress, but when publish, all works well, but when apple publisher reviews says that: “Channel content contains broken or missing text”. Only import title and images.
Posts have content in description field, image, tags.
Can you help us?
Thanks!

**Comment by atoupet-toki** [comment]
Same here .. do you use ACF?

**Comment by jcrafael** [comment]
Yes, How I need to do to fix this?

**Comment by atoupet-toki** [comment]
Don't know ... looking for a solution right now

**Comment by jcrafael** [comment]
Great! Thanks for help!

**Comment by atoupet-toki** [comment]
@jcrafael did you get something?

**Comment by inforfacildev** [comment]
Hello @atoupet-toki  can you help me in this topic?

**Comment by kevinfodness** [comment]
The Publish to Apple News plugin can only "see" what is in `post_content` in the database, so if you're saving all of your post's content to custom fields via ACF or another solution and surfacing that content via PHP in a template, the plugin has no way to see that content and therefore can't process anything for the article body. You will need to implement a filter to populate the content yourself so the plugin can parse the HTML. I would recommend looking at `apple_news_exporter_content`: https://github.com/alleyinteractive/apple-news/wiki/Action-and-Filter-Hooks#adminapple-actionsindexclass-exportphp-1
