### ISSUE TITLE
Unable to fetch a list of sections

### ISSUE THREAD

**Issue by Matovsky** [alleyinteractive/apple-news#609]
Before Gutenberg everything was good. I even reinstalled this plugin. API keys correct. But anyway can’t see sections when I’m editing my post. There “Unable to fetch a list of sections“. Same error when I open “Apple News > Sections”.

**Comment by kevinfodness** [comment]
This is most likely due to the date/time of your webserver being different than Apple's systems. We added an error message specific to this issue in the most recent version of the plugin (2.1.0), released today.

**Comment by andrewstaffell** [comment]
Hi, we are having this issue. Under Apple News > Sections it says `Unable to fetch a list of sections.` In the editor under the Apple News toolbar > Sections it just shows the spinner forever. More seriously, occasionally it's throwing an error that breaks the editor, the dreaded `The editor has encountered an unexpected error`. Doing `Copy Error` has a stack trace to
`/wp-content/plugins/publish-to-apple-news/build/pluginSidebar.js`.

I've tried changing the WP timezone, to no avail. If there are specific requirements about the server timezone, what are they exactly?

Anything else we can do to debug/fix this?

**Comment by kevinfodness** [comment]
Timezone is unrelated - the request converts the time to UTC first, so the time can be in any timezone. The important thing is that it's correctly synchronized with a time server. If, for example, your server is in EDT and you check the time on the server and what the server reports is more than about a minute off of what it should be, that will cause the API requests to fail in this way. You can also get errors with fetching a list of sections if your API credentials are incorrect, so please double check those also.

Can you copy the specific error message you are getting in the console for `pluginSidebar.js`?

**Comment by andrewstaffell** [comment]
Thanks for the quick response. Maybe it is an API credentials issue, I've just tested the .papi file with the command in Apple's own instructions (`papi-client channel get`) and it's saying `No value provided for required option '--endpoint'`, but the .papi file starts:
```
# Forkast
endpoint: https://news-api.apple.com
[...]
```

**Comment by kevinfodness** [comment]
There is a bug in version 2.2.0 where if fields in your `.papi` file contain special characters like a `/` or a `+` it can interfere with the parsing. I should have a fix out within the next day or so.

**Comment by andrewstaffell** [comment]
OK – is there any other possible endpoint than `https://news-api.apple.com`?

I've just realised that the gem expects the `.papi` file to be in the user home directory, and now that I've put it there I'm getting an error that says: ```key not found: :ciphers (KeyError)``` – does that make any sense to you?

Thanks a lot!

**Comment by kevinfodness** [comment]
Sorry, I should have read your message more closely - you're saying that trying it via the command-line is _also_ giving you an issue. Yes, you will need to ensure that the command line is able to connect before trying to add your `.papi` file to your WordPress site. There is no other endpoint - that's the same one I have in my file. My file looks like this (actual values redacted):

```
#Kevin Alley Test
endpoint: https://news-api.apple.com
channel_id: channel-id-goes-here
key: key-goes-here
secret: secret-goes-here
```

**Comment by kevinfodness** [comment]
My guess about the `key not found` error is that there's a problem with the way your `.papi` file is formatted - use mine as a reference.

**Comment by andrewstaffell** [comment]
Hmm. Thanks. I've just redone the `.papi` file using yours as a template and still getting that same error, strangely.

**Comment by kevinfodness** [comment]
Did you follow all of the instructions in Apple's README that came with the CLI tool about how to set it up? It requires the latest version of Xcode, command line tools, etc. I was having trouble as well until I ensured that everything was up-to-date.

The versions I have, which worked correctly:

macOS 11.5
Xcode 12.5.1
Xcode Command Line Tools (from a terminal, run `xcode-select --install`)
Ruby 2.6.3p62

**Comment by andrewstaffell** [comment]
I couldn't get the local script to run but with the latest plugin update it was pulling the list of sections correctly. 

However my colleague has just reported another error that crashes WP and stops him from accessing the editor. 

```
Error code: TypeError: Cannot read property 'apple_news_api_created_at' of undefined 
at render (https://forkast.news/wp-content/plugins/publish-to-apple-news/build/pluginSidebar.js?ver=399a6e300bdaabf151f1faecd2cfb13e:1:34739)
```

Any idea what causes that and how to remedy?

**Comment by kevinfodness** [comment]
What version of WordPress are you running?

**Comment by andrewstaffell** [comment]
5.8

**Comment by kevinfodness** [comment]
Thanks - I wasn't seeing this in my tests, and I'm also running 5.8, but I'll dig in further to see if I can figure out what's going on.

**Comment by kevinfodness** [comment]
OK, I might have a lead on this - the Apple News plugin needs to be able to read and write postmeta, and if this is a custom post type that was registered without support for `custom-fields` I could see how that error could occur. The only other explanation I have is if an early version of Gutenberg was in use that doesn't have support for some of the hooks we're using to interact with postmeta. I'm assuming that both you and your colleague are accessing the same WordPress instance - is that true? Can you reproduce the error yourself?

**Comment by andrewstaffell** [comment]
It does only seem to happen on custom post types, but adding `custom-fields` to the `supports` attribute at registration doesn't seem to fix it.

Still getting:

```
TypeError: Cannot read properties of undefined (reading 'apple_news_api_created_at')
at render
(/wp-content/plugins/publish-to-apple-news/build/pluginSidebar.js?ver=399a6e300bdaabf151f1faecd2cfb13e:2:34671)
```

**Comment by kevinfodness** [comment]
That's really strange - the `useEntityProp` hook is available in WordPress 5.8 and as long as `custom-fields` are supported for a custom post type, that hook shouldn't be returning `undefined`. I've got an issue open here to track progress on a graceful fallback: #884 Can we move further discussion there?

**Comment by bcpatters** [comment]
Do you have to have Wordpress 5.8 for the latest plugin 2.2.2 to work?  I'm on 5.6.4 rn.

I'm also not a coder so am having trouble creating an appropriate .papi file that I can just upload to the plugin - my channel is already approved but this so far is much more cumbersome in the past!  Sigh

**Comment by kevinfodness** [comment]
I noticed that you created a new issue, so I'll move the discussion to #885

**Comment by banago** [comment]
Just bumped on the same error on two different sites. Both are on the lastest WP and plugin versions. This seems to be JavaScript issue. See image below:

![js-error](https://user-images.githubusercontent.com/339914/134318852-4a3343a7-cec8-4f87-84dc-5d5f605d7260.png)

I hope this helps.

**Comment by kevinfodness** [comment]
@banago since this issue is closed, can you please open a new issue with this information?
