### ISSUE TITLE
API: FORBIDDEN error intermittently 

### ISSUE THREAD

**Issue by nate-allen** [alleyinteractive/apple-news#610]
We are randomly getting an "API: FORBIDDEN" error. We checked the API key, secret, and channel id. Everything is correct, and it only happens sometimes.

Any idea what would cause it? We're currently on version 1.3.0.

**Comment by sdkjambo** [comment]
Same here.  Around 50% of articles publish OK, 30% are FORBIDDEN and the rest "NOT_FOUND (keyPath articleId)".  Presumably that behaviour rules out typos in the credentials.

We have enabled admin debug email, though seemingly only successfully published articles generate an email.  But that aside, is there a checklist to run through for such issues?  For example, what permissions authors must have, removing blank spaces at end of articles, removing special characters from the post text, etc?

**Comment by kevinfodness** [comment]
Do you get any additional details on the FORBIDDEN error?

Apple's API servers are very strict about timestamps, so make sure your server is up-to-date via a reliable time server.

**Comment by sdkjambo** [comment]
I can switch debug emails back on, but the timestamp being an issue for us would make sense.  From 27 Jun onwards all published articles have a status of LIVE.  This coincides with us switching off updates to Apple News when posts are merely updated, as opposed to published new.

Prior to this date the FORBIDDEN and NOT_FOUND posts are only those with older "Last Updated At" dates than the date on which they were actually last updated, i.e. a post created and published to Apple News on 01 Jun is fine, no issues; a post created on 01 Feb (before plugin installed) and updated on 01 Jul shows as FORBIDDEN or NOT_FOUND and with a 'Last updated at date' of 01 Feb.

**Comment by kevinfodness** [comment]
The most recent version of the plugin (2.1.0) has additional error messaging around the dates being different error in particular.
