### ISSUE TITLE
Unicode Character Support

### ISSUE THREAD

**Issue by bcampeau** [alleyinteractive/apple-news#615]
Ensure that all unicode characters are effectively supported by the plugin.

**Comment by atoupet-toki** [comment]
Seems we got an error when content contains a '**à**'. Do you have any clue ??
Even our functions:
`function configure_apple_content( $content ) {
    $content = str_replace("à", "\u00e0", $content);
    return $content;
}
add_filter( 'apple_news_exporter_content_pre', 'configure_apple_content', 10, 2);`

returns : `des plus vieux \u00e9lixirs reconnus u00e0 ce jour!`
 ->Missing the `\`

All specials characters are encoded except '**à**'

Thanks a lot!!!!

**Comment by bcampeau** [comment]
French is not currently officially supported by Apple News, but we will be looking into this as part of this enhancement to the next version.

**Comment by atoupet-toki** [comment]
Thanks for your quick answer !! Can wait it'll be compatible :)

**Comment by amooreTO** [comment]
Now that Apple News is available in Canada, and French is supported by Apple News, one of the French publications I work with is experiencing the issue where `à` is being displayed as `?`.

Is there a target date for 2.0.0?
