### ISSUE TITLE
There has been an error with the API: FAILED_TO_PARSE_IMAGE - Failed to parse image with URI [https://platform.twitter.com/widgets.js]

### ISSUE THREAD

**Issue by talkingbaws** [alleyinteractive/apple-news#617]
Hello,

Just wondering if there's any help I could get on this please after installing the app and trying to publish for the first time?

Thanks,

Jonny

**Comment by kevinfodness** [comment]
This should be fixed in the most recent version, as the code for identifying image sources is now less greedy.
