### ISSUE TITLE
Multiple issues when posting from WP using the plugin

### ISSUE THREAD

**Issue by channeld** [alleyinteractive/apple-news#619]
Hi.
Credentials are fine.
When publishing from WP, I get different errors but not in all posts.
Error types are:

1. There has been an error with the API: NOT_FOUND (keyPath articleId)
2. The following components are unsupported by Apple News and were removed:
div
strong
div
<span>

Any ideas or specific instructions on what to avoid/implement in post content?

**Comment by dobstotev** [comment]
I get the same! I did the mistake of pushing through to Apple News all my articles without knowing that Apple News my reject them (for what ever reasons). Then I set up a new channel, and created a few articles manually to get approved and now i want to push my articles from the CMS but i get this:

NOT_FOUND (keyPath articleId)

As in my list of articles are stuck in some sort of mode and I cant refresh them with the current status based on the new channel (as in the new channel they were never published). Any ideas how to reset the status of the articles? I tried deleting the plug in and then reinstalling it again but it seems it has kept the settings in the database.

**Comment by kevinfodness** [comment]
Yes, it does keep the settings in the database. We just released version 2 of the plugin, and if you have the new block editor active (which ships by default in WordPress 5 and is codenamed "Gutenberg") you will now get a "Delete" button that should allow you to delete the article metadata. It may return an error when attempting to delete an article from Apple News via the API that doesn't exist, but it will also delete the database entries locally that point to that article.
