### ISSUE TITLE
WP Multisite Switch API using switch_to_blog

### ISSUE THREAD

**Issue by anagarajah** [alleyinteractive/apple-news#621]
We have a cross posting functionality within our multisite environment, In the following scenario while we do crosspost during "save_post" hook  the API seems to be not switching. Do you guys have a switch API function to cater this scenario?

Blog A:
- { Post ABC } published successfully 
- Apple API Push: { Post ABC } // published successfully

Blog B:
- { Post ABC } Crosspost from Blog A, published successfully
- Apple API Push: { Post ABC } // API Error

**Comment by kevinfodness** [comment]
We don't - I'll mark this as an enhancement.

**Comment by kevinfodness** [comment]
This is actually an issue with syndication copying over Publish to Apple News postmeta. You should exclude Publish to Apple News postmeta from being syndicated when using whatever syndication/distribution plugin you're using to copy content from one place to the other.
