### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by iamkingsleyf** [alleyinteractive/apple-news#626]
Hello;

Guys i kinda have suggestions and i don't know if it can make it to the next release... or if it will be considered at all.

1. I don't know if Apple allows bulk delete just like wordpress normal post, this should be considered.

2. When you checked the PUBLISHED status from the plugin in your dashboard it shows X amounts on Apple news but not X amount is on apple news because some throw in errors and was not pushed to apple news, hopefully there will be a way to filter these errors and display only successful articles that are available on Apple news. see https://imgur.com/a/EYXFydp

Thanks

**Comment by kevinfodness** [comment]
I'll mark these as enhancements for a future version.

**Comment by kevinfodness** [comment]
If you have auto-delete enabled, deleting the WP posts will also delete from Apple News. If you bulk delete posts in WP, it will also bulk delete from Apple News. We don't plan on adding an option to bulk delete from Apple News only while leaving the post published in WP.

There are filters on the Articles screen in Publish to Apple News that let you filter by status (published, not published, etc) - select the one you want and hit Filter and it will show you the proper status.

**Comment by iamkingsleyf** [comment]
Nice... will be returning to apple news as well.
