### ISSUE TITLE
Errors after update today

### ISSUE THREAD

**Issue by chuckmacak** [alleyinteractive/apple-news#630]
I just installed the latest update to the plugin and now I am recieving the errors below.

There has been an error with the API:
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->3->components->2->text)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->3->components->5->text)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->3->components->8->text)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->3->components->11->text)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->3->components->17->text)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->3->components->20->text)

**Comment by jwheck** [comment]
I am seeing the same thing after trying to publish a post to Apple News. 
Steps to reproduce: 
Go to Articles under Apple News plugin page.
Click "Publish" for an unpublished article.

**Comment by drcynthiaj** [comment]
Did anyone get any answers for this problem?

**Comment by lobin21** [comment]
See this for temporary solution:
[https://github.com/alleyinteractive/apple-news/issues/635](url)

**Comment by kevinfodness** [comment]
Does this have to do with `&nbsp;` entities? Can you try switching your output format to HTML?

**Comment by kevinfodness** [comment]
We just released v2 of the plugin. Can you confirm whether this is still an issue on the latest version?

**Comment by kevinfodness** [comment]
Consolidating discussion of this issue in #707
