### ISSUE TITLE
Fatal error: Uncaught Error: - Post Wordpress Update

### ISSUE THREAD

**Issue by thisisdrive** [alleyinteractive/apple-news#632]
I'm getting the below error after the update, please advise. 

Fatal error: Uncaught Error: Call to a member function can_be_anchor_target() on null in /home4/waiwb40afmbg/public_html/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php:105 Stack trace: #0 /home4/waiwb40afmbg/public_html/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php(733): Apple_Exporter\Builders\Components->add_pullquote_if_needed(Array) #1 /home4/waiwb40afmbg/public_html/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php(41): Apple_Exporter\Builders\Components->split_into_components() #2 /home4/waiwb40afmbg/public_html/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-builder.php(66): Apple_Exporter\Builders\Components->build() #3 /home4/waiwb40afmbg/public_html/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/class-exporter.php(216): Apple_Exporter\Builders\Builder->to_array() #4 /home4/waiwb40afmbg/public_html/wp-content/plugins/publish in /home4/waiwb40afmbg/public_html/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php on line 105
The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.

**Comment by kevinfodness** [comment]
Are you using the new block editor (Gutenberg)? We are adding full support for Gutenberg in v2, which should be shipping in the next few weeks.

**Comment by kevinfodness** [comment]
v2 is now out. Can you let me know if you still experience this issue on the new version?
