### ISSUE TITLE
Article without text because use wp tabs

### ISSUE THREAD

**Issue by inforfacildev** [alleyinteractive/apple-news#633]
Hello,
I need your help, because in our website we use wp tabs in posts and plugin doesn't import text from body.
Can you help us?
Thanks!

**Comment by kevinfodness** [comment]
Yep, you'll need to filter the content that the plugin sees to import the content from your custom fields. This filter gets called, which you can hook into and modify the content before Apple News looks at it for parsing:

`apply_filters( 'apple_news_exporter_content_pre', $post->post_content, $post->ID )`
