### ISSUE TITLE
&nbsp; causes API: INVALID_DOCUMENT

### ISSUE THREAD

**Issue by rnbronstein** [alleyinteractive/apple-news#635]
A Tiny MCE "quirk" causes `&nbsp;` entities to get added to the editor when the user switches between the Visual and Text editors. This causes blank paragraphs to be inserted in the JSON export for Apple News, which throws this error: `API: INVALID_DOCUMENT - "text" was "" should be not (null or an empty string)`.

I see that the blank element issue was marked as fixed in 1.4, but inspecting the JSON of the articles with this issue I can see that there are still elements like this:
```json
{
    "role": "body",
    "text": "<p> <\/p>",
    "format": "html",
    "textStyle": "default-body",
    "layout": "body-layout"
}
```

**Comment by lobin21** [comment]
Hi. I can confirm that. Removing `&nbsp;` will make the API to accept the request.

**Comment by kevinfodness** [comment]
We made some changes to the way encoding is handled in the in-development version of v2, so I'd be interested to see if this is fixed on the latest `master` branch (or when v2 officially ships).

**Comment by kevinfodness** [comment]
Version 2 is now out. Can you let me know if you continue to experience this behavior?

**Comment by joshdvx** [comment]
@kevinfodness Version 2 still does it for me. If final line is still "&nbsp;" I get the API error.

**Comment by kevinfodness** [comment]
Consolidating discussion of this issue on #707.
