### ISSUE TITLE
FAILED_TO_PARSE_IMAGE on embeds when using block editor

### ISSUE THREAD

**Issue by vincepettit** [alleyinteractive/apple-news#639]
Since switching to Wordpress block editor any articles that contain a YouTube embed give me an error message and won't publish.

Here is an example:

There has been an error with the API: FAILED_TO_PARSE_IMAGE - Failed to parse image with URI [https://www.youtube.com/embed/QC1x4uFZGGU?feature=oembed].

**Comment by mcgujohn** [comment]
This is also occurring with other embeds like Twitter, Reddit, Instagram etc.

There has been an error with the API: FAILED_TO_PARSE_IMAGE - Failed to parse image with URI [https://platform.twitter.com/widgets.js].

There has been an error with the API: FAILED_TO_PARSE_IMAGE - Failed to parse image with URI [https://www.redditstatic.com/comment-embed.js].

**Comment by vincepettit** [comment]
I'm seeing that too with other embeds, hadn't realised at the time:

<img width="1280" alt="Screenshot 2019-07-08 at 12 41 30" src="https://user-images.githubusercontent.com/530457/60807510-cf280080-a17d-11e9-9189-f72157448af0.png">

Frustrating as the error is stopping the content from being pushed on to Apple news

**Comment by kevinfodness** [comment]
Yep, we're working on Gutenberg support as part of v2 of the plugin, so this is a known issue. v2 should be out in the next few weeks.
