### ISSUE TITLE
No spec updates were found for Embed_Web_Video

### ISSUE THREAD

**Issue by gradywoodruff** [alleyinteractive/apple-news#640]
I'm getting a message that says "No spec updates were found for Embed_Web_Video" when I try to add theee Embeed Web Video component
![image](https://user-images.githubusercontent.com/748199/58835078-f3466e00-8622-11e9-90a5-ff79a8e5704d.png)

I selected the theme (not shown in screenshot), chose the component "Embed Web Video" and this is what the JSON looks like. 
![image](https://user-images.githubusercontent.com/748199/58835100-03f6e400-8623-11e9-96cf-3187ca5261cb.png)

When I hit "Save JSON" I get the error above

**Comment by kevinfodness** [comment]
The JSON you have in your screenshot looks like the default JSON for that component, so the error message makes sense - there is no configuration to update. What do you mean by "when I try to add the Embed Web Video component?" I'm wondering if you're trying to do something differently than how the plugin is designed to work.
