### ISSUE TITLE
Changes to Theme: Does it require all existing posts to be updated?

### ISSUE THREAD

**Issue by ryanrbftp** [alleyinteractive/apple-news#642]
Hi there,

We have made some changes to the default theme.

We have over 600 existing articles on Apple News. However, we have noticed that the theme changes are not reflected in the live News app for existing articles – they are only reflected when we update the post.

Do we have to force an update for each post to reflect the theme changes? How can we do this in bulk? We tried to force updated by visiting the plugin page and choosing the bulk action “publish” but we get the following, “Skipped push of article 9367 because it is already in sync.” etc.

Is there a way to FORCE an update in bulk?

Thank you for your help!

**Comment by ryanrbftp** [comment]
This was also posted here but we did not receive a response:
https://wordpress.org/support/topic/changes-to-theme-does-it-require-all-existing-posts-to-be-updated/

Happy to pay $ for support.

**Comment by ryanrbftp** [comment]
Never mind, just removing the catch did the trick

`	// Ignore if the post is already in sync.
		// if ( $this->is_post_in_sync() ) {
		// 	throw new \Apple_Actions\Action_Exception(
		// 		sprintf(
		// 			// Translators: Placeholder is a post ID.
		// 			__( 'Skipped push of article %d because it is already in sync.', 'apple-news' ),
		// 			$this->id
		// 		)
		// 	);
		// }`

**Comment by kevinfodness** [comment]
Yes, it is correct that you will need to update posts for changes to take effect on Apple. Articles, including layout and style options from themes, are bundled with the article JSON, which is only sent during a publish or update action. Making changes to the plugin's configuration, including themes, only apply to articles that are published or updated after the change is made.
