### ISSUE TITLE
Apple News cover art won't appear

### ISSUE THREAD

**Issue by ricksmoss** [alleyinteractive/apple-news#644]
The cover art images we've uploaded for our articles are not appearing on our Apple News articles; instead, the app is defaulting to the featured images we have in our WP articles. In the Apple News plugin settings, we have "yes" chosen for "Use Cover Art?" and we are uploading one of the correct sizes for each story (632x474) in the post's meta box. Any suggestions?

![cover-art-screen-shot](https://user-images.githubusercontent.com/51969405/59710156-6b419600-91d6-11e9-87e0-8135b5269420.jpg)

**Comment by kevinfodness** [comment]
Cover Art is only used if your story is featured, which requires some level of approval/curation from Apple. Otherwise, the featured image is used.
