### ISSUE TITLE
AdvertisingSettings is Deprecated

### ISSUE THREAD

**Issue by johnnyshankman** [alleyinteractive/apple-news#646]
The `AdvertisingSettings ` property of the apple news document is deprecated, and should be swapped out for an implementation of `AdvertisementAutoPlacement` instead.

https://developer.apple.com/documentation/apple_news/advertisingsettings
https://developer.apple.com/documentation/apple_news/advertisementautoplacement

**Comment by hrkhal** [comment]
AdvertisingSettings is only deprecated in version 1.9 of the Apple News API. This plugin uses 1.7 currently.

**Comment by kevinfodness** [comment]
I've marked this as an enhancement for inclusion in a future version of the plugin.

**Comment by kevinfodness** [comment]
This has been replaced with the new setting in the new version of the plugin, out today (2.1.0).
