### ISSUE TITLE
Inconsistent Publishing 

### ISSUE THREAD

**Issue by mglyanes** [alleyinteractive/apple-news#649]
Some posts don’t go through to AppleNews and keep being marked as ‘Pending’ in article list, or ‘Not published’ 
->This happens frequently on productions site and very rarely from dev site

What we troubleshoot it: 
-After the article is pushed to AppleNews and does not publish, we run this action a 2nd time. After 2nd attempt, the article sometimes publishes and sometimes does not. 
-There were cases when article would not be sent to AppleNews when it’s published but would be sent when it’s edited a minute later. 
-Some articles never get published on AppleNews (no JSON errors) even after many attempts and edits.

**Comment by dartiss** [comment]
As discussed with @kevinfodness, this is an issue being reported by a VIP client.

**Comment by dartiss** [comment]
This may be fixed by #607

**Comment by kevinfodness** [comment]
A few things to try:

* Set Remote Images to Yes, if it isn't already. If you are not using this setting, then the publish action involves uploading images to Apple, which can time out.
* Set Asynchronous Publishing to No if it isn't already. Combined with the setting above, you should get immediate feedback about whether an article publishes or not, as the publish action happens at the time you publish or update the article, versus being deferred to the cron/jobs system.

**Comment by kseniaglobalnews** [comment]
- Remote Images are already set to Yes
- We can't set Asynchronous Publishing to No because it may slow down or crash the post editor in case publishing to apple news fails or times out

**Comment by kevinfodness** [comment]
Async publishing was created to be used in concert with bundled images, where transferring the content over the wire would take a long time, and would potentially time out during publish. If you have remote images already set to yes, then the amount of time to send the article to Apple should be negligible, and we're using requests with a short timeout to prevent lockups during publish. I would strongly advise turning off async publishing to see if articles publish consistently.
