### ISSUE TITLE
Inconsistent Updating 

### ISSUE THREAD

**Issue by mglyanes** [alleyinteractive/apple-news#650]
Some updates are not set to AppleNews (no JSON errors) 
->Sometimes after making minor change in article and re-saving it the update goes through, other times it never updates after multiple attempts. Some updates are picked up immediately.

**Comment by dartiss** [comment]
As discussed with @kevinfodness, this is an issue being reported by a VIP client.

**Comment by kevinfodness** [comment]
This is likely related to #649 - please try the suggestions there and let me know if you see an improvement.

**Comment by kevinfodness** [comment]
Closing in favor of #649.
