### ISSUE TITLE
How do I add link to my website at the end of the Apple News article. 

### ISSUE THREAD

**Issue by g2311** [alleyinteractive/apple-news#653]
I would like add a link at the end of every article on Apple News so that readers can visit my site. How do I do that. I have attached a sample that I found on Apple News. 
<img width="324" alt="Screen Shot 2019-07-31 at 2 05 16 AM" src="https://user-images.githubusercontent.com/53513992/62199438-5a895180-b338-11e9-8e66-a80bc6c45437.png">

**Comment by TejasGajjar** [comment]
Did you got the solution for this @g2311 ?

**Comment by kevinfodness** [comment]
Version 2.1.0 of Publish to Apple News, which will be releasing soon, contains a new End of Article module that allows you to insert custom content at the end of your article using the Customize JSON feature. The customizations are per-theme.
