### ISSUE TITLE
Using add_filter() to pass value to the Apple News caption component

### ISSUE THREAD

**Issue by jmabel** [alleyinteractive/apple-news#655]
Hi, I would like to use add_filter() to pass the image credit text to the Apple News caption component, since we are not using the WP caption field for our image credit but this plugin “Better Image Credit plugin” so Apple News doesn’t see the credit for the image.

I would like to try passing the image credit value to Apple News caption component before Apple News Exporter is initialized using add_filter()!

But I don’t know what filter to use to access the caption component so I can pass it a value

I was looking at the different filter hooks and not sure what to use I was looking at this two apple_news_exporter_post_thumb, apple_news_register_component but not even sure they are the right one and if they are I don’t know what caption component variable name I should target to pass my value!

Would it be possible to point me to the right direction, and how to go about implementing it?

Thank you for the help.

**Comment by kevinfodness** [comment]
In the latest version, there is a filter called `apple_news_exporter_cover_caption`, which allows you to filter the caption for the cover image. For regular images, you can filter the JSON that is generated via `apple_news_image_json`, or you can insert the caption yourself using `apple_news_exporter_content`. If you use the same format that WordPress would (e.g., a `<figure>` and a `<figcaption>`) then the plugin will pick it up automatically.
