### ISSUE TITLE
Story Not Appearing in Apple News

### ISSUE THREAD

**Issue by GlueDigiStu** [alleyinteractive/apple-news#658]
I am using V1.4.4 of Publish to Apple News and v 5.2.2 of Wordpress.

On my posts page, I can see that the post is live on Apple News and get a link (i.e. https://apple.news/A8evRyJ-sTc--Ni00pmjFVQ) however when I visit the link it just says "Sorry, this story isn’t available in Apple News." with no information on what the error might be.

I have checked the JSON which is submitted for that particular article and there are no errors in there.

When publishing posts I sometimes see warn error messages about certain elements not being supported by apple news (<br> for example), although these don't appear all of time - and trying to republish an article doesn't make them appear so I can't drill down into the issue in any more detail.

Has anyone had a similar issue and could point me in the direction of a fix?

**Comment by kevinfodness** [comment]
Unfortunately, you'll need to follow up with Apple support about this - if the plugin is saying that it's live on Apple News, then that's what the Apple News API is reporting back to the plugin, so any misbehavior upstream would need to be investigated by Apple's team.
