### ISSUE TITLE
Error when posting from WP to apple news

### ISSUE THREAD

**Issue by estrahley** [alleyinteractive/apple-news#660]
I get this error when trying to post any article from my apple news plugin:

"The following components are unsupported by Apple News and prevented publishing:
div
div
div"

I don't know anything about coding or how to fix this. Any advice is appreciated.

Thanks!

**Comment by kevinfodness** [comment]
Can you try again with the most recent version of the plugin? It's likely that you have some HTML in your content that the plugin can't parse, and we've made some improvements to HTML handling in the most recent version. Also, can you ensure that the HTML support option is set to `yes` in plugin settings?
