### ISSUE TITLE
cURL error 56: SSLRead() return error -9806

### ISSUE THREAD

**Issue by tromano32** [alleyinteractive/apple-news#664]
can anyone help with publishing to apple news with this error code 

cURL error 56: SSLRead() return error -9806

wp5.2.2

**Comment by jomurgel** [comment]
This tends to happen when the version of SSL that comes with your version of cURL isn't compatible with, in this case, Apple's. 

I'd suggest taking a look at https://stackoverflow.com/questions/26461966/osx-10-10-curl-post-to-https-url-gives-sslread-error/26538127#26538127 to see if that resolves your issue.
