### ISSUE TITLE
The following components are unsupported by Apple News and were removed:

### ISSUE THREAD

**Issue by showbizmjr** [alleyinteractive/apple-news#665]
I am receiving this message on every post, please help.  

The following components are unsupported by Apple News and were removed:
a
div
a
div
div
a
a
div
strong
strong
div
a
div
strong
strong
div
a
div

**Comment by jomurgel** [comment]
Can you provide more information about the circumstances under which you see this message? When creating a post? When exporting a post? When publishing a post? etc.

Any additional information would be helpful: screenshots, log errors, etc.
