### ISSUE TITLE
Posting articles with embedded audio file

### ISSUE THREAD

**Issue by BruceInLouisville** [alleyinteractive/apple-news#667]
Hello! The plug-in works great for us, except for one problem.

We have posts with embedded podcasts, using either the player from LibSyn or from Podbean. In either case, the post publishes just fine, but the audio player gets eliminated. (In other words, on Apple News all you see is the text from the post.)

We've stopped publishing these podcast posts to Apple News, but would like to resume if there is a way to do it. I don't mind editing the posts directly in News Publisher if needed. Can you tell me a way to embed either or both of these audio players into an Apple News post?

**Comment by kevinfodness** [comment]
Hey @BruceInLouisville , thanks for using the plugin! We don't have native support for LibSyn or Podbean, but could look into whether there is a way to add support for the embeds if it's straightforward. For now, you could avail yourself of one of our hooks to either transform the embed into a format that the plugin can digest, or to remove them, such as `apple_news_exporter_content`: https://github.com/alleyinteractive/apple-news/wiki/Action-and-Filter-Hooks#adminapple-actionsindexclass-exportphp-1
