### ISSUE TITLE
BUG: 2.0.x Plugin no longer supports WP 4.9.x

### ISSUE THREAD

**Issue by pblasco** [alleyinteractive/apple-news#670]
On Wordpress 4.9.x, when using 2.0.1 of the plugin we are seeing the following error when navigating to Posts:

`Fatal error: Uncaught Error: Call to undefined function use_block_editor_for_post() in /var/www/html/sites/wirecutter/htdocs/wp-content/plugins/apple-news/includes/class-apple-news.php:228 Stack trace: #0 /var/www/html/sites/wirecutter/htdocs/wp-includes/class-wp-hook.php(286): Apple_News->action_admin_enqueue_scripts('edit.php') #1 /var/www/html/sites/wirecutter/htdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /var/www/html/sites/wirecutter/htdocs/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /var/www/html/sites/wirecutter/htdocs/wp-admin/admin-header.php(97): do_action('admin_enqueue_s...', 'edit.php') #4 /var/www/html/sites/wirecutter/htdocs/wp-admin/edit.php(303): require_once('/var/www/html/s...') #5 {main} thrown in /var/www/html/sites/wirecutter/htdocs/wp-content/plugins/apple-news/includes/class-apple-news.php on line 228`

`use_block_editor_for_post()` was added in WP 5.0.0

Was WP 4.9.x support supposed to be dropped in 2.0 or is this a bug?

**Comment by jomurgel** [comment]
@pblasco thanks for using our plugin! We did not intentionally remove support for an older version of WordPress and have a fix in place for an upcoming 2.0.2 release.

**Comment by kevinfodness** [comment]
Hi @pblasco - 

We just release v2.0.2 of the plugin, which should solve this issue. I did a manual test myself on the latest version of the 4.9 branch to confirm it was working before releasing. If you notice any additional issues on the new version, please let me know.
