### ISSUE TITLE
Section to Category mapping ignoring child categories (BUG?) 

### ISSUE THREAD

**Issue by kujain** [alleyinteractive/apple-news#671]
The Apple News Sections to WP category Mappings allows us to map a single WP category with an Apple News Section. However, this mapping seems to igmore a post assigned to a category that's a child of the mapped section eg.
I have mapped AN Culture to Arts & Entertainment WP category:
![image](https://user-images.githubusercontent.com/120631/64797507-7eeb6700-d54f-11e9-9d54-8f0a832c37e4.png)

Arts & Entertainment has subcategories and if a post has been assigned one of these, it gets assigned Main instead of Culture:
![image](https://user-images.githubusercontent.com/120631/64797638-b22df600-d54f-11e9-8136-81f916fe2a5a.png)

If this is by design, is there a filter I could use to adjust the assigned section before the auto(or manual) push to AN occurs?

I could manually add all child in the mapping, but considering there are about 50 subcategories, and that if anything structure changes, this would have to be manually handled, it can be a pain.
 
plugin v2.0.1
wp v5.1.2

**Comment by kevinfodness** [comment]
We will investigate subcategory mappings in a future version. Meanwhile, you can use the `apple_news_generate_json` filter to modify any aspect of the final JSON output prior to push: https://github.com/alleyinteractive/apple-news/wiki/Action-and-Filter-Hooks#includesapple-exporterclass-exporterphp

**Comment by kevinfodness** [comment]
We're going to leave this as-is. However, with the new Automation feature, you can specify multiple categories when mapping sections, and you could select the parent category and all child categories if you chose. If you want the behavior to be fully automatic, it would need to be done via filter.
