### ISSUE TITLE
INVALID_DOCUMENT – “text” was “” should be not (null or an empty string)

### ISSUE THREAD

**Issue by jomurgel** [alleyinteractive/apple-news#674]
Quite a few of my blog’s articles are not publishing to Apple News. The error for the link I have added above for ‘best spa breaks in Yorkshire’ was:

```
INVALID_DOCUMENT – “text” was “” should be not (null or an empty string) (keyPath components->1->components->6->text)
INVALID_DOCUMENT – “text” was “” should be not (null or an empty string) (keyPath components->1->components->36->text)
INVALID_DOCUMENT – “text” was “” should be not (null or an empty string) (keyPath components->1->components->58->text)
INVALID_DOCUMENT – “text” was “” should be not (null or an empty string) (keyPath components->1->components->81->text)
```

Any help much appreciated to help resolve this.

The page I need help with: https://yorkshirefoodguide.co.uk/blog/spa-breaks-yorkshire/

Via: https://wordpress.org/support/topic/invalid_document-text-was-should-be-not-null-or-an-empty-string-2/

**Comment by jomurgel** [comment]
It seems it does not like blank lines at the end of articles
(seen as '&nbsp;' in text mode).

Also previously had problems with other unusual characters that are not in the standard range – like you might find in french etc.

**Comment by jomurgel** [comment]
I can confirm this issue in the Classic editor by default, or in Gutenberg, if manually appended in the Code editor view.

**Comment by kevinfodness** [comment]
Consolidating discussion of this issue in #707
