### ISSUE TITLE
How can I add link to my website at the end of the Apple News article ?

### ISSUE THREAD

**Issue by TejasGajjar** [alleyinteractive/apple-news#679]
I would like to add a link at the end of every article on Apple News so that readers can visit my site. How can I do that?

**Comment by micahwave** [comment]
You can use the `apple_news_get_json` filter to modify the JSON to add a https://developer.apple.com/documentation/apple_news/body component.

**Comment by kevinfodness** [comment]
Thanks, @micahwave !
