### ISSUE TITLE
Articles with  image filenames with diacritics not uploading

### ISSUE THREAD

**Issue by vincepettit** [alleyinteractive/apple-news#683]
Not sure if this is Apple not letting the files upload or something to do with the plugin, but if there is an article with a letter that has a diacritic on a letter it doesn't work and I get the following message:

THERE HAS BEEN AN ERROR WITH THE API: INVALID_DOCUMENT - THE VALUE FOR THE PROPERTY "URL" AT LINE 1 AND COLUMN 402 IS NOT VALID: HTTPS://WWW.THECHECKEREDFLAG.CO.UK/WP-CONTENT/UPLOADS/2019/09/NICO-HÜLKENBERG-RENAULT-F1-TEAM-2019-FORMULA-1-ITALIAN-GRAND-PRIX-AUTODROMO-NAZIONALE-MONZA-DRIVERS-PARADE.JPG (KEYPATH COMPONENTS->0->COMPONENTS->0->URL)

**Comment by kevinfodness** [comment]
Unfortunately, that error message is coming directly from Apple's API. You will need to follow up with them.
