### ISSUE TITLE
Required property 'descriptors' is not provided AND Required property 'records' is not provided

### ISSUE THREAD

**Issue by prathimeshbpd** [alleyinteractive/apple-news#685]
There has been an error with the API:
INVALID_DOCUMENT - Cannot be empty. (keyPath components->4->data->descriptors)
INVALID_DOCUMENT - Required property 'descriptors' is not provided. (keyPath components->4->data->descriptors)

There has been an error with the API:
INVALID_DOCUMENT - Cannot be empty. (keyPath components->3->data->descriptors)
INVALID_DOCUMENT - Required property 'descriptors' is not provided. (keyPath components->3->data->descriptors)
INVALID_DOCUMENT - Required property 'records' is not provided. (keyPath components->3->data->records)

**Comment by kevinfodness** [comment]
Hi @prathimeshbpd —

Can you please follow the instructions here: https://github.com/alleyinteractive/apple-news/wiki/usage#getting-help

This will help us attempt to reproduce the issue you are seeing. Also, are you using Gutenberg or the classic editor?
