### ISSUE TITLE
remove div with id from Apple News

### ISSUE THREAD

**Issue by digibobdeluxe** [alleyinteractive/apple-news#686]
If I wanted to remove the entire contents of a div with the id of ‘buy-button’ that is on some of my posts onto Apple News (don’t want any buy buttons on Apple News basically)

Would inserting this line into admin/apple-actions/index/class-export.php work?

private function remove_tags( $html ) {
		$html = preg_replace( '/<style[^>]*>.*?<\/style>/i', '', $html );
		$html = preg_replace('!<div\s+id=“buy-button"\s>.*?</div>!is', '', $html);
		return $html;
	}

Thanks 
Bob

**Comment by digibobdeluxe** [comment]
btw, the reason I am asking is I don't have access to the plugins folder, due to restrictions, so I have to get this right first time with my request for a change! :-)

**Comment by kevinfodness** [comment]
You shouldn't modify the plugin source directly. We have a long list of filters to allow you to modify the behavior of the plugin without modifying plugin source. The most appropriate filter for this is likely `apple_news_exporter_content_pre`: https://github.com/alleyinteractive/apple-news/wiki/Action-and-Filter-Hooks#adminapple-actionsindexclass-exportphp-1

**Comment by digibobdeluxe** [comment]
Thank you, Kevin. Appreciate the answer :-)
