### ISSUE TITLE
Enhancement: Publish / Unpublish from within the post editor

### ISSUE THREAD

**Issue by PypWalters** [alleyinteractive/apple-news#687]
Hi Kevin, I am working with @paulschreiber and a VIP client on an enhancement to the plugin which we would like to submit back as a PR. Before we finish the work and submit the PR I was hoping to collaborate on an approach that will work best, and see if this is a feature you might be interested in including.

My client is very familiar with how Facebook Instant Articles and Amp can manage publishing from within the post edit screen. The feature we are proposing would try to replicate that experience for publishing and unpublishing for apple news.

![Screen Shot 2019-10-17 at 9 52 29 AM](https://user-images.githubusercontent.com/23455618/67015381-72b17700-f0c4-11e9-8386-3b434af1f2ee.png)

If a post is not currently published in WordPress, we would display 2 radio options to enable or disable the publish to apple news on publish and save that setting as post meta. If the setting to automatically publish to apple new is enabled, we can leverage the `apple_news_should_post_autopublish` filter to stop or allow the publish to proceed. 
If the editor has chosen to enable the publish in the post, but the auto publish setting is false, we can handle that with an additional condition to the constructor of the `Admin_Apple_Post_Sync` class and the do_publish function that checks the meta value of the post (set by the radio buttons described above) which will allow the post to still be published. If a post is published or unpublished from the existing plugin screen, we would also need to update this meta field to keep everything running as expected.

![Screen Shot 2019-10-17 at 9 52 40 AM](https://user-images.githubusercontent.com/23455618/67016262-ea33d600-f0c5-11e9-93ed-759f1320a2c9.png)

Once a post is published in WordPress we would switch from radio buttons to actual buttons that would allow the user to publish or unpublish a story via ajax depending on the post's apple news status. We could leverage `wp_ajax_push_post` within the current plugin to publish, and create a new ajax option to delete. 

Initially this would not have Gutenberg support, but that is something we will be adding to our own site in the coming months and could PR that back to you once that is ready as well.

Let me know if this is something you would be interested in incorporating, and if you have any suggestions for how we can make this approach better. Thanks!

**Comment by kevinfodness** [comment]
Thanks @PypWalters - I'll get you a response back on this tomorrow. I was out of the country on vacation until recently and I'm slowly digging myself out!

**Comment by kevinfodness** [comment]
The approach sounds good, although now that we're in v2 territory any updates we make to the plugin need to have support for both the classic editor and Gutenberg. We would, of course, welcome the PR in any case, but if you are not able to provide the Gutenberg end of things we would have to hold on deploying the feature to a new version until we also added the Gutenberg integration.

Sound okay?
