### ISSUE TITLE
apple_news_skip_push Not Working

### ISSUE THREAD

**Issue by bluemonkeydev** [alleyinteractive/apple-news#688]
This worked in the previous version but has been broken for about a month (unsure what release that was, might be 2 version ago.) Any thoughts? Did something change?

The $post_id is always blank.

```PHP
function apple_news_skip_push_callback( $post_id ) {
  $postcat = get_the_category( $post_id );
  error_log("ID: $post_id");
  $postcat_name = cat_id_to_name($post_id);
  if ( ! empty( $postcat ) ) {
    foreach ($postcat as $cat) {
      if ($cat->cat_ID == 18 || $cat->cat_ID == 19 || $cat->cat_ID == 649 || $cat->cat_ID == 627) {
		return false;
      }
    } 
  }
  return true; 
}

add_filter( 'apple_news_skip_push', 'apple_news_skip_push_callback', 10, 1 );
```

**Comment by PypWalters** [comment]
@bluemonkeydev info for the filter can be found here: 
https://github.com/alleyinteractive/apple-news/wiki/action-and-filter-hooks#adminapple-actionsindexclass-pushphp-1

Based on that, you are going to want to accept 2 parameters:
add_filter( 'apple_news_skip_push', 'apple_news_skip_push_callback', 10, 2 );

The second param is going to be the post ID, and the first will be the current value of the skip publish filter, so:
function apple_news_skip_push_callback( $value, $post_id ) {

Hope that helps!

**Comment by kevinfodness** [comment]
Yep, @PypWalters is correct here.

**Comment by bluemonkeydev** [comment]
Yeah - thank you so much. Perhaps a note on the documentation would be helpful.
