### ISSUE TITLE
Last Element: body-layout-last

### ISSUE THREAD

**Issue by rickalee** [alleyinteractive/apple-news#689]
If a non-body component (e.g. Youtube embed) is last element in post content it does not receive "layout": "body-layout-last"

This causes last component to show with no margin bottom and is especially obvious in iOS 13 Dark Mode.

**Comment by kevinfodness** [comment]
YouTube embeds in particular didn't have margin set on them, but this has been fixed in the in-development version 2.1.0, which will be released soon. Other components should have margin on them.
