### ISSUE TITLE
Manual publish button doesn't appear to work

### ISSUE THREAD

**Issue by smerriman** [alleyinteractive/apple-news#69]
Publishing a post with the manual publish button doesn't seem to work.

I have automatic publishing set to no, and the option to display a publish button in a metabox enabled.

Have done a lot of debugging. When the publish button is clicked on the post edit screen, we run through the `do_publish` function in class-admin-apple-meta-boxes.php, which passes us on to the `do_publish` function in class-admin-apple-post-sync.php.

In this function `$updated` gets set to false, since the post isn't on Apple News yet.

This condition is therefore true:

`! $updated && 'yes' != $this->settings->get( 'api_autosync' )`

Which means we return and never publish the post.

Am I missing something?

**Comment by smerriman** [comment]
Is that `!=` meant to be an `=`?

**Comment by bcampeau** [comment]
Thanks for the feedback. Will you be submitting a pull request for this?

**Comment by smerriman** [comment]
I'm not sure what the intention of that line of code is so was hoping someone familiar with the plugin would be able to confirm the best fix. If the same function happens to be called when auto-syncing is turned on, changing `!=` to `==` would then break auto syncing entirely. 

All I know is that the manual publish button does not work at all - I guess nobody else has used it before.

**Comment by bcampeau** [comment]
That's definitely not the intent of that line of code. There are settings to autosync and auto update which are separate. The manual button should definitely be fixed and I can add to the todo list, but there are quite a few items ahead of that at the moment, which is why I asked if you had intended to submit a pull request.

Thanks.

**Comment by smerriman** [comment]
Have looked into it further and that do_publish function is indeed called when either auto syncing or auto updating is on. So it needs to be able to tell whether it's fired by the action on save_post, or by clicking the button. I've added a pull request which passes in an additional parameter so you can tell which is which, then ignore the automatic condition if the button is clicked.

See the lower part of : https://github.com/alleyinteractive/apple-news/pull/74 (sorry, can't figure out how to split up the two commits.)

**Comment by bcampeau** [comment]
Yeah that's likely the issue. I'd really prefer to have these as two separate commits, but if you can't sort that out, then I'll review this soon. Thanks.

**Comment by smerriman** [comment]
Fixed now: https://github.com/alleyinteractive/apple-news/pull/78

**Comment by bcampeau** [comment]
Moving this to 1.0.9 because it's a dependency for enabling the UI for #89
