### ISSUE TITLE
The following components are not supported by Apple News and were removed: img

### ISSUE THREAD

**Issue by paraleadogg** [alleyinteractive/apple-news#690]
Hi,

I am running your apple news plugin on a multi-site install

WP version: 5.2.4
Plugin Verison: 2.0.3

When I try and publish an article to Apple News it successfully publishes, however, none of the in-content attachment images are present and I get the following error message:

![image](https://user-images.githubusercontent.com/10920375/67384258-bdc9ff00-f588-11e9-9e12-74ddaf366fcc.png)

This happens if 'Use remote images' is set to yes or no

Hitting download on the articles page of the plugin and examining the json I can see that only the main featured / header image seems to be present. None of the in-content attachments are in the json.

I've also checked the markup of the articles in question and images are there and have valid src attributes - although they also have srcset attributes as well

Any ideas?

**Comment by paraleadogg** [comment]
FYI I have "fixed" this for now by hooking into the apple_news_exporter_content filter and ensuring all images in content have absolute urls - this seems to have sorted it - it doesn't like relative urls

**Comment by kevinfodness** [comment]
Yeah, that makes sense. The default behavior of WordPress is to use absolute URLs to images, so it doesn't expect relative paths.

**Comment by jayhoogle** [comment]
> FYI I have "fixed" this for now by hooking into the apple_news_exporter_content filter and ensuring all images in content have absolute urls - this seems to have sorted it - it doesn't like relative urls

Realise this is closed @paraleadogg but just wondered if you could share how you achieved this? I'm coming up against the same issue with relative urls now.
