### ISSUE TITLE
Image captions not being pubilished

### ISSUE THREAD

**Issue by vincepettit** [alleyinteractive/apple-news#692]
I get the following error message and the captions are stripped out:

**The following components are unsupported by Apple News and were removed: figcaption**

**Comment by kevinfodness** [comment]
Can you provide your source content, either from the text tab in the classic editor or the value of `post_content` in Gutenberg, please? That will help us to identify where the issue is coming from.

Thanks.

**Comment by vincepettit** [comment]
Here's a snippet of part of the content that is being thrown back:

```
<!-- wp:image {"id":324396} -->
<figure class="wp-block-image"><img src="https://www.thecheckeredflag.co.uk/wp-content/uploads/2019/10/Webp.net-resizeimage-59.jpg" alt="Photo Credit:Red Bull Content Pool" class="wp-image-324396"/><figcaption>Photo Credit:Red Bull Content Pool</figcaption></figure>
<!-- /wp:image -->
```

**Comment by kevinlisota** [comment]
We are seeing the same error with captions not being published. Captions used to work fine on Apple News, so guessing one of the recent plugin updates is the culprit

**Comment by tkolnowski** [comment]
Hello, all. We are getting the same issue with captions not getting published since 2.00. We've since reverted to using version 1.44 - since the captions still worked in that version. Thank you so much for taking a look at this. We are on Gutenberg across the board.

**Comment by kujain** [comment]
Hi..just checking if there's any update on this issue? I am using v2.0.3 and though I don't see the above error message now, the `figcaption` text is just not getting included in the JSON!
Thanks very much!

**Comment by prvnngrj** [comment]
I still face this issue. Can someone please tell me which version to downgrade for which the image captions work?

**Comment by prvnngrj** [comment]
Actually, the latest update 2.0.4 fixes the issue for me.
