### ISSUE TITLE
API: PAID_ARTICLE_NOT_ALLOWED

### ISSUE THREAD

**Issue by iamkingsleyf** [alleyinteractive/apple-news#693]
Hi,

Good work guys how are you doing? i just returned to start using and i found the PAID? checkbox but after ticking  i got the follow error.

`There has been an error with the API: PAID_ARTICLE_NOT_ALLOWED

If you need assistance, please reach out for support on WordPress.org or GitHub.`

**Comment by kevinfodness** [comment]
Yeah, you have to have Apple turn that feature on for your channel before you can use it.
