### ISSUE TITLE
Gutenberg failure, reinstall?

### ISSUE THREAD

**Issue by pickrau** [alleyinteractive/apple-news#696]
Before I tried using Gutenberg, everything went swimmingly. Since I've removed Gutenberg (wasn't a fan, went back to classic), the Apple News article page refuses to load and the sections won't load either.

Is there a way to remove all Apple News information from the WP tables so I can reinstall?

Cheers

**Comment by kevinfodness** [comment]
Yes, all Apple News settings are stored in the `wp_options` table and their `option_name` starts with `apple_news_`. There is article-level metadata that I wouldn't recommend deleting, but if you need to, that's in the `wp_postmeta` table and it likewise has a meta key that starts with `apple_news_`.
