### ISSUE TITLE
Append utm To URL Before Sending to Apple?

### ISSUE THREAD

**Issue by bluemonkeydev** [alleyinteractive/apple-news#697]
Is there any way to add a utm tag to the URL before sending it to Apple? It would be very useful to track back traffic from Apple News.

I looked through the wiki and issues but couldn't find anything.

**Comment by kevinfodness** [comment]
I'd recommend using the `apple_news_exporter_content` filter and doing a find & replace of URLs that point to your site and add the UTM code to them. More info here: https://github.com/alleyinteractive/apple-news/wiki/Action-and-Filter-Hooks#adminapple-actionsindexclass-exportphp-1
