### ISSUE TITLE
Apple News Publisher Plugin Error- API: INVALID_DOCUMENT - "URL"

### ISSUE THREAD

**Issue by rodelk** [alleyinteractive/apple-news#699]
It appears for some reason Apple News is trying to publish one of my posts under a URL that does not exist. I have no idea where to fix this. As it seems Apple News is turning the content of my post into a URL. I appreciate any help

<img width="1123" alt="Screen Shot 2019-11-06 at 10 08 28 PM" src="https://user-images.githubusercontent.com/57472491/68358868-cd4c5a80-00e7-11ea-8a18-206be3b884cd.png">

**Comment by kevinfodness** [comment]
The new version of the plugin which was just released today (2.1.0) contains some additional HTML parsing fixes. Can you take a look and see if that resolves your issue?
