### ISSUE TITLE
Permissions Issues

### ISSUE THREAD

**Issue by ronaldyule** [alleyinteractive/apple-news#7]
I have installed the plugin to my web-server and when I go to click activate in the Wordpress menu it comes up with this error:

Parse error: syntax error, unexpected '{' in /mounted-storage/home142/sub015/sc87331-QOJL/DOMAIN/wp-content/plugins/apple-news-master/admin/apple-actions/index/class-push.php on line 136

I have read the part which says "Troubleshooting: Resolving Potential Permissions Issues" and have tried looking for “./apple-export/workspace” and “./apple-export/workspace/tmp” but cannot seem to find them. 

Could someone please point me in the right direction to try and solve this issue?

**Comment by bcampeau** [comment]
This file had a try/catch/finally block which is only supported in PHP 5.5 and above. I've removed this for compatibility with PHP 5.3, which the plugin does state and which it's clear your hosting provider is using.

Please pull the latest version and this should work for you now.

**Comment by ronaldyule** [comment]
Thanks for that but I now seem to be getting this error:

Fatal error: Can't use method return value in write context in /mounted-storage/home142/sub015/sc87331-QOJL/www.example.com/wp-content/plugins/apple-news-master/admin/apple-actions/class-api-action.php on line 73

**Comment by bcampeau** [comment]
I've made a couple more updates that are needed for PHP 5.3 compatibility if you can check again.

Thanks.

**Comment by ronaldyule** [comment]
That's great thank you, seems to be working!

**Comment by ronaldyule** [comment]
I'm trying to follow the part of the instructions "Publishing your WordPress Site to Apple News". I have clicked the link link at the top of the “API Settings” subsection of Settings > Apple News and it takes me to the following page:
![screen shot 2015-09-16 at 17 38 18](https://cloud.githubusercontent.com/assets/14302847/9911385/c86d09fc-5c99-11e5-9cc8-c1799438d8e1.png)

I cannot seem to find an option to find my API credentials anywhere. If you could provide greater detail of where to find it that would be greatly appreciated.

**Comment by bcampeau** [comment]
Unfortunately I can't help with that. You'll need to follow up directly with your contact at Apple to get your API credentials.
