### ISSUE TITLE
Image Embed Code showing outside image

### ISSUE THREAD

**Issue by simonjay** [alleyinteractive/apple-news#701]
Hello, new to this, so bear with me. We are using the Apple News plugin but we have a strange encounter where the embed code with caption is showing outside the image on Apple News drafts. This is a url: https://apple.news/AyOsIg4ZOQqWANwNqlguWnA and the code shows outside the images where the embed code has a caption.

I imagine there is a fix in JSON, I have seen the customise JSON option for general embed codes but not too sure what I could add there to fix the problem.

On our website rockshotmagazine.com the embed codes are not a problem. We use embed codes from Photoshelter, which is a photography storage site.  example embed code with caption here: 

[caption id="" align="alignnone" width="1000"]<a href="https://www.photoshelter.com/img-get/I0000Pt98VQbWqnU/s/1000/714/Calexico-and-Iron-Wine-15-15.jpg"><img title="Calexico and Iron &amp; Wine" src="https://www.photoshelter.com/img-get/I0000Pt98VQbWqnU/s/1000/714/Calexico-and-Iron-Wine-15-15.jpg" alt="Bridgewater Hall, Manchester (Mark Bromham)" width="1000" height="714" /></a> Lisa O'Neil[/caption]

with out caption: 

<a href="/gallery-image/Calexico-And-Iron/G0000BbvLBJZ33SI/I000050RgZnfVdAE"><img title="Calexico and Iron &amp; Wine" src="https://www.photoshelter.com/img-get/I000050RgZnfVdAE/s/1000/667/Calexico-and-Iron-Wine-17-17.jpg" alt="Bridgewater Hall, Manchester (Mark Bromham)" width="1000" /></a>

Now obviously I can see the difference in code and understand that the second one is more standard html I just wonder if there is a code fix to this problem?

Thanks, and as i say I an new to this but willing to learn (a lot) 
Simon

**Comment by kevinfodness** [comment]
We just released a new version of the plugin today (v2.1.0) that contains some fixes for caption parsing. Can you let me know if the latest version fixes this issue for you?
