### ISSUE TITLE
Scheduled Posts Don't Pass Through ID to apple_news_skip_push correctly

### ISSUE THREAD

**Issue by trevorllarson** [alleyinteractive/apple-news#702]
The following use of the apple_news_skip_push hook works correctly when directly publishing a post from the Edit Post page in the backend, but when a post is published using WordPress's standard scheduling process, the $post_id does not correctly come through.

```
function apple_news_skip_push_callback( $value, $post_id ) {

    $langSettings = wpml_get_language_information($post_id);

    if(is_array($langSettings) && isset($langSettings['language_code']) && $langSettings['language_code'] === "es") {
        error_log('Skipped Apple News Push: ' . get_the_title($post_id) . ' language is Spanish');
        return true;
    }
    error_log('Apple News Push: ' . get_the_title($post_id) . ' language is English');
    return false;

}

add_filter( 'apple_news_skip_push', 'apple_news_skip_push_callback', 10, 2 );
```

**Comment by kevinfodness** [comment]
I'm looking at the code and it *should* pass through correctly. I'll run a more robust test shortly.

**Comment by kevinfodness** [comment]
I can't reproduce this. I scheduled a post to publish, put a breakpoint on where we're calling the `apple_news_skip_push` filter, and verified that the second parameter is the post ID. Can you try this on the latest version (2.1.0, released today) and report back if you are still having the problem?
