### ISSUE TITLE
Alerts disabled in settings, but banner notifications still appearing

### ISSUE THREAD

**Issue by lynnwise** [alleyinteractive/apple-news#703]
I have disabled alerts on the settings page, but we are still getting regular banner notifications in WordPress. How do we disable alerts altogether?

**Comment by lynnwise** [comment]
<img width="1353" alt="apple-news-alerts" src="https://user-images.githubusercontent.com/42557575/70636785-ba9fd680-1bfb-11ea-8129-96549d866590.png">

**Comment by kevinfodness** [comment]
"Component alerts" in the settings page refers to a specific type of alert. There is no way, currently, to disable alerts entirely via the plugin. However, alerts are managed using usermeta, and the `Admin_Apple_Notice` class calls `update_user_meta` to add notices, so you could put a filter on `update_user_metadata` to check for a meta key of `apple_news_notice` and return `false` if encountered, which should have the effect of disabling notices in the plugin. I can't guarantee that it will catch all cases, but it should be fairly effective.
