### ISSUE TITLE
NOT_FOUND (keyPath articleId)

### ISSUE THREAD

**Issue by KarmaMole** [alleyinteractive/apple-news#704]
Keep getting this error for articles. They're on Apple News, so they got there, but these errors still show in Wordpress? Any idea what the problem is or how I can resolve it?

**Comment by kevinfodness** [comment]
That means that the plugin is trying to get information from Apple's API based on an article ID and it can't. You should look at the postmeta for the article in question and compare it to the article ID that is published on your channel. The postmeta key for the article ID will be `apple_news_api_id`.
