### ISSUE TITLE
Wordpress - There has been an error with the API

### ISSUE THREAD

**Issue by vmadeira81** [alleyinteractive/apple-news#705]
There has been an error with the API:
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->42->text)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->43->text)

**Comment by kevinfodness** [comment]
Consolidating discussion of this issue in #707
