### ISSUE TITLE
Remove Cover Art Support

### ISSUE THREAD

**Issue by yogeshbeniwal** [alleyinteractive/apple-news#706]
The CoverArt object is deprecated because Featured Stories in Apple News is no longer supported. Reference: https://developer.apple.com/documentation/apple_news/apple_news_format/apple_news_format_release_notes_for_ios_13_and_macos_10_15

**Comment by kevinfodness** [comment]
Cover Art has been removed in the `v2.1.0` feature branch and replaced with the ability to set a cover image and caption.
