### ISSUE TITLE
There has been an error with the API: INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->11->text)

### ISSUE THREAD

**Issue by Yayla007** [alleyinteractive/apple-news#707]
I am trying to publish from wordpress website to Apple News this keeps coming up

 There has been an error with the API: INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->11->text)  

I am trying to find out how can i fix this please help.

**Comment by miramedia** [comment]
Any news on this one? Same issue here

**Comment by liamodowd** [comment]
I'm also getting a similar error:

There has been an error with the API: INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->11->text)

But only when publishing articles from one of two categories, the other category on our site is fine.

**Comment by Kpudlo** [comment]
We're also getting a similar error on our website. We found that it was due to a blank paragraph being placed after an image. 

Once we removed that blank paragraph it worked OK, but this is definitely a concern!

**Comment by kevinpersson** [comment]
Thanks, that explained my problem in #711. The shortcode I used included an extra empty paragraph for space.

**Comment by kevinfodness** [comment]
There have been a number of reports of this issue over time, and we have added code to the plugin to address this issue at various points, including unit tests to test for known cases in which content in the editor would cause this error to occur. However, there appear to be one or more cases that aren't being handled properly, chief among them the `<p>&nbsp;</p>` problem. I'm running a few tests locally, and adding checks to our unit tests, to address any outstanding issues that would cause this to occur.

**Comment by kevinfodness** [comment]
Resolved via #788
