### ISSUE TITLE
URGENT - Image Sizes - Cover Art - Jetpack CDN - Jetpack Galleries

### ISSUE THREAD

**Issue by Jasmer** [alleyinteractive/apple-news#709]
Hello @kevinfodness @bcampeau @jomurgel

While we understand you are very busy creating great things for us!, we scoured GitHub at no avail and we need some quick clarification on a few items... 

&nbsp;
&nbsp;
&nbsp;

# **COVER ART**

* Settings > **Use Cover Art?**

* If we set this to **NO** my optimization plugin settings show no **apple news ca...** image sizes

* If we set this to **YES** my optimization plugin settings show 15 **apple news ca...** image sizes

* **Are we correct in understanding if we have **NO** selected, the [Publish to Apple News plugin](https://wordpress.org/plugins/publish-to-apple-news/) will generate 0 image sizes and the default Wordpress image sizes and default Theme image sizes will be used for Apple News?**

* **NO Selected**
<img width="357" alt="Before" src="https://user-images.githubusercontent.com/2568784/75418442-158ec300-58f9-11ea-8652-4ea90d3523a9.png">

* **YES selected**
<img width="359" alt="After" src="https://user-images.githubusercontent.com/2568784/75418495-3eaf5380-58f9-11ea-9275-3a2e21c5b5aa.png">

&nbsp;
&nbsp;
&nbsp;

# **COVERART DEPRECATED**

* Apple indicated [here](https://developer.apple.com/documentation/apple_news/apple_news_format/apple_news_format_release_notes_for_ios_13_and_macos_10_15) "The CoverArt object is deprecated because Featured Stories in Apple News is no longer supported." It is also mentioned here #706 

* **Is the Cover Art in [Publish to Apple News plugin](https://wordpress.org/plugins/publish-to-apple-news/) Settings the same CoverArt Apple is referring to?**

* **If so, does this mean the Cover Art selector should now always be set to NO? Or is there another purpose for this? Or will this option be removed in a future plugin update?**

&nbsp;
&nbsp;
&nbsp;

# **JETPACK ACCELERATOR (PHOTON) CDN**

* You mention in #339 "If you have a need to generate image crops on demand and offload the crops from your server, I would recommend looking into a product such as WordPress.com's Photon"

* **If we understand correctly, we can turn on Jetpack Accelerator (Photon) and then delete all my images sizes except for the original image? Is this what you are suggesting is possible and more efficient?** 

* _**If so...**_

  * _**Would this also suggest we can use [WP Offload Media](https://wordpress.org/plugins/amazon-s3-and-cloudfront/) plugin and offload the Media Library to Amazon S3 or Google Cloud Storage and serve with Cloudflare which also creates all images sizes including WebP format on the fly? This is our objective in the near future.**_

  * _**Are there any Publish to Apple News [Settings](https://github.com/alleyinteractive/apple-news/wiki/Configuration) we should be concerned about with this setup? e.g. Use Remote Images?**_

  * _**PLEASE BE AS VERBOSE AS YOU LIKE ON THIS SUBJECT AS IT IS OUR MOST IMPORTANT FOCUS**_

&nbsp;
&nbsp;
&nbsp;

# **JETPACK [TILED GALLERIES](https://jetpack.com/support/tiled-galleries/)**

* We see here in version [1.4.0 Added support for Jetpack Tiled Galleries](https://wordpress.org/plugins/publish-to-apple-news/#developers)

* **Does this extend to [Full Screen Carousel Galleries](https://jetpack.com/support/carousel/) as well?**

* **We discussed this briefly in 2017 [here](https://wordpress.org/support/topic/unable-to-fetch-a-list-of-sections-error-and-other-questions/). Thank you for your help!**

<img width="960" alt="Jetpack" src="https://user-images.githubusercontent.com/2568784/75421878-debcab00-5900-11ea-8a18-e44a20f501f6.png">

&nbsp;
&nbsp;
&nbsp;

**CONTINUED APPRECIATION**
Jasmer

**Comment by Jasmer** [comment]
Hello and URGENT @kevinfodness 

If you don't have time to answer my other questions from 17 days ago I understand, but this one I really need an answer to at your convenience.

**Does Apple News WP Plugin have any issue with offloading images to a bucket, S3, Google Cloud Storage or otherwise?**

In WP Offload Media plugin it states:

"Warning — Some plugins depend on the file being present on the local server and may not work when the file is removed."

<img width="731" alt="Screen Shot 2020-03-14 at 7 52 13 PM" src="https://user-images.githubusercontent.com/2568784/76693132-69eeae00-662e-11ea-8d74-b7c7309e07c6.png">

**_Is this an issue?_**

**Comment by Jasmer** [comment]
Hello @kevinfodness @bcampeau @jomurgel 

It's been 3 months, we just need a short answer to this, below, if you don't have time for the rest.

- Can we use WP Offload Media plugin and offload the Media Library to Amazon S3 or Google Cloud Storage and serve with Cloudflare which also creates all images sizes including WebP format on the fly? This is our objective in the near future.

- IN OTHER WORDS, will your plugin function without the media being present in the Wordpress Media Library? The WP Offload Media plugin will upload the images to Amazon S3, then delete the images in the Wordpress Media Library. Will this give Apple News enough time to upload them for its purposes?

- Are there any Publish to Apple News Settings we should be concerned about with this setup? e.g. Use Remote Images?

PLEASE BE AS VERBOSE AS YOU LIKE ON THIS SUBJECT AS IT IS OUR MOST IMPORTANT FOCUS

**Comment by kevinfodness** [comment]
Apologies for the delayed response on this issue.

Cover art is indeed deprecated and will be removed in a future version. I'd recommend that you set it to "No" to avoid the additional image sizes from being generated. The default behavior of the plugin is to leave this option set to "No" and it is opt-in.

For image processors, like Jetpack CDN/Photon or others, they should work by copying the source image to their servers and generating crops on-the-fly. You *should* be able to remove the additional crops from your server and keep just the originals, but you will need to test that yourself with the specific plugin you are using before you bulk delete images on my recommendation and then have an issue.

We always recommend that you set Use Remote Images to Yes unless there is a very specific reason why you can't.

Full screen carousel galleries are a display setting, and don't affect the general behavior of the shortcode itself, which is what this plugin uses to convert them into native galleries in Apple News. Full screen carousel galleries should work using this plugin out of the box. Please report back if they do not.

Specifically, on your question about remote images, if you set Remote Images to Yes with that plugin, it should work, as it uses the URL to the image, and does not expect the image to be present on the local filesystem (the specific warning from that plugin). However, I haven't tested the Publish to Apple News plugin with that plugin in particular, so I can't guarantee interoperability.

In terms of "gotchas" or things to worry about with this plugin interfacing with other plugins, the biggest one is that Publish to Apple News needs to be able to run `the_content` filter against post content *in an admin setting*. We have seen issues with interop with other plugins where the other plugins specifically do an `is_admin()` check before registering certain bits of functionality, so functions that hook into `the_content` are sometimes not registered if `is_admin()` is true, which means that some shortcodes / etc don't get picked up automatically. For the image offloading plugin you're looking at, if it does that, you may need to add a filter yourself to hook in that bit of functionality in that plugin so URLs are converted properly.

All of the above notwithstanding, you really just need to try it and see if it works!

**Comment by Jasmer** [comment]
Thanks so much @kevinfodness I'll get back to you soon with testing results. Hopefully, it will be helpful information for you and the community.

**Comment by Jasmer** [comment]
Hi @kevinfodness 

Confirmed! WP Offload Media configured with an AWS S3 bucket, with all images in the local WordPress Media Library offloaded to S3, creates no issue with Apple News.

We haven't tested the Jetpack galleries. I'll get back to you on this.

Much Appreciation,

Jas
