### ISSUE TITLE
Apple News option - changing to hidden gives API curl timeout error

### ISSUE THREAD

**Issue by kujain** [alleyinteractive/apple-news#712]
I am trying to hide a published (web) post from the Apple News channel. I noticed the hidden options in the Apple News sidebar for the post (Block Editor). However, when I enable it and update the post, I keep getting a timeout error. 
![image](https://user-images.githubusercontent.com/120631/77232583-453b8e80-6b78-11ea-8917-60c9bb9a1b63.png)

The auto-publish features are all enabled (auto publish/update/delete) and they work fine. But the above keeps timing out when updating the post and the hidden setting doesn't save or change anything in the channel.
![image](https://user-images.githubusercontent.com/120631/77232674-dd397800-6b78-11ea-9d38-dbad24bff3d9.png)

WP: 5.3.2
AN: 2.0.3

Thanks very much!

**Comment by kevinfodness** [comment]
I wasn't able to reproduce this specific error, but I am not able to just update the hidden flag and re-publish - the plugin says that the article is already in sync.
