### ISSUE TITLE
THERE HAS BEEN AN ERROR WITH THE API: FAILED_TO_PARSE_IMAGE - FAILED TO PARSE IMAGE WITH URI...

### ISSUE THREAD

**Issue by Siliconeer** [alleyinteractive/apple-news#715]
Hello,
I have been having an issue where the images are not being able to upload to Apple News. I have set remote images to "yes" and turned asynchronous publishing to "no." 
Here is the debug log:
`API Response:
Array
(
   [headers] => Requests_Utility_CaseInsensitiveDictionary Object
       (
           [data:protected] => Array
               (
                   [server] => AppleHttpServer/62e237dc531d
                   [date] => Tue, 31 Mar 2020 06:32:39 GMT
                   [content-type] => application/json;charset=utf-8
                   [content-length] => 340
                   [request-id] => 69e9d450-7319-11ea-8472-dbc956af8b33
                   [x-request-id] => 69e9d450-7319-11ea-8472-dbc956af8b33
                   [x-test-source-environment] => prod
                   [x-b3-traceid] => 29ed76ab538a4885
                   [strict-transport-security] => max-age=31536000
               )

       )

   [body] => {"errors":[{"code":"FAILED_TO_PARSE_IMAGE","keyPath":[],"value":"https://siliconeer.com/current/wp-content/uploads/2020/03/amazon-instacart-workers-protest-over-virus-safety.jpg","message":"Failed to parse image with URI [https://siliconeer.com/current/wp-content/uploads/2020/03/amazon-instacart-workers-protest-over-virus-safety.jpg]."}]}
   [response] => Array
       (
           [code] => 400
           [message] => Bad Request
       )

   [cookies] => Array
       (
       )

   [filename] => 
   [http_response] => WP_HTTP_Requests_Response Object
       (
           [response:protected] => Requests_Response Object
               (
                   [body] => {"errors":[{"code":"FAILED_TO_PARSE_IMAGE","keyPath":[],"value":"https://siliconeer.com/current/wp-content/uploads/2020/03/amazon-instacart-workers-protest-over-virus-safety.jpg","message":"Failed to parse image with URI [https://siliconeer.com/current/wp-content/uploads/2020/03/amazon-instacart-workers-protest-over-virus-safety.jpg]."}]}
                   [raw] => HTTP/1.1 400 Bad Request
Server: AppleHttpServer/62e237dc531d
Date: Tue, 31 Mar 2020 06:32:39 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 340
Connection: close
Request-Id: 69e9d450-7319-11ea-8472-dbc956af8b33
X-REQUEST-ID: 69e9d450-7319-11ea-8472-dbc956af8b33
X-TEST-SOURCE-ENVIRONMENT: prod
X-B3-TraceId: 29ed76ab538a4885
Strict-Transport-Security: max-age=31536000

{"errors":[{"code":"FAILED_TO_PARSE_IMAGE","keyPath":[],"value":"https://siliconeer.com/current/wp-content/uploads/2020/03/amazon-instacart-workers-protest-over-virus-safety.jpg","message":"Failed to parse image with URI [https://siliconeer.com/current/wp-content/uploads/2020/03/amazon-instacart-workers-protest-over-virus-safety.jpg]."}]}
                   [headers] => Requests_Response_Headers Object
                       (
                           [data:protected] => Array
                               (
                                   [server] => Array
                                       (
                                           [0] => AppleHttpServer/62e237dc531d
                                       )

                                   [date] => Array
                                       (
                                           [0] => Tue, 31 Mar 2020 06:32:39 GMT
                                       )

                                   [content-type] => Array
                                       (
                                           [0] => application/json;charset=utf-8
                                       )

                                   [content-length] => Array
                                       (
                                           [0] => 340
                                       )

                                   [request-id] => Array
                                       (
                                           [0] => 69e9d450-7319-11ea-8472-dbc956af8b33
                                       )

                                   [x-request-id] => Array
                                       (
                                           [0] => 69e9d450-7319-11ea-8472-dbc956af8b33
                                       )

                                   [x-test-source-environment] => Array
                                       (
                                           [0] => prod
                                       )

                                   [x-b3-traceid] => Array
                                       (
                                           [0] => 29ed76ab538a4885
                                       )

                                   [strict-transport-security] => Array
                                       (
                                           [0] => max-age=31536000
                                       )

                               )

                       )

                   [status_code] => 400
                   [protocol_version] => 1.1
                   [success] => 
                   [redirects] => 0
                   [url] => https://news-api.apple.com/channels/c97d8545-7935-4d49-8f32-7af0fb5d308c/articles
                   [history] => Array
                       (
                       )

                   [cookies] => Requests_Cookie_Jar Object
                       (
                           [cookies:protected] => Array
                               (
                               )

                       )

               )

           [filename:protected] => 
           [data] => 
           [headers] => 
           [status] => 
       )

)

Request Meta:

Array
(
   [data] => Array
       (
           [links] => Array
               (
                   [sections] => Array
                       (
                           [0] => https://news-api.apple.com/sections/9b9c5732-32b8-4cac-8195-cebe2f66fa95
                           [1] => https://news-api.apple.com/sections/bedcb1ed-e6fd-36de-9c6c-bedf62136387
                           [2] => https://news-api.apple.com/sections/e73ac686-6ee9-4e22-9585-c574f5e5696e
                           [3] => https://news-api.apple.com/sections/e95ced62-22ba-4966-a14a-4142614ec7f2
                       )

               )

           [isPaid] => 
           [isPreview] => 
           [isHidden] => 
           [isSponsored] => 
       )

)

Image Settings:
Use Remote images enabled 

JSON:
{"version":"1.7","identifier":"post-111462","language":"en-US","title":"Amazon, Instacart workers protest over virus safety","documentStyle":{"backgroundColor":"#fafafa"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"header","layout":"headerPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"https:\/\/siliconeer.com\/current\/wp-content\/uploads\/2020\/03\/amazon-instacart-workers-protest-over-virus-safety.jpg"}],"behavior":{"type":"parallax","factor":0.8000000000000000444089209850062616169452667236328125}},{"role":"container","layout":{"columnSpan":7,"columnStart":0,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#fafafa"},"components":[{"role":"title","text":"Amazon, Instacart workers protest over virus safety","format":"html","textStyle":"default-title","layout":"title-layout"},{"role":"byline","text":"by AFP | Mar 30, 2020 | 3:02 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"body","text":"<p><i>Amazon workers at Amazon\u2019s Staten Island warehouse stage a walkout to demand that the facility be shut down and cleaned after one staffer tested positive for the coronavirus (Angela Weiss)<\/i><\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>New York (AFP) \u2013 Amazon warehouse employees and Instacart delivery shoppers joined protests Monday to press safety demands, highlighting the risks for workers on the front lines of supplying Americans largely sheltering at home due to the COVID-19 pandemic.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>An estimated 50 to 60 employees joined a walkout at an Amazon worker warehouse in the New York borough of Staten Island, demanding that the facility be shut down and cleaned after a worker tested positive for the coronavirus.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>\u201cThere are positive cases working in these buildings infecting thousands,\u201d warehouse worker Christian Smalls wrote on Twitter.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Amazon, responding to an AFP query, said Smalls made \u201cmisleading\u201d statements about conditions and that he was supposed to be on quarantine.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>\u201cLike all businesses grappling with the ongoing coronavirus pandemic, we are working hard to keep employees safe while serving communities and the most vulnerable,\u201d Amazon said in a statement.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>\u201cWe have taken extreme measures to keep people safe.\u201d<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Meanwhile a group calling itself the Gig Workers Collective said it was maintaining its call for Instacart\u2019s independent contractors to strike despite new safety measures announced late Sunday by the company.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>\u201cWorkers aren\u2019t filling orders until our full demands are met,\u201d a spokesperson told AFP. \u201cThis isn\u2019t just about us, we want to also protect our customers.\u201d<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>It was not immediately clear how many of Instacart \u201cshoppers\u201d who are independent \u201cgig\u201d workers, were participating in the stoppage.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Instacart, which recently announced plans to hire some 300,000 people to help meet demand for grocery delivery, said in a statement it was \u201cfully operational\u201d and that the walkout caused \u201cno impact.\u201d<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>\u201cWe\u2019re continuing to see the highest customer demand in Instacart history and have more active shoppers on our platform today than ever before picking and delivering groceries for millions of consumers,\u201d said the San Francisco company, which operates in some 5,500 cities in the US and Canada.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>\u2013 More safety gear \u2013<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>The firm said Sunday it would provide additional health and safety supplies to full-service \u201cshoppers\u201d and would set a \u201cdefault\u201d tip based on customers\u2019 prior orders.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>The labor group, whose numbers were not known, called the Instacart moves \u201ca sick joke.\u201d<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>\u201cWe had been asking for hand sanitizer for many, many weeks. But apparently the company is capable of sourcing some with two days of work? Where was this before,\u201d the group said in a Medium post.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>A separate group of workers at the Amazon-owned grocery chain Whole Foods meanwhile called for a one-day stoppage or \u201csickout\u201d on Tuesday to press demands for improved health measures.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>The group calling itself \u201cWhole Worker\u201d said it was seeking guaranteed paid leave for quarantined workers, among other things.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>With much of the US population locked down, Americans are increasingly relying on delivery of food and other supplies from firms like Amazon.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>A report by NBC News said Amazon workers at two Southern California warehouses had presented demands to shut down the facilities for two weeks for sterilization while employees are tested for the virus.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Amazon has announced plans to hire an additional 100,000 people in the US, while rival Walmart is seeking to expand its workforce by 150,000.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p><i><b>Disclaimer:<\/b> Validity of the above story is for 7 Days from original date of publishing. Source: AFP.<\/i><\/p>","format":"html","textStyle":"default-body","layout":"body-layout-last"}]}],"componentTextStyles":{"default-body":{"textAlignment":"left","fontName":"HelveticaNeue-Light","fontSize":16,"tracking":0.0200000000000000004163336342344337026588618755340576171875,"lineHeight":20,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-title":{"fontName":"HelveticaNeue-CondensedBold","fontSize":48,"lineHeight":52,"tracking":0,"textColor":"#333333","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"HelveticaNeue","fontSize":12,"lineHeight":20,"tracking":0.0200000000000000004163336342344337026588618755340576171875,"textColor":"#7c7c7c"}},"textStyles":{"default-tag-code":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"},"default-tag-pre":{"textAlignment":"left","fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f","paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-tag-samp":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"}},"componentLayouts":{"body-layout":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":30}},"headerPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7},"headerBelowTextPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7,"margin":{"top":30,"bottom":0}},"title-layout":{"margin":{"top":30,"bottom":0}},"byline-layout":{"margin":{"top":10,"bottom":10},"columnStart":0,"columnSpan":7}},"metadata":{"thumbnailURL":"https:\/\/siliconeer.com\/current\/wp-content\/uploads\/2020\/03\/amazon-instacart-workers-protest-over-virus-safety.jpg","dateCreated":"2020-03-30T22:02:09+00:00","dateModified":"2020-03-30T22:02:09+00:00","datePublished":"2020-03-30T22:02:09+00:00","canonicalURL":"https:\/\/siliconeer.com\/current\/amazon-instacart-workers-protest-over-virus-safety\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"2.0.3"},"advertisingSettings":{"frequency":1,"layout":{"margin":{"top":15,"bottom":15}}}}

MIME request:
Authorization: HHMAC; key=a7ca37f3-5ce0-482b-8a2d-bf38853ed83e; signature=cuMEXTvqAjjQJJjQGqeO1d2572aoOjWWlS1xqAc3tZk=; date=2020-03-31T06:32:37+00:00
Content-Length: 9862
Content-Type: multipart/form-data; boundary=493d08d5505fcc2edecc55e72a37f1d7

--493d08d5505fcc2edecc55e72a37f1d7
Content-Type: application/json
Content-Disposition: form-data; name=metadata

{"data":{"links":{"sections":["https:\/\/news-api.apple.com\/sections\/9b9c5732-32b8-4cac-8195-cebe2f66fa95","https:\/\/news-api.apple.com\/sections\/bedcb1ed-e6fd-36de-9c6c-bedf62136387","https:\/\/news-api.apple.com\/sections\/e73ac686-6ee9-4e22-9585-c574f5e5696e","https:\/\/news-api.apple.com\/sections\/e95ced62-22ba-4966-a14a-4142614ec7f2"]},"isPaid":false,"isPreview":false,"isHidden":false,"isSponsored":false}}
--493d08d5505fcc2edecc55e72a37f1d7
Content-Type: application/json
Content-Disposition: form-data; name=my_article; filename=article.json; size=9133

{"version":"1.7","identifier":"post-111462","language":"en-US","title":"Amazon, Instacart workers protest over virus safety","documentStyle":{"backgroundColor":"#fafafa"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"header","layout":"headerPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"https:\/\/siliconeer.com\/current\/wp-content\/uploads\/2020\/03\/amazon-instacart-workers-protest-over-virus-safety.jpg"}],"behavior":{"type":"parallax","factor":0.8000000000000000444089209850062616169452667236328125}},{"role":"container","layout":{"columnSpan":7,"columnStart":0,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#fafafa"},"components":[{"role":"title","text":"Amazon, Instacart workers protest over virus safety","format":"html","textStyle":"default-title","layout":"title-layout"},{"role":"byline","text":"by AFP | Mar 30, 2020 | 3:02 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"body","text":"<p><i>Amazon workers at Amazon\u2019s Staten Island warehouse stage a walkout to demand that the facility be shut down and cleaned after one staffer tested positive for the coronavirus (Angela Weiss)<\/i><\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>New York (AFP) \u2013 Amazon warehouse employees and Instacart delivery shoppers joined protests Monday to press safety demands, highlighting the risks for workers on the front lines of supplying Americans largely sheltering at home due to the COVID-19 pandemic.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>An estimated 50 to 60 employees joined a walkout at an Amazon worker warehouse in the New York borough of Staten Island, demanding that the facility be shut down and cleaned after a worker tested positive for the coronavirus.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>\u201cThere are positive cases working in these buildings infecting thousands,\u201d warehouse worker Christian Smalls wrote on Twitter.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Amazon, responding to an AFP query, said Smalls made \u201cmisleading\u201d statements about conditions and that he was supposed to be on quarantine.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>\u201cLike all businesses grappling with the ongoing coronavirus pandemic, we are working hard to keep employees safe while serving communities and the most vulnerable,\u201d Amazon said in a statement.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>\u201cWe have taken extreme measures to keep people safe.\u201d<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Meanwhile a group calling itself the Gig Workers Collective said it was maintaining its call for Instacart\u2019s independent contractors to strike despite new safety measures announced late Sunday by the company.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>\u201cWorkers aren\u2019t filling orders until our full demands are met,\u201d a spokesperson told AFP. \u201cThis isn\u2019t just about us, we want to also protect our customers.\u201d<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>It was not immediately clear how many of Instacart \u201cshoppers\u201d who are independent \u201cgig\u201d workers, were participating in the stoppage.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Instacart, which recently announced plans to hire some 300,000 people to help meet demand for grocery delivery, said in a statement it was \u201cfully operational\u201d and that the walkout caused \u201cno impact.\u201d<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>\u201cWe\u2019re continuing to see the highest customer demand in Instacart history and have more active shoppers on our platform today than ever before picking and delivering groceries for millions of consumers,\u201d said the San Francisco company, which operates in some 5,500 cities in the US and Canada.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>\u2013 More safety gear \u2013<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>The firm said Sunday it would provide additional health and safety supplies to full-service \u201cshoppers\u201d and would set a \u201cdefault\u201d tip based on customers\u2019 prior orders.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>The labor group, whose numbers were not known, called the Instacart moves \u201ca sick joke.\u201d<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>\u201cWe had been asking for hand sanitizer for many, many weeks. But apparently the company is capable of sourcing some with two days of work? Where was this before,\u201d the group said in a Medium post.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>A separate group of workers at the Amazon-owned grocery chain Whole Foods meanwhile called for a one-day stoppage or \u201csickout\u201d on Tuesday to press demands for improved health measures.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>The group calling itself \u201cWhole Worker\u201d said it was seeking guaranteed paid leave for quarantined workers, among other things.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>With much of the US population locked down, Americans are increasingly relying on delivery of food and other supplies from firms like Amazon.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>A report by NBC News said Amazon workers at two Southern California warehouses had presented demands to shut down the facilities for two weeks for sterilization while employees are tested for the virus.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Amazon has announced plans to hire an additional 100,000 people in the US, while rival Walmart is seeking to expand its workforce by 150,000.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p><i><b>Disclaimer:<\/b> Validity of the above story is for 7 Days from original date of publishing. Source: AFP.<\/i><\/p>","format":"html","textStyle":"default-body","layout":"body-layout-last"}]}],"componentTextStyles":{"default-body":{"textAlignment":"left","fontName":"HelveticaNeue-Light","fontSize":16,"tracking":0.0200000000000000004163336342344337026588618755340576171875,"lineHeight":20,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-title":{"fontName":"HelveticaNeue-CondensedBold","fontSize":48,"lineHeight":52,"tracking":0,"textColor":"#333333","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"HelveticaNeue","fontSize":12,"lineHeight":20,"tracking":0.0200000000000000004163336342344337026588618755340576171875,"textColor":"#7c7c7c"}},"textStyles":{"default-tag-code":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"},"default-tag-pre":{"textAlignment":"left","fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f","paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-tag-samp":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"}},"componentLayouts":{"body-layout":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":30}},"headerPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7},"headerBelowTextPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7,"margin":{"top":30,"bottom":0}},"title-layout":{"margin":{"top":30,"bottom":0}},"byline-layout":{"margin":{"top":10,"bottom":10},"columnStart":0,"columnSpan":7}},"metadata":{"thumbnailURL":"https:\/\/siliconeer.com\/current\/wp-content\/uploads\/2020\/03\/amazon-instacart-workers-protest-over-virus-safety.jpg","dateCreated":"2020-03-30T22:02:09+00:00","dateModified":"2020-03-30T22:02:09+00:00","datePublished":"2020-03-30T22:02:09+00:00","canonicalURL":"https:\/\/siliconeer.com\/current\/amazon-instacart-workers-protest-over-virus-safety\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"2.0.3"},"advertisingSettings":{"frequency":1,"layout":{"margin":{"top":15,"bottom":15}}}}
--493d08d5505fcc2edecc55e72a37f1d7--`

**Comment by kevinfodness** [comment]
The image needs to be able to be read by Apple's servers. The error message you are seeing is what we are getting back from Apple's API. Is there anything about that URL (https://siliconeer.com/current/wp-content/uploads/2020/03/amazon-instacart-workers-protest-over-virus-safety.jpg) that is restricting access based on user-agent or IP or anything else?

If you can't think of anything that would be an issue with the server and access to images, then you will need to open up a support ticket with Apple, since their platform isn't able to read the image from your server.
