### ISSUE TITLE
Don't use get_user_attribute() for VIP Go

### ISSUE THREAD

**Issue by GaryJones** [alleyinteractive/apple-news#717]
The `get_user_attribute()` function is conditionally called in this plugin [here](https://github.com/alleyinteractive/apple-news/blob/1e5ec584ab5fce382cb28c1380bf96579eba089c/admin/class-admin-apple-notice.php#L354).

At least for sites on VIP Go, [this function has been deprecated](https://github.com/Automattic/vip-go-mu-plugins/blob/dfc36174ce2274def920a9ed4bf88e7d50303b35/vip-helpers/vip-deprecated.php#L460-L483). As you can see, it defaults to `get_user_meta()` anyway.

The `VIP_GO_APP_ENVIRONMENT` constant defined [here](https://wpvip.com/documentation/vip-go/vip-go-environments/#differentiating-environments-in-code) or can help if you need to differentiate between WordPress.com VIP and VIP Go environments.

**Comment by kevinfodness** [comment]
Resolved via #835.
