### ISSUE TITLE
Facebook component generates wrong URL

### ISSUE THREAD

**Issue by dhanendrannewscorp** [alleyinteractive/apple-news#721]
We are facing an issue with the Apple News plugin (v 2.0.3) when we add some Facebook links in the article content. Apple News rejects the JSON as it has some issues. When we looked into it found that for the Facebook component it expects a URL but some text was passed.

The text will look like below;
Like us on Facebook at <a href="https://www.facebook.com/XYZ/" target="_blank" rel="noopener">www.facebook.com/XYZ</a> and follow us from our main Twitter account at <a href="https://twitter.com/XYZ" target="_blank" rel="noopener">@XYZ</a>.

When we looked at the Facebook component from the plugin, it seems like it [strips](https://github.com/alleyinteractive/apple-news/blob/v2.0.3/includes/apple-exporter/components/class-facebook.php#L129) all the HTML elements and tries to [find](https://github.com/alleyinteractive/apple-news/blob/v2.0.3/includes/apple-exporter/components/class-facebook.php#L153) the facebook.com domain. When it finds the string, it considers the [entire line](https://github.com/alleyinteractive/apple-news/blob/v2.0.3/includes/apple-exporter/components/class-facebook.php#L154) as the URL.

This is just a text and not an embedded link, so it shouldn't be considered as FB post.

**Comment by kevinfodness** [comment]
Opened #722 to address.

**Comment by kevinfodness** [comment]
Fixed in latest `master`.
