### ISSUE TITLE
Blockquote error and fix

### ISSUE THREAD

**Issue by rhayncf** [alleyinteractive/apple-news#725]
https://github.com/alleyinteractive/apple-news/blob/6f0b4eb1a99394eae6871b1b3069efe4fe1e40a9/includes/apple-exporter/components/class-quote.php#L445

This line is causing an error on blockquotes. 

"There has been an error with the API: INVALID_DOCUMENT - Document has missing references. Couldn't find ComponentTextStyle on document for id: default-blockquote and, no inline value set!"

Making it the same as the line below fixes the issue.

GOOD:
'default-blockquote',

BAD
'default-blockquote-' . $text_alignment, (the blockquote ending "-" and $text_alignment can be removed.

Hope this helps!

**Comment by kevinfodness** [comment]
We included a fix for this issue in the most recent release. I'm going to close this issue, but if you download the most recent release and discover that it doesn't work for you, please let me know and I will re-open.
