### ISSUE TITLE
Trying to publish to Apple News - error

### ISSUE THREAD

**Issue by ADMINND** [alleyinteractive/apple-news#727]
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->26->text)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->30->text)

JSON file below:
{"version":"1.7","identifier":"post-1709","language":"en-US","title":"COVID-19 crisis in nursing homes is a gendered crisis","documentStyle":{"backgroundColor":"#fafafa"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"header","layout":"headerPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"https:\/\/quoimedia.com\/wp-content\/uploads\/2020\/05\/estabrooks-keefe-covid-19-crisis-in-nursing-homes-is-a-gender-crisis.jpg"}],"behavior":{"type":"parallax","factor":0.8000000000000000444089209850062616169452667236328125}},{"role":"container","layout":{"columnSpan":7,"columnStart":0,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#fafafa"},"components":[{"role":"title","text":"COVID-19 crisis in nursing homes is a gendered crisis","format":"html","textStyle":"default-title","layout":"title-layout"},{"role":"byline","text":"by NanciD | May 25, 2020 | 3:54 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"heading2","text":"Women are the majority of nursing home residents, care providers and unpaid family caregivers","format":"html","textStyle":"default-heading-2","layout":"heading-layout"},{"role":"body","text":"<p>We are all interdependent, as <a href=\"https:\/\/www.opendemocracy.net\/en\/openmovements\/covid-19-pandemic-reveals-and-exacerbates-crisis-care\/\">Karina Battyany wrote<\/a> on the crisis of care during COVID-19. \u201cAll of us have required or will require care at some moment in our lives.\u201d<\/p>","format":"html","textStyle":"dropcapBodyStyle","layout":"body-layout"},{"role":"body","text":"<p><strong>Who cares? <\/strong><\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Women care \u2014 doing the bulk of paid and unpaid caregiving <a href=\"https:\/\/www.unwomen.org\/en\/digital-library\/publications\/2017\/12\/long-term-care-for-older-people\">around the globe<\/a>, systemically underpaid and undervalued. This is even more true for women of colour. It is no coincidence that caregiving is rarely valued as part of the productive economy. It\u2019s too often invisible \u2014 even when it\u2019s central to our economy\u2019s function.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>In <a href=\"https:\/\/quoimedia.com\/missed-and-rushed-nursing-home-care-tasks-common-may-put-residents-at-risk\/\">nursing homes<\/a>, women are more than 2\/3rds of residents and more than 90% of paid staff. More than 80% of unpaid family caregivers are women.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p><strong>Why does this matter? <\/strong><\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Out of the many tragedies of COVID-19, we can seize the opportunity to re-envision the nursing home system and make it work for women and for all Canadians.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>The first wave of COVID-19 news stunned the world. We saw nursing homes in <a href=\"https:\/\/www.trtworld.com\/magazine\/the-massacre-of-italy-s-elderly-nursing-home-residents-35575\">Italy<\/a> and <a href=\"https:\/\/www.bbc.com\/news\/world-europe-52014023\">Spain<\/a> abandoned by care staff. Seniors with serious physical and mental challenges left to fend for themselves. Residents unfed, soiled and bewildered. Dead bodies in hallways and beds. The stuff of nightmares.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>It can\u2019t happen here, we thought. <a href=\"https:\/\/montrealgazette.com\/news\/local-news\/public-health-police-find-bodies-feces-at-dorval-seniors-residence-sources\/\">Until it did<\/a>. It didn\u2019t happen everywhere, but the extreme cases \u2014 canaries in a mine \u2014 finally focused our attention on Canada\u2019s nursing home system. This system has been in <a href=\"https:\/\/nationalpost.com\/news\/canada\/nursing-home-health-care-aides-need-more-training-suffer-worrisome-burnout-study\">disrepair through decades<\/a> of disjointed minor changes and benign neglect (that isn\u2019t actually so benign). It holds together with the goodwill and deep ideals of caring from its largely invisible workers, paid and unpaid, most of them women. We leave them to care for our aging spouses, siblings, parents, and grandparents.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>They must care for our loved ones in a system badly equipped to handle our aging population, in a society where family members live far apart. People live longer and longer, with higher and higher burden of chronic disease \u2014 foremost Alzheimer\u2019s disease and other dementias. Need for nursing home care keeps rising, but our essential resources of staff and supports are not keeping up. This gap widened until the COVID-19 crisis broke our system apart.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Canada\u2019s nursing home system has <a href=\"https:\/\/jamanetwork.com\/journals\/jamanetworkopen\/fullarticle\/2759764?utm_source=For_The_Media&amp;utm_medium=referral&amp;utm_campaign=ftm_links&amp;utm_term=012920\">not done well by paid care workers on the front line<\/a>, by <a href=\"https:\/\/calgaryherald.com\/opinion\/columnists\/opinion-unbefriended-seniors-are-the-forgotten-population\/\">Canadian seniors<\/a>, or by their <a href=\"http:\/\/evidencenetwork.ca\/canada-relying-too-heavily-on-unpaid-caregivers-at-a-cost\/\">unpaid caregivers<\/a> (family and friends). To re-envision our nursing home system, we must make it work for women.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p><strong>What do we know about women in the nursing home system?<\/strong><\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Women\u2019s caregiving in our nursing home system has <a href=\"https:\/\/www.researchgate.net\/publication\/286540256_Long-Term_Care_The_Global_Impact_on_Women\">tremendous economic and social costs<\/a>. Unpaid caregiving by family members and friends of people in nursing homes contributes to their under-employment, precarious employment, lower incomes, and poorer mental and physical health.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Research around the world shows that frontline workers in nursing homes \u2014 Canada\u2019s care aides \u2014 directly affect quality of care and quality of life for residents. For more than a decade, <a href=\"https:\/\/trecresearch.ca\/\">Translating Research in Elder Care<\/a> (TREC) has collected data about care aides from more than 90 nursing homes in British Columbia, Alberta, Manitoba and Saskatchewan. <a href=\"https:\/\/www.winnipegfreepress.com\/opinion\/analysis\/caring-for-caregivers-should-be-top-priority-565517532.html\">We\u2019ve learned that<\/a> 67% of care aides are over 40 years old and 61% speak English as a second language. A third of them work at more than one nursing home, often because nursing homes do not offer full-time hours for a living wage and benefits. <a href=\"https:\/\/www.cbc.ca\/news\/canada\/manitoba\/opinion-caring-caregivers-aides-1.4764832\">Their training is often poor for the complex care needed<\/a> by nursing home residents with dementia. Their work is physically demanding, with high injury rates. It is psychologically demanding with emotional stress, verbal and sometimes racialized abuse. <a href=\"https:\/\/jamanetwork.com\/journals\/jamanetworkopen\/fullarticle\/2759764?utm_source=For_The_Media&amp;utm_medium=referral&amp;utm_campaign=ftm_links&amp;utm_term=012920\">Our<\/a> data show that care aides routinely <a href=\"https:\/\/quoimedia.com\/missed-and-rushed-nursing-home-care-tasks-common-may-put-residents-at-risk\/\">report high rates of burnout, cynicism and exhaustion<\/a>.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>COVID-19 has added severe costs to this women\u2019s work. The <em>New York Times<\/em> reports that <a href=\"https:\/\/www.nytimes.com\/2020\/04\/18\/us\/coronavirus-women-essential-workers.html\">73% of the U.S. health care workers<\/a> infected since the outbreak began are women. (Canadian data not yet available).<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Over the next three decades, costs of care in nursing homes and private homes are projected to more than triple, growing from $22 billion to $71 billion each year. Over the same time, changes in family composition will result in 30% fewer close family members to give unpaid care. More older Canadians will rely on institutional care. It is our responsibility to equip paid and volunteer staff \u2014 most of them women \u2014 to give essential human connection and care. That care <em>should be<\/em> <em>given<\/em> in an authentic <em>home<\/em> where older and highly vulnerable Canadians can live a good life with meaning, until they die with loved ones around them.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p><strong>What can (and must) we do?<\/strong><\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>How do we redesign Canada\u2019s nursing home system to make it work? How do we redesign to halt the gender crisis for women, who are both the majority of caregivers and the majority of people receiving care?<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>First, we must build in thinking about gender at all levels: policy, systems, and strategy. Voices at the table in making decisions and policy must reflect the proportions of women working and living in nursing homes. Starting here could give high return on the investment, because these women know the system problems on the ground. Their frontline experience guides practical thinking on how to make positive changes.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>Second, we must build better long-term measurement of what goes on in nursing homes, because we can\u2019t change it if we haven\u2019t measured it. We must assess more than quality of care (which Canada does very well). We must measure quality of life directly, with strategies that go beyond just a medical model. We must also measure physical, mental, and emotional health of workers \u2014 quality of work life. We must improve by sharing what we measure transparently, reporting on what matters, and reviewing regularly.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>An early goal must be acceptable working conditions, including pay that reflects the value of the work. Staff must have time in their work schedule each day to do more than the absolute bare minimum of care \u2013 time to socialize with residents and meet more that minimal physical needs. Care must centre on people and relationships, not just on task lists.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>We know COVID-19 did not cause today\u2019s tragedy in nursing homes. It did shake the nursing home system, shining a stark light on deep and longstanding fault lines. In our high-income country, we accepted the way our nursing homes exist. We accepted that \u2018warehousing\u2019 our loved ones was good enough. We took advantage of those with dementia who wait for the voices of others to advocate. And that is shameful.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>What can (and must) we do? We must make caregiving an economic priority: make it visible and decide its value to society. We must pay for caregiving appropriately and support the particular needs of women caregivers. Our communities and our nursing homes can flourish in a healthy society that considers caregiving worthy of adequate training, good pay, and esteem in our planning. We can (and must) find new ways to care. COVID-19 has brought a naked urgency to this.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>We must (and can) act now. If we do not, as COVID-19 lays bare the nursing home crisis and its embedded crisis for women, we jeopardize the care of our most vulnerable \u2014 our moms and dads, our grandparents, our siblings and spouses, and our companions. They shaped Canada, just as we can now. We can do better.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p> <\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p><b><i>The situation surrounding COVID-19 is changing steadily and the above conditions and regulations may hav<\/i><\/b><b><i>e altered since the date of publication<\/i><\/b><\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p><em>Photo courtesy of iStock<\/em><\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p><a href=\"https:\/\/quoimedia.com\/la-portee-sexospecifique-de-la-crise-de-la-covid-19-dans-les-maisons-de-soins-infirmiers\/\">Lisez en fran\u00e7ais<\/a><\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p> <\/p>","format":"html","textStyle":"default-body","layout":"body-layout-last"}]}],"componentTextStyles":{"default-heading-2":{"fontName":"AvenirNext-Bold","fontSize":32,"lineHeight":36,"textColor":"#333333","textAlignment":"left","tracking":0},"dropcapBodyStyle":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"tracking":0,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18,"dropCapStyle":{"numberOfLines":4,"numberOfCharacters":1,"padding":5,"fontName":"AvenirNext-Bold","textColor":"#4f4f4f","numberOfRaisedLines":0}},"default-body":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"tracking":0,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-title":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"tracking":0,"textColor":"#333333","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"AvenirNext-Medium","fontSize":13,"lineHeight":24,"tracking":0,"textColor":"#7c7c7c"}},"textStyles":{"default-tag-code":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"},"default-tag-pre":{"textAlignment":"left","fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f","paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-tag-samp":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"}},"componentLayouts":{"heading-layout":{"columnStart":0,"columnSpan":6,"margin":{"bottom":15,"top":15}},"body-layout":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":30}},"headerPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7},"headerBelowTextPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7,"margin":{"top":30,"bottom":0}},"title-layout":{"margin":{"top":30,"bottom":0}},"byline-layout":{"margin":{"top":10,"bottom":10},"columnStart":0,"columnSpan":7}},"metadata":{"thumbnailURL":"https:\/\/quoimedia.com\/wp-content\/uploads\/2020\/05\/estabrooks-keefe-covid-19-crisis-in-nursing-homes-is-a-gender-crisis.jpg","dateCreated":"2020-05-25T15:54:54+00:00","dateModified":"2020-05-25T16:45:27+00:00","datePublished":"2020-05-25T15:54:54+00:00","canonicalURL":"https:\/\/quoimedia.com\/covid-19-crisis-in-nursing-homes-is-a-gender-crisis\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"2.0.4"},"advertisingSettings":{"frequency":1,"layout":{"margin":{"top":15,"bottom":15}}}}

**Comment by kevinfodness** [comment]
Consolidating discussion of this issue in #707
