### ISSUE TITLE
Featured image caption not included

### ISSUE THREAD

**Issue by andrewbeecher** [alleyinteractive/apple-news#730]
None of our articles are including the image caption and credit for featured images. The solution listed here: https://wordpress.org/support/topic/display-caption-for-featured-image/ does not work, as the image caption doesn't appear even when the photo is tapped on. Here is the JSON for an example article: https://pastebin.com/tGLuurrp.

What field does the plug-in source the header caption from? It pulls captions for in-text photos without any issues. Is there a way to customize the JSON to get it to appear? Or a filter we can add? Thanks!

**Comment by evollbrecht** [comment]
After looking around for a bit, I think that the issue has to do with `admin/apple-actions/index/class-export.php` and the way it handles the featured image, or post_thumbnail. As it is, line 110 is `$post_thumb = wp_get_attachment_url( get_post_thumbnail_id( $this->id ) ) ?: null;`; it seems to me that this would only pull the specific URL of the image, without fetching the associated caption and credit. That would also explain why in-text photos (fetched as html items as part of line 116, $`content = $this->get_content( $post );` ) have their captions and attributions intact. Is there a way to use a filter to add in the associated information to the post thumbnail / featured image at the top of the article? Could it be handled by fetching more than just the attachment URL when pulling the thumbnail? Or would a solution be more involved? Thanks in advance -- hope this helps clarify the issue

**Comment by kevinfodness** [comment]
Hi @evollbrecht and @andrewbeecher —

I've got a fix for this one in the `v2.1.0` branch. We are pulling the caption for the Cover component and both adding it to the lightbox and below the image. This feature is still under development and subject to change before we release the next version, but you're welcome to try it out and provide feedback in the meantime!

**Comment by kevinfodness** [comment]
In the in-development `v2.1.0` this is now controlled by a setting in the theme under Image Caption - the default is to not display a caption under the cover image (current behavior) but you can now enable it.
