### ISSUE TITLE
There has been an error with the API: INVALID_DOCUMENT - The value for the property "URL" at line 1 and column 3087 is not valid

### ISSUE THREAD

**Issue by RyanLAFB** [alleyinteractive/apple-news#735]
Never had had any issues in the past. Just updated the Apple New plugin and now I am getting this error:
There has been an error with the API: INVALID_DOCUMENT - The value for the property "URL" at line 1 and column 3087 is not valid: # (keyPath components->1->components->3->URL)

Any ideas as to why, or what URL would be tripping it? Is it not accepting any links in the article?

**Comment by kevinfodness** [comment]
Can you paste the value of the `post_content` field in the database here so I can attempt to reproduce? Meanwhile, I'll see if I can trigger it locally.

**Comment by kevinfodness** [comment]
I created a test post locally with links and it's handling them fine, so my guess is that there's something specific about your post that's triggering it. If you can get me the value from the content field, that will help me debug.

Can you also attach the generated article.json?

**Comment by RyanLAFB** [comment]
So it looks like I have "social buttons" (share to facebook, twitter, etc) that may be causing this problem. However, I have never had this issue until the plugin was updated today. Any workaround? Or will there be another update?

**Comment by kevinfodness** [comment]
I think it's due to the recently-added support for Gutenberg buttons. I'll put out an update that makes the selector more specific, which should solve this problem for you.

**Comment by RyanLAFB** [comment]
Ok yes that may certainly be it.

Here is the debug email I got if that helps at all:

API Response:
Array
(
   [headers] => Requests_Utility_CaseInsensitiveDictionary Object
       (
           [data:protected] => Array
               (
                   [server] => AppleHttpServer/e81851ddfbfa
                   [date] => Tue, 16 Jun 2020 01:10:12 GMT
                   [content-type] => application/json;charset=utf-8
                   [content-length] => 1340
                   [request-id] => 20df9b50-af6e-11ea-85cc-45743cebcc95
                   [x-request-id] => 20df9b50-af6e-11ea-85cc-45743cebcc95
                   [x-test-source-environment] => prod
                   [x-b3-traceid] => 237c8ec1249a420c
                   [strict-transport-security] => max-age=31536000
               )

       )

   [body] => {"errors":[{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",3,"URL"],"message":"The value for the property \"URL\" at line 1 and column 3087 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",4,"URL"],"message":"The value for the property \"URL\" at line 1 and column 3236 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",5,"URL"],"message":"The value for the property \"URL\" at line 1 and column 3385 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",6,"URL"],"message":"The value for the property \"URL\" at line 1 and column 3534 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",80,"URL"],"message":"The value for the property \"URL\" at line 1 and column 22724 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",81,"URL"],"message":"The value for the property \"URL\" at line 1 and column 22873 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",82,"URL"],"message":"The value for the property \"URL\" at line 1 and column 23022 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",83,"URL"],"message":"The value for the property \"URL\" at line 1 and column 23171 is not valid: #"}]}
   [response] => Array
       (
           [code] => 400
           [message] => Bad Request
       )

   [cookies] => Array
       (
       )

   [filename] => 
   [http_response] => WP_HTTP_Requests_Response Object
       (
           [response:protected] => Requests_Response Object
               (
                   [body] => {"errors":[{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",3,"URL"],"message":"The value for the property \"URL\" at line 1 and column 3087 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",4,"URL"],"message":"The value for the property \"URL\" at line 1 and column 3236 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",5,"URL"],"message":"The value for the property \"URL\" at line 1 and column 3385 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",6,"URL"],"message":"The value for the property \"URL\" at line 1 and column 3534 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",80,"URL"],"message":"The value for the property \"URL\" at line 1 and column 22724 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",81,"URL"],"message":"The value for the property \"URL\" at line 1 and column 22873 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",82,"URL"],"message":"The value for the property \"URL\" at line 1 and column 23022 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",83,"URL"],"message":"The value for the property \"URL\" at line 1 and column 23171 is not valid: #"}]}
                   [raw] => HTTP/1.1 400 Bad Request
Server: AppleHttpServer/e81851ddfbfa
Date: Tue, 16 Jun 2020 01:10:12 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 1340
Connection: close
Request-Id: 20df9b50-af6e-11ea-85cc-45743cebcc95
X-REQUEST-ID: 20df9b50-af6e-11ea-85cc-45743cebcc95
X-TEST-SOURCE-ENVIRONMENT: prod
X-B3-TraceId: 237c8ec1249a420c
Strict-Transport-Security: max-age=31536000

{"errors":[{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",3,"URL"],"message":"The value for the property \"URL\" at line 1 and column 3087 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",4,"URL"],"message":"The value for the property \"URL\" at line 1 and column 3236 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",5,"URL"],"message":"The value for the property \"URL\" at line 1 and column 3385 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",6,"URL"],"message":"The value for the property \"URL\" at line 1 and column 3534 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",80,"URL"],"message":"The value for the property \"URL\" at line 1 and column 22724 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",81,"URL"],"message":"The value for the property \"URL\" at line 1 and column 22873 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",82,"URL"],"message":"The value for the property \"URL\" at line 1 and column 23022 is not valid: #"},{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",83,"URL"],"message":"The value for the property \"URL\" at line 1 and column 23171 is not valid: #"}]}
                   [headers] => Requests_Response_Headers Object
                       (
                           [data:protected] => Array
                               (
                                   [server] => Array
                                       (
                                           [0] => AppleHttpServer/e81851ddfbfa
                                       )

                                   [date] => Array
                                       (
                                           [0] => Tue, 16 Jun 2020 01:10:12 GMT
                                       )

                                   [content-type] => Array
                                       (
                                           [0] => application/json;charset=utf-8
                                       )

                                   [content-length] => Array
                                       (
                                           [0] => 1340
                                       )

                                   [request-id] => Array
                                       (
                                           [0] => 20df9b50-af6e-11ea-85cc-45743cebcc95
                                       )

                                   [x-request-id] => Array
                                       (
                                           [0] => 20df9b50-af6e-11ea-85cc-45743cebcc95
                                       )

                                   [x-test-source-environment] => Array
                                       (
                                           [0] => prod
                                       )

                                   [x-b3-traceid] => Array
                                       (
                                           [0] => 237c8ec1249a420c
                                       )

                                   [strict-transport-security] => Array
                                       (
                                           [0] => max-age=31536000
                                       )

                               )

                       )

                   [status_code] => 400
                   [protocol_version] => 1.1
                   [success] => 
                   [redirects] => 0
                   [url] => https://news-api.apple.com/channels/ae4925a4-62e6-4125-82a2-0bdf8e5fb482/articles
                   [history] => Array
                       (
                       )

                   [cookies] => Requests_Cookie_Jar Object
                       (
                           [cookies:protected] => Array
                               (
                               )

                       )

               )

           [filename:protected] => 
           [data] => 
           [headers] => 
           [status] => 
       )

)


Request Meta:

Array
(
   [data] => Array
       (
           [links] => Array
               (
                   [sections] => Array
                       (
                           [0] => https://news-api.apple.com/sections/92fee629-f68b-382c-87a9-0817a8eed203
                       )

               )

           [isPaid] => 
           [isPreview] => 
           [isHidden] => 
           [isSponsored] => 
       )

)

**Comment by kevinfodness** [comment]
I'm going to issue a release tomorrow that rolls back support for the Link Button component, which turned out to be problematic for more reasons than just this specific issue. Can you, as a test, comment out line 108 in `includes/apple-exporter/class-component-factory.php` and verify that it fixes your issue?

**Comment by kevinfodness** [comment]
I just released version 2.0.6, which rolls back support for the new Link Button component. Please let me know if this fixes your issue. We'll take another look at the Link Button component and will issue another release that adds that functionality without causing other side effects.

**Comment by RyanLAFB** [comment]
Hey Kevin,

That seemed to have worked! Thank you so much for how prompt you took care of this. I apologize I wasn't much help in the information you were asking for. I own the site, but am no way a developer haha so I really had no idea where to find some of the information. But everything seems to be working now, so thanks again so much!

Will update you if anything changes. Keep up the great work.

**Comment by kevinfodness** [comment]
Glad to help!
