### ISSUE TITLE
Assign sections by category is not checked by default

### ISSUE THREAD

**Issue by ankitgadents** [alleyinteractive/apple-news#737]
When using Gutenberg editor, "Assign sections by category" checkbox is not being ticked by default in plugin sidebar for Apple News.

I have checked in the API response and there `automaticAssignment` field is set to true. 

[CPWP-710](https://nidigitalsolutions.jira.com/browse/CPWP-710)

![Check](https://user-images.githubusercontent.com/48545657/84360611-fc7bfa80-abe7-11ea-9829-3b10c98fafa9.png)

Problem lies in plugins/apple-news/assets/js/pluginsidebar/components/sidebar/index.js#272

`autoAssignCategories: 'null' === selectedSections`,

it should be 

`autoAssignCategories: '""' === selectedSections`

If we do this problem gets resolved.

Can you please look into it?

**Comment by jomurgel** [comment]
@ankitgadents version 2.0.7 of Apple News is now available which addresses this issue noted above.
