### ISSUE TITLE
Scheduled Wordpress Post Not Published To Apple News 

### ISSUE THREAD

**Issue by imangossblog** [alleyinteractive/apple-news#748]
Whenever I schedule a WordPress post, it does not publish to Apple News and goes to the "Not Published" section so I have to manually publish it later. But If I publish directly from WordPress, there is no issues. How I can fix this?

**Comment by kevinfodness** [comment]
This behavior requires "Automatically publish to Apple News when published in WordPress" to be set to "yes" in settings. Can you confirm that is the case?
