### ISSUE TITLE
Publish to apple news plugin is not compatible with Wordpress 5.4.2

### ISSUE THREAD

**Issue by Vinutavin** [alleyinteractive/apple-news#752]
I have recently updated wordpress version of website to WordPress 5.4.2, the UI of Manage Setting page of publish to apple news plugin is disturbed. Can you please look in to this and can you check if the publishing to apple news is working. By when the stable release compatible with wordpress version-5.4.2 is available .

**Comment by kevinfodness** [comment]
There's a visual bug with the select menus on that screen, but it doesn't impact the plugin's ability to function, or even to select options on that screen. There is a fix for that visual bug in the forthcoming v2.1.0.

**Comment by Vinutavin** [comment]
Thank you kevinfodness.
