### ISSUE TITLE
Invalid Style Error - API Publishing Error

### ISSUE THREAD

**Issue by dobstotev** [alleyinteractive/apple-news#753]
Hey guys, I have the following error:

`There has been an error with the API: INVALID_DOCUMENT - Invalid style. (keyPath components->1->components->13->style)`

This is my article code:
https://pastebin.com/srS54HDd

I am not sure what the API refers to Invalid Style. Any ideas?

**Comment by kevinfodness** [comment]
Can you attach the generated `article.json` by going to Apple News > Articles, finding the article that's causing the issue, and clicking Download? It doesn't like something about the style definition for one of your components.
