### ISSUE TITLE
API problem 

### ISSUE THREAD

**Issue by IrishWhiskeyMagazine** [alleyinteractive/apple-news#770]
Hi I am getting errors when trying to send to Apple News 

Here are the pastebin links 

https://pastebin.com/Nc3XcBzZ

https://pastebin.com/wdLfUfEB

Thanks 
Andrew

**Comment by kevinfodness** [comment]
Apple News doesn't like empty content - I'd imagine that the `<div></div>` is what is causing the problem. Thanks for the source - this gives me something to test against. We've implemented several fixes for this issue in the past, but there continue to be new cases of it occurring, and the checker on Apple's end is very strict.

**Comment by kevinfodness** [comment]
Tracking this issue in #707 - I have a fix in #788
