### ISSUE TITLE
Byline override not working for me

### ISSUE THREAD

**Issue by kic00** [alleyinteractive/apple-news#772]
We have a custom byline we would like to use to override the one we send to apple news.  I implemented the following code but it doesn't seem to work.  Any ideas?
apply_filters('apple_news_exporter_byline', $byline, $post->ID);

**Comment by kevinfodness** [comment]
If that's literally the code that you're using, then it seems to be a misapplication of the filter system. Try the following instead:

```php
add_filter(
	'apple_news_exporter_byline',
	function ( $byline, $post_id ) {
		return get_post_meta( $post_id, 'my_custom_byline_key', true );
	},
	10,
	2
);
```

That assumes that you are storing the custom byline override in postmeta. You will need to change the meta key from `my_custom_byline_key` to the actual postmeta key that you are using.
