### ISSUE TITLE
High wp-json requests

### ISSUE THREAD

**Issue by vincepettit** [alleyinteractive/apple-news#779]
We've noticed a lot of requests from **/wp-json/apple-news/v1/get-notifications?_locale=user** on our snapshots that seem to taking around 2-3 seconds per request to process, resulting in our server resources being overloaded at times.

**Comment by kevinfodness** [comment]
That's ... a significant amount of time per request. The goal with those requests was to get any messages that should be displayed to a user in a Gutenberg context (versus the normal admin notices area in a non-Gutenberg contexts). We will look into a way to streamline this process. The notices are stored in usermeta - is it possible that you have a large usermeta table, and that's what's contributing to the slowness? have you profiled the requests to see where the bottleneck is?

**Comment by kevinfodness** [comment]
We have totally refactored the way we are handling notifications and have removed this endpoint completely in the new version, which we will be releasing soon. In the new version, we will be attaching notifications to existing REST API communication with Gutenberg, either custom routes defined by Apple News for doing things like publishing or updating, as well as the general post update response, so notifications will be displayed after actions are taken that generate them.

Thanks for your feedback!
