### ISSUE TITLE
Admin_Apple_Post_Sync::do_publish() fires before all rest field values have been saved when using Gutenberg.

### ISSUE THREAD

**Issue by hrkhal** [alleyinteractive/apple-news#790]
`do_publish()` fires on the `save_post` hook which is too early if a theme or plugin saves any rest field values via the rest api in Gutenberg that they may later rely on when publishing to Apple News. 

Post meta saved via the rest api in Gutenberg (`register_rest_field()`) is saved after after the `save_post` hook has run.

The `save_post` hook works fine when the classic editor is in use or if Gutenberg is enabled but with all of the meta being saved via back ported meta boxes. 

It also works "well enough" when saving meta via the rest api if the site has the async publishing option enabled due to the delay in publishing allowing the post meta to be saved in time.

`do_publish()` should be hooked into the `rest_after_insert_post` (and other enabled post types) hook if the Gutenberg editor is in use. This will ensure all post meta is saved before attempting publish of the article. 

In our use case we're checking post meta in the `apple_news_skip_push` filter and this always worked as expected while in async mode but disabling async has now highlighted the issue.

**Comment by kevinfodness** [comment]
Yep, you're absolutely right. On initial insertion, `save_post` works as expected, but on update via the REST API, it performs the `wp_update_post` before it handles terms / meta / etc, resulting in the situation you describe.

**Comment by kevinfodness** [comment]
There is a new hook being added in WP 5.6 to solve exactly this problem: https://core.trac.wordpress.org/changeset/49172

We will plan on adopting that hook when it becomes available for installations running WP 5.6+, and will fall back to the old (and admittedly buggy) behavior for older versions of WP.

**Comment by hrkhal** [comment]
Good to hear that the core issue is being addressed. We can till 5.6 for this fix.

**Comment by hrkhal** [comment]
@kevinfodness With 5.6 around the corner when is 2.1.1 due to be released?

**Comment by kevinfodness** [comment]
Working on putting together a release now, which will likely go out Monday.

**Comment by kevinfodness** [comment]
Resolved via #836.
