### ISSUE TITLE
All settings lost on deactivate

### ISSUE THREAD

**Issue by smerriman** [alleyinteractive/apple-news#80]
Temporarily deactivating and then reactivating the plugin causes all admin settings to be lost. It looks like this deliberate via the `apple_news_deactivate_wp_plugin` hook.

This isn't very good practice at all. The uninstall hook should be used instead: https://codex.wordpress.org/Function_Reference/register_uninstall_hook

**Comment by bcampeau** [comment]
Yikes! I think this came into the source before I took it over. Just seeing this now!

Feel free to send a PR and I will *definitely* merge that ASAP!
