### ISSUE TITLE
Custom feed component add-ons

### ISSUE THREAD

**Issue by Alexmcleman1** [alleyinteractive/apple-news#800]
![thumbnail_thumbnail_image0](https://user-images.githubusercontent.com/71818730/94126278-53cc7080-fe4f-11ea-99e9-30b03ed8e2a0.png)
I am using the Alley Interactive Apple News plugin for Wordpress.

I am looking to add a feature at the bottom of Apple News feeds that are Link button components or linked text buttons, which are featured on a range of news publisher feeds. They are essentially CTAs for things like "subscribe, visit the website, etc"

I understand that the Alley plugin cannot yet support these features, I was wanting to know if 1) There is a short-term workaround? or 2) If a new update is planned to include these features.

Thanks

A

**Comment by kevinfodness** [comment]
Version 2.1.0, which is under active development and is nearing release, includes support for a new "End of Article" component that allows you to add custom JSON to be appended to the end of every article, customizable per theme, using the Customize JSON feature.

If you need more control than this, you can always filter the final JSON output for any article and inject whatever you like using the `apple_news_generate_json` filter: https://github.com/alleyinteractive/apple-news/wiki/Action-and-Filter-Hooks#includesapple-exporterclass-exporterphp
