### ISSUE TITLE
register_rest_route was called incorrectly

### ISSUE THREAD

**Issue by syednumans** [alleyinteractive/apple-news#804]
Notice: register_rest_route was called incorrectly. The REST API route definition for apple-news/v1/user-can-publish/(?P\d+) is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback.

**Comment by kevinfodness** [comment]
This has been fixed in the in-development version 2.1.0, which will be released soon. Thanks for flagging!
