### ISSUE TITLE
Performance issues with new Apple News Status column in 1.04

### ISSUE THREAD

**Issue by smerriman** [alleyinteractive/apple-news#81]
Every time the Apple News admin page is visited, an API request is sent for every listed post to Apple News to fetch the status, with no caching whatsoever. This causes the page to be very slow loading, and if email logging is activated, 20 emails to be sent out any time anyone views the page.

Not sure on a fix, but if there isn't a quick one might want to revert the change.

**Comment by smerriman** [comment]
It looks like the request code is also in the meta box function, meaning slowness + an email every time someone visits a post edit screen - vital this doesn't happen.

**Comment by bcampeau** [comment]
Reverting is not an option. Working on a fix.

**Comment by bcampeau** [comment]
Addressed by #82. Version 1.0.5 will be live on .org shortly and sending a request to VIP to update their version.
