### ISSUE TITLE
"The response is not a valid JSON response" on version 2.1.0

### ISSUE THREAD

**Issue by claudiulodro** [alleyinteractive/apple-news#810]
A number of sites started reporting "The response is not a valid JSON response" errors after updating to yesterday's release. This happens right when the edit post page is first loaded and happens because the response of the API call that fetches the Apple News info is invalid JSON in certain situations (I haven't had a chance to fully debug to see the exact situation, but it's something to do with failing to fetch info from Apple News)

<img width="781" alt="Screen Shot 2020-10-06 at 10 02 12 AM" src="https://user-images.githubusercontent.com/7317227/95229764-d50ff580-07b5-11eb-8b12-49f612d0ece5.png">

This is the response from the network request when editing the post:

```
<div class="apple-news-notice apple-news-notice-error" role="alert"><p>Unable to fetch a list of sections.</p></div>[]
```

You can see that the above is most definitely not valid JSON. :)

**Comment by kevinfodness** [comment]
Thanks for the report, @claudiulodro - we'll dig into this!

**Comment by kevinfodness** [comment]
My hot take on this is that it's likely due to a date/time mismatch on the server versus the Apple systems, in which case you should also see a warning on other Apple News pages indicating that a `DATE_NOT_RECENT` error was encountered. However, we can certainly improve the error messaging and ensure that the response is valid JSON.

**Comment by claudiulodro** [comment]
Thanks for the quick response! If it helps your debugging, on further investigation it looks like all of the sites except maybe one had activated the plugin but never entered API keys (not sure why they had it active in that case but 🤷‍♂️), so I definitely think it is something related to failure handling.

**Comment by kevinfodness** [comment]
That's extremely helpful. We're doing some checks in a few places about whether API keys have been entered, but likely not at the level of certain custom REST endpoints, so I can add that as a check as well. Thanks!
