### ISSUE TITLE
There has been an error with the API: FAILED_TO_PARSE_IMAGE - Failed to parse image with URI [bundle://phone.svg]

### ISSUE THREAD

**Issue by jlariza** [alleyinteractive/apple-news#811]
Good day,

We are receiving this message when trying to publish a post on Apple news.

```
There has been an error with the API: FAILED_TO_PARSE_IMAGE - Failed to parse image with URI [bundle://phone.svg].
```

However, the phone.svg picture appears in the list under

```
Image Settings:

Bundled images:
```

The image is coming from a plugin folder, hosted in the same server (no CDN is being used)

What may be happening? how does the `bundled images` work?

Thank you,

**Comment by kevinfodness** [comment]
Apple News Format doesn't support SVGs, only JPG, PNG, and GIF: https://developer.apple.com/documentation/apple_news/apple_news_format/preparing_image_video_audio_music_and_arkit_assets#3359109
