### ISSUE TITLE
Curl Error 28, Not Published status of the articles of Apple News Plugin

### ISSUE THREAD

**Issue by iMangoss** [alleyinteractive/apple-news#818]
I have been using the Plugin "Publish To Apple News" for a long time. But I am getting frequent error in the Articles section of the plugin as "There has been an error with your request: cURL error 28: Resolving timed out after 3000 milliseconds" and due to which sync status is set to Not Published and Apple news status as the error above. So appreciate it if you could resolve this issue at the earliest.

![image](https://user-images.githubusercontent.com/19321797/97303309-5709b080-1882-11eb-9dd8-84aaedb3fa06.png)

Here's a debugger log of the error in one of the post.

API Response:
WP_Error Object
(
    [errors] => Array
        (
            [http_request_failed] => Array
                (
                    [0] => A valid URL was not provided.
                )

        )

    [error_data] => Array
        (
        )

)

Request Meta:

Array
(
    [data] => Array
        (
            [links] => Array
                (
                    [sections] => Array
                        (
                            [0] => https://news-api.apple.com/sections/9bfb833f-4fbc-4cd7-b17d-c752b12375f5
                        )

                )

            [isPaid] =>
            [isPreview] =>
            [isHidden] =>
            [isSponsored] =>
            [maturityRating] => GENERAL
        )

)

Image Settings:

Bundled images:
https://www.theapplebyte.net/wp-content/uploads/2020/10/iphone-xr-deals.jpg
https://www.theapplebyte.net/wp-content/uploads/2020/10/iphone-xr-deals.jpg

JSON:
{"version":"1.11","identifier":"post-24204","language":"en-US","title":"Unlocked iPhone XR is Available At Cheapest Rate That You Won't Find Anywhere","documentStyle":{"backgroundColor":"#fafafa"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"header","layout":"headerPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"bundle:\/\/iphone-xr-deals.jpg"}],"behavior":{"type":"parallax","factor":0.8000000000000000444089209850062616169452667236328125}},{"role":"container","layout":{"columnSpan":7,"columnStart":0,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#fafafa"},"components":[{"role":"title","text":"Unlocked iPhone XR is Available At Cheapest Rate That You Won't Find Anywhere","format":"html","textStyle":"default-title","layout":"title-layout"},{"role":"byline","text":"by Apple Byte | Oct 27, 2020 | 11:53 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"body","text":"<p>Right now, you can grab a stunning <a href=\"https:\/\/www.amazon.com\/dp\/B07P6Y7954\/ref=as_li_ss_tl?&amp;linkCode=ll1&amp;tag=applebyte-20&amp;linkId=91003714783405d940e9bef92aec1aab&amp;language=en_US\"><strong>iPhone XR with 64 GB<\/strong><\/a> of internal capacity as part of the Amazon Renewed scheme for just $384.<\/p>","format":"html","textStyle":"dropcapBodyStyle","layout":"body-layout"},{"role":"body","text":"<p>This device is completely unlocked and can accept any SIM card to prevent you from locking yourself onto a single network. If you have a monthly SIM-only deal and do not want an agreement with a particular carrier to be bound, this is extremely helpful. If you travel often and need to use a different SIM card from a different country, it also helps.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"container","layout":{"columnStart":0,"columnSpan":6,"margin":{"bottom":20,"top":20}},"style":{"backgroundColor":"#eeee22"},"components":[{"role":"quote","text":"<p><a href=\"https:\/\/www.theapplebyte.net\/otterbox-iphone-11-pro-max-currently-on-sale\/\">OtterBox iPhone 11\/Pro\/Max Currently On Sale<\/a><\/p>","format":"html","layout":"blockquote-layout","textStyle":"default-blockquote-left"}]},{"role":"body","text":"<p>This specific iPhone XR version is finished in Black with an internal storage capacity of 64 GB. You also get 5 GB of free iCloud storage from your Apple account and you can upgrade your cloud storage for a small amount of money. It has a beautiful 6.1-inch Liquid Retina display with a 1792\u00d7828-pixel resolution at 326ppi and True Tone technology.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>It runs the Apple A12 Bionic chip with the company\u2019s second-generation Neural Engine and is rated IP67, allowing it to withstand dust and water up to a maximum depth of 1 meter for up to 30 minutes. As with all Apple devices, thanks to the forward-facing TrueDepth camera system, it also offers a stunning camera experience and has to Face ID instead of Touch ID.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"container","layout":{"columnStart":0,"columnSpan":6,"margin":{"bottom":20,"top":20}},"style":{"backgroundColor":"#eeee22"},"components":[{"role":"quote","text":"<p><a href=\"https:\/\/www.theapplebyte.net\/this-cheap-accessory-is-actually-a-wearable-speaker-that-you-can-pair-with-an-iphone\/\">This Cheap Accessory is Actually A Wearable Speaker That You Can Pair With An iPhone!<\/a><\/p>","format":"html","layout":"blockquote-layout","textStyle":"default-blockquote-left"}]},{"role":"body","text":"<p>In all of these circumstances, we want to reaffirm that this deal is part of an Amazon Renewed scheme and, as such, is not new, but was inspected by Amazon\u2019s qualified suppliers on a professional basis. The Amazon 90-day cash back guarantee also comes with:<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>If you just don\u2019t want to pay the amount of ridiculous money for the newly announced Apple iPhone 12 range, it can be a perfect compromise for you at an amazing cost. There are no price reductions or discount codes required for this price to be unlocked.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout-last"}]}],"componentTextStyles":{"dropcapBodyStyle":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"tracking":0,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18,"dropCapStyle":{"numberOfLines":4,"numberOfCharacters":1,"padding":5,"fontName":"AvenirNext-Bold","textColor":"#4f4f4f","numberOfRaisedLines":0}},"default-body":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"tracking":0,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-blockquote-left":{"fontName":"AvenirNext-Regular","fontSize":18,"textColor":"#000000","lineHeight":24,"textAlignment":"left","tracking":0},"default-title":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"tracking":0,"textColor":"#333333","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"AvenirNext-Medium","fontSize":13,"lineHeight":24,"tracking":0,"textColor":"#7c7c7c"}},"textStyles":{"default-tag-code":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"},"default-tag-pre":{"textAlignment":"left","fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f","paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-tag-samp":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"}},"componentLayouts":{"body-layout":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":30}},"blockquote-layout":{"contentInset":{"bottom":true,"left":true,"right":true,"top":true}},"headerPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7},"headerPhotoLayoutWithCaption":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7,"margin":{"bottom":24}},"headerBelowTextPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7,"margin":{"top":30,"bottom":0}},"title-layout":{"margin":{"top":30,"bottom":0}},"byline-layout":{"margin":{"top":10,"bottom":10},"columnStart":0,"columnSpan":7}},"metadata":{"thumbnailURL":"bundle:\/\/iphone-xr-deals.jpg","dateCreated":"2020-10-27T12:23:59+00:00","dateModified":"2020-10-27T06:23:20+00:00","datePublished":"2020-10-27T12:23:59+00:00","canonicalURL":"https:\/\/www.theapplebyte.net\/iphone-xr-deals\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"2.1.0"},"autoplacement":{"advertisement":{"bannerType":"any","distanceFromMedia":"10vh","enabled":true,"frequency":5,"layout":{"margin":15}}}}

MIME request:
Authorization: HHMAC; key=f80fef40-425e-4470-ab9c-21a9ba679bd7; signature=X6IEaEPfSANeW1+j6/ufcH0LMGgDyVY0PeO187TbPmU=; date=2020-10-27T12:24:02+00:00
Content-Length: 63391
Content-Type: multipart/form-data; boundary=7c74f9393f8c7e0509352bc319d7f5d1

--7c74f9393f8c7e0509352bc319d7f5d1
Content-Type: application/json
Content-Disposition: form-data; name=metadata

{"data":{"links":{"sections":["https:\/\/news-api.apple.com\/sections\/9bfb833f-4fbc-4cd7-b17d-c752b12375f5"]},"isPaid":false,"isPreview":false,"isHidden":false,"isSponsored":false,"maturityRating":"GENERAL"}}
--7c74f9393f8c7e0509352bc319d7f5d1
Content-Type: application/json
Content-Disposition: form-data; name=my_article; filename=article.json; size=7076

{"version":"1.11","identifier":"post-24204","language":"en-US","title":"Unlocked iPhone XR is Available At Cheapest Rate That You Won't Find Anywhere","documentStyle":{"backgroundColor":"#fafafa"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"header","layout":"headerPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"bundle:\/\/iphone-xr-deals.jpg"}],"behavior":{"type":"parallax","factor":0.8000000000000000444089209850062616169452667236328125}},{"role":"container","layout":{"columnSpan":7,"columnStart":0,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#fafafa"},"components":[{"role":"title","text":"Unlocked iPhone XR is Available At Cheapest Rate That You Won't Find Anywhere","format":"html","textStyle":"default-title","layout":"title-layout"},{"role":"byline","text":"by Apple Byte | Oct 27, 2020 | 11:53 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"body","text":"<p>Right now, you can grab a stunning <a href=\"https:\/\/www.amazon.com\/dp\/B07P6Y7954\/ref=as_li_ss_tl?&amp;linkCode=ll1&amp;tag=applebyte-20&amp;linkId=91003714783405d940e9bef92aec1aab&amp;language=en_US\"><strong>iPhone XR with 64 GB<\/strong><\/a> of internal capacity as part of the Amazon Renewed scheme for just $384.<\/p>","format":"html","textStyle":"dropcapBodyStyle","layout":"body-layout"},{"role":"body","text":"<p>This device is completely unlocked and can accept any SIM card to prevent you from locking yourself onto a single network. If you have a monthly SIM-only deal and do not want an agreement with a particular carrier to be bound, this is extremely helpful. If you travel often and need to use a different SIM card from a different country, it also helps.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"container","layout":{"columnStart":0,"columnSpan":6,"margin":{"bottom":20,"top":20}},"style":{"backgroundColor":"#eeee22"},"components":[{"role":"quote","text":"<p><a href=\"https:\/\/www.theapplebyte.net\/otterbox-iphone-11-pro-max-currently-on-sale\/\">OtterBox iPhone 11\/Pro\/Max Currently On Sale<\/a><\/p>","format":"html","layout":"blockquote-layout","textStyle":"default-blockquote-left"}]},{"role":"body","text":"<p>This specific iPhone XR version is finished in Black with an internal storage capacity of 64 GB. You also get 5 GB of free iCloud storage from your Apple account and you can upgrade your cloud storage for a small amount of money. It has a beautiful 6.1-inch Liquid Retina display with a 1792\u00d7828-pixel resolution at 326ppi and True Tone technology.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>It runs the Apple A12 Bionic chip with the company\u2019s second-generation Neural Engine and is rated IP67, allowing it to withstand dust and water up to a maximum depth of 1 meter for up to 30 minutes. As with all Apple devices, thanks to the forward-facing TrueDepth camera system, it also offers a stunning camera experience and has to Face ID instead of Touch ID.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"container","layout":{"columnStart":0,"columnSpan":6,"margin":{"bottom":20,"top":20}},"style":{"backgroundColor":"#eeee22"},"components":[{"role":"quote","text":"<p><a href=\"https:\/\/www.theapplebyte.net\/this-cheap-accessory-is-actually-a-wearable-speaker-that-you-can-pair-with-an-iphone\/\">This Cheap Accessory is Actually A Wearable Speaker That You Can Pair With An iPhone!<\/a><\/p>","format":"html","layout":"blockquote-layout","textStyle":"default-blockquote-left"}]},{"role":"body","text":"<p>In all of these circumstances, we want to reaffirm that this deal is part of an Amazon Renewed scheme and, as such, is not new, but was inspected by Amazon\u2019s qualified suppliers on a professional basis. The Amazon 90-day cash back guarantee also comes with:<\/p>","format":"html","textStyle":"default-body","layout":"body-layout"},{"role":"body","text":"<p>If you just don\u2019t want to pay the amount of ridiculous money for the newly announced Apple iPhone 12 range, it can be a perfect compromise for you at an amazing cost. There are no price reductions or discount codes required for this price to be unlocked.<\/p>","format":"html","textStyle":"default-body","layout":"body-layout-last"}]}],"componentTextStyles":{"dropcapBodyStyle":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"tracking":0,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18,"dropCapStyle":{"numberOfLines":4,"numberOfCharacters":1,"padding":5,"fontName":"AvenirNext-Bold","textColor":"#4f4f4f","numberOfRaisedLines":0}},"default-body":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"tracking":0,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-blockquote-left":{"fontName":"AvenirNext-Regular","fontSize":18,"textColor":"#000000","lineHeight":24,"textAlignment":"left","tracking":0},"default-title":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"tracking":0,"textColor":"#333333","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"AvenirNext-Medium","fontSize":13,"lineHeight":24,"tracking":0,"textColor":"#7c7c7c"}},"textStyles":{"default-tag-code":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"},"default-tag-pre":{"textAlignment":"left","fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f","paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-tag-samp":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"}},"componentLayouts":{"body-layout":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":30}},"blockquote-layout":{"contentInset":{"bottom":true,"left":true,"right":true,"top":true}},"headerPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7},"headerPhotoLayoutWithCaption":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7,"margin":{"bottom":24}},"headerBelowTextPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7,"margin":{"top":30,"bottom":0}},"title-layout":{"margin":{"top":30,"bottom":0}},"byline-layout":{"margin":{"top":10,"bottom":10},"columnStart":0,"columnSpan":7}},"metadata":{"thumbnailURL":"bundle:\/\/iphone-xr-deals.jpg","dateCreated":"2020-10-27T12:23:59+00:00","dateModified":"2020-10-27T06:23:20+00:00","datePublished":"2020-10-27T12:23:59+00:00","canonicalURL":"https:\/\/www.theapplebyte.net\/iphone-xr-deals\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"2.1.0"},"autoplacement":{"advertisement":{"bannerType":"any","distanceFromMedia":"10vh","enabled":true,"frequency":5,"layout":{"margin":15}}}}
--7c74f9393f8c7e0509352bc319d7f5d1
Content-Type: application/octet-stream
Content-Disposition: form-data; name=iphone-xr-dealsjpg; filename=iphone-xr-deals.jpg; size=55617

(binary contents of iphone-xr-deals.jpg)
--7c74f9393f8c7e0509352bc319d7f5d1--

**Comment by kevinfodness** [comment]
Hi @iMangoss —

Thanks for using our plugin! I'll do my best to help you out.

This error is being reported by the `cURL` program on your webserver, and indicates that your webserver isn't able to look up the IP address of Apple's servers using the DNS protocol. That indicates that there is a networking problem with your webserver. Unfortunately, this is a problem with your webserver itself, and isn't something that is controlled by the plugin.

This article indicates that there may be problems with resolving certain DNS entries if your server is using Google's DNS servers in some regions: https://www.digitalocean.com/community/questions/how-to-solve-curl-error-28-resolving-timed-out-after-10518-milliseconds

I would recommend reaching out to your hosting provider to validate the DNS settings and diagnose the issue from there. The specific Apple hostname that the plugin is attempting to access is `news-api.apple.com`. While connected to your webserver, you should be able to look up that domain name and get a response. For example, on a linux system, while ssh'd in, you should be able to run `host news-api.apple.com` and get a response similar to this:

```
news-api.apple.com is an alias for publisher-api.news.apple-dns.net.
publisher-api.news.apple-dns.net has address 17.56.48.13
```
