### ISSUE TITLE
Provide examples for using the `apple_news_generate_json` filter

### ISSUE THREAD

**Issue by matthewmcvickar** [alleyinteractive/apple-news#820]
I have a site where the client wants to use different gallery component layouts for different galleries. Currently, this Publish to Apple News plugin provides a switch to turn all galleries to either `gallery` (a scrolling carousel) or `mosaic`.

I got around this by inserting a token before the gallery I want to be a mosaic instead and looking for that token when processing the JSON. It took a bit of trial and error to see how I could walk through and edit the components in the JSON response. For example, to access the body components I had to look at the source code to figure out the structure of the JSON required `$json['components'][1]['components']` to get at the article body components.

Could you add an example of how to use this filter, and perhaps other examples for things commonly done with other filters?

Also, if there's a better way to have done this, let me know. Here's how I did it:

Template code:

```php
// ...
<h3>Mosaic Image Gallery</h3>
<p>mosaic-layout</p> // The token we'll look for in the `apple_news_generate_json` hook.
<div class="gallery">
<?php
foreach ( $gallery['items'] as $item ) {
// ...
```

And then my function on the `apple_news_generate_json` filter hook:

```php
// Use the mosaic format instead of the standard scrolling gallery format for certain galleries.
function apple_news__set_gallery_to_mosaic_for_product_slideshows( $json, $post_id ) {
  // The header is the first element in the `components` array, so get the
  // second element in the array, which has the body components.
  $body_components = $json['components'][1]['components'];

  // The placeholder token to look for.
  $mosaic_gallery_token = '<p>mosaic-layout</p>';

  // Go through each component.
  foreach ( $body_components as $index => $component ) {
    // Check if component is a mosaic gallery token.
    if ( $component['text'] == $mosaic_gallery_token ) {
      // Go to the next element and change its role to mosaic.
      $body_components[$index + 1]['role'] = 'mosaic';

      // Empty this marker component to hide it.
      $body_components[$index] = array();
    }
  }

  // Update the JSON and return it.
  $json['components'][1]['components'] = $body_components;

  return $json;
}
add_filter( 'apple_news_generate_json', 'apple_news__set_gallery_to_mosaic_for_product_slideshows', 99, 2 );
```

**Comment by kevinfodness** [comment]
Yep, this is a fine way to do it. We recently revamped our action and filter hook section of the wiki to be significantly more detailed and complete: https://github.com/alleyinteractive/apple-news/wiki/Action-and-Filter-Hooks

Clicking on any of the hook names will take you to a detail view, like this: https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_generate_json
