### ISSUE TITLE
Latest Ally Interactive Apple News plugin update

### ISSUE THREAD

**Issue by Alexmcleman1** [alleyinteractive/apple-news#821]
I am wanting to check this is the latest Ally Interactive update for the Apple News plugin that features End of Article experiences.

https://wordpress.org/support/plugin/publish-to-apple-news/

Thanks

A

**Comment by kevinfodness** [comment]
Yes, version `2.1.0` is the latest, and yes, it features the End of Article feature, which is documented more fully here: https://github.com/alleyinteractive/apple-news/wiki/Customizing-JSON#end-of-article

**Comment by Alexmcleman1** [comment]
Great, thanks for the update.

One more on this topic. Is it possible to build multiple EoA experiences?

Such as having one or two on top of one another?

A

**Comment by kevinfodness** [comment]
There's only the one field, but you can add whatever JSON you want there, so you could use the one field but add multiple containers so visually it appears that there are more than one.

**Comment by Alexmcleman1** [comment]
I have an another question regarding adding styling to a container.

I am looking to add an underline to the top text layer "ENERGY VOICE \u2013 Join The Global Energy Conversation", but I keep getting either an error message or the update does not appear.

Would you be able to provide insight into where I would add the object:

"underline": {
        "color": "#FFC800"
}

Below is the full field.

{
    "role": "container",
    "style": {
        "backgroundColor": "#f2f2f2",
        "conditional": [
            {
                "backgroundColor": "#565656",
                "conditions": [
                    {
                        "preferredColorScheme": "dark",
                        "minSpecVersion": "1.14"
                    }
                ]
            }
        ]
    },
    "components": [
        {
            "role": "container",
            "components": [
                {
                    "role": "body",
                    "text": "ENERGY VOICE \u2013 Join The Global Energy Conversation",
                    "textStyle": {
                        "Underlined": "true",
                        "fontName": "AvenirNext-Bold",
                        "textAlignment": "center",
                        "textTransform": "uppercase",
                        "conditional": [
                            {
                                "textColor": "#ffffff",
                                "conditions": [
                                    {
                                        "preferredColorScheme": "dark",
                                        "minSpecVersion": "1.14"
                                    }
                                ]
                            }
                        ]
                    },
                    "format": "html"
                },
                {
                    "role": "body",
                    "text": "Get the latest news and insight: what matters in oil & gas, power and the energy transition.",
                    "format": "html",
                    "textStyle": {
                        "fontName": "AvenirNext-Regular",
                        "textAlignment": "center",
                        "conditional": [
                            {
                                "textColor": "#ff481a",
                                "conditions": [
                                    {
                                        "preferredColorScheme": "dark",
                                        "minSpecVersion": "1.14"
                                    }
                                ]
                            }
                        ]
                    },
                    "layout": {
                        "maximumContentWidth": "60cw"
                    }
                },
                {
                    "role": "link_button",
                    "URL": "https:\/\/www.energyvoice.com\/subscribe\/",
                    "text": "Subscribe",
                    "textStyle": {
                        "textColor": "#ff481a",
                        "fontName": "AvenirNext-Bold",
                        "fontSize": 18,
                        "lineHeight": 18,
                        "textAlignment": "center",
                        "textTransform": "none",
                        "conditional": [
                            {
                                "textColor": "#ff481a",
                                "conditions": [
                                    {
                                        "perferredColorScheme": "dark",
                                        "minSpecVersion": "1.14"
                                    }
                                ]
                            }
                        ]
                    },
                    "style": {
                        "backgroundColor": "#4f4f4f",
                        "mask": {
                            "type": "corners",
                            "radius": 5
                        }
                    },
                    "layout": {
                        "minimumContentWidth": 400,
                        "margin": {
                            "top": 15
                        },
                        "padding": {
                            "top": 15,
                            "bottom": 15,
                            "left": 40,
                            "right": 40
                        }
                    }
                },
                {
                    "role": "link_button",
                    "URL": "https:\/\/www.energyvoice.com\/category\/podcast\/",
                    "text": "Listen",
                    "textStyle": {
                        "textColor": "#ff481a",
                        "fontName": "AvenirNext-Bold",
                        "fontSize": 18,
                        "lineHeight": 18,
                        "textAlignment": "center",
                        "textTransform": "none",
                        "conditional": [
                            {
                                "textColor": "#ff481a",
                                "conditions": [
                                    {
                                        "perferredColorScheme": "dark",
                                        "minSpecVersion": "1.14"
                                    }
                                ]
                            }
                        ]
                    },
                    "style": {
                        "backgroundColor": "#4f4f4f",
                        "mask": {
                            "type": "corners",
                            "radius": 5
                        }
                    },
                    "layout": {
                        "minimumContentWidth": 400,
                        "margin": {
                            "top": 15
                        },
                        "padding": {
                            "top": 15,
                            "bottom": 15,
                            "left": 40,
                            "right": 40
                        }
                    }
                },
                {
                    "role": "link_button",
                    "URL": "https:\/\/www.energyvoice.com\/",
                    "text": "Read",
                    "textStyle": {
                        "textColor": "#ff481a",
                        "fontName": "AvenirNext-Bold",
                        "fontSize": 18,
                        "lineHeight": 18,
                        "textAlignment": "center",
                        "textTransform": "capitalize",
                        "conditional": [
                            {
                                "Underlined": "true",
                                "textColor": "#ff481a",
                                "conditions": [
                                    {
                                        "perferredColorScheme": "dark",
                                        "minSpecVersion": "1.14"
                                    }
                                ]
                            }
                        ]
                    },
                    "style": {
                        "backgroundColor": "#4f4f4f",
                        "mask": {
                            "type": "corners",
                            "radius": 5
                        }
                    },
                    "layout": {
                        "minimumContentWidth": 400,
                        "margin": {
                            "top": 15
                        },
                        "padding": {
                            "top": 15,
                            "bottom": 15,
                            "left": 40,
                            "right": 40
                        }
                    }
                }
            ]
        }
    ]
}

**Comment by kevinfodness** [comment]
I think it's because you've capitalized `underline`. It should be all lowercase: https://developer.apple.com/documentation/apple_news/textstyle
