### ISSUE TITLE
Apple news cover component image should have apple_news_build_image_src filter

### ISSUE THREAD

**Issue by ShashwatMittal** [alleyinteractive/apple-news#822]
When we try to filter the image URLs for an article we have `apple_news_build_image_src`, but it currently only applies to the body of the article. The featured image of the article does not follow the same approach. That should also follow the same filter.
Filter exists in
https://github.com/alleyinteractive/apple-news/blob/develop/includes/apple-exporter/components/class-image.php#L183
Need to be added in
https://github.com/alleyinteractive/apple-news/blob/develop/includes/apple-exporter/components/class-cover.php#L157-L169

**Comment by kevinfodness** [comment]
The cover image is actually built using a different process, and the information is passed into the cover component. The filter you are looking for is `apple_news_exporter_post_thumb`: https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_exporter_post_thumb

Additionally, you can filter the cover image caption: https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_exporter_cover_caption

**Comment by ShashwatMittal** [comment]
@kevinfodness Thanks for the quick response. I think that's reasonable in that case.
