### ISSUE TITLE
Clarify source of admin errors

### ISSUE THREAD

**Issue by mslinnea** [alleyinteractive/apple-news#823]
When there is an error from the API, the error message says "There has been an error with the API: DUPLICATE_ARTICLE_FOUND" (for example).  It would be nice to have this say "from the Apple News API" to clarify the source.  There are also other error messages that stem from this plugin that do not specify their source.  It would make troubleshooting easier if the error said it was from the Apple News plugin.

**Comment by kevinfodness** [comment]
PR merged.
