### ISSUE TITLE
Display Error Value Field for DUPLICATE_ARTICLE_FOUND

### ISSUE THREAD

**Issue by mslinnea** [alleyinteractive/apple-news#824]
According to [Apple documentation](https://developer.apple.com/documentation/apple_news/update_an_article), DUPLICATE_ARTICLE_FOUND error happens for the following reasons:

>DUPLICATE_ARTICLE_FOUND. An article with a source URL or a thumbnail is considered a duplicate if the article is posted on the same channel, using the same title, source URL, or thumbnail, within a 24-hour period. An article without a source URL and thumbnail is considered a duplicate if the article is posted on the same channel, using the same title, within a 24-hour period. The original article ID is provided in the value field.

Note that it says that the "**The original article ID is provided in the value field.**"

It would be helpful if this original article ID were displayed in the error message so that we could track down what article Apple thinks this is a duplicate of.

**Comment by kevinfodness** [comment]
This is a good idea. Also, #833 is likely related to this, as it was causing a disconnect between WordPress and Apple when using Gutenberg under certain circumstances, which would lead to a situation where the article in WP should have been updating on Apple, but was instead publishing a new article, which was flagged as a duplicate.

**Comment by kevinfodness** [comment]
Fixed via #971
