### ISSUE TITLE
Table Background in Dark Mode

### ISSUE THREAD

**Issue by chumbothewhale** [alleyinteractive/apple-news#830]
HTML tables have a black background with black text when viewed on Mac dark mode. If "role" is "htmltable" then I suggest adding:

`"style": {
            "backgroundColor": "#ffffff"
          },`

**Comment by kevinfodness** [comment]
Thanks for the issue report. We recently added support for dark mode in the plugin - I will test it again with tables specifically.

**Comment by kevinfodness** [comment]
I confirmed that the dark mode table background color selection in the theme customizer is not properly translating to the output.

**Comment by kevinfodness** [comment]
Fixed via #978
