### ISSUE TITLE
Is there a way to download article JSON files without adding API keys?

### ISSUE THREAD

**Issue by benlk** [alleyinteractive/apple-news#832]
My use case is that I'm a developer working for an agency that's contracted to work on a large site. That large site doesn't hand out their API credentials to anyone.

Do I really need an API key to generate downloadable articles for use with Apple News Preview? 

My expectation is that, even without an API key:
- I'd be able to see the list of articles at `wp-admin/admin.php?page=apple_news_index`
- I'd be able to [download articles from that page](https://github.com/alleyinteractive/apple-news/wiki/usage#downloading-posts)

**Comment by benlk** [comment]
resolution: By adding fake credentials (channel id `test`, API key `test`, API secret `test) the plugin unlocked far enough to allow me to see the "Download" buttons.

**Comment by kevinfodness** [comment]
Glad you got a resolution!
