### ISSUE TITLE
Question: Multiple Apple News Theme Options

### ISSUE THREAD

**Issue by Greigh** [alleyinteractive/apple-news#838]
Hello,
I am looking over my Autoload options and I notice several Apple news theme inserts. They aren't on for autoload, but are all of them necessary? 
![Screen Shot 2021-02-26 at 12 58 46 PM](https://user-images.githubusercontent.com/57759540/109337414-c2648e80-7832-11eb-8355-da3a530fa6e5.png)

Thanks for your help!

**Comment by kevinfodness** [comment]
These options contain the theme configuration for each of the loaded themes. You can remove these options by deleting themes you aren't using.
