### ISSUE TITLE
Some posts are not being published automatically.

### ISSUE THREAD

**Issue by jlariza** [alleyinteractive/apple-news#845]
Good day,

We are using the plugin in our site to publish the posts on apple news. This is how the plugin is currently configured:

![image](https://user-images.githubusercontent.com/16421045/110702089-115ddc80-81c0-11eb-8a4a-27bba3a23120.png)

However, not all posts are being published automatically. We have to go and hit "Publish" on `/wp-admin/admin.php?page=apple_news_index` once a post is created. Else, it will not appear on apple news.

What are we missing to make sure that all posts are published automatically?

Thank you,

**Comment by kevinfodness** [comment]
On Apple News > Settings, enable debugging and enter your email address as the admin email. When a post attempts to publish, you will receive an email with a lot of information in it, which includes the response from the Apple API. If you receive the email and there is an error in the response, take a look at what it is telling you and see if you can resolve the errors. If you don't receive the email at all, then that tells you that it's not attempting to publish at all. Also, I'm assuming that all of the articles you are attempting to publish are posts and are not the other types that aren't selected (media, views, premium issues, premium article, templates, biography, commentary, etc)?

**Comment by jlariza** [comment]
Thank you @kevinfodness . We will try debugging to discard that it is an error from the server.


Yes, we are publishing only posts; no other post type.

**Comment by kevinfodness** [comment]
Hi @jlariza - any updates here? Were you able to figure out what was going wrong?
