### ISSUE TITLE
Articles with tables not posting to Apple News

### ISSUE THREAD

**Issue by ghost** [alleyinteractive/apple-news#847]
I run an Apple News page for an online magazine news site and have recently been running into this issue where articles with tables won't post to An and throw these codes. IDK what look for as I inherited the theme when I started but I would definitely like to get this fixed ASAP as our AN followers have missed a couple of big stories. 

<img width="1246" alt="Screen Shot 2021-04-01 at 10 28 38 PM" src="https://user-images.githubusercontent.com/81788286/113373825-b8561400-9339-11eb-99d4-3c1f2290871d.png">

**Comment by kevinfodness** [comment]
Can you provide the source HTML for the table? That will help me debug.
