### ISSUE TITLE
Toggling "Manual Section Selection" causes sections to not save properly

### ISSUE THREAD

**Issue by timbolimboslice** [alleyinteractive/apple-news#848]
In the plugin sidebar, if a user interacts with the "Assign sections by category" checkbox, it causes the `apple_news_section` meta key to be saved as an empty array. 

This then causes issues when adding sections later on as they get ignored by this **[check here](https://github.com/alleyinteractive/apple-news/blob/develop/admin/class-admin-apple-sections.php#L124)**. 

To replicate:
- Go to add a new post.
- Interact with checkbox, 'Assign sections by category' in plugin sidebar.
- Save draft
- Check the `apple_news_sections` meta_key in the wp_postmeta table. It should be an empty array.
- Go back to post, turn on  'Assign sections by category'.
- Add a mapped section
- Publish Post
- Check the `apple_news_sections` meta_key in the wp_postmeta table. It will still be an empty array. 

The filter `apple_news_get_sections_for_post` is also getting ignored.

**Comment by kevinfodness** [comment]
I've got a fix for this in #855.

**Comment by kevinfodness** [comment]
@timbolimboslice — I just released v2.1.3 which contains the fix for this issue. Can you try it out and let me know if it resolves the problem for you, please?
