### ISSUE TITLE
Apple News publish workflow - set to Draft Articles by default

### ISSUE THREAD

**Issue by kujain** [alleyinteractive/apple-news#849]
Hi there!

Is there a way to automate the publish workflow to set the article in AN in Draft mode by default? I am looking into this to be able to schedule WHEN an article gets published in AN. I could do this by setting the AN to manual publish but the Apple News interface for publishing would be much simpler.

As an alternative, is there a way to SCHEDULE the publishing of posts to Apple News from within the Wordpress CMS? Then the posts do not get automatically published but rather follow the scheduling times to publish. Ideally we can set the schedule based on specific post data (eg. article with a specific tag gets published at midnight etc.).

Thanks!!

**Comment by kevinfodness** [comment]
This is a great suggestion - I'll add it to the enhancements backlog.

**Comment by kevinfodness** [comment]
I'm removing this from the roadmap. If you have auto-publish set on articles in Publish to Apple News, and you schedule a WordPress post to publish at a certain time, it will also publish to Apple News at that time. If you want to default articles to draft, you can do that via a filter, but it's not a common enough use case to add it natively to the plugin.
