### ISSUE TITLE
There has been an error with the Apple News API: INVALID_ARTICLE_LANGUAGE

### ISSUE THREAD

**Issue by amooreTO** [alleyinteractive/apple-news#854]
My site is in French, and therefore all of our articles are in French.

Sometimes when we try to publish to Apple News, we get the following error: `There has been an error with the Apple News API: INVALID_ARTICLE_LANGUAGE`

Can you confirm what might be some of the reasons why this error might occur? Is there a way to force the article language to be French?

**Comment by hjbarraza** [comment]
In our case, we made the mistake of selecting the wrong language in the publication settings page. 
https://www.icloud.com/#newspublisher/

Do you have selected French (Your Country) as the Content Language?

<img width="953" alt="Screen Shot 2021-07-13 at 22 35 12" src="https://user-images.githubusercontent.com/519515/125557050-c474b2a9-f872-452d-816a-2c3b6e1e67b7.png">

**Comment by kevinfodness** [comment]
The plugin uses the language of the site (specifically, `get_bloginfo( 'language' )`, but it can be filtered using https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_exporter_language. I would expect that the setting for the site language would remain consistent, so it's not clear to me why this would only fail some of the time. However, you could use the filter to ensure it is always set to the correct value. However, note that Apple News only supports English and Canadian French, so you will need to ensure that the language code is `fr-ca`.

> Note: Apple News supports content only in English and Canadian French. If you select a different language and Apple News later adds support for that language, you'll be notified by email.

ref: https://support.apple.com/guide/news-publisher/apply-to-publish-using-apple-news-format-apde42330c66/1.0/icloud/1.0

**Comment by amooreTO** [comment]
@kevinfodness just wanted to update you that filtering `apple_news_exporter_language` and forcing the language to be `fr-ca` worked for me :)

**Comment by kevinfodness** [comment]
Great!
