### ISSUE TITLE
Apple News Error Messages

### ISSUE THREAD

**Issue by SustainHealth** [alleyinteractive/apple-news#862]
Hi Kevin,

Hopefully the attached loads up ok this time.

Thanks again.

Andy

![Screenshot 2021-07-06 at 19 03 44](https://user-images.githubusercontent.com/73250758/124653899-c5812280-de95-11eb-9c07-413f4bd48bc5.png)

**Comment by kevinfodness** [comment]
All of these are issues with the image URLs specified. For the ones that point to domains other than yours, such as Twitter or Instagram or Gmail, it's likely that those providers are preventing Apple from downloading the images, and that is why you are getting the "could not access URL" message. For the others, the common factor seems to be special characters in the URL, such as quote marks or accents on the characters. Is publish failing on _all_ articles, or only some? Can you try publishing an article with images that don't have special characters in them (which you should be able to do by re-uploading a copy of the image to the media library with the special characters replaced by non-accented versions of the letters)?

Fundamentally, these are errors that are coming from Apple's News API and they are rejecting the URLs you are specifying for some of these images.

**Comment by SustainHealth** [comment]
Ah I totally understand.

The majority of articles publish without any problems.

Thank you for clarifying.

As always your time is much appreciated.
