### ISSUE TITLE
Getting certain font style not available in wordpress 5.7.2

### ISSUE THREAD

**Issue by balajikrishnannewsuk** [alleyinteractive/apple-news#864]
Hello Team,

I am getting certain font style is not available in wordpress 5.7.2, could you please help me to resolve the same.

Thanks,
Balaji K
![Screenshot 2021-07-15 at 12 09 56 PM](https://user-images.githubusercontent.com/62639915/125902056-3d7580e3-b732-43a2-904c-adc517bdf3ef.png)

**Comment by kevinfodness** [comment]
Custom fonts need to be loaded on Apple's side. Have you contacted Apple to have them load the custom font onto your channel? The error you are seeing is from Apple's API, so it will need to be handled from their end.
