### ISSUE TITLE
Relative URL Image SRC Problem

### ISSUE THREAD

**Issue by bjm1** [alleyinteractive/apple-news#865]
Currently $meta['thumbnailURL'] in class-metadata.php does not apply a filter. 

Should the "apple_news_build_image_src" filter also apply to $meta['thumbnailURL']?

My problem is that relative urls are being returned in the json instead of absolute urls (because of another plugin). 

Should the script check to make sure all urls are absolute for all images, links, etc.

**Comment by kevinfodness** [comment]
There is some logic in the plugin already to handle root-relative URLs, but it's possible that it's not firing in your case. I can look into this for inclusion in the plugin, but you can also filter the final JSON and replace them yourself in the interim: https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_generate_json

**Comment by kevinfodness** [comment]
This seems related to #852 so I'm going to track progress there.
