### ISSUE TITLE
Images aligned to the side with links are not working

### ISSUE THREAD

**Issue by misaalami** [alleyinteractive/apple-news#867]
If an image is aligned to the side **and** has a link attached to it, then it will either be stripped from the content, or have the wrong "layout". It is nonetheless a bug that needs to be addressed.

To replicate this issue:

1. Insert an image in the content.
2. Align it to the left.
3. Click on the image block, and then click the "Add Link" button.
4. Assign an external URL to this image.
5. Finally, check JSON. The image block is never converted properly. Sometimes, it can appear as `"layout": "full-width-image"` (which is incorrect), but most of the time it is stripped from the content.

Can you kindly look into this? Please feel free to give me a shout if you need any feedback on how to replicate this issue.

**Comment by misaalami** [comment]
Do you need any further insights in reproducing this issue? Thanks.

**Comment by kevinfodness** [comment]
Thanks for the report, @misaalami - I will look into this as part of a future update.

**Comment by misaalami** [comment]
Thanks very much @kevinfodness. Please let me know if you need anything from my end. I tested this again on a fresh install and the bug is definitely there.

**Comment by kevinfodness** [comment]
I can't replicate the behavior of the image being stripped from the content, but the image does indeed go full width.

**Comment by misaalami** [comment]
> I can't replicate the behavior of the image being stripped from the content, but the image does indeed go full width.

@kevinfodness I just tested it, and yes, you are right. With the current version of the plugin, the image goes full width. Like this:

        {
          "role": "photo",
          "URL": "bundle://example.jpg",
          "layout": "full-width-image"
        },

Would be great to have this bug resolved in the upcoming versions. Thanks Kevin.

**Comment by kevinfodness** [comment]
Yep, I've marked this a bug so we can resolve it. I can confirm that wrapping the image in a link is what causes it to no longer respect the alignment setting.

**Comment by dlh01** [comment]
This should be addressed by #1116, which will be included in the upcoming version 2.5 release. Please follow up if you continue to experience this issue after updating. Thanks!
