### ISSUE TITLE
wp_after_insert_post fires twice

### ISSUE THREAD

**Issue by PypWalters** [alleyinteractive/apple-news#871]
When publishing a post to apple news with autosync and auto update enabled, the hook `wp_after_insert_post` fires twice creating an error saying "Skipped push of article {post_id} because it is already in sync"

Removing the hook within do_publish resolves the issue:
`remove_action( 'wp_after_insert_post', [ $this, 'do_publish' ], 10, 2 );`

**Comment by kevinfodness** [comment]
That is likely an unfortunate side effect of how Gutenberg works. If you have metaboxes, Gutenberg actually triggers two requests - the first to save things that Gutenberg is responsible for, and the second to save the content of metaboxes. There is no way to know whether an update is going to trigger two requests, or whether a second request is coming after the first, so the `wp_after_insert_post` hook would fire twice in that case. More info here: https://github.com/WordPress/gutenberg/issues/15094
