### ISSUE TITLE
Custom Post Types are posting to Apple News, even though they are not selected

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/apple-news#879]
Copied from WordPress.org: https://wordpress.org/support/topic/custom-post-types-are-posting-to-apple-news-even-though-they-are-not-selecte/

Original text:

> Hi There, We are having an intermittent problem where Post Types that have not been selected under “Choose the post types that are eligible for publishing to Apple News.” Are still being published. This does not happen every single time, which makes debugging the issue difficult. Any recommendations on how to solve? We are on the most up to date version of the plugin currently.

**Comment by sarahlesh** [comment]
Thanks for looking into it! It's a strange one.

**Comment by kevinfodness** [comment]
This seems to be working as expected for me—I can't reproduce the issue. Can you provide some additional details about the steps you are taking? Is this for a specific post type? Is the post type built in or custom? Do you have the auto-sync feature turned on, or are you triggering a publish manually? Any additional information you can provide would be helpful.

**Comment by AnselTk1** [comment]
We are having this issue as well. Only "posts" is selected for auto publishing but it appears to be auto publishing all post types. Auto Publish is turned on. When I view the post editor for the custom post types the Apple News meta box is not displayed.

**Comment by lobitoisaias** [comment]
Hola me puden ayudar con un problema que me sale en la aplicación. me sale clave invalida.

**Comment by kevinfodness** [comment]
I'm still not able to reproduce this issue, and the very first thing the post autosync function does is check to see if the post type is in the list of enabled post types before continuing with the push.
