### ISSUE TITLE
Manual publish yields error

### ISSUE THREAD

**Issue by antonkusters** [alleyinteractive/apple-news#88]
Hi,

Since a few weeks the manual publish button (both in a WordPress post and in the post list of plugin) seems to have stopped working, showing the following error in WP: 

> "There has been an error with the API. Please make sure your API settings are correct and try again: INVALID_DOCUMENT, INVALID DOCUMENT"

I have checked and re-entered all API keys to no avail. The plugin worked fine before that, there was no specific event or anything in our posting habits that triggered this (to my knowledge).

I enabled debugging, and this is the detailed error message:

```
Array 
( 
[headers] => Array 
( 
[date] => Tue, 08 Mar 2016 11:18:51 GMT 
[request-id] => 1814d88d-485b-4c7b-9963-45996e3c4837 
[content-type] => application/json; charset=UTF-8 
[content-length] => 281 
[connection] => keep-alive 
) 

[body] => {"errors":[{"code":"INVALID_DOCUMENT","keyPath":["root","components","[3]","text"],"message":"\"text\" was \"\\\"\\\"\" should be not (null or an empty string)"},{"code":"INVALID_DOCUMENT","keyPath":["root","components","[3]"],"message":"no components defined for role=heading4"}]} 
[response] => Array 
( 
[code] => 400 
[message] => Bad Request 
) 

[cookies] => Array 
( 
) 

[filename] => 
) 

```
using latest version of WP, and (i think) latest version of this plugin (v1.0.5)

thank you,

anton

**Comment by bcampeau** [comment]
The Apple News plugin yields this error for any document that has a parsing error. The only way to find the actual error is to download the JSON file and images and drag it into the News Preview tool. You can then debug and fix the actual error.

**Comment by antonkusters** [comment]
Thank you for pointing me in the right direction. I was able to fix the post.

FYI, the error was that there was a HTML H4 tag with no content inside at the start of the post, it threw the following error on Apple News preview:

```
Error: "text" was "\"\"" should be not (null or an empty string)
document -> components -> [3] -> text

Error: no components defined for role=heading4
document -> components -> [3]
```

Apparently the fact that it was empty caused the error.

thanks again,
a
