### ISSUE TITLE
Fail gracefully when a CPT doesn't have support for custom-fields

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/apple-news#884]
Currently, if a user is using the Gutenberg editor with a custom post type, and they haven't registered the custom post type with support for `custom-fields`, then the plugin's code will cause Gutenberg to crash. The `usePostMeta` custom hook is assumed to return an object for meta and a function for setting meta, but if there is no support for meta on the post type, it will instead return `[undefined, undefined]`.

1. Make the `usePostMeta` custom hook more robust by ensuring it always returns an object (even if the object is empty) and a function (the function should just do `console.error` with a message about why it isn't able to save postmeta). This should fix the issue with the editor crashing.
2. Determine if the post doesn't support `custom-fields` and display a warning message to the user instructing them on how to add support for `custom-fields` to the post type in order to use the Publish to Apple News plugin.

**Comment by kevinblanco** [comment]
Thanks @kevinfodness that worked out.
