### ISSUE TITLE
Can't get the Alley Apple News Plugin to work

### ISSUE THREAD

**Issue by bcpatters** [alleyinteractive/apple-news#885]
I have everything setup with Apple however after their plugin update, the Alley plugin is asking for a custom configuration file or .papi file -or- to enter the details manually but I have no idea how to do either.  No real step-by-step listing on the plugin manufacturer's site and Apple is passing the buck.  HELP!

**Comment by bcpatters** [comment]
Help!

**Comment by kevinfodness** [comment]
I created a new section on our wiki with detailed instructions on working with `.papi` files: https://github.com/alleyinteractive/apple-news/wiki/configuration#api-settings
