### ISSUE TITLE
Not possible to publish to a specific Apple News Section

### ISSUE THREAD

**Issue by antonkusters** [alleyinteractive/apple-news#89]
Hi,

When creating sections within Apple News, there seems to be no way to publish a post from WP to a specific Apple News section (using the manual publish button)

There seem to be no controls or settings to be able to switch from the default section to any other section. Could this functionality possibly be added to the plugin? e.g. via the "Options" link (now used to set the pull quote)?

I'm asking because It is not possible from within iCloud Apple News manager (or any other place that I'm aware of) to move a published post to a different section manually.

thanks...

a

**Comment by bcampeau** [comment]
I'll look into this in the next couple weeks and see what can be done here.

**Comment by antonkusters** [comment]
Thanks... we have about 965 stories that fit into a few different sections... we're making good use of the plugin for sure 😊 

thanks again,

a

**Comment by Asif2BD** [comment]
Any update? Or timeframe when we could have this? Much needed.
