### ISSUE TITLE
pluginSidebar.js include code causing error

### ISSUE THREAD

**Issue by robbie-hay** [alleyinteractive/apple-news#890]
I am using the latest version of Publish to Apple News 2.2.2 with the latest version of WP 5.8.1. There seems to be an error in the plugin when I open a post type that I enable for Apple News, but do NOT want to have a side bar meta box. 

To fix the issue, I had to update your plugin code in includes/class-apple-news.php at line 340 with the following code. Fill free to use to fix or perhaps this can be resolved elsewhere in your code.

> // Bail if "Show a publish meta box on post types that have Apple News enabled." is configured as "No" in settings. pluginSidebar.js is unnecessary and causes an error with react.
> if ( Admin_Apple_Settings_Section::$loaded_settings['show_metabox'] == 'no' ) { return; }

Below is the error readout in the browser from the editor with [myhostdomain] being a replacement for my domain url. Looks to be a possible react duplication error.

> render@[myhostdomain]/wp-content/plugins/publish-to-apple-news/build/pluginSidebar.js?ver=399a6e300bdaabf151f1faecd2cfb13e:2:34643
> we@[myhostdomain]/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:84:294
> zj@[myhostdomain]/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:226:498
> Th@[myhostdomain]/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152:225
> tj@[myhostdomain]/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152:154
> Te@[myhostdomain]/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146:153
> Te@[native code]
> [myhostdomain]/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61:69
> unstable_runWithPriority@[myhostdomain]/wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25:261
> Pg@[myhostdomain]/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61:16
> ha@[myhostdomain]/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60:453
> Ja@[myhostdomain]/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:224:402
> ch@[myhostdomain]/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:93:81
> ch@[native code]
> e@[myhostdomain]/wp-includes/js/dist/data.min.js?ver=a9e98fe3ad76884fe7909ba8348395b7:2:20892
> t@[myhostdomain]/wp-includes/js/dist/data.min.js?ver=a9e98fe3ad76884fe7909ba8348395b7:2:20959
> [myhostdomain]/wp-includes/js/dist/data.min.js?ver=a9e98fe3ad76884fe7909ba8348395b7:2:15083
> b@[myhostdomain]/wp-includes/js/dist/data.min.js?ver=a9e98fe3ad76884fe7909ba8348395b7:2:8589
> [myhostdomain]/wp-includes/js/dist/redux-routine.min.js?ver=fd5f93d1f8206c65d1891cf1f898211e:2:1354
> some@[native code]
> r@[myhostdomain]/wp-includes/js/dist/redux-routine.min.js?ver=fd5f93d1f8206c65d1891cf1f898211e:2:9237
> [myhostdomain]/wp-includes/js/dist/redux-routine.min.js?ver=fd5f93d1f8206c65d1891cf1f898211e:2:9187
> [myhostdomain]/wp-includes/js/dist/redux-routine.min.js?ver=fd5f93d1f8206c65d1891cf1f898211e:2:6329
> some@[native code]
> r@[myhostdomain]/wp-includes/js/dist/redux-routine.min.js?ver=fd5f93d1f8206c65d1891cf1f898211e:2:9237
> [myhostdomain]/wp-includes/js/dist/redux-routine.min.js?ver=fd5f93d1f8206c65d1891cf1f898211e:2:9182
> promiseReactionJob@[native code]

**Comment by kevinfodness** [comment]
Thanks for the report. The metabox setting only applies to the classic editor - the Gutenberg PluginSidebar is always present on post types that are configured to support Apple News. Users can choose to hide it or not using the Gutenberg controls. However, it shouldn't be erroring like this. I'll look into it.

**Comment by kevinfodness** [comment]
I think this is actually related to #884, for which I have a fix. I'm going to close this, but if the issue continues once I have published the next version of the plugin (2.3.0) let me know.
