### ISSUE TITLE
After updating to 2.2.2 version not working anymore (I did the PAPI thing)

### ISSUE THREAD

**Issue by kevinblanco** [alleyinteractive/apple-news#891]
Hello, 

My site has been using the 2.1.2 version plugin for a long time, and after updating to 2.2.2 the publishing to apple news does not work. 

I followed the guidelines mentioned on your Wiki to generate a PAPI file, which I validated with `papi-client channel get` command and I got a success response. 

When I try to publish a new article to Apple News this is the error I get:

 
```Fatal error: Uncaught Error: Class '\Apple_Exporter\Components\Slug' not found in /code/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/class-component-factory.php:196 Stack trace: #0 /code/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php(515): Apple_Exporter\Component_Factory::get_components_from_node(Object(DOMText)) #1 /code/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php(796): Apple_Exporter\Builders\Components->get_components_from_node(Object(DOMText)) #2 /code/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php(42): Apple_Exporter\Builders\Components->split_into_components() #3 /code/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-builder.php(66): Apple_Exporter\Builders\Components->build() #4 /code/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/class-exporter.php(219): Apple_Exporter\Builders\Builder->to_array() #5 in /code/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/class-component-factory.php on line 196```

I made sure I used the right CMS API , I even generated a new pair of keys which I validated and read all your wiki, no success. 

Please help.

**Comment by kevinblanco** [comment]
PHP Version 7.3 
WordPress 5.7.2

**Comment by kevinfodness** [comment]
It sounds to me like not all of the files made it onto your server during the upgrade. The slug component was a new component that was added in version 2.2, and there should be a file for it at `includes/apple-exporter/components/class-slug.php`. If that file is not present at that path in the plugin folder, then that's the problem. I would recommend removing and re-installing the plugin to ensure you have all of the files for the latest version.

**Comment by kevinblanco** [comment]
Hello Kevin, 

Thanks for the reply, I did tried to reinstall and you were right, now the plugin is installed and it publishes content successfully. Now, I have another (bigger) problem I'd like to ask for any advise, when I try to edit any article on the site, the site goes down and i get this error: 

```
TypeError: Cannot read properties of undefined (reading 'apple_news_api_created_at')
    at render (/plugins/publish-to-apple-news/build/pluginSidebar.js?ver=399a6e300bdaabf151f1faecd2cfb13e:2:34671)
    at we (wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:84:293)
    at zj (wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:226:496)
    at Th (wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152:223)
    at tj (wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:152:152)
    at Te (wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:146:151)
    at wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61:68
    at unstable_runWithPriority (wp-includes/js/dist/vendor/react.min.js?ver=16.13.1:25:260)
    at Da (wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:60:280)
    at Pg (wp-includes/js/dist/vendor/react-dom.min.js?ver=16.13.1:61:14)
```

Do you have any idea of what could have caused this? I also turned off `Show a publish meta box on post types that have Apple News enabled.` to see if that helps, and it does not. 

Thanks in advance @kevinfodness

**Comment by kevinfodness** [comment]
Yes, that is most likely due to you using a custom post type that is not registered with support for `custom-fields` (which is required for Apple News to be able to save data to postmeta). More info at #884. I'm going to close this issue in favor of that one. If you have additional questions, you can post them there.
