### ISSUE TITLE
Apple News API: FAILED_TO_PARSE_IMAGE...is there a way to strip non-supported images before post?

### ISSUE THREAD

**Issue by tripslip38** [alleyinteractive/apple-news#909]
Long before I knew I needed to push articles to Apple News, I created a Wordpress site that uses SVGs for icons and certain images. SVG is cool...really flexible vector format that's supported by modern browsers.

But in posting to the Apple News API, it errors with
`Apple News API: FAILED_TO_PARSE_IMAGE - Failed to parse image with URI [https://domain/wp-content/uploads/2021/07/imagename.svg]`

Probably not going to convince Apple to change their API but is it possible to use this plugin as a mechanism to strip unsupported image types from the post content so that we can at least get the content through? My only other option is to go back and replace every SVG with bitmaps. Would rather not do that just for Apple News.

**Comment by kevinfodness** [comment]
Yep, you can do that via a filter. The easiest way of handling it is likely the [apple_news_exporter_content filter](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_exporter_content). You should be able to do a find and replace on image tags that reference SVGs and just remove them from the flow, or programmatically replace them with alternate references, if that's viable.

**Comment by tripslip38** [comment]
Nice. I'm using the Alley WP plugin though, and I don't see any options to define filters in the admin pages. Is it something I should define in functions.php?

**Comment by kevinfodness** [comment]
Yep, that's right, you would put the filter in your functions.php file.

**Comment by tripslip38** [comment]
Kevin, I need a little guidance in how to utilize the filter. Do I do something like this in functions.php?

```
apply_filters( 'apple_news_exporter_content', $content, $post->ID );

function apple_news_exporter_content($content){
	
   $content = preg_replace('/<img[^>]+./','', $content);
   return $content;

}
```
Wondering if this is more of a skeleton that identifies the variables in use for the state of the page processing, or if there is already a function defined called apple_news_exporter_content?

**Comment by kevinfodness** [comment]
No, you need to use `add_filter`, like this: https://developer.wordpress.org/plugins/hooks/filters/

An example would be something like:
```php
function my_theme_filter_apple_news_exporter_content( $content ) {
    $content = preg_replace('/<img[^>]+./','', $content);
    return $content;
}
add_filter( 'apple_news_exporter_content', 'my_theme_filter_apple_news_exporter_content' );
```

That logic would, of course, remove _all_ images from your content, so you will likely need to adjust the logic in the function.

**Comment by tripslip38** [comment]
Ok, that helps! yeah that function is pretty heavy handed, need to tune it to just strip one file type.

**Comment by tripslip38** [comment]
I've got this now in my functions.php:
```
function inv8_apple_news_exporter_content($content){
   $content = preg_replace('/<img src\s*=\s*"(.+svg)"[^>]*>/g','', $content);
   return $content;
}
add_filter( 'apple_news_exporter_content','inv8_apple_news_exporter_content');
```

But the API response is still: 

```
There has been an error with the Apple News API: FAILED_TO_PARSE_IMAGE - Failed to parse image with URI [https://domain/filepath/Mendelev_Mend-Patch.svg].
```

Am I doing that right? Regex is tested and does match the entire <img> tag.

**Comment by kevinfodness** [comment]
Yep, that's right. However, another location that uses images is in the metadata - it's possible the error is coming from there. Can you go to Apple News > Articles, find the article in question, and click the Download button to download the JSON? You should be able to search for `.svg` in that file and figure out what references remain. If you need to filter metadata, you can use the [apple_news_metadata](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_metadata) filter in addition to the one you have above to modify those values. Note that metadata doesn't appear in downloaded JSON - it's sent along with the request - so it might be a little harder to debug.

Also, the regex you have above assumes that the `src` attribute is exactly one space from the `<img` tag. If there is another attribute or a line break in there, the regex will fail to match the image.

Alternately, you could filter the final JSON that the plugin produces and look for SVG references there and delete / modify references as necessary using the [apple_news_generate_json](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_generate_json) filter.

**Comment by tripslip38** [comment]
Thanks Kevin, good suggestions. I had assumed that since every attempt to publish results in an error message from the API, that Apple has no submissions stored for me to download?

**Comment by tripslip38** [comment]
You're right. I downloaded the JSON from the plugin articles list and there is a svg reference under metadata.

What's a good way to alter the JSON programmatically in PHP? Do I have to convert to an array, delete that key, then reoutput from array to JSON? Is there an easier way?

**Comment by kevinfodness** [comment]
The download actually happens from the plugin itself, not from Apple. It's a good way to test the JSON that _would_ be sent to Apple on a publish operation.

If you use the `apple_news_metadata` filter that I linked above, it comes in as an array, and it's easy to work with.
