### ISSUE TITLE
Duplicate of https://goo.gl/vg8EUj posting here since it appears support isn't given on Wordpress site

### ISSUE THREAD

**Issue by mdrankin** [alleyinteractive/apple-news#91]
This is a duplicate of https://goo.gl/vg8EUj re-posting here as I haven't seen a responce to any support threads on the plugin's wordpress page at https://wordpress.org/support/plugin/publish-to-apple-news

I've just started with the plugin. I've submitted several of my existing articles to Apple News, however only one is showing on their side. Also none are showing what I open Apple News on my iPhone when logged into iCoud with my Apple News Account. All articles I have submitted show as Live and Published in the plugin. I haven't submitted by channel for final approval as yet because I want to preview the drafts first to make sure I'm happy with the typesetting. Any idea what is going wrong?

I have also contacted Apple News Publishing Support and am waiting for the their response.

**Comment by mdrankin** [comment]
It should be noted that if I deleted one of my CMS drafts in iCloud - news Publisher, another of my articles pops into place. So this could be a limitation on Apple's side. Perhaps the plugin is doing everything correctly and the issue is Apple's?

**Comment by bcampeau** [comment]
This isn't something the plugin controls, though I'd recommend enabling debug mode to see the actual API responses and see if any errors are being returned as a first step.

**Comment by bcampeau** [comment]
This was discussed and resolved here: https://wordpress.org/support/topic/draft-content-not-appearing-in-apple-news?replies=17#post-8166424
