### ISSUE TITLE
body-layout-last not found.

### ISSUE THREAD

**Issue by p-w0rld** [alleyinteractive/apple-news#910]
Getting this issue when trying to publish an article, I've tried customizing JSON from WordPress but unable to find anything related to layout in the body component.

> There has been an error with the Apple News API:
> INVALID_DOCUMENT - Component layout with identifier
> body-layout-last
> not found. (keyPath components->1->components->2->layout)

Here is the JSON with some redacted info, the issue appearing on line 116.

https://gist.github.com/pvo1028/8a25aa945476af59e4b9e42a7232d1d8#file-article-json-L116

**Comment by kevinfodness** [comment]
I'll be releasing an update within the next week or two to address this. Thanks for the report!
