### ISSUE TITLE
apple_news_generate_json sends null json

### ISSUE THREAD

**Issue by p-w0rld** [alleyinteractive/apple-news#911]
I read in the docs that this filter will allow you to make any changes to the JSON before it's uploaded to Apple News.

I want to use it to change URL file extensions in all the "components" objects of the JSON.  

```
function my_apple_news_generate_json($json) {
// parse through entire json and change URL file extensions in all components objects.
}

add_filter('apple_news_generate_json','my_apple_news_generate_json');
```

Simply having the function empty or filled with code sends "null" json and I confirmed this when I download/publish the article to apple news.

A possible work around I could do is create a function for each component which may contain a URL but I'm curious as to why the generate_json filter is doing this?

**Comment by fraserboag** [comment]
Apologies if I'm misunderstanding - but are you remembering to `return $json;` in your my_apple_news_generate_json() function?

Filters expose a particular piece of data, allow you to modify it, and then return the modified version. If you don't return anything, then that would explain why you were seeing 'null' or similar.

**Comment by kevinfodness** [comment]
+1 to what @fraserboag said - filters _must_ return a value otherwise it ends up with `null`, as you are experiencing.
