### ISSUE TITLE
New theme name warnings

### ISSUE THREAD

**Issue by marcusharding** [alleyinteractive/apple-news#913]
When creating a new theme the following warning message is present in the name field as well as the page body:

"Warning: Undefined variable $theme_name in /mnt/storage/stage/www/wp-content/plugins/publish-to-apple-news/admin/partials/page-theme-edit.php on line 37"

It looks as though there just needs to be a check as to wether a theme name is present and if not return an empty string for example rather than spitting out a warning string.

Thanks

**Comment by kevinfodness** [comment]
I'll take a look - thanks!

**Comment by kevinfodness** [comment]
When you created the new theme, did you specify a name for it in the theme name box at the top?
