### ISSUE TITLE
How I can add/modify author name in apple news using WordPress.

### ISSUE THREAD

**Issue by haseeb-sixlogics** [alleyinteractive/apple-news#915]
How can I add/modify the author's metadata property? Which filter or hooks is used for it?

**Comment by kevinfodness** [comment]
By default, the plugin will use the author's `display_name` from WordPress if you are using standard WordPress authors. If you are using Co-Authors Plus, it will use the display name for the coauthor.

If you want to modify the metadata that is sent to Apple without making changes to the authors themselves, you can do that via the https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_metadata filter. The authors are housed in the `authors` property.
