### ISSUE TITLE
Publish to Apple News does not connect to Wordpress

### ISSUE THREAD

**Issue by kai360mag** [alleyinteractive/apple-news#918]
Please help! Everytime I try to publish to Apple News I get this error message: There has been an error with the Apple News API: API_KEY_NOT_FOUND

Can anyone assist?
the360mag.com

**Comment by kevinfodness** [comment]
You need to follow the instructions on configuring your `.papi` file and verifying it through the Apple News API CLI: https://github.com/alleyinteractive/apple-news/wiki/configuration#api-settings

**Comment by kai360mag** [comment]
Kai please chime in when possible 

⁣Thanks in advance,
Vaughn Lowery (he/him)
President
360 MAGAZINE
the360mag.com
off: (213) 841-1841
@VaughnLowery
@360Magazine

￼

Please disregard typos as we are constantly mobile. This message contains information that may be confidential and privileged. Unless you are the intended recipient (or authorized to receive this message for the intended recipient), you may not use, copy, disseminate or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail, and delete the message. Thank you very much.​

On Mar 3, 2022, 2:53 PM, at 2:53 PM, Kevin Fodness ***@***.***> wrote:
>You need to follow the instructions on configuring your `.papi` file
>and verifying it through the Apple News API CLI:
>https://github.com/alleyinteractive/apple-news/wiki/configuration#api-settings
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/alleyinteractive/apple-news/issues/918#issuecomment-1058426736
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by kai360mag** [comment]
We have installed the Apple News Publisher Plugin to our wordpress site and put the API key, channel ID and a secret into the plugin, but for no apparent reason the posts are not being shown in the Apple News dashboard.

⁣Thanks in advance,
Vaughn Lowery (he/him)
President
360 MAGAZINE
the360mag.com
off: (213) 841-1841
@VaughnLowery
@360Magazine



Please disregard typos as we are constantly mobile. This message contains information that may be confidential and privileged. Unless you are the intended recipient (or authorized to receive this message for the intended recipient), you may not use, copy, disseminate or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail, and delete the message. Thank you very much.​

On Mar 3, 2022, 2:53 PM, at 2:53 PM, Kevin Fodness ***@***.***> wrote:
>You need to follow the instructions on configuring your `.papi` file
>and verifying it through the Apple News API CLI:
>https://github.com/alleyinteractive/apple-news/wiki/configuration#api-settings
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/alleyinteractive/apple-news/issues/918#issuecomment-1058426736
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by kevinfodness** [comment]
Per my earlier comment, have you verified the `.papi` file using the CLI tool as Apple recommends?

If your credentials are validated and properly uploaded to the site, then you should be able to go to Apple News > Sections in WordPress and see a list of sections from your channel. If you see an error on this screen, then it means that your API credentials are not working.

**Comment by 360magazine** [comment]
Has this issued been resolved ?

⁣Thanks in advance,
Vaughn Lowery (he/him)
President
360 MAGAZINE
the360mag.com
off: (213) 841-1841
@VaughnLowery
@360Magazine



Please disregard typos as we are constantly mobile. This message contains information that my be confidential and privileged. Unless you are the intended recipient (or authorized to receive this message for the intended recipient), you may not use, copy, disseminate or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail, and delete the message. Thank you very much.​

On Apr 7, 2022, 4:19 PM, at 4:19 PM, Kevin Fodness ***@***.***> wrote:
>Closed #918.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/alleyinteractive/apple-news/issues/918#event-6391780893
>You are receiving this because you were mentioned.
>
>Message ID:
***@***.***>

**Comment by kevinfodness** [comment]
Did you see my previous message about verifying the `.papi` file using the Apple News API CLI as Apple recommends?

**Comment by 360magazine** [comment]
No we didn't 

Skyler please see below 

⁣Thanks in advance,
Vaughn Lowery (he/him)
President
360 MAGAZINE
the360mag.com
off: (213) 841-1841
@VaughnLowery
@360Magazine



Please disregard typos as we are constantly mobile. This message contains information that my be confidential and privileged. Unless you are the intended recipient (or authorized to receive this message for the intended recipient), you may not use, copy, disseminate or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail, and delete the message. Thank you very much.​

On Apr 7, 2022, 5:15 PM, at 5:15 PM, Kevin Fodness ***@***.***> wrote:
>Did you see my previous message about verifying the `.papi` file using
>the Apple News API CLI as Apple recommends?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/alleyinteractive/apple-news/issues/918#issuecomment-1092205875
>You are receiving this because you were mentioned.
>
>Message ID:
***@***.***>

**Comment by 360magazine** [comment]
Hi! The .papi file seems to be connected, however we're having issues 
with uploading the three draft articles to the site. I downloaded the 
files as json files, but they don't seem to work.
--
Thanks,
Skyler Johnson
360 MAGAZINE
https://the360mag.com

Please disregard typos as we are constantly mobile. This message 
contains information which may be confidential and privileged. Unless 
you are the intended recipient (or authorized to receive this message 
for the intended recipient) you may not use, copy, disseminate or 
disclose to anyone the message or any information contained in the 
message. If you have received this message in error, please advise the 
sender by reply e-mail, and delete the message. Thank you very much.

**Comment by kevinfodness** [comment]
Can you clarify what you mean by "uploading three draft articles to the site?" Do you mean pushing three draft articles to your Apple News channel? You should be able to create posts in WordPress, then check the box to indicate that the article is a draft in the Apple News sidebar on the post edit view, and then click Publish to send the article to Apple News. If it publishes to your channel successfully, it should tell you so, or it should indicate what went wrong.

I don't know what you mean by "they don't seem to work" in reference to downloading the files as JSON files.

**Comment by kai360mag** [comment]
Skyler see below 

⁣Thanks in advance,
Vaughn Lowery (he/him)
President
360 MAGAZINE
the360mag.com
off: (213) 841-1841
@VaughnLowery
@360Magazine



Please disregard typos as we are constantly mobile. This message contains information that my be confidential and privileged. Unless you are the intended recipient (or authorized to receive this message for the intended recipient), you may not use, copy, disseminate or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail, and delete the message. Thank you very much.​

On Apr 7, 2022, 6:06 PM, at 6:06 PM, Kevin Fodness ***@***.***> wrote:
>Can you clarify what you mean by "uploading three draft articles to the
>site?" Do you mean pushing three draft articles to your Apple News
>channel? You should be able to create posts in WordPress, then check
>the box to indicate that the article is a draft in the Apple News
>sidebar on the post edit view, and then click Publish to send the
>article to Apple News. If it publishes to your channel successfully, it
>should tell you so, or it should indicate what went wrong.
>
>I don't know what you mean by "they don't seem to work" in reference to
>downloading the files as JSON files.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/alleyinteractive/apple-news/issues/918#issuecomment-1092253651
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by 360magazine** [comment]
Essentially, the icloud News publisher is requesting three separate 
draft articles to "show the Apple News team what kind of content we 
would like to publish." I downloaded separate articles as json files via 
apple news > articles, clicking the download option. They downloaded as 
json files, yet when I treid to upload them, there appeared to be an 
error stating that they weren't json files.
--
Thanks,
Skyler Johnson
360 MAGAZINE
https://the360mag.com

Please disregard typos as we are constantly mobile. This message 
contains information which may be confidential and privileged. Unless 
you are the intended recipient (or authorized to receive this message 
for the intended recipient) you may not use, copy, disseminate or 
disclose to anyone the message or any information contained in the 
message. If you have received this message in error, please advise the 
sender by reply e-mail, and delete the message. Thank you very much.

**Comment by kevinfodness** [comment]
If you are going to publish content to Apple News from WordPress, you need to use the method I described to send the articles to Apple News via their API, not by downloading the JSON files. Apple wants to verify that your CMS is properly configured to send articles, and the plugin is designed to be used in this way.

Downloading the JSON files is fine to check them locally in News Preview.

I would encourage you to open the downloaded JSON files in a text editor to verify that the JSON was properly created for your articles and that you aren't experiencing any errors during JSON creation.

**Comment by kai360mag** [comment]
So, the Apple news appears to be working as the articles appear to be 
publishing and the articles say they're live. However, when I try and 
copy the news IRL and click on the link, it says the article doesn't 
exist.
--
Thanks,
Skyler Johnson
360 MAGAZINE
https://the360mag.com

Please disregard typos as we are constantly mobile. This message 
contains information which may be confidential and privileged. Unless 
you are the intended recipient (or authorized to receive this message 
for the intended recipient) you may not use, copy, disseminate or 
disclose to anyone the message or any information contained in the 
message. If you have received this message in error, please advise the 
sender by reply e-mail, and delete the message. Thank you very much.

**Comment by kevinfodness** [comment]
Can you see the articles in iCloud Publisher? It sounds like Apple hasn't fully approved your channel yet, so you may not be able to see the articles by clicking the link until that happens. At this point it sounds like the plugin is operating as expected, and you should follow up with Apple support for next steps on getting your channel approved by them.

**Comment by 360magazine** [comment]
Can someone forward us a direct link, screenshot or instructions on how to locate our station?

⁣Thanks in advance,
Vaughn Lowery (he/him)
President
360 MAGAZINE
the360mag.com
off: (213) 841-1841
@VaughnLowery
@360Magazine



Please disregard typos as we are constantly mobile. This message contains information that my be confidential and privileged. Unless you are the intended recipient (or authorized to receive this message for the intended recipient), you may not use, copy, disseminate or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail, and delete the message. Thank you very much.​

On Apr 8, 2022, 11:38 AM, at 11:38 AM, kai360mag ***@***.***> wrote:
>So, the Apple news appears to be working as the articles appear to be 
>publishing and the articles say they're live. However, when I try and 
>copy the news IRL and click on the link, it says the article doesn't 
>exist.
>--
>Thanks,
>Skyler Johnson
>360 MAGAZINE
>https://the360mag.com
>
>Please disregard typos as we are constantly mobile. This message 
>contains information which may be confidential and privileged. Unless 
>you are the intended recipient (or authorized to receive this message 
>for the intended recipient) you may not use, copy, disseminate or 
>disclose to anyone the message or any information contained in the 
>message. If you have received this message in error, please advise the 
>sender by reply e-mail, and delete the message. Thank you very much.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/alleyinteractive/apple-news/issues/918#issuecomment-1093014827
>You are receiving this because you were mentioned.
>
>Message ID:
***@***.***>

**Comment by kai360mag** [comment]
Hi Kevin,

We completed everything and apple news seems to be connected. 

Is there anything else you need from us?

⁣Thanks in advance,


Vaughn Lowery (he/him)
President
360 MAGAZINE
the360mag.com
off: (213) 841-1841
@VaughnLowery
@360Magazine



Please disregard typos as we are constantly mobile. This message contains information that my be confidential and privileged. Unless you are the intended recipient (or authorized to receive this message for the intended recipient), you may not use, copy, disseminate or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail, and delete the message. Thank you very much.​

On Apr 15, 2022, 11:52 AM, at 11:52 AM, 360 MAGAZINE ***@***.***> wrote:
>Kevin,
>
>Can you please forward us a contact for Apple news support so we can
>inquire on approval status ?
>
>⁣Thanks in advance,
>Vaughn Lowery (he/him)
>President
>360 MAGAZINE
>the360mag.com
>off: (213) 841-1841
***@***.***
***@***.***
>
>
>
>Please disregard typos as we are constantly mobile. This message
>contains information that my be confidential and privileged. Unless you
>are the intended recipient (or authorized to receive this message for
>the intended recipient), you may not use, copy, disseminate or disclose
>to anyone the message or any information contained in the message. If
>you have received the message in error, please advise the sender by
>reply e-mail, and delete the message. Thank you very much.​
>
>On Apr 8, 2022, 1:50 PM, at 1:50 PM, Kevin Fodness
***@***.***> wrote:
>>Can you see the articles in iCloud Publisher? It sounds like Apple
>>hasn't fully approved your channel yet, so you may not be able to see
>>the articles by clicking the link until that happens. At this point it
>>sounds like the plugin is operating as expected, and you should follow
>>up with Apple support for next steps on getting your channel approved
>>by them.
>>
>>--
>>Reply to this email directly or view it on GitHub:
>>https://github.com/alleyinteractive/apple-news/issues/918#issuecomment-1093132835
>>You are receiving this because you authored the thread.
>>
>>Message ID:
***@***.***>

**Comment by 360magazine** [comment]
What is this

⁣Thanks in advance,


Vaughn Lowery (he/him)
President 
360 MAGAZINE
the360mag.com
tel: +12138411841
@VaughnLowery
@360Magazine


Please disregard typos as we are constantly mobile. This message contains information that my be confidential and privileged. Unless you are the intended recipient (or authorized to receive this message for the intended recipient), you may not use, copy, disseminate or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail, and delete the message. Thank you very much.​

On Oct 11, 2022, 4:54 AM, at 4:54 AM, kai360mag ***@***.***> wrote:
>Hi Kevin,
>
>We completed everything and apple news seems to be connected. 
>
>Is there anything else you need from us?
>
>⁣Thanks in advance,
>
>
>Vaughn Lowery (he/him)
>President
>360 MAGAZINE
>the360mag.com
>off: (213) 841-1841
***@***.***
***@***.***
>
>
>
>Please disregard typos as we are constantly mobile. This message
>contains information that my be confidential and privileged. Unless you
>are the intended recipient (or authorized to receive this message for
>the intended recipient), you may not use, copy, disseminate or disclose
>to anyone the message or any information contained in the message. If
>you have received the message in error, please advise the sender by
>reply e-mail, and delete the message. Thank you very much.​
>
>On Apr 15, 2022, 11:52 AM, at 11:52 AM, 360 MAGAZINE ***@***.***>
>wrote:
>>Kevin,
>>
>>Can you please forward us a contact for Apple news support so we can
>>inquire on approval status ?
>>
>>⁣Thanks in advance,
>>Vaughn Lowery (he/him)
>>President
>>360 MAGAZINE
>>the360mag.com
>>off: (213) 841-1841
>***@***.***
>***@***.***
>>
>>
>>
>>Please disregard typos as we are constantly mobile. This message
>>contains information that my be confidential and privileged. Unless
>you
>>are the intended recipient (or authorized to receive this message for
>>the intended recipient), you may not use, copy, disseminate or
>disclose
>>to anyone the message or any information contained in the message. If
>>you have received the message in error, please advise the sender by
>>reply e-mail, and delete the message. Thank you very much.​
>>
>>On Apr 8, 2022, 1:50 PM, at 1:50 PM, Kevin Fodness
>***@***.***> wrote:
>>>Can you see the articles in iCloud Publisher? It sounds like Apple
>>>hasn't fully approved your channel yet, so you may not be able to
>see
>>>the articles by clicking the link until that happens. At this point
>it
>>>sounds like the plugin is operating as expected, and you should
>follow
>>>up with Apple support for next steps on getting your channel
>approved
>>>by them.
>>>
>>>--
>>>Reply to this email directly or view it on GitHub:
>>>https://github.com/alleyinteractive/apple-news/issues/918#issuecomment-1093132835
>>>You are receiving this because you authored the thread.
>>>
>>>Message ID:
>***@***.***>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/alleyinteractive/apple-news/issues/918#issuecomment-1274341564
>You are receiving this because you were mentioned.
>
>Message ID:
***@***.***>

**Comment by kai360mag** [comment]
We completed all of the paperwork almost 2 months via only and we initially applied almost 2 years ago.

Is the norm? Is there anyone in leadership we can speak to?

⁣Thanks in advance,
Vaughn Lowery (he/him)
President
360 MAGAZINE
the360mag.com
off: (213) 841-1841
@VaughnLowery
@360Magazine



Please disregard typos as we are constantly mobile. This message contains information that my be confidential and privileged. Unless you are the intended recipient (or authorized to receive this message for the intended recipient), you may not use, copy, disseminate or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail, and delete the message. Thank you very much.​

On Apr 8, 2022, 1:50 PM, at 1:50 PM, Kevin Fodness ***@***.***> wrote:
>Can you see the articles in iCloud Publisher? It sounds like Apple
>hasn't fully approved your channel yet, so you may not be able to see
>the articles by clicking the link until that happens. At this point it
>sounds like the plugin is operating as expected, and you should follow
>up with Apple support for next steps on getting your channel approved
>by them.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/alleyinteractive/apple-news/issues/918#issuecomment-1093132835
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by kai360mag** [comment]
Kevin,

Can you please forward us a contact for Apple news support so we can inquire on approval status ?

⁣Thanks in advance,
Vaughn Lowery (he/him)
President
360 MAGAZINE
the360mag.com
off: (213) 841-1841
@VaughnLowery
@360Magazine



Please disregard typos as we are constantly mobile. This message contains information that my be confidential and privileged. Unless you are the intended recipient (or authorized to receive this message for the intended recipient), you may not use, copy, disseminate or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail, and delete the message. Thank you very much.​

On Apr 8, 2022, 1:50 PM, at 1:50 PM, Kevin Fodness ***@***.***> wrote:
>Can you see the articles in iCloud Publisher? It sounds like Apple
>hasn't fully approved your channel yet, so you may not be able to see
>the articles by clicking the link until that happens. At this point it
>sounds like the plugin is operating as expected, and you should follow
>up with Apple support for next steps on getting your channel approved
>by them.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/alleyinteractive/apple-news/issues/918#issuecomment-1093132835
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by kevinfodness** [comment]
Unfortunately, I don't have a contact that I can forward to you, you will need to work with Apple Support through their portal.

**Comment by kai360mag** [comment]
Can someone help us connect?

⁣Thanks in advance,


Vaughn Lowery (he/him)
President 
360 MAGAZINE
the360mag.com
tel: +12138411841
@VaughnLowery
@360Magazine


Please disregard typos as we are constantly mobile. This message contains information that my be confidential and privileged. Unless you are the intended recipient (or authorized to receive this message for the intended recipient), you may not use, copy, disseminate or disclose to anyone the message or any information contained in the message. If you have received the message in error, please advise the sender by reply e-mail, and delete the message. Thank you very much.​

On Oct 11, 2022, 4:35 AM, at 4:35 AM, 360magazine ***@***.***> wrote:
>Can someone forward us a direct link, screenshot or instructions on how
>to locate our station?
>
>⁣Thanks in advance,
>Vaughn Lowery (he/him)
>President
>360 MAGAZINE
>the360mag.com
>off: (213) 841-1841
***@***.***
***@***.***
>
>
>
>Please disregard typos as we are constantly mobile. This message
>contains information that my be confidential and privileged. Unless you
>are the intended recipient (or authorized to receive this message for
>the intended recipient), you may not use, copy, disseminate or disclose
>to anyone the message or any information contained in the message. If
>you have received the message in error, please advise the sender by
>reply e-mail, and delete the message. Thank you very much.​
>
>On Apr 8, 2022, 11:38 AM, at 11:38 AM, kai360mag ***@***.***> wrote:
>>So, the Apple news appears to be working as the articles appear to be
>
>>publishing and the articles say they're live. However, when I try and
>
>>copy the news IRL and click on the link, it says the article doesn't 
>>exist.
>>--
>>Thanks,
>>Skyler Johnson
>>360 MAGAZINE
>>https://the360mag.com
>>
>>Please disregard typos as we are constantly mobile. This message 
>>contains information which may be confidential and privileged. Unless
>
>>you are the intended recipient (or authorized to receive this message
>
>>for the intended recipient) you may not use, copy, disseminate or 
>>disclose to anyone the message or any information contained in the 
>>message. If you have received this message in error, please advise the
>
>>sender by reply e-mail, and delete the message. Thank you very much.
>>
>>-- 
>>Reply to this email directly or view it on GitHub:
>>https://github.com/alleyinteractive/apple-news/issues/918#issuecomment-1093014827
>>You are receiving this because you were mentioned.
>>
>>Message ID:
>***@***.***>
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/alleyinteractive/apple-news/issues/918#issuecomment-1274311168
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>
