### ISSUE TITLE
MIME_PART_INVALID_SIZE Error

### ISSUE THREAD

**Issue by kkranzo** [alleyinteractive/apple-news#92]
I received the below response/error when setting up an article to publish:

[body] => {"errors":[{"code":"MIME_PART_INVALID_SIZE","keyPath":["tumblr_ngerha4yez1tlysmeo1_500.gif"]}]}

What would be the reason for the error?

**Comment by bcampeau** [comment]
This is a known issue and slated to be investigated/resolved in the next two weeks.

**Comment by jwaddingham** [comment]
Hello, I'm getting a similar error when trying to publish an individual article: MIME_PART_MISSING_FILENAME

**Comment by bcampeau** [comment]
This hasn't been updated on WordPress.org or VIP yet, but the latest `master` branch here now has a potential fix and at the very least, more verbose logging for this error.

This was deployed in #109

**Comment by kkranzo** [comment]
When will the plugin be updated in the repository?

**Comment by bcampeau** [comment]
By tomorrow. If you can't wait, you can download the latest master branch from github.

**Comment by kkranzo** [comment]
Okay, great. Thanks!
