### ISSUE TITLE
apple_news_exporter_byline hook doesn't work

### ISSUE THREAD

**Issue by rodrigoovares** [alleyinteractive/apple-news#921]
Hi there, I'm using Advance Custom Fields to change the article author on my site so I used the "apple_news_exporter_byline" hook to replace the wp user article creator for the selected on the ACF. This was working good but from a couple of months stoped working.

I debugged my code and the hook function is returning the correct author but on the apple news publisher the Byline fiels is still showing the user article creator.  

This is the function return to the hook:
 
<img width="582" alt="Screen Shot 2022-02-03 at 23 08 15" src="https://user-images.githubusercontent.com/56041153/152644917-fbe88fd9-54f6-4617-b59a-4a1c1c5f1a35.png">

and this is what the byline on apple news show
<img width="603" alt="Screen Shot 2022-02-05 at 08 57 07" src="https://user-images.githubusercontent.com/56041153/152644964-72191908-be9d-459d-a13f-5240519779db.png">

**Comment by kevinfodness** [comment]
I took a look at this and it _should_ be working correctly. We did make a change to the components that are used for authorship - there is a new component that only displays the author, versus the author and the publication date on the same line. Can you verify that the `apple_news_exporter_byline` hook is actually firing when you're publishing or downloading your article?
