### ISSUE TITLE
WordPress Post Embeds Trigger an Error When Publishing

### ISSUE THREAD

**Issue by seanrasmussen** [alleyinteractive/apple-news#922]
Recently, we've been getting this error on multiple magazine websites. It's a new problem that we've never seen before, so it may have to do with recent WordPress updates... _(see below for full error)_

To produce the error, 

1. add an article embed (a URL on a line by itself, to another article on the same site), then
2. publish/update the article

"There has been an error with the Apple News API: INVALID_DOCUMENT - "URL" was "https://runningmagazine.ca/sections/training/adjust-your-mindset-to-speed-up-injury-recovery/embed/#?secret=XXXXXXXXX#?secret=XXXXXXXX" should be valid URL with one of ["http","https","#","webcal","stocks","action","music","musics","tel","mailto"] scheme(s) (keyPath components->3->components->3->components->1->additions->0->URL), INVALID_DOCUMENT - "URL" was "https://runningmagazine.ca/the-scene/6-lessons-runners-can-learn-from-their-dogs/embed/#?secret=XXXXXXXX#?secret=XXXXXXX" should be valid URL with one of ["http","https","#","webcal","stocks","action","music","musics","tel","mailto"] scheme(s) (keyPath components->3->components->18->components->1->additions->0->URL)"

**Note** that I replaced the secret keys with XXXXX just in case.

**Comment by kevinfodness** [comment]
This error is coming from the Apple News API, so Apple is flagging that URL as being invalid. At a glance, it likely has to do with the fact that there are multiple `#?` in the URL. If you change the structure of the URL to not include those elements, does Apple's API still flag the URL as being problematic?

**Comment by seanrasmussen** [comment]
Hi Kevin, the thing is, those URLs aren't actually real. Something fishy going on with how the Apple News plugin is handling the WordPress embeds, I think.

**Comment by kevinfodness** [comment]
#924 may be related to this - is it possible that the actual URL is `https://runningmagazine.ca/sections/training/adjust-your-mindset-to-speed-up-injury-recovery/embed/#?secret=XXXXXXXXX` without the second `secret` parameter?

**Comment by kevinfodness** [comment]
Or, is the URL just `#?secret=XXXXXXXXX`? Apple News doesn't understand hash-based URLs without the domain, so there is some code in the plugin to add the URL of the current page before the hash.

**Comment by seanrasmussen** [comment]
The URL that is being embedded in the post is actually just https://runningmagazine.ca/sections/training/adjust-your-mindset-to-speed-up-injury-recovery/

Not sure why the plugin is adding that to the URL when it gets sent to Apple. It's weird. And it's new behavior.

**Comment by kevinfodness** [comment]
The plugin isn't adding `#?secret` to the URL. I'm not sure where that's coming from. As you said, it may be related to recent WordPress updates, so I'll start my investigation there. Thanks!

**Comment by kevinfodness** [comment]
This is in fact coming from WordPress itself, and is specific to embedding WordPress posts in other WordPress posts: https://github.com/WordPress/WordPress/blob/master/wp-includes/embed.php#L488

I will update the issue title accordingly, and flag it as a bug for resolution.

**Comment by seanrasmussen** [comment]
@kevinfodness Thanks for tracking this down. Much appreciated.
