### ISSUE TITLE
TIkTok urls causing Apple News publish to fail

### ISSUE THREAD

**Issue by kujain** [alleyinteractive/apple-news#924]
When our content has a tiktok link, the publish push appears to fail with the following error:

`
   [body] => {"errors":[{"code":"INVALID_DOCUMENT","keyPath":["components",1,"components",4,"additions",0,"URL"],"value":"https://www.tiktok.com/foryou?#/@shaylamherrington/video/?#/@shaylamherrington/video/7028380780745510191","message":"\"URL\" was \"https://www.tiktok.com/foryou?#/@shaylamherrington/video/?#/@shaylamherrington/video/7028380780745510191\" should be valid URL with one of [\"http\",\"https\",\"#\",\"webcal\",\"stocks\",\"action\",\"music\",\"musics\"] scheme(s)"}]}
`

The URL embedded in the content is this:
`https://www.tiktok.com/foryou?#/@shaylamherrington/video/7028380780745510191`

Plugin version:  2.3.1
WP version: 5.9

**Comment by kevinfodness** [comment]
Interesting, it appears to be duplicating part of the URL. I'll take a look. This might be related to #922 .

**Comment by kevinfodness** [comment]
Can you provide more information on how you are adding or embedding the TikTok link? When I use the TikTok Gutenberg block it works fine. Are you using Gutenberg or the classic editor? Is this for an embed? Are you using an iframe? Or is this just in a link somewhere?

**Comment by kujain** [comment]
Thanks for looking into this @kevinfodness !
I reviewed the structure of the article and the issue is not coming from an embed link, but rather a direct link in the body!
Here is the copy markup in the editor:
```html
<!-- wp:paragraph -->
<p>In a recent TikTok, user <a href="https://www.tiktok.com/foryou?#/@shaylamherrington/video/7028380780745510191" target="_blank" rel="noreferrer noopener">Shayla  Herrington</a>&nbsp;shared the three telltale signs of an ill-fated marriage she heard from a wedding photographer  who's been in the business for more than 10 years.</p>
<!-- /wp:paragraph -->
```

The above is triggering the following JSON markup:
```JSON
{
   "role":"body",
   "text":"<p>In a recent TikTok, user <a  href=\"https:\/\/www.tiktok.com\/foryou?#\/@shaylamherrington\/video\/?#\/@shaylamherrington\/video\/7028380780745510191\">Shayla Herrington<\/a> shared the three telltale signs of an ill-fated marriage she heard from a wedding photographer who\u2019s been in the business for more than 10 years.<\/p>",
   "format":"html",
   "textStyle":"default-body",
   "layout":"body-layout"
},
```

For some reason, the above link structure seems to appending additional params to the url! 
I tested the embed that is also placed below it and both the standard embed block and the tiktok embed block generate the proper markup so I don't believe them to be the issue.

Hope this helps...

**Comment by kevinfodness** [comment]
Thanks, this is super helpful!

**Comment by kevinfodness** [comment]
I tried this out on my Apple News test environment (latest version of WordPress - 5.9.1, latest version of Publish to Apple News - 2.3.1, PHP 7.4, using the Twenty Twenty Two theme) and it worked correctly, which makes me think that something else is modifying those URLs on your environment. Could you try (in a test environment) disabling plugins or switching themes and seeing if the URL stops getting malformed? You should be able to test it by going to Apple News > Articles and then clicking Download on the article that is having the issue, which will give you the article JSON, and you can look in there for the URLs.

**Comment by kujain** [comment]
Thanks @kevinfodness I'll test further and report back soon. Glad to know that my debugging process is the same as what  you have recommended !
