### ISSUE TITLE
Filter for in-body images caption

### ISSUE THREAD

**Issue by marounmelhem** [alleyinteractive/apple-news#927]
First of all, thanks a lot for the great work you did with this plugin.

Similar to the [`apple_news_exporter_cover_caption`](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_exporter_cover_caption) filter, I was wondering if there's a way to filter the caption of in-body images.
I've noticed that there isn't any [documented filter](https://github.com/alleyinteractive/apple-news/wiki/action-and-filter-hooks#filter-hooks) to handle that so I wanted to check if there's a turnaround for this.

What we're trying to accomplish is the following: appending image credits (which is a custom image meta we've configured) to the image caption of the cover image and in-body images. This worked great for the cover image using the following code:
```php
/**
 * Append image credits to its caption in Apple News.
 *
 * @param string $caption  Image caption.
 * @param int    $post_id  Post ID.
 *
 * @return string
 */
function apple_news_append_credits_to_cover_caption( $caption, $post_id ) {
	if ( $caption && $post_id ) {
		$image_credits = get_post_meta( get_post_thumbnail_id( $post_id ), 'credit', true );

		// Append the image credit if it exists or return the caption.
		return ! empty( $image_credits ) ?
			$caption . ' ' . strtoupper( $image_credits ) :
			$caption;
	}
}

add_filter( 'apple_news_exporter_cover_caption', __NAMESPACE__ . '\apple_news_append_credits_to_cover_caption', 10, 2 );
```

Is there a current way to do the same for in-body images (which might require using the `$attachment_id` instead of the `$post_id`) or this has to be a new feature request (if so, is this planned for any upcoming release)?

**Comment by kevinfodness** [comment]
This is where the wildcard filters come in. I would recommend using https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_%7B%24component_name%7D_json and using `image` as the component name (the dynamic part of the hook). Unfortunately, this hook does not provide you with the original HTML, so you would need to do a bit of legwork to match the URL of the image for the component to the caption that's associated with the image, but that's not an insurmountable task. Alternately, you could use something like https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_exporter_content or https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_exporter_content_pre to add the caption to the post content _before_ the Apple News parser gets its hands on it. If you do it right, then the parser will be able to properly convert your image captions. (Basically, just mimic the HTML that WordPress would generate for the image with a caption, and the plugin can take it from there.)

**Comment by marounmelhem** [comment]
Thanks @kevinfodness for the suggestions and support.
