### ISSUE TITLE
Where does exporter pull from?

### ISSUE THREAD

**Issue by kkranzo** [alleyinteractive/apple-news#93]
How does the exporter grab the data for each post? 

The reason I ask is that we have some custom post styles that we use for things like galleries, so in those cases the actual content of the post would be seen as empty, but should actually have the data instead from some custom fields. Basically there is a custom template in my theme like single-gallery.php. So how could I get that applied over to Apple News as well?

And on that same note, is there a way to check for something being created in the Apple News format? For example, I have a custom shortcode that I need to output in a certain format in order for the plugin to render properly. So in my custom shortcode in my functions.php is there something like the below I could use?

```
if (is_apple_news()) {
 //do something
}
```

**Comment by bcampeau** [comment]
There are many filters available to control the output of your content. It sounds like you may need a custom component in which case you can write your own component class and add it via this filter: https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-exporter/class-component-factory.php#L93

You can also always filter the parsing of the body content here too: https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-exporter/class-markdown.php#L63

Unfortunately this isn't a simple answer and does require some custom coding to resolve.

**Comment by kkranzo** [comment]
Okay, so there is no way for me to change what the post content has in it before the apple news content is parsed?

For example, I have the custom shortcode below for galleries (it just pulls images attached to that post):

[showgallery id="1234"]

However, in order for a gallery to be created correctly for Apple News with this plugin it would need to be formatted like below:

[gallery ids="729,732,731,720"]

So I was thinking I would just reformat my custom shortcode to be in the format the plugin needs before anything gets parsed. Is that possible?

I was thinking I could do it using the pre_get_posts action, but I would only want to do it for when the content was being queried for Apple News. That is why I was wondering if there was any way to check for something like if (is_apple_news()). Is there no way to check that a query being made is coming from this plugin?

**Comment by bcampeau** [comment]
I think I misunderstood your request. Yes, you can absolutely do that. There are two filters you can use that run before and after the normal `the_content` filter called `apple_news_exporter_content_pre` and `apple_news_exporter_content`. You're going to want to use `apple_news_exporter_content_pre` to update the shortcode in your example.

https://github.com/alleyinteractive/apple-news/blob/master/admin/apple-actions/index/class-export.php#L101-L106

**Comment by kkranzo** [comment]
Okay, great!

So it would be something like this, correct?

```
add_filter( 'apple_news_exporter_content_pre', 'configure_apple_content', 10, 2 );
function configure_apple_content( $content, $postID ) { 
	//do stuff before parsing here
}
```

**Comment by bcampeau** [comment]
Yes

**Comment by kkranzo** [comment]
Awesome, thanks.

**Comment by kkranzo** [comment]
Actually, is there any way to just check to see if the apple exporter is the item pulling the content?

That way I could just add a check in my shortcode setup like below:

```
add_shortcode("showgallery", "custom_gallery_shortcode");
function custom_gallery_shortcode($atts) {
    if (coming_from_apple_news_exporter) {
        //do apple news specific shortcode
    } else {
        //do the normal setup
    }
}
```

That way I would have to RegEx search through all the content to replace my custom gallery shortcodes with the default Wordpress gallery shortcodes.

Is that possible?

**Comment by kkranzo** [comment]
Or could I just have the below setup so that the plugin just overrides/sets up a new gallery shortcode to run before it exports?

add_filter( 'apple_news_exporter_content_pre', 'configure_apple_content', 10, 2 );
function configure_apple_content( ) { 
    remove_shortcode('showgallery');
    add_shortcode('showgallery', 'apple_news_gallery');
}

function apple_news_gallery {
    //output apple news specific gallery shortcode here
}

**Comment by iamjolly** [comment]
> Actually, is there any way to just check to see if the apple exporter is the item pulling the content?

@bcampeau :: 

This would help me resolve my issue (related to this) much faster. Any thoughts on this? I'd love to have the ability to run something like this: 
```
if (is_apple_news()) {
 //do something
} 
```
So that my other content filter can be ignored when Publish to Apple News grabs the content.

**Comment by bcampeau** [comment]
You could easily use `apple_news_exporter_content_pre` to remove a filter or set a global and then re-add the filter (if needed) in `apple_news_exporter_content`.

**Comment by iamjolly** [comment]
OK. I *think* I understand now. Since `apple_news_exporter_content_pre` fires before calling the content that has my offending filter firing on it, then I can add a global for something like `is_apple_news` and set it to `true`. Then I can conditionally ignore my original filter, correct? If so, I should be all set. Thank you for the help!

**Comment by bcampeau** [comment]
Yes

**Comment by iamjolly** [comment]
Please tell me where to send the beer and/or refreshments. Cheers, and thanks again!

**Comment by bcampeau** [comment]
None required. Glad this was helpful for you.

**Comment by iamjolly** [comment]
So, I'm getting one thing happening which isn't right... 

I see this when publishing: 

> The following components are unsupported by Apple News and were removed:
> script
> ins
> script
> div

Here's the code I'm running to do this: 

```
add_filter( 'apple_news_exporter_content_pre', 'set_is_apple_news', 10, 2 );
function set_is_apple_news( $content, $postID ) { 
    global $is_apple_news; 
    $is_apple_news = true;
}

// Display Google Ads after 2nd paragraph on post pages
add_filter( 'the_content', 'hugga_ads_inside_content' );
 function hugga_ads_inside_content( $content ) {

      //We don't want to modify the_content in de admin area
      if( !is_admin() || !$is_apple_news == true ) { ... 
```

Something isn't allowing the apple_news_exporter to run fully.  Can you see what I'm doing wrong here?

**Comment by bcampeau** [comment]
That message indicates that your body content contains components that can't be supported by Apple News. There is a plugin setting that allows you to fail when that happens, warn about it, or do nothing. You can adjust that as you see fit.

With regards to your code, unfortunately we can't help you debug your custom code. We can only advise on what filters might be best for you.
