### ISSUE TITLE
Category/date not rendering (garbled) on Apple News articles

### ISSUE THREAD

**Issue by 2paragraphs** [alleyinteractive/apple-news#931]
Dates below title on Apple News posts render as: #M j, Y (see image)
Category isn't there either (which is fine), but garbled date looks bad.
Could not find this specific issue elsewhere. Please advise. Thank you!
![apple news date not showing](https://user-images.githubusercontent.com/45519326/162024764-a5b1b285-b7c7-45e6-97b8-43d84db810f9.jpg)
example URL: 
https://2paragraphs.com/2022/03/demi-moore-bruce-willis-photo-like-poster-for-divorced-couple-happiness-mushrooms/

**Comment by kevinfodness** [comment]
You're likely missing the closing `#` in the date format box in your theme configuration. If you go to Apple News > Themes, find the theme that you're using, then click Edit, and expand "Combined Date and Author," then check the value for "Combined Date and Author Format" it should end with a `#`.

For example, the default value is:

`by #author# | #M j, Y | g:i A#`

If the closing `#` isn't present, then the string matcher won't match the date formatting pattern, and it will appear garbled, as you have in your screenshot.

**Comment by 2paragraphs** [comment]
Thank you. Fixed perfectly. Very grateful to you.

**Comment by kevinfodness** [comment]
Great! Glad it was a quick fix.
