### ISSUE TITLE
Pound symbol shown as question mark

### ISSUE THREAD

**Issue by gergonzalez** [alleyinteractive/apple-news#932]
We are having issues to publish an article with the pound symbol. The title is fine the pound symbols is correctly encoded to unicode, but h2 headings are shown as question marks. And paragraphs that uses this symbol have been stripped.

`"title":"Everton could reportedly face legal action over \u00a3373m losses"`

But h2:
`{"role":"heading2","text":"Everton recorded a financial loss of over ?300m for the last three seasons","format":"html" ...`

Just an example, this is the apple news article:
https://apple.news/AsyYgxAcCTJuUsjOnAmhmpA

And the site article:
https://www.joe.co.uk/sport/everton-legal-action-327695

Thanks!

**Comment by kevinfodness** [comment]
Hi @gergonzalez —

This is working properly for me on the latest version of the plugin running the Twenty Twenty Two theme and no other plugins, so my guess is that something in your theme or one of the other plugins you are running is interfering.

![image](https://user-images.githubusercontent.com/2650828/162784979-30c35a21-2c63-4345-b91e-a5cbafa68ee3.png)

Can you try (in a non-production environment) disabling other plugins and/or switching your theme to see if you can isolate the issue?

**Comment by gergonzalez** [comment]
@kevinfodness thanks so much for the quick response. 

Testing it.

**Comment by gergonzalez** [comment]
@kevinfodness it seems it was related to the plugin version, once we updated to the latest version the issue is fixed. 

Apologies for bothering instead of having check that.

Thanks so much!

**Comment by kevinfodness** [comment]
Great, glad to hear it's working!
