### ISSUE TITLE
Gallery looking for <ul> and not parent <figure>

### ISSUE THREAD

**Issue by rogerthatbro** [alleyinteractive/apple-news#934]
Been working with this plugin a lot for a recent client. We are converting our galleries into content the plugin can use, hence basic WordPress galleries. I've installed a vanilla WordPress install with this plugin, and generated a basic gallery, and the layout breaks, because WordPress creates something similar to below:

```
<figure class="wp-block-gallery">
  <ul class="blocks-gallery-grid">
    ... stuff in here ...
  </ul>
</figure>
```

But the plugin looks for 'wp-block-gallery' which it believes is on a `<ul>` tag or a `<div>` and not a parent `<figure>`.

**Comment by kevinfodness** [comment]
We put a fix in place for galleries not working in the most recent version, 2.3.2. Can you confirm that you're running version 2.3.2 of the plugin?

**Comment by rogerthatbro** [comment]
Yes, it says 2.3.2, but I'm installing through the WordPress backend, and not from Github.

**Comment by kevinfodness** [comment]
Yep, that's fine, as long as the version says 2.3.2. I'll take a further look.

**Comment by kevinfodness** [comment]
This should be working properly in the latest version. We haven't received any other similar reports. There's even an automated test that includes the wp-block-gallery class on a figure element that's working properly.
