### ISSUE TITLE
Cannot Download or Publish – Critical Error

### ISSUE THREAD

**Issue by josephrorr** [alleyinteractive/apple-news#935]
Hello! Thanks to those who are willing to read this and maybe have a solution.

Everything has been good up until this point, but now when I hit Publish, I get the dreaded Wordpress Critical Error:

There has been a critical error on this website.
[Learn more about troubleshooting WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)

I'm trying to send my first 3 articles to Apple News to be evaluated. 

- Or do my first few articles need to be manual first?
- Does anyone know some troubleshooting steps I might be able to take? 
- Is there any conflict with WP Bakery type of builders? 

Any help would be appreciate as I do not know where to go from here,

Thanks so much all! – Joseph

**Comment by kevinfodness** [comment]
If you're getting the critical error message, you need to look at your server's error logs to figure out what is causing the critical error.

There should not be a conflict with WP Bakery. If the content is saved to post_content, then the plugin will see it. If not, you will need to apply a filter in order to pass in the content that the plugin needs.

However, the first step is debugging the error.

You need to send the articles from WordPress so that Apple can verify that the connection and publishing is working correctly from the plugin.

**Comment by josephrorr** [comment]
Thanks, Kevin! I was out of the country for a little bit and haven't had time to respond. 

When I'm troubleshooting, should I turn debug to true in wp-config.php? 

Any advice would be helpful to debug and get this working. 

Happy to pay for your time as well, just let me know.

**Comment by kevinfodness** [comment]
Apologies for the delay in responding, I'm just getting back from some time off myself. Yes, enabling WP_DEBUG would be helpful here.

**Comment by josephrorr** [comment]
No worries! Thanks for responding.  Attached is a debug.log – I have a developer looking into this (although not a specialist in this like you). I hope you had some nice time away! Joseph ***@***.*** From: Kevin FodnessSent: Wednesday, October 5, 2022 11:14 AMTo: alleyinteractive/apple-newsCc: Joseph Orr; AuthorSubject: Re: [alleyinteractive/apple-news] Cannot Download or Publish – Critical Error (Issue #935) Apologies for the delay in responding, I'm just getting back from some time off myself. Yes, enabling WP_DEBUG would be helpful here.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by kevinfodness** [comment]
@josephrorr the attachment you sent on your email didn't make it to the GitHub issue. Would it be possible for you to paste it into GitHub directly or upload it somewhere and link it?

**Comment by josephrorr** [comment]
[05-May-2022 19:51:12 UTC] PHP Warning:  Undefined array key "conditional" in /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/components/class-body.php on line 161
[05-May-2022 19:51:12 UTC] PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/components/class-body.php:161
Stack trace:
#0 /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/components/class-body.php(161): array_merge(Array, NULL)
#1 /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/components/class-component.php(225): Apple_Exporter\Components\Body->register_specs()
#2 /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/class-component-factory.php(181): Apple_Exporter\Components\Component->__construct('<p>Months befor...', Object(Apple_Exporter\Workspace), Object(Apple_Exporter\Settings), Object(Apple_Exporter\Builders\Component_Text_Styles), Object(Apple_Exporter\Builders\Component_Layouts), NULL, Object(Apple_Exporter\Builders\Component_Styles))
#3 /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/class-component-factory.php(212): Apple_Exporter\Component_Factory::get_component('p', '<p>Months befor...')
#4 /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php(515): Apple_Exporter\Component_Factory::get_components_from_node(Object(DOMElement))
#5 /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php(803): Apple_Exporter\Builders\Components->get_components_from_node(Object(DOMElement))
#6 /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-components.php(42): Apple_Exporter\Builders\Components->split_into_components()
#7 /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/builders/class-builder.php(66): Apple_Exporter\Builders\Components->build()
#8 /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/class-exporter.php(219): Apple_Exporter\Builders\Builder->to_array()
#9 /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/class-exporter.php(144): Apple_Exporter\Exporter->generate_json()
#10 /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/admin/apple-actions/index/class-push.php(560): Apple_Exporter\Exporter->generate()
#11 /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/admin/apple-actions/index/class-push.php(297): Apple_Actions\Index\Push->generate_article()
#12 /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/admin/apple-actions/index/class-push.php(92): Apple_Actions\Index\Push->push(NULL)
#13 /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/admin/class-admin-apple-index-page.php(395): Apple_Actions\Index\Push->perform()
#14 /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/admin/class-admin-apple-index-page.php(167): Admin_Apple_Index_Page->push_action(25414)
#15 /nas/content/live/newflwn/wp-includes/class-wp-hook.php(307): Admin_Apple_Index_Page->page_router('')
#16 /nas/content/live/newflwn/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#17 /nas/content/live/newflwn/wp-includes/plugin.php(474): WP_Hook->do_action(Array)
#18 /nas/content/live/newflwn/wp-admin/admin.php(175): do_action('admin_init')
#19 {main}
  thrown in /nas/content/live/newflwn/wp-content/plugins/publish-to-apple-news/includes/apple-exporter/components/class-body.php on line 161

**Comment by josephrorr** [comment]
Just saw your comment on WP forum @josephrorr - now we are both perplexed, because I haven't modified any files and running the latest version of PHP on WP Engine environment. I deleted and reinstalled before - would an incorrect .papi file generate this error? I can submit my details of that if you think it'd be helpful to assess...at that, it shouldn't throw up a critical error, right? I am running multisite, not sure if that has anything to do with it either.

**Comment by kevinfodness** [comment]
Which version of PHP, specifically? 8.0 or 8.1?

**Comment by josephrorr** [comment]
8.0 with option to downgrade to 7.4, which I do not wish to do.

**Comment by kevinfodness** [comment]
The plugin should be compatible with 8.0 but I will investigate this more thoroughly and get back to you.

**Comment by josephrorr** [comment]
I'm disabling plugins to see if that does the trick.

**Comment by josephrorr** [comment]
> I'm disabling plugins to see if that does the trick.

Did not work.

**Comment by josephrorr** [comment]
Hello! Just following up to see if you made any new discoveries in regards to PHP 8.0 vs earlier versions. I deleted a lot of plugins that could have been causing conflict, and even disabled all of them as a test, and still experienced the issues. I don’t want to bother, just seeing if you got anywhere. Joseph ***@***.*** From: Kevin FodnessSent: Wednesday, October 5, 2022 12:36 PMTo: alleyinteractive/apple-newsCc: Joseph Orr; MentionSubject: Re: [alleyinteractive/apple-news] Cannot Download or Publish – Critical Error (Issue #935) The plugin should be compatible with 8.0 but I will investigate this more thoroughly and get back to you.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by kevinfodness** [comment]
I haven't yet, but I should have more info by the end of the week.

**Comment by kevinfodness** [comment]
The plugin is now fully compatible with PHP versions up to 8.2.
