### ISSUE TITLE
Publish status not syncing with apple news

### ISSUE THREAD

**Issue by seanrasmussen** [alleyinteractive/apple-news#939]
We just started seeing problems with Apple News giving DUPLICATE_POST errors when trying to publish new articles. 

Here's the exact message:

**There has been an error with the Apple News API: DUPLICATE_ARTICLE_FOUND**

It seems that the issue is being caused by a disconnect on the publish status between the plugin and the API. See my next comment.

**Comment by seanrasmussen** [comment]
I want to follow up on this. I just checked the actual Apple News feed, and they aren't "false" duplicate posts. The problem is that the posts ARE on apple news, but the plugin has not recorded the post properly.  So, you can't update and you can't remove a post. The connection to Apple News seems corrupted? in some way.

**Comment by kevinfodness** [comment]
This is really strange - the logic that pushes the post to Apple should be recording the Apple News ID in the API response and saving it to postmeta immediately. The window for something to break down here is extremely small. Is it possible that you have a mirrored or non-production environment that is pushing the same posts? Do you see any errors in your server error logs? If you inspect postmeta in the database for the posts that are marked as duplicates, do you see the Apple News postmeta keys with things like the article ID?

What version of WP are you running, and what version of PHP on the server?

**Comment by seanrasmussen** [comment]
Hi Kevin, there's no staging environment at the moment. 
PHP: 7.4
WordPress: 6.0
(we're on WPEngine)

So, it's not saving the Apple News ID, I guess? I'll need to poke around and look at server logs and such. 

We have 3 other sites we use this plugin on, and they seem OK with the same environment.... Except we are getting some timeouts once in a while...

**Comment by seanrasmussen** [comment]
The articles with the issues (the most recent ones) have a "Last updated at" status of "Never", and an "Apple News status" of "N/A", and "Sync status" of "Unpublished"

**Comment by kevinfodness** [comment]
OK, I have a theory. One of our other teams reported some slowness with the Apple News API, and part of the narrow window where this could be an issue is if the request makes it to Apple but your webserver gives up waiting on a response from Apple, so the resulting unique ID never makes it back to be saved to postmeta, even though the request was (eventually) successful. You can filter `apple_news_post_args` and set `$args['timeout']` to be a higher value. For POST requests, the default is 30 seconds, but you can increase that to 60 seconds, for example.

ref: https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_%7B%24verb%7D_args

**Comment by seanrasmussen** [comment]
Thanks Kevin, that sounds like a good theory. I'll see if I can set the timeout higher and hope that fixes it. I also set the image loading to what you recommend...

**Comment by seanrasmussen** [comment]
Once an article is out of sync with the plugin, is there any way that we can go in and remove those posts from Apple News? We want to update some and delete some...

**Comment by kevinfodness** [comment]
Yep, you can go in through iCloud News Publisher and delete them, and then re-publish them from WordPress.

**Comment by seanrasmussen** [comment]
Great, I deleted, and tried to republish. The error is a timeout issue, as theorized:

**There has been an error with the Apple News API: There has been an error with your request: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received**

It's weird that it is just with this one site, though...

**Comment by kevinfodness** [comment]
I'd recommend opening a support thread with Apple to see if there's something going on with their API and this is a temporary thing.

Typically, what might cause a timeout is if you are not using remote images and trying to send Apple bundled images, which can be large and take a long time to upload. Can you confirm that you are using the remote images setting (set to yes)?

If remote images are set to yes, and you're still getting timeouts after 30s, that's likely either a network issue with your hosting provider or with Apple's API.

**Comment by seanrasmussen** [comment]
Yes, I set the images to be remote. 

I'll reach out to Apple support to see if they are having any issues... 

Also checking with WPEngine to see about anything they can do...

**Comment by seanrasmussen** [comment]
So, I heard back from Apple. They are, indeed, having issues with the API. Here's what they said:

**_We are experiencing article processing delay today with our API. The issue has subdued, and you should no longer be seeing the timeout issue._** 

Not sure what "subdued" means. Sounds like they haven't fully fixed it yet :-)

**Comment by kevinfodness** [comment]
Yeah, that's my read too.
