### ISSUE TITLE
Using WooCommerce "Hand-picked Products" block prevents posting to Apple News

### ISSUE THREAD

**Issue by HighTechDad** [alleyinteractive/apple-news#940]
While not 100% confirmed (and still looking for a common issue), whenever I try to post an article on my site (usually a review) that has a WooCommerce "Hand-picked Products" block, the post to Apple News via the plugin fails. 
My question is, is there a way to validate that it is, indeed, an issue with some scripting in the WooCommerce block? Is there anything I can do to test? Thank you!

**Comment by kevinfodness** [comment]
Can you post the specific error that you're seeing?

**Comment by kevinfodness** [comment]
Also, please see the "need help" section at the top of our wiki: https://github.com/alleyinteractive/apple-news/wiki

**Comment by HighTechDad** [comment]
Will review the need help. The error is simply that the article cannot be published. I will turn on debugging and see if I can get further detail. And if I try to download the JSON, it is a zero byte file. Thx.

**Comment by kevinfodness** [comment]
Oh, if the JSON is giving you a zero byte file, then something is going badly wrong. Take a look at your PHP error log.
