### ISSUE TITLE
Date showing in exert field 

### ISSUE THREAD

**Issue by GaryBultitude1** [alleyinteractive/apple-news#941]
Hey, I think I have an issue with the setup of the JSON file. 
When I create a draft article onto iCloud, the extert is showing the date. 
Does anyone know how to fix this please?

Screen shot attached

![Screenshot 2022-07-05 at 15 51 46](https://user-images.githubusercontent.com/108746660/177357658-6fe50c59-4e36-47ab-890f-90f54e26a413.png)
d

**Comment by kevinfodness** [comment]
Hi @GaryBultitude1 - Please follow the steps in [Getting Help](https://github.com/alleyinteractive/apple-news/wiki/Usage#getting-help) so that we have enough information to be able to take a closer look.
