### ISSUE TITLE
Bulk Publish: 403 Forbidden 

### ISSUE THREAD

**Issue by cherifzouein** [alleyinteractive/apple-news#944]
Hello (again),

Upon using the bulk publish feature, selecting all articles on a given listing page, I often get a 403 Forbidden error. The command sometimes turns out successful. Wondering if anyone ran into this and has insights in how to solve it, I have more than 2,000 articles to publish :)

**Comment by kevinfodness** [comment]
Is there any additional information, either in server logs or returned via the browser, that would indicate why the FORBIDDEN message is being displayed? Is the error coming from the webserver (e.g., a blank white page with 403 Forbidden in plain black text) or are you seeing it as a WordPress admin error message (which could indicate that it's coming from Apple's API)? Screenshots would be helpful.

**Comment by cherifzouein** [comment]
Apologies!

Steps to repro:
1. Login to WP
2. Navigate to Articles section
3. Filter by unpublished
4. Select all 25 articles on page
5. Hit Bulk Action / Publish / Apply
6. Observe error
There's a related 403 console error, inspecting the request in the network tab I'm not finding anything more specific.

I wonder if it could be an individual article failing and resulting  in this? We have NR on the server but not seeing any errors in the logs.

Thanks for your help!

![image](https://user-images.githubusercontent.com/823524/180267743-8440339c-72b1-4bbc-bca0-ec4e05d2bf6d.png)

**Comment by kevinfodness** [comment]
The Publish to Apple News plugin doesn't throw 403 errors itself, so it's got to be coming from WordPress core or another plugin. The typical source for a 403 in WordPress core is if you're using an expired nonce, which usually only happens if you leave the admin open for a really long time and then try to take an action without reloading the page or navigating somewhere else first.

Do you have any security plugins running on your site?

**Comment by cherifzouein** [comment]
Understood, will investigate further. We have one that reroutes the login page to another path, but once logged in any calls to wp-admin still works

**Comment by cherifzouein** [comment]
Still investigating but this seems to be an issue with our hosting setup, closing

**Comment by cherifzouein** [comment]
@kevinblanco figured it out. Our hosting's CDN and WAF are invalidating the noonce. We're now using our non-CDN covered domain to configure and use the plugin :X

**Comment by kevinfodness** [comment]
Great, glad you got it sorted!
