### ISSUE TITLE
Disable apple_news_skip_push filter 

### ISSUE THREAD

**Issue by patrickeg360** [alleyinteractive/apple-news#947]
Hello @kevinfodness ! I am a product manager for a digital media company that owns several blog/websites. 

We are using your plugin to push content to Apple News and are receiving an error message for "Skipped push of article [ID] due to the apple_news_skip_push filter." but, we never explicitly added this filter to our plugin. We are using Wordpress VIP.

Can we remove this filter in wp-admin in the plugin settings?
Or, is there another way for our engineers to remove this filter?
Thanks!

**Comment by kevinfodness** [comment]
That filter likely exists _somewhere_ in the code that you are running. We also run a lot of sites on WordPress VIP and don't run into this problem, so it's likely not platform related. Could you check the other plugins that you are using?

**Comment by kevinfodness** [comment]
Alternately, if you can reproduce this problem locally, you can look at the `$wp_filter` global, which has properties with the name of each action or filter hook and information about what function to execute (under the `callbacks` property within the hook). That could help point you to where it's being registered. In order to _unregister_ the hook, you first need to figure out where it's being registered so you know which one to unhook.

**Comment by patrickeg360** [comment]
Thanks @kevinfodness ! We will reproduce locally and confirm where it's being registered. 

As for checking the other plugins we are using, are there any you have heard impacting your plugin in the past? This has been a running theory but are unsure how to confirm which plugin could be causing this. Cheers!

**Comment by patrickeg360** [comment]
These are our active plugins. I removed a few that we built in-house

Google News Sitemaps
Ads.txt Manager
Advanced Custom Fields
Categories to Tags Converter Importer
CMB2
CMB2 Field Type: Ajax Search
CMB2 Field Type: Attached Posts
CMB2 Post Search field
Contact Form 7Settings \|
Edit Flow
Head, Footer and Post Injections
Heartbeat Control by WP Rocket
Metro Sitemap
NextPage Buttons
oEmbed Plus
ProfilePressSettings \|
Publish to Apple News
Web Stories  \| Settings
WPCOM Legacy Redirector
Yoast Duplicate PostSettings \|
Yoast SEORequired by Yoast SEO Premium \| FAQ \| Settings
Yoast SEO Premium
Yoast SEO: NewsSettings \|

**Comment by kevinfodness** [comment]
I haven't heard of any plugins that affect our plugin in this way, no. I would recommend performing a search within PHP files in the `wp-content` directory of your site for the string `apple_news_skip_push`. An example of how to do this on the command line for a unix-like system (e.g., not Windows) would be:

```sh
grep -r 'apple_news_skip_push' --include=*.php
```

When I ran that command on one of my WordPress VIP sites, which is running some of the same plugins that you are, the only location that was returned was within the Publish to Apple News plugin itself, and the default value for that filter is `false`. Something on your site is setting it to `true`.

I'll also note that I'm on the most recent version of the Publish to Apple News plugin, so if your installation is out of date, I would recommend updating and seeing if that fixes the issue as well.
