### ISSUE TITLE
Need help with Custom Fonts 

### ISSUE THREAD

**Issue by kevinblanco** [alleyinteractive/apple-news#949]
Hello, 

I need to use custom fonts in my Apple News account. I followed your documentation this way: 

1. Added the custom fonts to Apple News (OTF format) [See screenshot here](https://api.monosnap.com/file/download?id=eYHQSpv8Z5J1IkOwbaS8pFhr8xoHmi)

2. Added the [Filter for the Fonts List](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_fonts_list): 
```
add_action( 'after_setup_theme', 'kevin_custom_fonts_apple', 0 );
function kcm_custom_fonts_apple() {
	$prefix = get_stylesheet_directory_uri() . "/fonts";
	$fonts = [
		"$prefix/TiemposText-Medium.otf",
		"$prefix/TiemposText-MediumItalic.otf",
		"$prefix/TiemposHeadline-Regular.otf",
		"$prefix/TiemposHeadline-RegularItalic.otf",
		"$prefix/Graphik-Medium.otf",
		"$prefix/Graphik-MediumItalic.otf",
		"$prefix/Graphik-Regular.otf",
		"$prefix/Graphik-RegularItalic.otf",
		"$prefix/Graphik-Semibold.otf",
		"$prefix/Graphik-SemiboldItalic.otf",
	];
	apply_filters( 'apple_news_fonts_list', $fonts );
}
```
I made sure that the fonts are actually on the server and the filename are the same as the ones in Apple News, but, If I try to set the font for the theme these custom fonts doesn't show up so I can define these custom fonts in the theme. 

[See screenshot here](https://api.monosnap.com/file/download?id=qdN5Yuw9etDPxdghoSRxrHF6Nj0VGM)

So the help I need is how can I get the theme to use these custom fonts? I also tried using the Customize JSON section but the font family is not editable in that area. 

Thanks in advance

Using Version 2.3.2 of the Plugin in WP 5.9.3

**Comment by kevinfodness** [comment]
Your filter setup is incorrect. It should be:

```php
add_filter( 'apple_news_fonts_list', 'kcm_custom_fonts_apple' );
function kcm_custom_fonts_apple( $fonts ) {
    $fonts[] = 'TiemposText-Medium';
    // etc for the other font names
    return $fonts;
}
```

Note that what you are adding to the fonts list needs to be the TrueType name of the font, which may not be the same as the filename.

More info here: https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_fonts_list

**Comment by kevinblanco** [comment]
Hello @kevinfodness , 

I hope you are doing well. Thanks a lot for your kind help. I tried what you mentioned like this: 

```
add_filter( 'apple_news_fonts_list', 'kcm_custom_fonts_apple' );
function kcm_custom_fonts_apple( $fonts ) {
	
	$fonts[] = 'TiemposHeadline-Regular';
	return $fonts;
}
```

But its not working :( I also tried passing the URI of the TTF instead of the font name: 

```
add_filter( 'apple_news_fonts_list', 'kcm_custom_fonts_apple' );
function kcm_custom_fonts_apple( $fonts ) {

 	$prefix = get_stylesheet_directory_uri() . "/fonts";
	
	$fonts[] = 'TiemposHeadline-Regular';
	$fonts[] = "$prefix/TiemposHeadline-Regular.ttf";
	
	return $fonts;
}

```

But it didn't worked neither, using just the font name or the font URI in the theme, here you can see it in the theme https://monosnap.com/file/YbLwGGdLTu08rarkSCyw5LPYsc1xgl  and here you can confirm that the font is actually date kcm-1100-kcmedia.pantheonsite.io/https://kcm-1100-kcmedia.pantheonsite.io/wp-content/themes/kcm/fonts/TiemposHeadline-Regular.ttf 

Thanks in advance for any other clue!

**Comment by kevinfodness** [comment]
A URI won't work, it needs to be the TrueType name of the font, and the font needs to be installed on the computer that you are using to access WordPress. You should be able to open the font file and get the TrueType name, which may be different than the filename.

**Comment by kevinblanco** [comment]
Thanks a lot! That was the issue I had to have them installed on my machine. Thanks a lot Kevin
