### ISSUE TITLE
YouTube regex not handling shortlinks correctly

### ISSUE THREAD

**Issue by bcampeau** [alleyinteractive/apple-news#95]
See: https://wordpress.org/support/topic/preg_match-for-youtube-embed-is-stripping-number-from-end-of-url

Appears that https://youtu.be/aE-G_BblWb8 is being converted to https://www.youtube.com/embed/aE-G_BblWb

**Comment by jamesabruce** [comment]
I figured out a fix after studying a bit on regex.... I'm not sure why this was placed in there, but removing the [^ ] appears to work. 

	const YOUTUBE_MATCH = '#^https?://(?:www\.)?(?:youtube\.com/watch\?v=([\w\-]+)|youtu\.be/([\w\-]+))[^ ]+$#';

	const YOUTUBE_MATCH = '#^https?://(?:www\.)?(?:youtube\.com/watch\?v=([\w\-]+)|youtu\.be/([\w\-]+))+$#';

**Comment by bcampeau** [comment]
Looks like the break occurred here: https://github.com/alleyinteractive/apple-news/commit/2cf5f6c8854c526221b1ba095ec325e31f669e31

@smerriman do you recall why you added `[^ ]` to that part of the regex?

**Comment by smerriman** [comment]
Yep, my mistake - it's to handle all of the extra query parameters that are often at the end of youtube URLs. Should be [^ ]* rather than [^ ]+ though in case there are none.

**Comment by bcampeau** [comment]
This is fixed in the latest master branch.
