### ISSUE TITLE
JSON Files Give Error

### ISSUE THREAD

**Issue by tvshowsace** [alleyinteractive/apple-news#952]
Thank you for your help. I have the plugin installed. When I download articles and try to upload them to Apple to apply for Apple News I get an error. When I do my own json files I get an error. I need help uploading in JSON files to get approved. Thank you.

**Comment by eshanfelt** [comment]
I am in the same situation. We created three JSON files from the plugin and tried to upload them to Apple News Publisher. Here's a Loom video that shows exactly what's happening. And I've also attached a sample JSON file if that helps.

[https://www.loom.com/share/ee41db84389044d2aff7320f07e55e92](https://www.loom.com/share/ee41db84389044d2aff7320f07e55e92)
[article json files.zip](https://github.com/alleyinteractive/apple-news/files/9568965/article.json.files.zip)

**Comment by tvshowsace** [comment]
I was able to apply by getting the plugin and letting it populate the json for me. I applied several weeks ago though and still waiting to hear back.

**Comment by eshanfelt** [comment]
Thx, @tvshowsace ... I will give that a try. I do know that iClould News Publisher is VERY slow to respond to any requests for new approvals, updates, etc. I've done this before.  :-)  And I thought Google News support was slow. LOL!

**Comment by kevinfodness** [comment]
Yes, having the plugin push the files into your channel is the correct way to go. Once you have submitted the three articles via the plugin, you have to wait for Apple to review and approve your channel.
