### ISSUE TITLE
Mapping custom fields to Apple News fields

### ISSUE THREAD

**Issue by kevinblanco** [alleyinteractive/apple-news#953]
Hello, 

Thanks in advance for your kind help. I have a custom field on my Posts (with ACF) and I'd like that field to be mapped the `Intro Text` field in apple news, the `Intro Text` field is shown in the articles previews like here and also in the articles. 

https://monosnap.com/file/UaO7NVd5ieO1q7O9ZYNBUykwssb2D7

Thanks in advance, I have't found a way to understand how fields and content is mapped.

**Comment by kevinfodness** [comment]
Take a look at this filter: https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_%7B%24component_name%7D_json

You should be able to filter the JSON for the intro component and populate it based on what is in postmeta, as saved by ACF. Note that the "component name" part of the filter name is dynamic, and you will need to use `intro` as the component name.
