### ISSUE TITLE
Publishing not allowed 

### ISSUE THREAD

**Issue by Simonia** [alleyinteractive/apple-news#954]
Plz help someone❤️🙏🏻

**Comment by yogeshbeniwal** [comment]
Pls provide more details on what help you need.

**Comment by kevinfodness** [comment]
Please review the Getting Started section on our wiki and ensure you have followed all of the steps: https://github.com/alleyinteractive/apple-news/wiki/configuration#getting-started

Once you have, please follow the steps in the "need help" section at the top here: https://github.com/alleyinteractive/apple-news/wiki

**Comment by Simonia** [comment]
Hello I dunno why Im not approved.

De bedste hilsner
Christina Simonia Straarup
 
Redaktør på Yesbjerg.dk
Formand for Lokalråd Øst
Fotograf og Dronepilot www.iluften.dk
Næstformand i Børns Voksenvenner
Næstformand i Cykling uden alder
Ambassadør for Nationalpark Vadehavet
Projektleder på Happy Xmas Trees Esbjerg 2019/2020

**Comment by kevinfodness** [comment]
@Simonia you will need to follow up with Apple support. This plugin is not maintained by Apple, and I am unable to help you get your channel approved.

**Comment by Simonia** [comment]
Aw Thx

De bedste hilsner
Christina Simonia Straarup
 
Redaktør på Yesbjerg.dk
Formand for Lokalråd Øst
Fotograf og Dronepilot www.iluften.dk
Næstformand i Børns Voksenvenner
Næstformand i Cykling uden alder
Ambassadør for Nationalpark Vadehavet
Projektleder på Happy Xmas Trees Esbjerg 2019/2020
