### ISSUE TITLE
Update to adhere to coding standards

### ISSUE THREAD

**Issue by mboynes** [alleyinteractive/apple-news#96]
This plugin should be updated to adhere to WordPress Coding Standards. Much of it does already, it just needs a once-over to e.g. convert indentation to tabs.

**Comment by koconder** [comment]
@mboynes might be good to update Travis CI, Scrutinizer and PHPUnit tests to validate changes and updates. I have recently re-built the very outdated CI support for WP plugins (https://github.com/koconder/wordpress-test-template), can also test for dependency issues by load up any other 3rd party plugins such as caching etc. Let me know if you need a hand, happy to build out the PR for working Travis CI etc to expose the issues.

Once we have CI and code coverage reports, these can be used to automate a large number of the commits, provided it passes tests.
