### ISSUE TITLE
"Array to string conversion" notice when saving post meta "apple_news_sections"

### ISSUE THREAD

**Issue by andyblackwell** [alleyinteractive/apple-news#963]
`NOTICE: PHP message: PHP Notice: Array to string conversion in /var/www/html/public/wp/wp-includes/rest-api/fields/class-wp-rest-meta-fields.php on line 424`

Notice is thrown by WP in `is_meta_value_same_as_stored_value()` for post meta `apple_news_sections`, because it is registered as `type: string` but the sanitize filter returns the value as an array. This conversion also causes `is_meta_value_same_as_stored_value()` to always return false for this meta key, since it casts the array to a string (`"Array"`) for this check.

https://github.com/alleyinteractive/apple-news/blob/v2.3.3/admin/class-admin-apple-news.php#L157-L163

to reproduce: save a post in the editor, this notice will be thrown during the `/wp-json/wp/v2/posts/[post-id]` ajax request that saves the post

**Comment by chief1983** [comment]
I am seeing this issue as well, and on PHP 8 it is now a warning, which made it bubble up through our error reporting, generating a lot of noise in our logging and Sentry monitoring.  So +1 interested in a fix eventually.

**Comment by kevinfodness** [comment]
Good catch! Adding this as a bug for resolution in a future version.

**Comment by attackant** [comment]
Thanks @chief1983 and @andyblackwell  going to wrap this into the next release.

**Comment by attackant** [comment]
The PR here breaks unit tests so this needs further investigation.

**Comment by attackant** [comment]
I'm closing this because I can't duplicate the issue, and applying the suggested patch throws other PHP notices.  This is an old bug report and may have already been fixed. If it is still happening, please provide more details for how to duplicate the issue. Thanks!

**Comment by srtfisher** [comment]
Reopening this as I was able to recreate it on a client site.
