### ISSUE TITLE
Excerpt Field on Apple News Filled with Date/Time instead of Excerpt Field from Wordpress

### ISSUE THREAD

**Issue by bhcourierProd** [alleyinteractive/apple-news#964]
Hi,

Please let me know any additional info I can provide to help with this issue. I'm seeing that when the wordpress plugin automatically publishes articles to Apple News, the excerpt field on Apple News is populated with the date/time of publication rather than the excerpt field from the Wordpress editor. This is consistent across all the test posts uploaded to Apple News prior to our channel going live. Any advice on how to address this? 

Thank you!

**Comment by kevinfodness** [comment]
The component that uses the excerpt is called `Intro` and it has to be enabled in the meta component order. Unless you're talking about the excerpt metadata property? That field is also populated using the content of the excerpt field. It's likely something is filtering that value before it is sent to Apple News. Is it possible that you're changing the output of the Intro component to use it like a byline or publication date?
