### ISSUE TITLE
Apple News credentials

### ISSUE THREAD

**Issue by bjm1** [alleyinteractive/apple-news#966]
Apple News credentials suddenly stopped working as of 2.3.3 update. Is there a new format?

Regenerating keys has not worked either.

**Comment by kevinfodness** [comment]
What version did you upgrade from? The format hasn't changed in the database in a very long time, although the interface for uploading new credentials changed in version 2.2.0. However, if your credentials were working previously, the update to v2.3.3 would not have broken your existing credentials.
