### ISSUE TITLE
New Component Registration

### ISSUE THREAD

**Issue by shamim23** [alleyinteractive/apple-news#969]
I am trying to register a new component. A few options in mind - 
  - Add it as a body component (modify json file before publish) 
  - Add it in the plugin
  - Use a filter like apple_news_initialize_components. The question is how do I use it?

**Comment by kevinfodness** [comment]
The `apple_news_initialize_components` filter will pass an associative array of component types to component classes that are meant to process them. You would need to create a new component class that is similar to the components defined here: https://github.com/alleyinteractive/apple-news/tree/develop/includes/apple-exporter/components and then you can use that filter to add your custom component to the list of components that will be run on export. You would need to code your `node_matches` function to determine whether to apply the custom component (e.g., look for a specific class on an enclosing element, for example).

**Comment by umeshnevase** [comment]
@kevinfodness How can I register new component by extending Apple News plugin in new plugin? The solution you have suggested is need to make modification in original Publish to Apple News plugin. It will get lost. once I update the plugin.

**Comment by mogmarsh** [comment]
@umeshnevase you should use the `apple_news_initialize_components` filter in your plugin to add additional items to the component array, referencing classes in your plugin.

For example:
```
add_filter( 'apple_news_initialize_components', [ $this, 'initialize_custom_components' ] );

/**
 * Add our own custom components.
 *
 * @param array $components Array of components.
 *
 * @return array
 */
public function initialize_custom_components( $components ): array {
	$components[ 'my_component' ] = 'My_Component_Class';

	return $components;
}
```

This code would be in your plugin, and `My_Component_Class` would be a class in your plugin.
