### ISSUE TITLE
date stamps in metadata ignores

### ISSUE THREAD

**Issue by norcross** [alleyinteractive/apple-news#98]
I've been testing the three date stamps that can be added to the `metadata` array, but it appears as though they are ignored by Apple News, showing the date is was published to Apple instead of the date passes. 

Is this an issue with Apple or the plugin?

**Comment by bcampeau** [comment]
Did you check the JSON output?

**Comment by norcross** [comment]
I did. it's outputting the data in the ISO format the documentation outlines.

**Comment by bcampeau** [comment]
Sorry, I think I misunderstood your initial request. I've always seen Apple News show the date it was pushed to them. I would expect the metadata dates to override that, but if not then that's a question for their support team.

I'm going to open a new issue to add those dates to the metadata in the plugin however.
