### ISSUE TITLE
Sidebar to wordpress/apple news plug in

### ISSUE THREAD

**Issue by brookegs** [alleyinteractive/apple-news#983]
There is currently no way to integrate sidebars into Apple News versions of articles. Without an integration, side bar content just gets put randomly into an article, which is confusing to read. Can we create a way to create a sidebar on Apple News, or toggle something on the Wordpress side to exclude side bar content from Apple News ?

**Comment by kevinfodness** [comment]
We have a number of filters available that will let you do exactly that. Sidebars are inserted in different ways on different sites, which could be anything from Gutenberg blocks to custom logic in the theme or a third party plugin, shortcodes, etc. You can use either [apple_news_exporter_content](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_exporter_content) or [apple_news_exporter_content_pre](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_exporter_content_pre) to filter out your sidebars or to move them to a different location (e.g., the end of the article).
