### ISSUE TITLE
Trying to publish to Apple News—HELP WANTED

### ISSUE THREAD

**Issue by MotherwellMag** [alleyinteractive/apple-news#985]
WE have been approved for Apple News and are trying to start publishing from Wordpress. Every time, though, we get a message that says: There has been an error with the Apple News API: WRONG_SIGNATURE.

I have tried to follow the instructions to manually insert the papi file (using the ID, KEY, SECRET). But I do not know what it means to 'run a command in a terminal' so perhaps I haven't proplerly verified the connection?

Please help!!!

**Comment by kevinfodness** [comment]
Typically `WRONG_SIGNATURE` is an issue with the server's time being too far off from a timeserver - see this issue for some suggestions on what to try: https://github.com/alleyinteractive/apple-news/issues/853
