### ISSUE TITLE
Apple News JSON is invalid and cannot be published.

### ISSUE THREAD

**Issue by ashwinness** [alleyinteractive/apple-news#988]
We are trying to publish content to Apple News but the validation for the JSON is failing whenever we add Emojis to the content.

I have tested this behavior in the latest version of the plugin. When we pass the Emojis in the content, it always returns with the same error – JSON ins invalid(screenshot attached)

When I try downloading the JSON from the Apple News menu, it says as null with the status FAILED_PROCESSING_UPDATE.

Once I remove the emojis from the content, the post goes through without any issue. Does Apple News NOT support emojis in the content? Or is there anything we are missing to be able to include emojis in the content?

![image](https://user-images.githubusercontent.com/87417675/215753086-6c576b3c-4368-4adf-a03c-99a5372dff45.png)

**Comment by kevinfodness** [comment]
Apple News does support emojis in content. Can you see whether you're using HTML format for articles or not (Apple News > Settings > Enable HTML Support)?

**Comment by ashwinness** [comment]
I verified the settings and we have enabled HTML Support. I tried toggling on/off and verifying, but the same error message pops up JSON `The Apple News JSON is invalid and cannot be published on review link.`

**Comment by kevinfodness** [comment]
I just tested this and it worked properly for me, which makes me wonder if something else is going on. Can you please download the article JSON for the article that is failing, upload it somewhere, and link it here, please?

**Comment by ashwinness** [comment]
Hi @kevinfodness . Sorry took long to respond. We are not seeing the JSON whe we download the article. The file just contains the word 'null'.

**Comment by kevinfodness** [comment]
That means that something is going seriously wrong during the export. Can you check your PHP error logs to see if there's a clue there?

It's possible that your host doesn't have support for `mbstring`: https://make.wordpress.org/hosting/handbook/server-environment/

The plugin makes use of multibyte string functions, like `mb_strlen` and `mb_substr`, and loads HTML content using UTF-8 encoding for parsing. If your server is set up without multibyte support, or if your data is being saved using an encoding other than UTF-8, that could explain why emoji aren't working for you (but are for me).

**Comment by ashwinness** [comment]
Hi @kevinfodness . Just verified on the servers. We have enabled and have support for `mbstring` on our servers.

**Comment by kevinfodness** [comment]
The next place I would check would be the PHP error logs, then. It's likely something is going wrong that's captured there. The plugin itself supports emoji, and we haven't had other reports of issues related to emoji in some time, so it's highly likely that there is something specific to your server configuration that's causing this issue for you.

You're running the most recent version of the Publish to Apple News plugin, right? We had extended our support for emoji in a prior release, but that's been several years ago now.

**Comment by Prathimareddy23** [comment]
@kevinfodness , Thanks for helping . We used  WP function `wp_staticize_emoji` to convert emojis into static img,  with add filter of apple news `apple_news_exporter_content` and it seems to be working now. I will update more on this once we complete all our testing.

**Comment by kevinfodness** [comment]
Glad you found a workaround, but I'm curious to know why emoji weren't supported natively, since both WP and this plugin have support for them. Let me know if you are able to get to the bottom of that.
