### ISSUE TITLE
Custom Post Type with ACF fields - Publishing to Apple News

### ISSUE THREAD

**Issue by seanrasmussen** [alleyinteractive/apple-news#989]
I couldn't find this in the wiki. We want to design a custom affiliate page post type, and template that has a bunch of ACF fields that creates a nice layout. How can we publish this to Apple news while keeping all of the custom ACF layouts? Or is not not possible? 

Thanks in advance for any insights!

**Comment by kevinfodness** [comment]
The plugin is designed to operate on whatever HTML comes out of the `post_content` field in the database after being run through `the_content` filter. Depending on how you have ACF set up, the plugin may pick up nothing at all to convert, or it may pick up some complex HTML that won't render nicely without doing some additional work. It's likely that you're going to need to use one or more filters to write custom code to adapt what you're doing in ACF to a format that will work for Apple News.

At a basic level, you can use the [apple_news_exporter_content filter](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_exporter_content) to adjust what HTML is passed to this plugin for conversion into Apple News components. If you need a higher degree of control over what components are rendered, you can filter the final article JSON using the [apple_news_generate_json filter](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_generate_json) and inject whatever custom logic you like, including replacing the article contents entirely using custom logic you define, which will give you full control over what is being sent to Apple News. Although it requires a lot of custom coding, this approach is necessary if you want to have highly designed articles using custom components.

**Comment by seanrasmussen** [comment]
Thanks. That points me in the right direction. It makes me wonder how it all goes with Gutenberg blocks...!!!??? We are using classic editor for this site, but just curious!

**Comment by kevinfodness** [comment]
Gutenberg blocks save their content to `post_content`. Dynamic blocks that render their content via PHP happen as part of `the_content` filter, so as far as the plugin is concerned, it's all just HTML to be parsed. The plugin has supported Gutenberg for several years now and there are a number of automated tests that use Gutenberg block syntax as part of the test setup as well. Custom Gutenberg blocks that render specific markup still need to be filtered similar to what I recommended above, however.
