### ISSUE TITLE
Automation View does not show custom taxonomy terms after saving.

### ISSUE THREAD

**Issue by timbolimboslice** [alleyinteractive/apple-news#996]
After the most recent update, `2.4`, terms in custom taxonomies do not show the name of the term after saving changes. Default taxonomies like categories seem to work fine. Screenshot attached.

![Screenshot 2023-03-06 at 10 35 56 AM](https://user-images.githubusercontent.com/11657201/223173206-fa10b974-8d27-4f8c-a27a-d7e24d97c4bf.png)

Looking at the console, it appears the WP API can't find the terms, see screenshot:

<img width="879" alt="Screenshot 2023-03-06 at 12 28 11 PM" src="https://user-images.githubusercontent.com/11657201/223198781-ab05a5ac-7795-48a7-8495-9961afed9cf4.png">

**Comment by kevinfodness** [comment]
Thanks for the issue report, @timbolimboslice - it appears that something is breaking down when attempting to build the REST API URL for the custom taxonomy, which should be using the `rest_namespace` and `rest_base` for the taxonomy: https://github.com/alleyinteractive/apple-news/blob/develop/assets/js/components/term-selector/index.jsx#L29

Do you have `show_in_rest` set to `true` for your custom taxonomy?

ref: https://developer.wordpress.org/reference/functions/register_taxonomy/

**Comment by timbolimboslice** [comment]
Hey Kevin, thanks for the quick reply. I did poke around with this a little more and we do have that property set to true, but it looks like the URL is being rewritten / redirected.

I'll continue to look at it and see if this is an issue on our end.

**Comment by timbolimboslice** [comment]
This ended up being a conflict with the plugin, [WP No Taxonomy Base](https://github.com/markoheijnen/wp-no-taxonomy-base). Closing out the issue.
