### ISSUE TITLE
Apple news Youtube embed videos 

### ISSUE THREAD

**Issue by shamim23** [alleyinteractive/apple-news#998]
The youtube embeds using do not load at times (I do see the the loading circle.). Other times it takes minutes to load I see the the loading circle. 

ex -   {
      "role": "embedwebvideo",
      "URL": "https://www.youtube.com/embed/MpVtZAYslOk",
      "layout": "video-layout"
    }

**Comment by kevinfodness** [comment]
Hi @shamim23 —

You will need to open a support ticket with Apple about this issue. The JSON being delivered to Apple News by this plugin is correct, and any issue with slow loading of the video would be happening within the Apple News app. These forums are maintained by the Publish to Apple News plugin developer (Alley) and we can only offer help with the plugin itself.
